### ISSUE TITLE
Fail to load topology/sof-apl-pcm512x.tplg on up^2

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/sof#100]
environment:
sof-dev: a3a39f21218c074c71cd28b0c2c782b1626df3e3
sof:  2d92796072856e530c3a1bce4f0a9ce2c74692d4
soft: 47339d2302f445c3b35d50f9720ee649dd2f739b

log ：

[dmesg5.log](https://github.com/thesofproject/sof/files/2192986/dmesg5.log)

**Comment by tlauda** [comment]
Driver problem., not FW related.

**Comment by lgirdwood** [comment]
@zhuqingliang it's a topology (likely) or kernel issue. Can you close and re-open in correct issue area.

**Comment by zhuqingliang** [comment]
The bug is moved to soft , please refer to https://github.com/thesofproject/soft/issues/29
