### ISSUE TITLE
'ipc timed out' on GordonPeak once boot up

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/sof#102]
environment:
sof-dev: a3a39f21218c074c71cd28b0c2c782b1626df3e3
sof:  2d92796072856e530c3a1bce4f0a9ce2c74692d4
soft: 47339d2302f445c3b35d50f9720ee649dd2f739b
tplg file name :
topology/sof-apl-tdf8532.tplg

reproduce steps:
check dmesg log once boot up

log:
[dmesg7.log](https://github.com/thesofproject/sof/files/2193135/dmesg7.log)
[rmbox7.log](https://github.com/thesofproject/sof/files/2193136/rmbox7.log)

**Comment by tlauda** [comment]
Fixed on master. Please confirm and close.

**Comment by keqiaozhang** [comment]
This issue is fixed.

**Comment by Jocelyn-Li** [comment]
@Jocelyn-Li test

**Comment by Jocelyn-Li** [comment]
@Jocelyn-Li test

**Comment by Jocelyn-Li** [comment]
@Xu Guangxin  test

**Comment by Jocelyn-Li** [comment]
@Xu Guangxin  test

**Comment by Jocelyn-Li** [comment]
@xuguangxin test

**Comment by Jocelyn-Li** [comment]
@tlauda can you update the PR fix here?

**Comment by xiulipan** [comment]
Fixed by https://github.com/thesofproject/sof/issues/99
