### ISSUE TITLE
volume: zipper noise with fast changes

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#103]
When I play on Up2 w/ the PCM512x codec, I can hear zipper noise when I keep pressing on up and down arrows to change the PGA Master Volume. This was reported before but apparently the fixes aren't enough. I view this as a bug, volume changes should not introduce audio artifacts (same as soft mute).

**Comment by tlauda** [comment]
@plbossart HiFi3 or generic implementation?

**Comment by plbossart** [comment]
This was on APL so I guess HiFi3.

**Comment by lgirdwood** [comment]
@singalsu this may need ZC or a smaller step size.

**Comment by singalsu** [comment]
@lgirdwood Sure, I will check some options after doing the updates to my UP2. Also as 3rd option logarithmic step could cope with larger step length. Zero crossings detection based volume update could be best but it would need largest amount of work.

**Comment by singalsu** [comment]
I can now repeat the issue with my UP2+HiFiBerry after some struggle with fresh code. It's a bit hard to hear the zipper with music but with sine (997 Hz) it's quite audible.

**Comment by singalsu** [comment]
The effect is also a bit different when pressing cursor keys in alsamixer vs. running successive commands like
'amixer sset 'PGA1.0 Master Playback Volume 1',0 10 10'
and
'amixer sset 'PGA1.0 Master Playback Volume 1',0 32 32'
so there may be two different issues. For the cursor keys case I wonder if the previous ramp has completed before the new target gain is received.

Note: I'm testing with gcc compiled FW. But it looks like the HiFi3 version just uses different copy function versions while the volwork code is shared so the issue should be the same.

**Comment by singalsu** [comment]
I will submit a pull request with 250 ms long linear volume ramp (was 64 ms) and with gain value update rate increased to  every 1 ms (was 2 ms). I can still hear very silent zipper noise with sine wave but no more with music. If it's considered still too noisy maybe there's still room for some ramp length increase. Or consider changing ramp to logarithmic (still a small change) or even use ZC detection (major change, includes HiFi3 optimized code).
