### ISSUE TITLE
Kernel QA scripts are broken

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#1039]
sof/tools/test/qa/run_test.sh has obviously not been run in a long time:

FIRMWARE_PATH="/lib/firmware/intel"

The new default is /lib/firmware/intel/sof for firmware and /lib/firmware/intel/sof-tplg for topology files.

**Comment by xun2z** [comment]
pr#1044  is to fix this.

**Comment by lgirdwood** [comment]
@xun2z can this be closed now ?
