### ISSUE TITLE
sof-logger causes machine to hang on reboot if still open 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#1043]
There appears to be a bug in the sof-logger on the glk-005-drop/master branch where the sof-logger will causes a system to hang if it is still open when reboot is called.

Reproduce steps:
1. open ssh and open sof-logger:
    sof-logger -l sof-apl.ldc -t 
2. open second ssh and call reboot
    sudo reboot
3. watch chromebook hang

**Comment by keqiaozhang** [comment]
@Jiangxinx , please help to check this issue on UP^2 board.

**Comment by Jiangxinx** [comment]
This issue can also be reproduced on UP2 with PCM512x.

**Test env:**
sof master: 4d715e06
kernel sof-dev: ee19d24e
tplg: sof-apl-pcm512x.tplg

**Comment by mengdonglin** [comment]
Will check from Linux side at first.

**Comment by keqiaozhang** [comment]
More information about this bug:
1. On GLK Chromebook, this issue can also be reproduced by:
    console 1: cat /sys/kernel/debug/sof/trace 
    console 2: reboot the system
2. This issue cannot be reproduce on UP2 with ubuntu OS. I also tried cros-sof-v4.14-rebase branch on UP2. logger works well with Ubuntu.

I guess this issue may related to ChromeOS file system.

**Comment by lgirdwood** [comment]
@keqiaozhang this is a rare use case for chrome so can be deprioritized, especially since this is working on Ubuntu etc. @mengdonglin

**Comment by plbossart** [comment]
On 2/26/19 12:19 AM, Keqiao Zhang wrote:
>
> More information about this bug:
>
>  1. On GLK Chromebook, this issue can also be reproduced by:
>     console 1: cat /sys/kernel/debug/sof/trace
>     console 2: reboot the system
>  2. This issue cannot be reproduce on UP2 with ubuntu OS. I also tried
>     cros-sof-v4.14-rebase branch on UP2. logger works well with Ubuntu.
>
> I guess this issue may related to ChromeOS file system.
>
In my experience be it on Baytrail or Up2, when the system cannot reboot 
it's usually due to memory corruption and issues on module remove.

You should try to remove the modules to simulate a reboot with KASAN 
enabled (see memory-debug-defconfig) and see how this goes.

**Comment by keqiaozhang** [comment]
> @keqiaozhang this is a rare use case for chrome so can be deprioritized, especially since this is working on Ubuntu etc. @mengdonglin

Yes, let set the priority of this issue as P2 and it's aligned with Google.

**Comment by keqiaozhang** [comment]
@plbossart 
Today I tried to remove modules with KASAN enabled, but no system hang when unloading modules.  Besides, I found one kernel issue, dai links are missing in sof_link_unload, see /thesofproject/linux/issues/680. 

Test steps:
1. Enable KASAN in kernel:
```
+CONFIG_SLUB_DEBUG_ON=y
+CONFIG_SLUB_STATS=y
+CONFIG_KASAN=y
+CONFIG_KASAN_EXTRA=y
+# CONFIG_KASAN_INLINE is not set
+CONFIG_KASAN_OUTLINE=y
```
2. Update the new kernel on GLK, then open logger:
sof-logger -l sof-apl.ldc -t 
3. Remove modules.

**Comment by mengdonglin** [comment]
@keqiaozhang Is this issue still there?

**Comment by keqiaozhang** [comment]
@mengdonglin 
Yes, this issue still can be reproduced on GLK chromeOS with latest sof/driver code base.

**Comment by lgirdwood** [comment]
@keqiaozhang still reproduced ?

**Comment by keqiaozhang** [comment]
@lgirdwood ,
Yes, this issue can still be reproduced on GLK ChromeOS with latest sof/master-50bd96d.
But Ubuntu OS has no such issue.
kernel: cros-sof-v4.14-rebase-a1d6bf0d

**Comment by tlauda** [comment]
@keqiaozhang Still reproduced?

**Comment by aiChaoSONG** [comment]
issue not produced on CML Chrome(helios)

**Comment by ClarexZhou** [comment]
Close for old issue on GLK and not reproduce on cml chrome.
