### ISSUE TITLE
The volume of rear channels can not be changed on GP platform.

### ISSUE THREAD

**Issue by zhigang-wu** [thesofproject/sof#106]
when you play the four-channel music file on the GP platform, you will find the rear channel volume
can not be changed. the root cause is:
the tplg did not support this feature.
the "C_CONTROLMIXER" in "pipe-volume-playback.m4" and "pipe-volume-capture.m4"
only support two channels volume change.

I am not familiar with the m4 language. and who can help fix this issue?
but please pay attention during your fix, this change would affect the tplg script in the test folder.

**Comment by tlauda** [comment]
Should be moved to soft repo.

**Comment by lgirdwood** [comment]
@RanderWang please open this as topology issue.

**Comment by Jocelyn-Li** [comment]
Moved to https://github.com/thesofproject/soft/issues/31
