### ISSUE TITLE
noise issue when both front L and front R are connected on GP-MRB

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#107]
This issue occurs when both front L and front R are connected, but disconnect one of them, the noise will disappear.
sof-dev:a3a39f21218c074c71cd28b0c2c782b1626df3e3
sof-master:c4a9cca0a94969fbf1ecb42d660c0e40279d9ffa
soft-master:2abbfc0910ce9767d01462638d719309746844d1
tplg:sof-apl-tdf8532.tplg

how to reproduce:
1. ensure both front L and front R are connected.
2. aplay -D hw:0,0 -f S32_LE -r 48000 -c 4 /home/rander/4ch_32bit.wav , you can hear the noise and the noise sounds like a rustle.
3. disconnect front L or front R. the noise will disappear

**Comment by lgirdwood** [comment]
This does not appear to be a firmware bug, perhaps the codec settings need adjusted to driver both L & R outputs here ?

**Comment by keqiaozhang** [comment]
No codec kctls are exposed in amixer setting.
![amixer](https://user-images.githubusercontent.com/22468760/42749519-8288ddf6-8916-11e8-9c80-3ab55461527a.PNG)

**Comment by lgirdwood** [comment]
The codec driver then. Should be logged as a driver issue.

**Comment by keyonjie** [comment]
tdf8532 codec driver doesn't export any kcontrol at the moment, it's controlled via ioc i2c command, if we can make sure the data is correct on SSP pins, better to report them to Dirana or integration team.

**Comment by zhigang-wu** [comment]
no sure this noise is still exist during playing the sine wave or not, if yes we could use the scope to probe the point of analog output.

**Comment by plbossart** [comment]
On 7/16/18 3:53 AM, Keyon wrote:
> tdf8532 codec driver doesn't export any kcontrol at the moment, it's 
> controlled via ioc i2c command, if we can make sure the data is correct 
> on SSP pins, better to report them to Dirana or integration team.

Yes, there is no requirement for volume control in the firmware for that 
specific board but still it's a good issue to fix to make sure we can do 
volume control for 2+ channels

**Comment by keqiaozhang** [comment]
This issue is moved to thesofproject/linux#34
