### ISSUE TITLE
Regression: HDA audio is failed on master

### ISSUE THREAD

**Issue by RanderWang** [thesofproject/sof#1133]
There are many many XRUN error in FW. It is caused by this commit:  dai: change flow of component copy (https://github.com/thesofproject/sof/commit/407be960c0b9591b2b43f7943d7be08c7efb271b#diff-9f8de02ec82000817dd1a9bbccac158c)

**Comment by RanderWang** [comment]
duplicate

**Comment by wenqingfu** [comment]
> duplicate

duplicate of who? 1114?  if so, please don't save the four key stroke '1' '1' '1' '4', sir.. duplicate have 50% information, 'duplicate of 1114" have 100% information.

**Comment by RanderWang** [comment]
yes, I get it.

**Comment by lgirdwood** [comment]
@RanderWang please also use the duplicate label too.
