### ISSUE TITLE
host: update testbench to handle components properly

### ISSUE THREAD

**Issue by jajanusz** [thesofproject/sof#1199]
Since #1167 comp inits are not exported so testbench cannot get them with dlsym

**Comment by jajanusz** [comment]
I prefer to change logic to load it from comp_init section instead of having hardcoded names like now.

@singalsu Are you ok with that?

**Comment by lgirdwood** [comment]
@jajanusz ack, lets load all types from the init section

**Comment by ranj063** [comment]
@jajanusz yes I think it makes sense. Thanks!

**Comment by jajanusz** [comment]
Fixed in #1227
