### ISSUE TITLE
[BUG] tools/coredumper: wrong formatting

### ISSUE THREAD

**Issue by mmaka1** [thesofproject/sof#1217]
**Describe the bug**
There are a couple of issues with the format of the output:

- `-l` options does not work unless verbose mode is on, but the usage does not mention that,
- verbose mode require tty (should not) which makes it less useful when piped with 'more' for example,
- core header fields should be printed separately and clearly described as the core header, while they are mixed with cpu registers now,
- some rows begins with `|` while others begins with `#`, marks are unclear.

**Comment by abonislawski** [comment]
all done in PR #1220
