### ISSUE TITLE
[BUG][WHL HDA] incorrect sound when playback

### ISSUE THREAD

**Issue by xun2z** [thesofproject/sof#1251]
### Description
The playback is not right with the clock frequency on both WHL RVP and CML laptop.

### Cause
commit: [cavs: ssp: generic ssp mclk configuration for cavs ](https://github.com/thesofproject/sof/commit/f5e78430ff3dbbe8bcceca5f0f4f1fa86bbd78b8) is the cause. 
Playback is OK when this commit is reverted.

### To Reproduce
**kernel**
(since recent regression, I prefer to use this branch): [rander/cml-validation-branch](https://github.com/RanderWang/linux/tree/cml-validation-branch)
[regression #1: linux/issues/767 ](https://github.com/thesofproject/linux/issues/767) (this can be fixed by former branch)
[regression #2: linux/issues/774 ](https://github.com/thesofproject/linux/issues/774) (this still exists, I do a work-around to delete the /usr/bin/pulseaudio)

**firmware**
master newest commit: ed6ac05f6b884b5aa5597bf739fc97527bdab909

**test step**
play some music on HDA device
```sh
aplay -Dhw:0,0 48California_Dreaming.wav
```
you will hear noise, no dmesg error since the clock is the cause. ([incorrect_sound_sample.zip](https://github.com/thesofproject/sof/files/3066692/issue1251.zip))

### Impact
this blocks our release on whl.

**Comment by bkokoszx** [comment]
I believe that setting XTAL clock as a default clock on CNL will fix the problem (#1246). I will try also investigate what is a problem with PLL_FIXED (96 MHz) clock - I'm a little confused, because master/slave ssp with this clock passed.

**Comment by mengdonglin** [comment]
@xun2z Please share test steps. And please share kmesg and sof trace if there is any error.

**Comment by bkokoszx** [comment]
@mengdonglin @xun2z 
@zrombel has checked this issue with #1246 patch on our python tests and regression does not exist.

@xun2z 
Could you confirm that applying #1246 fixes this issue?

**Comment by xun2z** [comment]
confirm fixed on our HDA device
