### ISSUE TITLE
[FEATURE] IPC fuzzer.

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#1279]
**Is your feature request related to a problem? Please describe.**
IPC mechanism needs to be fuzzed to ensure continuity of service.

**Describe the solution you'd like**
Userspace IPC fuzzer that can load and "manufacture" IPC to send to FW running on Qemu

**Comment by lbetlej** [comment]
Is the goal to implement a custom user space fuzzer from scratch or to provide an easy connection for existing 3rd party fuzzers into SOF stack ?

**Comment by ranj063** [comment]
> Is the goal to implement a custom user space fuzzer from scratch or to provide an easy connection for existing 3rd party fuzzers into SOF stack ?

@lbetlej we're starting off with a very primitive fuzzer from scratch. But this will probably need to evolve to use a fuzzing library if suitable later on.

**Comment by lgirdwood** [comment]
@ranj063 I assume we will be good to merge our current fuzzer after IPC is done ?

**Comment by lgirdwood** [comment]
@ranj063 anything still pending here ? I'm assuming we are all done for initail fuzzer ?

**Comment by ranj063** [comment]
> @ranj063 anything still pending here ? I'm assuming we are all done for initail fuzzer ?

@lgirdwood yes we're done for the time being. I will add APL support next
