### ISSUE TITLE
Retrieve information about time since boot to provide the correct trace timestamps after system resume

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof#130]
After suspend/resume, the trace timestamps are reset to 0 and do not align with the kernel logs. 
We need this enhancement to be able to provide an offset with information about time since boot and offset the the trace timestamps accordingly.

**Comment by jajanusz** [comment]
@ranj063 Is issue solved with #1194 ?

**Comment by lgirdwood** [comment]
@bardliao can we close now ?

**Comment by bardliao** [comment]
> @bardliao can we close now ?

In my opinion, yes.
