### ISSUE TITLE
[FEATURE] pv flag should be passed to meu for signing

### ISSUE THREAD

**Issue by mmaka1** [thesofproject/sof#1310]
This flag should be another parameter (like priv key path) to enable pre- and post-pv signing.

**Comment by jajanusz** [comment]
@mmaka1 What should that flag do? Is it some bit in manifest that is 0/1 when it's pre/post-pv signing?

**Comment by mmaka1** [comment]
In case of post-pv signing, there should be `-mnpv true` appended to the meu args.

**Comment by jajanusz** [comment]
Enabled in #1384 , user is able to pass any flag that is needed, not just pv
