### ISSUE TITLE
[BUG] SOF HDA mode has errors when adding routes from sof-hda-generic.tplg

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof#1353]
**Describe the bug**
HDA mode has topology parsing errors. There is no source or sink widget are available. This can be observed in every linux booting time. As CNL/CFL/WHL share same binaries, kernel/firmware/topology files, same problem is observed in those platforms.

**To Reproduce**
I tested with daily build of 0430, but latest version of linux/sof project have same issue.
firmware image = sof-cnl.ri
topology = sof-hda-generic-2ch.tplg renamed to sof-hda-generic.tplg

Boot to linux with SOF HDA mode then dmesg.
[whl_sof-hda_booting.log](https://github.com/thesofproject/sof/files/3136225/whl_sof-hda_booting.log)

[    5.237850] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no source widget found for iDisp3 Tx
[    5.237851] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp3 Tx -> direct -> hifi3
[    5.237853] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no sink widget found for iDisp3 Tx
[    5.237854] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp3_out -> direct -> iDisp3 Tx
[    5.237855] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no source widget found for iDisp2 Tx
[    5.237856] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp2 Tx -> direct -> hifi2
[    5.237857] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no sink widget found for iDisp2 Tx
[    5.237858] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp2_out -> direct -> iDisp2 Tx
[    5.237860] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no source widget found for iDisp1 Tx
[    5.237860] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp1 Tx -> direct -> hifi1
[    5.237862] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no sink widget found for iDisp1 Tx
[    5.237862] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route iDisp1_out -> direct -> iDisp1 Tx
[    5.237867] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no source widget found for Analog CPU Playback
[    5.237867] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route Analog CPU Playback -> direct -> Analog Codec Playback
[    5.237869] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no sink widget found for Analog CPU Playback
[    5.237870] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route codec0_out -> direct -> Analog CPU Playback
[    5.237871] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no source widget found for Digital CPU Playback
[    5.237872] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route Digital CPU Playback -> direct -> Digital Codec Playback
[    5.237874] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no sink widget found for Digital CPU Playback
[    5.237874] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route codec1_out -> direct -> Digital CPU Playback
[    5.237876] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no source widget found for Alt Analog CPU Playback
[    5.237877] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route Alt Analog CPU Playback -> direct -> Alt Analog Codec Playback
[    5.237878] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no sink widget found for Alt Analog CPU Playback
[    5.237879] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route codec2_out -> direct -> Alt Analog CPU Playback
[    5.237881] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no source widget found for Analog CPU Capture
[    5.237882] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route Analog CPU Capture -> direct -> codec0_in
[    5.237883] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no sink widget found for Analog CPU Capture
[    5.237884] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route Analog Codec Capture -> direct -> Analog CPU Capture
[    5.237885] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no source widget found for Digital CPU Capture
[    5.237886] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route Digital CPU Capture -> direct -> codec1_in
[    5.237888] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no sink widget found for Digital CPU Capture
[    5.237889] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route Digital Codec Capture -> direct -> Digital CPU Capture
[    5.237890] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no source widget found for Alt Analog CPU Capture
[    5.237891] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route Alt Analog CPU Capture -> direct -> codec2_in
[    5.237893] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: no sink widget found for Alt Analog CPU Capture
[    5.237893] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: Failed to add route Alt Analog Codec Capture -> direct -> Alt Analog CPU Capture

**Comment by xiulipan** [comment]
@fredoh9 
Maybe you can try to solve this by adding something in `sof-hda-generic.m4` and `sof-hda-generic-idisp.m4` like the following to remove them
https://github.com/thesofproject/sof/blob/6e4faef8e7fea2e4ec71d9bc012680b446c7f8e5/tools/topology/sof-glk-rt5682.m4#L172-L192
