### ISSUE TITLE
[BUG] UAPI tokens.h not aligned between kernel and firmware

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#1378]
**Describe the bug**

The SOF repo did not follow the kernel changes for the effect->process change, please fix. we should not have any EFFECT_TYPE anywhere in the firmware, it's PROCESS_TYPE now.

Also the definitions for SCHED_PERIOD/DEADLINE and TIME_DOMAIN/TIMER were not updated.

What a glorious mess.

**Comment by wenqingfu** [comment]
@michalgrodzicki to reassign

**Comment by plbossart** [comment]
@juimonen can you chime and check with @jajanusz what needs to be done?

**Comment by juimonen** [comment]
@plbossart @jajanusz 
this should do it, but please you check it also:
https://github.com/thesofproject/sof/pull/1402

as I see these are defined correctly in tokens.m4 which topology uses.

**Comment by jajanusz** [comment]
WIP #1381
