### ISSUE TITLE
[FEATURE]trace point reorder in platform_init function

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof#1388]
**Is your feature request related to a problem? Please describe.**
The trace point value now used in `platform_init` is out of order. After some refine of codec, there leave some blank trace point as well as miss trace point. The trace point is now misleading for new platform enable and QEMU debug.

**Describe the solution you'd like**
The trace point should be grouped and increase in order and did not miss any init function track.

**Comment by bkokoszx** [comment]
@xiulipan 
Do you mean for example that TRACE_BOOT_SYS_SCHED (0x3500) appears after TRACE_BOOT_PLATFORM_CLOCK (0x4150)?

**Comment by lgirdwood** [comment]
@bkokoszx yes, the ordering should be sequential with gaps for future use.
