### ISSUE TITLE
[FEATURE] Allow updating EQs during playback/capture

### ISSUE THREAD

**Issue by singalsu** [thesofproject/sof#1391]
**Is your feature request related to a problem? Please describe.**

Currently the EQs can be updated by sof-eqctl only when the pipeline they belong to is idle.

In audio tuning scenario it is desirable to on-the-fly re-configure the EQs to quickly measure or subjectively evaluate the impact of new tuning without need to start/stop system audio servers etc.

**Describe the solution you'd like**

Therefore supporting the change in runtime when the resources (RAM) needed by new tuning are equal or less compared old new tuning the switch should be supported. An attempt to use more resources can be prevented if there's risk that buffers re-allocation consumes too much time.

**Describe alternatives you've considered**

No alternatives seen at the moment.

**Additional context**

Due to only targeting audio tuning engineer's needs this enhancement does not suggest a perfectly glitch-free transition. Especially the recursive filters need to be reset to ensure stable operation. Due to the state variables reset there will some small break in audio when re-configured.

**Comment by singalsu** [comment]
@lgirdwood @dbogdzix I just created this enhancement to address the closed Docs issue #116.

**Comment by lgirdwood** [comment]
@singalsu I've made this P1 for v1.5, the EQ should accept the new coefficients and only update them when after copy() completes.
Btw, I'm assuming updating the coefficients here is equivalent of adjusting EQ sliders on a traditional HiFi ?

**Comment by singalsu** [comment]
@lgirdwood Yep, the update on the fly can be made if the new configuration request is now larger than previous. It's not in practice a severe limitation, in filter tuning the IIR or FIR order can be kept the same. I'm assuming we would not do free()-malloc() during playback.

We don't have direct slider adjustable EQ type in firmware. But it could be supported by having some computing in user space. For IIR it would be quite simple (for parametric EQ or fixed bands "GUI") and for FIR (arbitrary response "GUI") need IFFT in user space.

**Comment by lgirdwood** [comment]
@singalsu sounds like a topic for the audio conference. @plbossart I guess we need alsamixer/alsalib support for binary TLV sliders for EQ type users.

**Comment by plbossart** [comment]
That wasn't what I was suggesting, rather that the application can provide new binary data at any time, and the the firmware takes care of smoothing transitions to avoid pop-clicks.

**Comment by singalsu** [comment]
I've now started working with this feature.

**Comment by singalsu** [comment]
SOF PR #2065 implements this feature for IIR EQ type. I'll do the same for FIR after the solution for IIR is reviewed.

**Comment by singalsu** [comment]
Status update: This is half done. I still need to make this for FIR. ETA ww02 2020.

**Comment by singalsu** [comment]
SOF PR #2259 will complete the work for this enhancement issue when it is merged.

**Comment by singalsu** [comment]
This feature is complete since SOF commit c0b9b4057e4dc408c9af5c9695b9d052ab1d3702 .

**Comment by singalsu** [comment]
This is OK to close!
