### ISSUE TITLE
[FEATURE] cAVS (apl, cnl, icl, ...) clk defs need cleanup and deduplication

### ISSUE THREAD

**Issue by mmaka1** [thesofproject/sof#1398]
1. Static platform specific data and defs are mixed with the defs related to run-time clock settings.
2. Most of the cAVS platforms code may be de-duplicated and moved to a common headers.

There is experimental code (requires testing and cleanup of the default clock setting at boot complete) available here:
https://github.com/mmaka1/sof/tree/cavs-clk-def-dedup

**Comment by lgirdwood** [comment]
@mmaka1 ACK.

**Comment by jajanusz** [comment]
@mmaka1 Done in #1431 ?
