### ISSUE TITLE
[BUG] APL GCC toolchain uses older version from Cadence

### ISSUE THREAD

**Issue by tlauda** [thesofproject/sof#1401]
**Describe the bug**
APL GCC toolchain uses older version from Cadence, which causes compilation failure with the latest updated headers.

**Comment by lgirdwood** [comment]
@tlauda I've updated locally but I still see the same issues. Can you confirm the code is generated for CNL ?

**Comment by tlauda** [comment]
@lgirdwood I haven't checked the binary, but compared GCC build logs in CI and they are basically the same, meaning same parameters are used. Also I've checked make files and other stuff and everything is the same for both APL and other platforms. I don't see any other root cause than toolchain.

**Comment by lgirdwood** [comment]
@tlauda thanks, this one is confusing. I need to check again, I rebuilt APL GCC with the updates but I've lost all this work as my NUC has died. I'll revisit when I'm back from travelling.

**Comment by jajanusz** [comment]
@lgirdwood @tlauda ping

**Comment by lgirdwood** [comment]
@jajanusz this got stuck in my NUC failure. Will fix for 1.4
