### ISSUE TITLE
[BUG] Userspace structures in uapi/user are not using ABI header 

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#1403]
**Describe the bug**
Userspace has no way of informing FW or driver of ABI used for binary kcontrol data.

**Expected behavior**
Userspace will use struct sof_abi_hdr as header for all binary kcontrol structures.

**Impact**
showstopper. will cause random breakage in the future.

Needs added to FW headers, kernel headers and userspace tools.

**Comment by lgirdwood** [comment]
@plbossart fyi, needs to be done prior to next kernel release.

**Comment by lgirdwood** [comment]
@plbossart I see this has just been removed from kernel uapi, so it just a FW/tool change now.

**Comment by wenqingfu** [comment]
Liam agreed to fix it

**Comment by lgirdwood** [comment]
@singalsu I'm looking for users of the structures in include/user/eq.h but cant find any non firmware users ? How is the ABI currently specified for this data ?

**Comment by lgirdwood** [comment]
@singalsu one more thing, I also cant see where eqctl inserts ABI information, I guess this in the .txt files ?

**Comment by ranj063** [comment]
@lgirdwood yes the ABI is manually added into the txt files

**Comment by lgirdwood** [comment]
Merged #1517

**Comment by singalsu** [comment]
@lgirdwood The EQ tool gets the ABI via function SOF/tools/tune/eq/eq_get_abi.m. Currently the version is hard coded there manually to 3.0.0.

I've been wondering if tools like sof-ctl could return the ABI header in usable form for Matlab code. The C headers can't be used for other languages easily.

**Comment by lgirdwood** [comment]
@singalsu I intend to add some features requests for this.
