### ISSUE TITLE
[IMPROVEMENT] Add IPC structs' fields documentation

### ISSUE THREAD

**Issue by marcinx-zielinski** [thesofproject/sof#1429]
We need to have our IPCs documented to know clearly what is the purpose/role of and possibly constraints on each of the IPC struct's fields. For example, now we have:
```
struct sof_ipc_comp_reply {
    struct sof_ipc_reply rhdr;
    uint32_t id;
    uint32_t offset;
} __attribute__((packed));
```
This doc assumes that a programmer has in-depth code knowledge: what are _offset_, _id_? Another example:
```
struct sof_ipc_pipe_ready {
    struct sof_ipc_cmd_hdr hdr;
    uint32_t comp_id;
} __attribute__((packed));
```
What is the acceptable range of _comp_id_?

**Comment by lgirdwood** [comment]
@lbetlej I'll move this into v1.6

**Comment by lgirdwood** [comment]
This is partially done. Move to v1.7.

**Comment by lgirdwood** [comment]
@mwasko @mrajwa how are we now for IPC field docs ? I've seen updates but not sure if we can close yet ?

**Comment by mrajwa** [comment]
Sorry I have no clue, @mwasko do you follow this?

**Comment by lgirdwood** [comment]
Now started, some structure have fields for doxygen but some are still missing. To be completed in v1.9 as part IPC abstraction.

**Comment by kv2019i** [comment]
I'll go ahead and close this even if this was only partially done.
