### ISSUE TITLE
[BUG] Samples cut from recording

### ISSUE THREAD

**Issue by wwittbrx** [thesofproject/sof#1466]
### Description

All but first iteration of master-slave playback and capture will return a wave with first sample cut. This happens for most of the available formats with few exceptions:

TestPtpSimpleLoopbackMasterPlayback16000Hz32b32b8ch
TestPtpSimpleLoopbackMasterPlayback24000Hz16b16b8ch
TestPtpSimpleLoopbackMasterPlayback24000Hz32b32b8ch
TestPtpSimpleLoopbackMasterPlayback48000Hz16b16b8ch
TestPtpSimpleLoopbackMasterPlayback48000Hz32b32b4ch
TestPtpSimpleLoopbackMasterPlayback48000Hz32b32b8ch

Topology for this test uses 2 SSP ports, one set as master, second as slave. Ports are connected by wire to form external loopback.

```
Host -> Buff -> SSP0 (master, playback)
                 ||
Host <- Buff <- SSP1 (slave, capture)
```

Stream loop:

1. Create playback and capture streams
2. Capture stream trigger start (note that this on slave pipe, which means it won't really start until playback stream is triggered, possible race here)
3. Playback stream trigger start
4. Wait for file to stop streaming
5. Playback stream trigger pause, trigger stop, free
6. Capture stream trigger pause, trigger stop, free
7. Repeat

### Recipe

**FW**
https://github.com/thesofproject/sof/commits/master
https://github.com/thesofproject/sof/commit/df48bfce777fff094c1257965c87c55c5b9ba0ad

**Platform**
APL RVP

### Reproduction steps

1. Run all test cases from test_01_ptp_simple_loopback_master_playback.py with playback_iterations set to 2

### Logs and files

Example for test case TestPtpSimpleLoopbackMasterPlayback8000Hz16b16b1ch with playback_iterations set to 5. In the example first wave is recorded correctly. Each subsequent iteration misses first sample.

![image](https://user-images.githubusercontent.com/41670517/58171686-d4e18980-7c96-11e9-9d94-f9c650f4c5e7.png)

[dma_trace_1_sink.log](https://github.com/thesofproject/sof/files/3207172/dma_trace_1_sink.log)

**Comment by lgirdwood** [comment]
@wwittbrx good find. What is the capture source ? dmic, SSP, etc and what is the pipeline. The one thing that occurs  to me is the SSP/DMIC FIFO could be missing the first sample if there is a race at stream start ?

**Comment by wwittbrx** [comment]
I have added more information about topology and stream operations in main comment for visibility. A race is possible, but it is interesting to me that first iteration always has all samples and every subsequent one does not. I have run this for about 150 iterations to check that it always misses first sample. If this was a race I think we would see first iteration sometimes fail and subsequent iterations sometimes pass.

**Comment by lgirdwood** [comment]
@wwittbrx ok, is this digital or analog loopback, you mentioned a wire ? This could also be a race at shutdown where a stale sample is left in a FIFO ?

**Comment by wwittbrx** [comment]
This is analog loopback
