### ISSUE TITLE
[BUG] KD sporadic glitches

### ISSUE THREAD

**Issue by wwittbrx** [thesofproject/sof#1467]
### Description

Stress tests of KD with DMIC test case reveal sporadic glitches with reproduction rate of ~0.2%. Logs and waves of failed iterations attached.

![image](https://user-images.githubusercontent.com/41670517/58243998-05d2c480-7d52-11e9-837a-a32ec1d00f45.png)

![image](https://user-images.githubusercontent.com/41670517/58244094-3581cc80-7d52-11e9-8037-74cc841678fb.png)

### Recipe

**FW**
https://github.com/thesofproject/sof/tree/glk-012-stable-branch
https://github.com/thesofproject/sof/commit/ddde684d7296f3059e195d4dfe9c832367fcddfb

**Platform**
APL RVP

### Reproduction steps

1. Run test_03_kd_with_dmic.py with iterations set to 1000 (may need more iterations for reproduction depending on luck)

### Logs and files

[logs.zip](https://github.com/thesofproject/sof/files/3207463/logs.zip)

**Comment by lgirdwood** [comment]
@wwittbrx best to always paste the error message from the logs in the description (only a few lines needed), that ways it obvious whether its a pipeline, dmic, dma bug etc. The issue subject can also be renamed to reflect the error in the logs.

**Comment by wwittbrx** [comment]
Unfortunately the logs don't contain any errors so I couldn't do that. I have added wave screenshots for visibility without going into logs zip. I am also currently stress testing simple DMIC capture to check if this is indeed KD related or just DMIC related. Will update as soon as I am confident with findings.

**Comment by wwittbrx** [comment]
After over a 1000 iterations of simple DMIC capture and not detecting any glitches I would assume that the problem is with KD itself.

**Comment by mrajwa** [comment]
@wwittbrx, just to clarify, glitches occur not only in first 2100 ms but also later?

**Comment by mrajwa** [comment]
also, can you provide information about history_depth and preamble you used for this test?

**Comment by mrajwa** [comment]
I haven't debug this issue yet because we have higher priority issue (the occurrence of this one is very low + it wasn't noticed outside slim driver). However at first glance it suggest me a **dmic** issue, especially when I look at the first screenshot, the waveform is cut but then restores with **damped** amplitude. After another while it is normal again. @singalsu what do you think about this?

**Comment by singalsu** [comment]
@mrajwa I'll take a look into the wavs, thanks for attaching those as well.

**Comment by singalsu** [comment]
The only thing looking like this a buggy driver could do would be to launch in mid-recording the gain ramp (shouldn't happen). Adding a trace print to function dmic_work() would show in trace when the DMIC HW gain registers are updated.

Though gain ramp controls left and right channels simultaneously and in this code the channels are updated next to each other so something higher priority only cause the code to pause.

It this test acoustical or done with DMIC injector? Could the injector cause issues (is it slave to the DMIC interface like a real microphone is)?

**Comment by singalsu** [comment]
Based on log file seems that mic clock is set to 800 kHz. If the test was acoustical with real microphone it would be good to check the datasheet of the microphone that (a low-power mode clock) 800 kHz is within normal operation range.

**Comment by wwittbrx** [comment]
Test is performed with DMIC injector. As I said in the earlier comment, I don't think the problem is with DMIC itself, as I stress tested DMIC and glitches do not happen without KD pipeline. Preamble time is set to 500, and history depth is set to 0, so I guess it takes the default value.

**Comment by lgirdwood** [comment]
@wwittbrx do we have a meaningful reproduction rate or are there methods to increase the reproduction rate ? It could be KD logic related since the sine waveforms do seem to join up nicely from your screenshot. i.e. we stop processing for several periods then restart.

**Comment by wwittbrx** [comment]
Reproduction rate is ~0.2%. I don't know of any methods to increase it. We could maybe reduce individual iteration execution time to run stress tests faster, I will provide more info if successful.

**Comment by mrajwa** [comment]
> Preamble time is set to 500, and history depth is set to 0

@wwittbrx, it means detection is active after 500ms and you will drain **zero** bytes from history buffer, is that what you really want in this test? Also the default `history depth` shall be set to 2100 ms.

**Comment by wwittbrx** [comment]
@mrajwa I meant that I don't set history depth at all in this test. That means that in the IPC we send zeroes for this field. I was under the impression that if we do that, we will fall back to default defined in FW code, which as you said is 2100.

**Comment by mrajwa** [comment]
Still reproducible?

**Comment by wwittbrx** [comment]
This issue cannot be reproduced with d1f4320, closing.
