### ISSUE TITLE
[BUG] Logger files need license info

### ISSUE THREAD

**Issue by jajanusz** [thesofproject/sof#1498]
Files below ~~are missing licenses~~ have GPL License. Please add BSD license + copyright. 

List of files:
```
./sof/tools/logger/convert.c
./sof/tools/logger/logger.c
./sof/tools/logger/convert.h

```

**Comment by jajanusz** [comment]
@lgirdwood @plbossart  We have GPL license in logger, should it be like this?
The same goes for rimage, should it be gpl?

**Comment by lgirdwood** [comment]
@jajanusz there is no reason why it needs to be GPL. All contributions to logger are from Intel so please update to BSD.

**Comment by akloniex** [comment]
License has been updated. PR was merged.
@jajanusz please close this issue.

**Comment by jajanusz** [comment]
@akloniex thanks
Added in #1505
