### ISSUE TITLE
[BUG] GDB files need license info 

### ISSUE THREAD

**Issue by jajanusz** [thesofproject/sof#1499]
Files below are missing licenses. Please add BSD license + copyright. Actually these files without that shouldn't be even in repo. Blocker for #1458 

Sorry for troubling you, but author should apply that initial license. I don't know if I can touch these files without your permission.

List of files:
```
./sof/src/gdb/ringbuffer.c
./sof/src/include/sof/gdb/ringbuffer.h
./sof/src/include/sof/gdb/gdb.h

```

**Comment by lgirdwood** [comment]
@mrajwa this is blocker for v1.3 release.
