### ISSUE TITLE
Trace: The trace output is not displayed when it arrives

### ISSUE THREAD

**Issue by singalsu** [thesofproject/sof#157]
The trace in APL platform doesn't update the display per trace event but in larger blocks only when more trace data arrives. E.g. it is not possible to see volume trace events for latest alsamixer key press for PGA gains. Or as other example I can't see DMIC capture trace events before I run another capture.

This makes debugging harder when the needed information need to be looked back from much earlier trace data.

**Comment by lgirdwood** [comment]
Trace should be sent every 500ms or when buffer > half full, whichever happens first. @RanderWang can you check.

**Comment by RanderWang** [comment]
two issue for this case. I will create two PRs for this issue

**Comment by xiulipan** [comment]
fixed by #204

**Comment by keqiaozhang** [comment]
Confirmed this issue is fixed by thesofproject/sof/pull/204。
