### ISSUE TITLE
[FEATURE] Linker Section alignment for BYT, HSW, IMX8

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#1576]
**Is your feature request related to a problem? Please describe.**
Linker section alignment can be optimised like https://github.com/thesofproject/sof/pull/1568 for CAVS targets.

**Describe the solution you'd like**
Same optimisation for non CAVS targets.

**Comment by dbaluta** [comment]
@paulstelian97 can you please have a look at this?

**Comment by dbaluta** [comment]
@paulstelian97 Thanks! So, this is resolved for IMX8. Intel people need to have a look for byt and hsw.

**Comment by lgirdwood** [comment]
@dbaluta great, @mengdonglin this one is trivial, needed for non CAVS versions.

**Comment by lgirdwood** [comment]
@mengdonglin anyone with a free hour to do this for v1.4rc2 ?

**Comment by lgirdwood** [comment]
@mengdonglin ping

**Comment by lgirdwood** [comment]
Seems not needed on older platforms and done on the newer ones. Closing.
