### ISSUE TITLE
[FEATURE] Allocator custom block mappings via kconfig

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#1577]
**Is your feature request related to a problem? Please describe.**
Allow allocator HEAP pool and block mappings to be customised via Kconfig.

**Describe the solution you'd like**
Kconfig menu would allow for sizing of HEAP pools like IMR, LPSRAM, uncache, etc (size == 0 means pools is disabled) and also allow the block mappings for each size to be specified. Kconfig not expected to validate the selection (unless it can) as compiler should throw an error if pre-processing fails.

**Comment by lgirdwood** [comment]
Supported in Zephyr. Moving to v1.9 as part f Zephyr integration.

**Comment by kv2019i** [comment]
Moving to v2.6 for evalution. This is partially addressed with current SOF Zephyr support, but the heap sizes are still not configurable via Kconfig.

**Comment by lgirdwood** [comment]
Fixed by Zephyr.
