### ISSUE TITLE
[FEATURE] Allow DMIC to accept 24/32 fifo bits config

### ISSUE THREAD

**Issue by wwittbrx** [thesofproject/sof#1591]
**Is your feature request related to a problem? Please describe.**

This feature is required for keyword detection pipelines with 24/32 format. Currently when trying to configure DMIC this way we get error: fifo_bits EINVAL.

**Describe the solution you'd like**

Add support for configuring DMIC for 24/32 format capture.

**Comment by singalsu** [comment]
The DMIC HW supports only S16_LE and S32_LE compatible data formats so the conversion to S24_4LE would need to happen in FW.

**Comment by lgirdwood** [comment]
@singalsu @wwittbrx can be done by adding volume in the topology. i.e. 32bit DMIC with volume converting 32 -> 24.

**Comment by tlauda** [comment]
Currently it will be supported by adding volume and later on we will do pcm conversion in some other component (after converter and volume separation).
