### ISSUE TITLE
BCLK jitters with m/n dividers

### ISSUE THREAD

**Issue by sathyap-chrome** [thesofproject/sof#1623]
**Describe the bug**
With m/n divider patches taken in, we used the attached topology to get below configuration:
BCLK = 128fs with TDM PCM B format, 4ch, 32bit/ch

The BCLK is expected to be 6.144 Mhz.
Measurements on board showed jitters on BCLK and also variance between 6-8 Mhz.

Find the attached scope shot too.

Provide more details on if the variance and jitters is expected and if it is, what are possible ways to reduce the same.

**To Reproduce**
Steps to reproduce the behavior: (e.g. list commands or actions used to reproduce the bug) 
Use configuration in Topology and FW with below configuration & Check BCLK.

**Reproduction Rate**
Customer reported its seen all the time, Yet to verify on our end.

**Expected behavior**
BCLK with better accuracy and less jitter

**Impact**
Help understand the limitations if any of the solution and also any changes needed on HW.

**Environment**
1) SOF FW & topology Commit :
abe892c2b8ad ssp: add M/N divider
dc6a38858ec0 ssp: SCR comment
43ae5a072cc7 topology: Add CML topology support for rt1011 variant -Topology attached for reference
f82d9dad7bd4 topology: add volume component to demux topology - cml_drop_004 

2) Name of the topology file
DAI config provided at the end.

3) Name of the platform(s) on which the bug is observed.
Currently on customer board using the topology. will try to replicate on RVP tomorrow

4) Reproducibility Rate. If you can only reproduce it randomly, it’s useful to report how many times the bug has been reproduced vs. the number of attempts it’s taken to reproduce the bug.

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

Scope shot of BCLk: 
![scope_3_BCLK](https://user-images.githubusercontent.com/48010719/60982769-63e55680-a356-11e9-88fa-3190bab28abe.png)

DAI config used -:

DAI_CONFIG(SSP, 1, 5, SSP1-Codec,
	SSP_CONFIG(**DSP_B**, SSP_CLOCK(mclk, 24000000, codec_mclk_in),
		SSP_CLOCK(bclk, **6144000**, codec_slave),
		SSP_CLOCK(fsync, 48000, codec_slave),
		SSP_TDM(**4**, **32**, 3, 3),
		SSP_CONFIG_DATA(SSP, 1, **32**)))

**Comment by abonislawski** [comment]
This is how it works. The average frequency will be 6.144MHz. 
![m6144ch4](https://user-images.githubusercontent.com/45165721/61036030-8b750700-a3c8-11e9-80a6-05305a1d3eb5.png)
