### ISSUE TITLE
[BUG] Glitches occured during ERS tests randomly.

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/sof#1655]
**Describe the bug**
Glitches was detected in EchoReferenceSignal python tests on random freq/sample&container size and channels count

**To Reproduce**
Run fw_14_echo_reference_signal/test_00_ptp_ers.py.
Mostly the test repetition passed.

**Reproduction Rate**
About 15% from 400 iterations.

**Expected behavior**
clean sound, no glitches, no noises

**Impact**
noise can be heard

**Environment**
1. Windows/python tests:
```
                           pipe_cap
                        +--------------------+
        +----------+    | +------+   +-----+ |   +----+
        | Host cap |<-----|Buffer|<--| Dai |<----|SSP0|
        +----------+    | +------+   +-----+ |   +----+
                        +--------------------+    |  |
                                                  |  |
                            pipe_plb              |  |
                        +--------------------+    |  |
        +----------+    | +------+   +-----+ |   +----+
        | Host plb |----->|Buffer|-->| Dai |---->|SSP0|
        +----------+    | +--||--+   +-----+ |   +----+
                        +----||--------------+
                             ||
                       +-------------+
                       | Buf2Buf DMA |
                       +-------------+
                             ||
                             ||  pipe_echo
                        +----||------------------+
        +-----------+   | +--\/----+   +-------+ |
        | Host echo |<----| Buffer |<--| V Dai | |
        +-----------+   | +--------+   +-------+ |
                        +----------------------- +
```

        Standard SSP loopback for verification purposes;
        Virtual Dai (ERS type) with Buffer-to-Buffer DMA to serve as echo reference signal provider;
2. Platform: WHL-RVP/I2S mode.
3. Firmware:
branch: cml-006-drop-stable
commit: 8ceb5b6e

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/41113230/61526464-bee41100-aa1a-11e9-9440-748881493a1f.png)

**Log**

[dma_trace_1_sink.log](https://github.com/thesofproject/sof/files/3410515/dma_trace_1_sink.log)
[dma_trace_1_sink.bin.txt](https://github.com/thesofproject/sof/files/3410516/dma_trace_1_sink.bin.txt)

**Comment by tlauda** [comment]
@emilchudzik To be retested when feature is finally implemented on master.
