### ISSUE TITLE
[BUG] Glitches on stream when another stream is being started

### ISSUE THREAD

**Issue by zrombel** [thesofproject/sof#1665]
**Description**
When stream is being stared a glitch can be found on already running stream.
Example of three playback pass-through pipelines:
Sending trigger start to all pipelines:
2019-07-23 13:34:55,303 | Sending StreamTrigStart (60040000, 00000000)
2019-07-23 13:34:55,709 | Sending StreamTrigStart (60040000, 00000000)
2019-07-23 13:34:55,975 | Sending StreamTrigStart (60040000, 00000000)
Time delta between first and last TrigStart ipc is 672ms.
And on wave recorded on first pipeline glitch can be seen after approximately 660ms from start:
![image](https://user-images.githubusercontent.com/40820404/61709514-bd368800-ad4f-11e9-929d-39193d8512ac.png)

![image](https://user-images.githubusercontent.com/40820404/61709789-45b52880-ad50-11e9-873c-fce255fef039.png)

**To Reproduce**
Start consecutive streams on multi pipeline topology.

**Reproduction Rate**
~30%

**Environment**
1) Branch: Master, commit: a513ac7251b16aa9be0f443af091c40f7b8cf084 
2) All platforms

**Comment by tlauda** [comment]
@zrombel Pleas verify with master.

**Comment by wenqingfu** [comment]
@zrombel ping for update...

**Comment by zrombel** [comment]
Bug cannot be reproduce on FW commit 89ef0 of master brach. Closing Issue.
