### ISSUE TITLE
[FEATURE] FW boot metadata needs to include compiler name and version

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#1678]
**Is your feature request related to a problem? Please describe.**
We need to be able to determine firmware compiler and compiler version from firmware boot metadata.

**Describe the solution you'd like**
Some non debug fields added to FW boot structure.

**Comment by lgirdwood** [comment]
@ktrzcinx I guess this can be closed now ?

**Comment by ktrzcinx** [comment]
Yes
