### ISSUE TITLE
[BUG]support Baytrail-CR ssp0 aif1?

### ISSUE THREAD

**Issue by youling257** [thesofproject/sof#1709]
<6>[    4.577860] bytcr_rt5640 bytcr_rt5640: BIOS Routing: AIF1 connected
<6>[    4.596005] bytcr_rt5640 bytcr_rt5640: quirk IN3_MAP enabled
<6>[    4.601385] bytcr_rt5640 bytcr_rt5640: quirk realtek,jack-detect-source 2
<6>[    4.606758] bytcr_rt5640 bytcr_rt5640: quirk realtek,over-current-threshold-microamp 2000
<6>[    4.612543] bytcr_rt5640 bytcr_rt5640: quirk realtek,over-current-scale-factor 1
<6>[    4.618121] bytcr_rt5640 bytcr_rt5640: quirk DIFF_MIC enabled
<6>[    4.623439] bytcr_rt5640 bytcr_rt5640: quirk SSP0_AIF1 enabled
<6>[    4.628744] bytcr_rt5640 bytcr_rt5640: quirk MCLK_EN enabled
<6>[    4.634016] bytcr_rt5640 bytcr_rt5640: info: override FE DAI link SSP2-Codec
<6>[    4.666478] sof-audio-acpi 80860F28:00: Topology: ABI 3:9:0 Kernel ABI 3:8:0
<4>[    4.685722] sof-audio-acpi 80860F28:00: warn: topology ABI is more recent than kernel
<4>[    4.691715] sof-audio-acpi 80860F28:00: warning: widget type 1 name codec_out0 not handled
<4>[    4.704825] sof-audio-acpi 80860F28:00: warning: widget type 7 name ssp2 Rx not handled
<4>[    4.714369] sof-audio-acpi 80860F28:00: warning: widget type 1 name codec_out1 not handled
<4>[    4.724213] sof-audio-acpi 80860F28:00: warning: widget type 7 name ssp2 Tx not handled
<4>[    4.730971] sof-audio-acpi 80860F28:00: warning: widget type 0 name codec_in0 not handled
<4>[    4.743652] sof-audio-acpi 80860F28:00: warning: widget type 0 name codec_in1 not handled
<4>[    4.757498] sof-audio-acpi 80860F28:00: ASoC: Parent card not yet available, widget card binding deferred
<3>[    4.782728] bytcr_rt5640 bytcr_rt5640: ASoC: no source widget found for modem_out
<3>[    4.795584] bytcr_rt5640 bytcr_rt5640: ASoC: Failed to add route modem_out -> direct -> ssp0 Tx
<3>[    4.801617] bytcr_rt5640 bytcr_rt5640: ASoC: no source widget found for ssp0 Rx
<3>[    4.807070] bytcr_rt5640 bytcr_rt5640: ASoC: Failed to add route ssp0 Rx -> direct -> modem_in
<3>[    4.812236] bytcr_rt5640 bytcr_rt5640: ASoC: no source widget found for ssp0 Tx
<3>[    4.817771] bytcr_rt5640 bytcr_rt5640: ASoC: Failed to add route ssp0 Tx -> direct -> AIF1 Playback
<3>[    4.823020] bytcr_rt5640 bytcr_rt5640: ASoC: no sink widget found for ssp0 Rx
<3>[    4.827974] bytcr_rt5640 bytcr_rt5640: ASoC: Failed to add route AIF1 Capture -> direct -> ssp0 Rx
<3>[    4.832905] bytcr_rt5640 bytcr_rt5640: ASoC: failed to init SSP2-Codec: -19
<3>[    4.837794] bytcr_rt5640 bytcr_rt5640: ASoC: failed to instantiate card -19
<1>[    4.842970] BUG: kernel NULL pointer dereference, address: 0000000000000040
<1>[    4.847683] #PF: supervisor read access in kernel mode
<1>[    4.852367] #PF: error_code(0x0000) - not-present page
<6>[    4.857027] PGD 80000000794a0067 P4D 80000000794a0067 PUD 794a1067 PMD 0 
<4>[    4.861719] Oops: 0000 [#1] PREEMPT SMP PTI
<4>[    4.866418] CPU: 3 PID: 1188 Comm: ueventd Not tainted 5.3.0-rc3-android-x86_64+ #1
<4>[    4.871165] Hardware name: Insyde ONDA Tablet/ONDA Tablet, BIOS ONDA.D890HBBNR0A 03/11/2015
<4>[    4.875935] RIP: 0010:rt5640_set_jack+0x197/0x1f0 [snd_soc_rt5640]
<4>[    4.880720] Code: 05 d7 41 c6 44 24 5a 01 eb 8b 8b 7d 1c e8 a1 74 a0 d6 4c 89 ef e8 49 a4 9c d6 48 8d 7d 70 e8 50 a4 9c d6 48 8b 85 e8 00 00 00 <f6> 40 40 02 75 14 48 c7 85 e8 00 00 00 00 00 00 00 31 c0 5b 5d 41
<4>[    4.885713] RSP: 0018:ffffb4b50055f990 EFLAGS: 00010286
<4>[    4.890688] RAX: 0000000000000000 RBX: ffff9f5d76dfe818 RCX: 0000000000000000
<4>[    4.895650] RDX: 0000000000000001 RSI: 0000000000000000 RDI: ffff9f5d76d3b088
<4>[    4.900626] RBP: ffff9f5d76d3b018 R08: ffff9f5dba438480 R09: ffff9f5dba438598
<4>[    4.905597] R10: 0000000000000000 R11: ffffffff97e39488 R12: 0000000000000000
<4>[    4.910550] R13: ffff9f5d76d3b0e0 R14: 0000000000000001 R15: ffffffffc00eb5a0
<4>[    4.915546] FS:  0000000000000000(0000) GS:ffff9f5dbb780000(0063) knlGS:00000000081cd0b4
<4>[    4.920554] CS:  0010 DS: 002b ES: 002b CR0: 0000000080050033
<4>[    4.925569] CR2: 0000000000000040 CR3: 0000000036dcc000 CR4: 00000000001006e0
<4>[    4.930590] Call Trace:
<4>[    4.935622]  soc_cleanup_component+0x12/0x80
<4>[    4.940645]  soc_remove_link_components.isra.14+0x47/0x60
<4>[    4.945712]  soc_cleanup_card_resources+0xff/0x320
<4>[    4.950801]  snd_soc_instantiate_card+0x533/0xc90
<4>[    4.955881]  ? __kmalloc_track_caller+0x1b9/0x200
<4>[    4.960928]  snd_soc_register_card+0x14e/0x170
<4>[    4.965901]  devm_snd_soc_register_card+0x3c/0x80
<4>[    4.970750]  snd_byt_rt5640_mc_probe.cold.8+0x57d/0x615 [snd_soc_sst_bytcr_rt5640]
<4>[    4.975503]  platform_drv_probe+0x35/0x80
<4>[    4.980109]  really_probe+0xf7/0x3a0
<4>[    4.984586]  driver_probe_device+0x5d/0x100
<4>[    4.988918]  device_driver_attach+0x4f/0x60
<4>[    4.993143]  __driver_attach+0x92/0x140
<4>[    4.997256]  ? device_driver_attach+0x60/0x60
<4>[    5.001226]  ? device_driver_attach+0x60/0x60
<4>[    5.005150]  bus_for_each_dev+0x77/0xc0
<4>[    5.009088]  bus_add_driver+0x1b3/0x1f0
<4>[    5.013021]  ? 0xffffffffc008d000
<4>[    5.016935]  driver_register+0x6b/0xb0
<4>[    5.020852]  ? 0xffffffffc008d000
<4>[    5.024773]  do_one_initcall+0x4f/0x224
<4>[    5.028724]  ? __vunmap+0x21d/0x250
<4>[    5.032642]  do_init_module+0x5a/0x220
<4>[    5.036418]  load_module+0x2461/0x25c0
<4>[    5.040062]  ? __se_sys_finit_module+0xbe/0xf0
<4>[    5.043589]  __se_sys_finit_module+0xbe/0xf0
<4>[    5.046967]  do_fast_syscall_32+0x8e/0x250
<4>[    5.050321]  entry_SYSENTER_compat+0x7c/0x8e
<4>[    5.053640] Modules linked in: snd_soc_sst_bytcr_rt5640(+) snd_soc_rt5640 snd_soc_rl6231 snd_intel_sst_acpi snd_intel_sst_core snd_soc_sst_atom_hifi2_platform
<4>[    5.057161] CR2: 0000000000000040
<4>[    5.060694] ---[ end trace ab3a533ae54fd57f ]---
<4>[    5.064228] RIP: 0010:rt5640_set_jack+0x197/0x1f0 [snd_soc_rt5640]
<4>[    5.067805] Code: 05 d7 41 c6 44 24 5a 01 eb 8b 8b 7d 1c e8 a1 74 a0 d6 4c 89 ef e8 49 a4 9c d6 48 8d 7d 70 e8 50 a4 9c d6 48 8b 85 e8 00 00 00 <f6> 40 40 02 75 14 48 c7 85 e8 00 00 00 00 00 00 00 31 c0 5b 5d 41
<4>[    5.071797] RSP: 0018:ffffb4b50055f990 EFLAGS: 00010286
<4>[    5.076191] RAX: 0000000000000000 RBX: ffff9f5d76dfe818 RCX: 0000000000000000
<4>[    5.080302] RDX: 0000000000000001 RSI: 0000000000000000 RDI: ffff9f5d76d3b088
<4>[    5.084171] RBP: ffff9f5d76d3b018 R08: ffff9f5dba438480 R09: ffff9f5dba438598
<4>[    5.088046] R10: 0000000000000000 R11: ffffffff97e39488 R12: 0000000000000000
<4>[    5.091924] R13: ffff9f5d76d3b0e0 R14: 0000000000000001 R15: ffffffffc00eb5a0
<4>[    5.095807] FS:  0000000000000000(0000) GS:ffff9f5dbb780000(0063) knlGS:00000000081cd0b4
<4>[    5.099747] CS:  0010 DS: 002b ES: 002b CR0: 0000000080050033
<4>[    5.103694] CR2: 0000000000000040 CR3: 0000000036dcc000 CR4: 00000000001006e0

**Comment by tlauda** [comment]
@youling257 Kernel issue. Please move this bug to kernel repo: https://github.com/thesofproject/linux/issues.
