### ISSUE TITLE
[BUG] allocating continious blocks can set wrong first free

### ISSUE THREAD

**Issue by dabekjakub** [thesofproject/sof#1714]
alloc.c line 299
```
/* update first_free if needed */
if (map->first_free == start)
   map->first_free += count;
```

Probable bug here - this is not always first free (it most likely works now because we do not free resources mid work yet)	but if there was a realocation or any block was fited in a hole in memory this can result in first free beeing block which is already used.

**Comment by lgirdwood** [comment]
@dabekjakub good catch, any ETA for fix ?

**Comment by dabekjakub** [comment]
As soon as i finish up alignment and pm memory features- week or two.

**Comment by lgirdwood** [comment]
@dabekjakub ping
