### ISSUE TITLE
"DSP panic"Stress test: start playback and capture at same time and pause/release for capture will cause DSP panic 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#174]
Reproduce steps:
1. open a console and run: 
   aplay -D hw:0,0 -f dat -c 2 /dev/zero & arecord -D hw:0,0 -f dat -c 2 /dev/null -i 
2. Press the space key to do pause/release for capture.
Simple pause/release for capture will make firmware xrun, but the pipeline recovery success when no playback.

[dmesg.log](https://github.com/thesofproject/sof/files/2243981/dmesg.log)
[rmbox-t.log](https://github.com/thesofproject/sof/files/2243982/rmbox-t.log)
[rmbox.log](https://github.com/thesofproject/sof/files/2243983/rmbox.log)

**Comment by tlauda** [comment]
Isn't it the duplicate of #168?

**Comment by keqiaozhang** [comment]
@tlauda
Thanks for your input. I will try to revert PR143 and test it again,  if it cannot be reproduced, I will close this bug.

**Comment by keqiaozhang** [comment]
Confirmed that this issue is fixed by PR#178.
