### ISSUE TITLE
"DSP panic" Stress test: inject xrun and do pause/release for capture will cause DSP panic on GP-MRB

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#175]
How to reproduce:
1. run: arecord -Dhw:0,0 -f dat -c 2 /dev/null -i 
2. inject xrun for capture.
    echo 1 > /proc/asound/card0/pcm0c/sub0/xrun_injection
3. press space key to do pause/release for capture.

tplg: test-ssp4-mclk-0-I2S-volume-s16le-s16le-48k-24576k-nocodec.tplg

[rmbox.log](https://github.com/thesofproject/sof/files/2244189/rmbox.log)
[dmesg.log](https://github.com/thesofproject/sof/files/2244190/dmesg.log)

**Comment by tlauda** [comment]
Isn't it the duplicate of #168?

**Comment by xiulipan** [comment]
@tlauda I think they are the same

**Comment by keqiaozhang** [comment]
@tlauda @xiulipan 
Thanks for your input. I will try to revert PR143 and test it again,  if it cannot be reproduced, I will close this bug.

**Comment by keqiaozhang** [comment]
Confirmed that this issue is fixed by PR#178.
