### ISSUE TITLE
[FEATURE] rimage: support for TGL code signing

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#1833]
**Is your feature request related to a problem? Please describe.**
rimage needs to be able to sign tigerlake fw binaries.

**Describe the solution you'd like**
rimage needs to have command line option for TGL that will use TGL manifest and sign TGL binaries.

**Comment by lgirdwood** [comment]
Moving to v1.7. rimage needs support for SHA384 and for PSS signing via OpenSSL.

**Comment by marc-hb** [comment]
See also PR #3187

**Comment by lgirdwood** [comment]
@KaiChuan-Hsieh fyi
