### ISSUE TITLE
[BUG]Glitches in beginning of playback via SRC pipe

### ISSUE THREAD

**Issue by singalsu** [thesofproject/sof#1843]
**Describe the bug**
Especially with 48 kHz content playback to Media Playback device the first fraction of a second has discontinuities in output waveform. The effect can be heard when listening carefully.

Witht other sample rates like 32 kHz there's typically one glitch. 48 kHz has several (5).

**To Reproduce**
Playback of 48 kHz content to hw:0,4 device in UP^2 with default topology sof-apl-pcm512x.tplg.

**Reproduction Rate**
Always.

**Expected behavior**
Clean playback start.

**Impact**
It's an annoyance.

**Environment**
1) Branch name and commit hash of 3 repositories: sof (firmware), linux (kernel driver) and soft (tools & topology).
2) Name of the topology file
3) Name of the platform(s) on which the bug is observed.
4) Reproducibility Rate. If you can only reproduce it randomly, it’s useful to report how many times the bug has been reproduced vs. the number of attempts it’s taken to reproduce the bug.

**Screenshots or console output**
![up2_hw04_48k_play](https://user-images.githubusercontent.com/28754793/65229365-d56b1f00-dad4-11e9-9872-0aee282e67af.png)
![up2_hw04_32k_play](https://user-images.githubusercontent.com/28754793/65229381-db610000-dad4-11e9-8ffd-96c0dbe89eea.png)

**Comment by lgirdwood** [comment]
@singalsu I assume SRC is reading ahead ? It could just be we need to zero all SRC source buffer before we start.

**Comment by tlauda** [comment]
@singalsu On BYT it looks even worse with 48 kHz:

![image](https://user-images.githubusercontent.com/40232714/66643641-71dd9880-ec1f-11e9-93b9-0f70c3d7fc24.png)

**Comment by tlauda** [comment]
@singalsu Yes, it's clean also on BYT. Closing this one. Please create new bug.
