### ISSUE TITLE
Clock API needs to be reworked

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#186]
The clock API does not account for the fact that a given SSP can be programmed to work with different sources (XTAL, PLL)

**Comment by lgirdwood** [comment]
@RanderWang @mengdonglin moving this to v1.4

**Comment by lgirdwood** [comment]
@jajanusz @dbaluta I guess this is all good now ?

**Comment by lgirdwood** [comment]
Zephyr has flexible clock APIs - moving to v1.9 for Zephyr integration.

**Comment by mengdonglin** [comment]
Fixed by Zephyr.
