### ISSUE TITLE
[FEATURE] Add DMA trace run-time enable/disable feature

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/sof#1860]
**Is your feature request related to a problem? Please describe.**
At the moment, DMA trace will be enabled and started by default, we can't pause or disable it after it is started. This will lead to issue that it is impossible to fulfil the feature when the system is entering some special state (e.g. low power d0i3 state where DMA trace is required to be stopped).

**Describe the solution you'd like**
implement DMA trace disable/free interface, introduce new IPC messages to respond these requirement from host.

**Comment by mrajwa** [comment]
> This will lead to issue that it is impossible to fulfil the feature when the system
I don't understand what is the issue here, are you trying to say logs during d0i3 should not be send or what?

**Comment by lgirdwood** [comment]
@mrajwa @keyonjie I'm assuming this is a request for an new IPC command to disable the DMA trace ?

**Comment by akloniex** [comment]
dma-trace API extended in PR https://github.com/thesofproject/sof/pull/1995

**Comment by tlauda** [comment]
@keyonjie Does the current API extension is enough for you, so this issue can be closed?

**Comment by lgirdwood** [comment]
@keyonjie ping

**Comment by paulstelian97** [comment]
@keyonjie Does this still apply?

**Comment by keyonjie** [comment]
@paulstelian97 @lgirdwood yes, this is closed via PR#1995
