### ISSUE TITLE
[BUG][APL][CI]Speaker-test on APL_UP2_NOCODEC - IPC timed out (from gitlab)

### ISSUE THREAD

**Issue by Jiangxinx** [thesofproject/sof#1868]
**Describe the bug**
From CI (https://gitlab.devtools.intel.com/sof-ci/sofcitest/issues/186), hw_params didn't go through well sometimes while do speaker-test on APL_UP2_NOCODEC platform.
https://tcr.sh.intel.com/#/tests/fc68dcdf-70cb-4c51-ae73-370d8ba68cb8/detail
https://tcr.sh.intel.com/#/tests/53744105-f046-4004-925f-0993eb388a00/detail

By the way, I can't reproduce this issue manually.

**To Reproduce**
1. speaker-test -D hw:0,0 -r 48000 -c 2 -f s16_le -l 3 -t wav -P 8

**Output**
```
2019-09-23 18:47:03 UTC [REM_COMMAND]: speaker-test -D hw:0,0 -r 48000 -c 2 -f s16_le -l 3 -t wav -P 8
Unable to set hw params for playback: Connection timed out

arecord: set_params:1363: Unable to install hw params:
```

**dmesg**
```
[  139.351006 <    0.000798>] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x30100000 size 48
[  139.351031 <    0.000025>] sof-audio-pci 0000:00:0e.0: status: fw entered - code 00000005
[  139.351111 <    0.000080>] sof-audio-pci 0000:00:0e.0: error: unexpected fault 0x00000000 trace 0x00004000
[  139.351121 <    0.000010>] sof-audio-pci 0000:00:0e.0: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[  139.351126 <    0.000005>] sof-audio-pci 0000:00:0e.0: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[  139.351154 <    0.000028>] sof-audio-pci 0000:00:0e.0: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[  139.351166 <    0.000012>] sof-audio-pci 0000:00:0e.0: error: waking up any trace sleepers
[  139.351174 <    0.000008>] sof-audio-pci 0000:00:0e.0: error: load pipeline ipc failure
[  139.351181 <    0.000007>] sof-audio-pci 0000:00:0e.0: error: failed to load widget type 32 with ID: 55
[  139.351185 <    0.000004>] sof-audio-pci 0000:00:0e.0: error: failed to restore pipeline after resume -110
```

**Environment**
Firmware: 0b471290 https://github.com/thesofproject/sof/commits/master
Kernel: f05b2682 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: sof-apl-nocodec.tplg

**Comment by wenqingfu** [comment]
If you cannot reproduce it manually, I would like it to be reported later.  The links quoted are not qualified for using on Github, anyway. Please quote CI test results on 01.org
