### ISSUE TITLE
[BUG] hw param installation failed in wov test on GLK Chrome

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof#1869]
**Describe the bug**
once run arecord on wov pipeline, there will be an "Unable to install hw params" message in the terminal, check kernel and sof logs, you'll see the issue.

**To Reproduce**
run `arecord -Dhw:0,8 -M -N -r 16000 -c2 -f s16_le -vvv -d 5  wov.wav`

**Reproduction Rate**
100%

**Environment**
1) Branch
    * Kernel:  topic/sof-dev {e03f8829}
    * SOF: master {d42c0195}
2) Name of the topology file
    * Topology: {sof-glk-da7219-kwd.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {GLK Chrome}
4) OS: Ubuntu1804

```
[  156.530557] sof-audio-pci 0000:00:0e.0: period_bytes:0x1f80
[  156.530558] sof-audio-pci 0000:00:0e.0: periods:3
[  156.530576] sof-audio-pci 0000:00:0e.0: stream_tag 2
[  156.530580] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  156.537181] sof-audio-pci 0000:00:0e.0: error: ipc error for 0x60010000 size 20
[  156.537184] sof-audio-pci 0000:00:0e.0: error: hw params ipc failed for stream 2
[  156.537187] sof-audio-pci 0000:00:0e.0: ASoC: 0000:00:0e.0 hw params failed: -22
[  156.537190]  DMIC16k: ASoC: hw_params FE failed -22**
[  156.537194] sof-audio-pci 0000:00:0e.0: pcm: free stream 8 dir 1
[  156.549353] sof-audio-pci 0000:00:0e.0: pcm: close stream 8 dir 1
[  159.050083] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x20140000 successful
[  159.055083] sof-audio-pci 0000:00:0e.0: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  159.055199] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  159.055227] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x1010303 successful
[  159.055231] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x1000303 successful
[  159.055234] sof-audio-pci 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 3
[  159.055254] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000010 at  00000044
```
```
 CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1          MEM         154896893.593750 154896896.000000      src/lib/alloc.c:273 	error: 342 blocks needed for allocation but only 341 blocks are remaining
    0      1         PIPE         154900036.875000      3143.281250 src/audio/pipeline.c:414 	pipeline_prepare() error: ret = -5,dev->comp.id = 50
    0      1          IPC         154900054.531250        17.656250    src/ipc/handler.c:304 	ipc: pipe 8 comp 50 prepare failed -5


```

**Comment by aiChaoSONG** [comment]
This issue can also be observed on CML Chrome with [wovapp](https://github.com/aiChaoSONG/wovapp) in S24_LE mode.
run `./wovapp -Dhw:0,8 -d5 -t -s -fs24_le -p 400 -N`
*Notice: this app works fine in s16_le mode*

**Comment by YvonneYang2** [comment]
Check on WHL-I2S, same behavior as CML Chrome when run wovapp in s24_le mode. 
This app also woks fine in s16_le mode .

**Comment by aiChaoSONG** [comment]
I bisect commit by commit, sof commit a35ec91 cause this issue. As the commit is from 40 days ago, please look at it and fix this issue asap. @mrajwa

**Comment by lgirdwood** [comment]
@aiChaoSONG can you confirm these WoV params are supported ? Otherwise this result would be expected. @keyonjie care to comment on what rates/formats are supported here.

**Comment by keyonjie** [comment]
@lgirdwood I think the error happens because either 'kpb->sel_sink' or 'kpb->host_sink' is NULL. @mrajwa can you help check what happens here?

**Comment by mrajwa** [comment]
@aiChaoSONG, please paste whole firmware error log. Your bisect candidate is likely wrong too.

**Comment by tlauda** [comment]
Ancient bug. Everything is working now.
