### ISSUE TITLE
[BUG][GLK] KWD is broken

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof#1909]
**Describe the bug**
Set hwparams failed.
Firmware return errors,
src/lib/alloc.c:273   error: 6 blocks needed for allocation but only 1 blocks are remaining

Whereas aplay and arecord are working fine in other pipelines.

**To Reproduce**
sudo su
arecord -N -M -Dhw:0,8 -c 2 -r 16000 -f s16_le tmp.wav -vvv

**Reproduction Rate**
100%

**Expected behavior**
start keyword dection

**Impact**
broken feature

**Environment**
1) Daily build 20191008
    * Kernel: df832fb2
    * SOF: fee25179
2) Name of the topology file
    * Topology: sof-glk-da7219-kwd.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: GLK-bobba ubuntu

**Screenshots or console output**
sudo su
arecord -N -M -Dhw:0,8 -c 2 -r 16000 -f s16_le tmp.wav -vvv
Recording WAVE 'tmp.wav' : Signed 16 bit Little Endian, Rate 16000 Hz, Stereo
arecord: set_params:1363: Unable to install hw params:
ACCESS:  MMAP_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 16000
PERIOD_TIME: 126000
PERIOD_SIZE: 2016
PERIOD_BYTES: 8064
PERIODS: (3 4)
BUFFER_TIME: 501000
BUFFER_SIZE: 8016
BUFFER_BYTES: 32064
TICK_TIME: 0

*sof-logger output
[1007_glk_kwd_failure_logger.log](https://github.com/thesofproject/sof/files/3699824/1007_glk_kwd_failure_logger.log)

 CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME    CONTENT
    0      1          MEM         1248716077.656250              nan      src/lib/alloc.c:273   error: 7 blocks needed for allocation but only 1 blocks are remaining
    0      1          MEM         1248722926.510417      6848.854004      src/lib/alloc.c:273   error: 342 blocks needed for allocation but only 341 blocks are remaining
    0      1          MEM         1248726120.208333      3193.697998      src/lib/alloc.c:273   error: 6 blocks needed for allocation but only 1 blocks are remaining
    0      1         PIPE         1248726194.583333        74.375000 src/audio/pipeline.c:420   pipeline_prepare() error: ret = -5,dev->comp.id = 50
    0      1          IPC         1248726201.458333         6.875000    src/ipc/handler.c:305   ipc: pipe 8 comp 50 prepare failed -5
    0      1          EDF         1248729342.395833      3140.937500 edule/timer_domain.c:34    timer_report_delay(): timer 3 delayed by 1211 uS 23265 ticks

**Comment by aiChaoSONG** [comment]
This is the same issue as #1869
