### ISSUE TITLE
[BUG] remove void* arithmetic

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#1913]
**Describe the bug**
SOF codebase has multiple instances of doing arithmetic with void pointer. This is illegal both in ANSI C and C++, although allowed by many compilers.

There's no good reason to have such code in the codebase.

**To Reproduce**
Pass -pedantic-errors or -Werror-pointer-arith to GCC build.

**Reproduction Rate**
100%

**Expected behavior**
No illegal C/C++ constructs used.

**Impact**
When building SOF with Zephyr as the RTOS, this causes issues as void*-arithmetic is forbidden in Zephyr build system.

**Environment**
Latest sof/master.

FYI @finikorg

**Comment by plbossart** [comment]
+1

**Comment by lgirdwood** [comment]
@kv2019i do you have an ETA for fix and also GCC flag updates ?

**Comment by kv2019i** [comment]
@lgirdwood wrote:
> @kv2019i do you have an ETA for fix and also GCC flag updates ?

No, nobody has signed up to this task yet. This is not on the priority list (at least yet).

**Comment by paulstelian97** [comment]
On this side of cosmetic fixes, I think I could get to this one. For the moment, I'm waiting for the asserts PR to be merged and am planning on fixing #1999 first. After those I think I could add this one in my backlog.

**Comment by paulstelian97** [comment]
On it, added a flag, draft PR coming up today, full PR possibly also today.
