### ISSUE TITLE
[BUG][TGL] multi-pipeline playback or capture failed with 'DSP panic'

### ISSUE THREAD

**Issue by Bin-QA** [thesofproject/sof#1924]
**Describe the bug**
Running multiple pipelines can cause DSP Panic on TGL.

**To Reproduce**
Scenario 1:
Playback via headset (device 0,0) and HDMI monitor (device 0,4) simultaneously.
1. In terminal to run "aplay -D hw:0,0 -f dat 48California_Dreaming.wav"
2. In other terminal to run "aplay -D hw:0,4 -f dat 48California_Dreaming.wav"

Scenario 2:
Playback and capture via headset simultaneously.
1. In terminal to run "aplay -D hw:0,0 -f dat 48California_Dreaming.wav"
2. In other terminal to run "arecord -Dhw:0,0 -fs16_le -c2 -r 48000 -vv -i test.wav"

**Reproduction Rate**
100%

**Expected behavior**
Can run multi-pipeline on TGL

**Actual Result**
DSP Panic will happen when starting the 2nd pipeline

**Environment**
Firmware: c8bc4b2 https://github.com/thesofproject/sof/commits/tgl-002-drop-stable
Kernel: intel-next kernel, tag intel-5.4-rc2-2019-10-10, commit id: fc2de5669533
tplg: sof-hda-generic.m4
platform: TGL with onboard ALC711 in HD-A mode. Connected an external monitor via microHDMI port.

**Screenshots or console output**
```
[  565.126849] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x600a0001: GLB_STREAM_MSG: POSITION
[  565.126869] sof-audio-pci 0000:00:1f.3: nothing to do in IPC IRQ thread
[  565.127226] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x24001e successful
[  565.127236] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  565.127487] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  565.127503] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=1
[  565.127907] sof-audio-pci 0000:00:1f.3: **error : DSP panic!**
[  565.127914] sof-audio-pci 0000:00:1f.3: panic: dsp_oops_offset 788480 offset 788480
[  565.127932] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[  565.128379] sof-audio-pci 0000:00:1f.3: error: runtime exception
```
[aplay.abi.log](https://github.com/thesofproject/sof/files/3720373/aplay.abi.log)
[aplay.dmesg.log](https://github.com/thesofproject/sof/files/3720374/aplay.dmesg.log)
[debug-sof.tar.gz](https://github.com/thesofproject/sof/files/3720375/debug-sof.tar.gz)
[md5sum.txt](https://github.com/thesofproject/sof/files/3720376/md5sum.txt)

**Comment by Bin-QA** [comment]
Verify patch:  https://patch-diff.githubusercontent.com/raw/thesofproject/linux/pull/1037.patch
Couldn't catch "POSTION" in dmesg keyword
This Bug still exist

**Comment by jajanusz** [comment]
@Bin-QA Repro recipe is incomplete - What kernel did you use?

**Comment by Bin-QA** [comment]
@jajanusz internel test kernel

**Comment by jajanusz** [comment]
@Bin-QA We don't work on BUGs with kernel that we don't have, if you want us to reproduce error, please give commit hash of kernel that you see error with.

**Comment by slawblauciak** [comment]
Please check on a timer-driven pipeline, with SSP or SDW.
To make a pipeline timer-driven in the topology, the 11th param of PIPELINE_PCM_ADD has to be set to SCHEDULE_TIME_DOMAIN_TIMER.

**Comment by xiulipan** [comment]
@jajanusz Can you try to dump the exception with sof-coredump-to-gdb.sh?
The exception is attached.

**Comment by Bin-QA** [comment]
Add kernel configure for Kernel

[config.txt](https://github.com/thesofproject/sof/files/3728588/config.txt)

**Comment by keqiaozhang** [comment]
@jajanusz 
This issue is gone after applying https://github.com/thesofproject/sof/pull/1955 and https://github.com/thesofproject/sof/pull/1956.
