### ISSUE TITLE
ipc_comp_dai_config really needs some refactoring

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/sof#1954]
ipc_comp_dai_config really needs some refactoring. Outer switch can be replaced with an if so that we can decrease the number of indentation levels.

This is a good first issue.

_Originally posted by @dbaluta in https://github.com/thesofproject/sof/pull/1951#issuecomment-542668791_

**Comment by tlauda** [comment]
@dbaluta Fixed by #1997 and #2003.

**Comment by dbaluta** [comment]
@tlauda thanks!
