### ISSUE TITLE
[BUG] SOF FW compiling fail when disable TRACE in menuconfig

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/sof#1980]
**Describe the bug**
SOF FW compiling fail when disable TRACE in menuconfig

**To Reproduce**
run make menuconfig, de-select the TRACE, save and build.

**Reproduction Rate**
100%
**Expected behavior**
build should success.
**Impact**
It block debugging the FW behavior on removing trace.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: any
    * SOF: master, latest
2) Name of the topology file
    * Topology: any
3) Name of the platform(s) on which the bug is observed.
    * Platform: {cnl}

**Comment by paulstelian97** [comment]
i.MX is also affected. I'm getting compile error from kpb.c,

**Comment by paulstelian97** [comment]
Tentative fix pushed.

**Comment by paulstelian97** [comment]
@keyonjie Can you please check the issue is resolved? (if not please reopen)
