### ISSUE TITLE
[BUG] PM status is active for SDW master with non-existence SDW device

### ISSUE THREAD

**Issue by RanderWang** [thesofproject/sof#1989]
On Comet-lake with 3 SDW codecs, rt715 on link0,  rt1308 on link1,  rt715 on link3 and no device on link2.  After rebooting, SDW2 master on link2 is always active, and this makes SOF always active.  

The expect behavior is if there is one link without any devices, their pm_runtime status should be marked as ‘Unsupported’, and that should not prevent the system from going to sleep nor should it have any impact on other devices

**Comment by tlauda** [comment]
What does it have to do with firmware?

**Comment by plbossart** [comment]
yes, it's a pm_runtime bug on the kernel side. @RanderWang please move this to the Dark Side

**Comment by RanderWang** [comment]
sorry,  I should created this bug at kernel side. I will move it to kernel side

**Comment by RanderWang** [comment]
I made a mistake , it should be reported in kernel side
