### ISSUE TITLE
[BUG] Glitch and extra buffers output happens in the end of playback with media pipe

### ISSUE THREAD

**Issue by singalsu** [thesofproject/sof#2004]
**Describe the bug**
This bug was noticed when playing back 1s and 30s long low frequency sine wave test clip. Just before the heard output end there's an audible glitch. It appears in recorded audio as a discontinuity in the waveform. The glitch is about 100ms before the end independently of clip length. 

The same happens if aplay is interrupted with ctrl-c. The glitch is near the end of audio output.

When capturing the analog line-out it is seen that the glitch happens the length length of playback clip. The continued audio playback after the glitch is apparently copy of old buffers content. The captured length of 1.0s tone clip play is 1.1s.

The issue happens when playing back other than 48 kHz content. The glitch looks similar with e.g. 32 kHz an 44.1 kHz content.

The pipeline consists of components PCM - PGA - SRC - Mixer - PGA - DAI. A simpler test pipeline with  PCM - SRC - PGA - DAI does not have this problem.

**To Reproduce**
Use UP^2 board with HifiBerry DAC+ and default topology sof-apl-pcm512x.tplg. Play back 44.1 kHz wav clip with aplay to device hw:0,4 (card 0: sofbxtpcm512x [sof-bxt-pcm512x], device 4: Media Playback 4 (*) []).  Listen and record the output.

**Reproduction Rate**
Always.

**Expected behavior**
Clean end of playback without annoying glitches.

**Impact**
Annoyance.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 21147939958a35363dfd01563d004094198c917d
    * SOF: ffe904c9f9013b87d2c163eab0ca03ef34560315
2) Name of the topology file
    * Topology: sof-apl-pcm512x.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: UP^2 with HiFiBerry DAC+

**Screenshots or console output**
![Screenshot from 2019-10-24 12-27-24](https://user-images.githubusercontent.com/28754793/67557349-99535b80-f71d-11e9-93db-1633be66bc3b.png)

**Comment by tlauda** [comment]
@singalsu Could you verify whether it happens with nocodec on loopback with the same pipeline? It looks like codec problem.

**Comment by tlauda** [comment]
@singalsu Ping.

**Comment by singalsu** [comment]
@tlauda It's not a codec issue since it depends pipeline and happens with media pipe that inputs other than 48 kHz content. Though this issue is old so I should re-test if this still happens.

**Comment by tlauda** [comment]
@singalsu Could you verify whether the bug still exists?

**Comment by singalsu** [comment]
I just checked that this issue does not happen with current SOF git repositories:

Kernel Branch: topic/sof-dev
Kernel Commit: 40e44b3a8841
SOF Branch: master
SOF Commit: c4aa4c176

![Screenshot from 2020-09-24 17-45-40](https://user-images.githubusercontent.com/28754793/94161128-06232880-fe8e-11ea-8bee-b8a9dad331e6.png)

This issue can be closed!
