### ISSUE TITLE
[BUG][CML][HDA] fixed distortion pattern at the beginning of recording on headset pipeline

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof#2101]
**Describe the bug**
run arecord on headset capture pipeline, you will see volume keeps high at the beginning, even there is no sound. check the recorded wave, you can see a fixed distortion pattern, and all headset recorded waves have the same distortion.

if no headset connected when run arecord, no distortion found.

![Screenshot from 2019-11-18 10-24-51](https://user-images.githubusercontent.com/52959957/69020275-e4941d80-09ee-11ea-8e03-0de0c58bc070.png)

**To Reproduce**
run `arecord -Dhw:0,0 -fs32_le -r 48000 -c 2  -i -vvv headset.wav`

**Reproduction Rate**
10/10

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {fd302303}
    * SOF: {655d077f}
2) Name of the topology file
    * Topology: {sof-hda-generic-2ch.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {Dell HDA platform with ALC 3204 codec}

[sof_logger_trace.log](https://github.com/thesofproject/sof/files/3856576/sof_logger_trace.log)

**Comment by lgirdwood** [comment]
@singalsu @bardliao  what do you think, this could just be the mic powering UP.

**Comment by plbossart** [comment]
likely something in the HDaudio codec driver and/or bad settings applied?

**Comment by bardliao** [comment]
Looks like a power up pop. @aiChaoSONG How long will the max volume continue? Will you see the same issue on DMIC recording?

**Comment by aiChaoSONG** [comment]
@bardliao only see this on headset capture pipeline, and the max volume duration is very short, about 0.35s.

**Comment by bardliao** [comment]
> @bardliao only see this on headset capture pipeline, and the max volume duration is very short, about 0.35s.

So I think it is a codec issue (or limitation). I think we can close this issue since there is nothing we can do.

**Comment by singalsu** [comment]
This would be fixed by inserting an IIR EQ into capture path. If someone with access to this device and test an enhanced topology can contact me I can make a patch to sof-hda-generic-2ch.tplg to test with.

**Comment by singalsu** [comment]
@bardliao @aiChaoSONG Can you please check if SOF PR #2109 helps for this.

**Comment by lgirdwood** [comment]
@singalsu good work, btw this is worthy of a technical note on sof-decs i.e. a small howto.

**Comment by singalsu** [comment]
I was able to repeat this issue with a device that I have. There's no volume ramp happening in capture, I'll try to  make a fix for this and related problems https://github.com/thesofproject/linux/issues/1463 and https://github.com/thesofproject/linux/issues/1480.

**Comment by plbossart** [comment]
thanks @singalsu for looking into this.

**Comment by singalsu** [comment]
I have a fix under development that is done in firmware to launch a volume ramp in beginning of copy() operations if the driver control sequence has not initiated it. I don't think it can be fixed in driver in simple way because the PM controls cache hides the unmute transition from firmware. 

Combination of ramp and DC block works well but I need to eliminate the volume setting dependent ramp length variation for the start ramp (use the whole topology defined time even if the gain request is much lower than max. volume).

**Comment by lgirdwood** [comment]
@singalsu can we have topology tuple flags for ramp up/down at stream start, this way we can turn it off/on as needed.

**Comment by singalsu** [comment]
We have a single token for ramp length but the same length is used for both start and during streaming. The ramp is turned off by setting length to zero.

**Comment by singalsu** [comment]
@aiChaoSONG The PR #2109 is merged so I re-tested this on a WHL HDA platform with headset disconnected. The start waveform is now clean so I think this can be closed.

![Screenshot from 2020-01-24 14-11-11](https://user-images.githubusercontent.com/28754793/73068367-b7169500-3eb3-11ea-981b-a9ebdb2ba55a.png)

**Comment by singalsu** [comment]
Closing this issue.
