### ISSUE TITLE
[FEATURE] TGL SOF fw build with otc 3k key

### ISSUE THREAD

**Issue by sathya-nujella** [thesofproject/sof#2158]
Need SOF fw build with otc 3k key.
Please provide build infra/methodology for TGL.

For TGL, below keys are added.. TGL sof fw build should utilize the keys:
   rimage: keys: add new 3k key   
        ./rimage/keys/
                otc_private_key_3k.pem
                otc_public_key_3k.pem

**Comment by marc-hb** [comment]
@sathya-nujella I believe #3187 implemented this, can you confirm so we can close? It seems to work for a number of people, see #3187. Note this require the MEU_TOOL, rimage is not enough.

For TGL support in rimage there is another issue: #1833

**Comment by lgirdwood** [comment]
See https://github.com/thesofproject/rimage/pull/33 for rimage CAVS 2.5 signing WIP PR.

**Comment by cujomalainey** [comment]
I believe this is complete since the PR is closed

**Comment by lgirdwood** [comment]
Yes code is upstream in rimage now.
