### ISSUE TITLE
Trace error: "dma eI2" when doing pause/release

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#225]
This issue happens on BYT when playback or capture. but it doesn't affect audio.  The reproducibility is low < 5%.
[rmbox-t.log](https://github.com/thesofproject/sof/files/2287023/rmbox-t.log)
[rmbox.log](https://github.com/thesofproject/sof/files/2287025/rmbox.log)

How to reproduce:
1. aplay -Dhw:0,0 -f dat -c 2 /dev/zero & arecord -D hw:0,0 -f dat -c 2 /dev/null -i 
2. press the space key to do pause/release for capture.
3. check the rmbox

Error log:
using 19.20MHz timestamp clock
0x0 [15512.024334]      delta [********]        dma eI2
0x10 [15512.024337]     delta [0.000002]        value 0x0000000000000001
0x20 [2783.935138]      delta [********]        dma eI2
0x30 [2783.935140]      delta [0.000002]        value 0x0000000000000002
0x40 [2783.936138]      delta [0.000998]        dma eI2
0x50 [2783.936140]      delta [0.000002]        value 0x0000000000000002
0x60 [2783.937138]      delta [0.000998]        dma eI2
0x70 [2783.937140]      delta [0.000002]        value 0x0000000000000002

**Comment by lgirdwood** [comment]
@xiulipan lets also dump the error code if we can. It's probably harmless notification and could be verbose trace level.

**Comment by xiulipan** [comment]
@lgirdwood 
will done. I believe this is because BYT will have three channel enable with only one IRQ handler.
Let me try to enable all SSP on BYT and have a test.

**Comment by mengdonglin** [comment]
@ZhendanYang could you check if this issue is still there with new logger?

**Comment by ZhendanYang** [comment]
@mengdonglin BYT is in bad health at the moment. I can't check this issue for now. I'll check this issue as soon as BYT become healthy.

**Comment by lgirdwood** [comment]
@ZhendanYang I cant find "el2" in the source. Can you re-test with master.

**Comment by ZhendanYang** [comment]
Blocked by #443 . And rmbox and logger are both empty.

**Comment by tlauda** [comment]
@ZhendanYang Any update?

**Comment by xiulipan** [comment]
@tlauda 
I think we can close this issue. Since no more rmbox is working now.
