### ISSUE TITLE
[FEATURE] Stub loader for Kabby and Skylake platforms

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof#2256]
**Is your feature request related to a problem? Please describe.**
Kabby and Skylake platforms have immutable keys for loading DSP firmware which prevents SOF from being loaded without having Intel sign the blobs.

**Describe the solution you'd like**
The alternative is have a stub loaded that is signed with the intel key and have that stub load OTC signed builds through the existing communication mechanisms with the DSP. Ideally this would be able to load SOF builds with minimal changes to the build format. There will obviously be changes needed since the bootloader will handle some init code that the firmware will not need to rerun. 

**Describe alternatives you've considered**
Alternative is to have Intel sign all builds, this prevents upgrades without having intel sign every build produced by any non-intel party. This makes development on those platforms basically impossible externally.

**Additional context**
#1899

**Comment by cujomalainey** [comment]
@dgreid

**Comment by jajanusz** [comment]
@lgirdwood @mmaka1 Doesn't it break security at all?

**Comment by lgirdwood** [comment]
@jajanusz I don't think so, IIUC it means that the stub will only boot code signed with Google Private key, in a similar way we have today with the OEM key manifest on APL+. It also wont work on any system with secure OS boot enabled in BIOS. I would say it's only useful on Chrome and Linux/Windows booting with secure boot disabled (where there is no security anyway)

**Comment by plbossart** [comment]
and Chromebooks use the community key anyways starting with GLK, so it'd be the same level of security (essentially guaranteed by the protected filesystem, not by firmware signature).

**Comment by cujomalainey** [comment]
That is correct, we use the open source keys since we rely on our fs verification for firmware integrity. Once the device is in dev mode users can create their own firmware signed with the open source keys.

**Comment by chrysophylax** [comment]
As a Linux end-user, I'd gladly rather take no secure boot and have working sound :+1:

**Comment by lgirdwood** [comment]
@cujomalainey @dgreid @chrysophylax I'm working on some prototype code now, will test on APL.

**Comment by JannF** [comment]
Is there any progress besides the closed referenced ticket?

**Comment by cujomalainey** [comment]
@JannF this is also closed based no the resolution in #1899
