### ISSUE TITLE
[FEATURE] Make dai.c generic and move DAI specific code into DAI drivers.

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#2269]
**Is your feature request related to a problem? Please describe.**
dai.c contains programming code for ssp, hda etc, this IP specific code should be in the dai driver and not the DAI core.

**Describe the solution you'd like**
Move all DAI specific logic to dai drivers.

**Comment by lgirdwood** [comment]
@RanderWang any progress here ?

**Comment by mengdonglin** [comment]
@lgirdwood Now the SSP specific code is in https://github.com/thesofproject/sof/blob/master/src/drivers/intel/ssp/ssp.c
and HDA spefic code is in https://github.com/thesofproject/sof/blob/master/src/drivers/intel/hda/hda.c 

In dai.c, only function dai_config() has some type-specific logic https://github.com/thesofproject/sof/blob/master/src/audio/dai.c#L759

Do you think we need to modify this part? There is some Freescale code involved.

**Comment by lgirdwood** [comment]
@mengdonglin Ok, lets push into v.1.7 @dbaluta fyi some imx parts also need moved.

**Comment by paulstelian97** [comment]
@lgirdwood Should I also take care of moving the i.MX parts from there in my existing PR #3368 or that is worth a new separate one?

**Comment by lgirdwood** [comment]
@paulstelian97 It's probably best if this was done atomically in one PR - we can do for v1.7

**Comment by paulstelian97** [comment]
> @paulstelian97 It's probably best if this was done atomically in one PR - we can do for v1.7

Fair enough.

**Comment by lgirdwood** [comment]
@paulstelian97 any update ?

**Comment by paulstelian97** [comment]
In the backlog, might try to sprint it these days if I get a bit of extra time (right now trying to update Xtensa compiler for i.MX platforms).

**Comment by lgirdwood** [comment]
Ok, lets move it for later.

**Comment by lgirdwood** [comment]
Update: half implemented in v1.8 as part of IPC refactoring, to be completed in v1.9 with IPC abstraction

**Comment by kv2019i** [comment]
Moving to v2.6 to check this. We now lifted the DAI abstraction into Zephyr, so we should have a clean split now.

**Comment by mengdonglin** [comment]
@kv2019i  Can we close this? Already done in Zephyr or are there any remaining items?

**Comment by kv2019i** [comment]
Ack @mengdonglin , I think we can close this. @lgirdwood Ok for you? There is still a few place that relate to converting from IPC DAI type specific structures into the generai dai.h interface of Zephyr. No actual IP programming is anymore present.

**Comment by mengdonglin** [comment]
Thank you @kv2019i  Closing.
