### ISSUE TITLE
Pulseaudio fails to playback with topology sof-cnl-rt274,tplg

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/sof#230]
Summary: There are ipc error in dmesg after booting on cnl.

Environment:
sof-dev: 5420b87addf10a074fb81a555dff05a4a177af93
sof: bfc7e467f7b283d0b7db5dff7321c8c5ec400980
soft: a01d56f852d0b0fa865b666e5e7acc4baee1e1be
tplg file: sof-cnl-rt274,tplg

Logs:
[dmesg.log](https://github.com/thesofproject/sof/files/2296513/dmesg.log)
[rmbox.log](https://github.com/thesofproject/sof/files/2296514/rmbox.log)
[rmbox-t.log](https://github.com/thesofproject/sof/files/2296515/rmbox-t.log)

**Comment by lgirdwood** [comment]
@SinianYang this looks like Pulseaudio trying lots of different hw_params() and is expected. Not an error unless all hw_params are rejected, in that case it's a topology bug.

**Comment by xiulipan** [comment]
@lgirdwood 
If this is some issues with our `SectionPCMCapabilities` in tplg.
Should we not pass some un-supported in tplg for diver?

**Comment by SinianYang** [comment]
@lgirdwood  If I turn off Pulseaudio, there is no ipc error. Once I run pulseaudio --start, ipc error occurs. And paplay, parecord can't work normally.

**Comment by mengdonglin** [comment]
We only have 1 CNL RVP used by validation team. Drop this when we have new GLV board?

**Comment by mengdonglin** [comment]
Close this bug since we no longer support ALC274 codec but use no codec mode to test CNL platform.
