### ISSUE TITLE
[FEATURE] Developer guide document for testbench usage

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#2342]
**Is your feature request related to a problem? Please describe.**
A simple document describing what the test bench is, why it is useful and how to use it. i.e all the steps needed with some example where users can see it working..

**Comment by lgirdwood** [comment]
I would also add context here about how this also allow GDB and valgrind usage too, i.e. since SOF memory resource calls are mapped to malloc and friends then valgrind can detect leaks, out of bounds access etc

**Comment by singalsu** [comment]
Yep, that's very useful.

**Comment by lgirdwood** [comment]
@singalsu are we good, can we close now ?

**Comment by singalsu** [comment]
@lgirdwood Sorry this is not yet done, this is open and should be kept until I've done this.

**Comment by lgirdwood** [comment]
@singalsu ping

**Comment by singalsu** [comment]
The PR https://github.com/thesofproject/sof-docs/pull/286 is not yet merged. It has the content that was discussed here so I expect only grammar improvements needed.

**Comment by lgirdwood** [comment]
@singalsu it should be merged soon by @deb-intel
@juimonen can you approve too. Thanks.

**Comment by deb-intel** [comment]
@lgirdwood @singalsu Yes, I will merge / edit PR 286 (and 248) today.
