### ISSUE TITLE
[FEATURE] Documentation how to use sof mux/demux component

### ISSUE THREAD

**Issue by juimonen** [thesofproject/sof#2351]
**Is your feature request related to a problem? Please describe.**
We don't have documentation for mux/demux component.

**Describe the solution you'd like**
We should have some documentation.

**Describe alternatives you've considered**
Documentation is the only way.

**Comment by lgirdwood** [comment]
@juimonen are we good, can we close now ?

**Comment by juimonen** [comment]
yes let's close
