### ISSUE TITLE
[FEATURE] trace: make last trace item persistent 

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#2371]
**Is your feature request related to a problem? Please describe.**
Currently only trace_error() messages are entered into the persistent buffer. This means we are unable to find the fault if FW crashes and DMA trace buffer is not flushed.

**Describe the solution you'd like**
Reserve the first item in the persistent trace buffer (error buffer) for the last trace message. This way (for any FW crash) the last trace item is always available regardless of DMA trace buffer copy status. i.e. we always write the current trace message to the top of the persistent buffer for every trace call.

**Comment by paulstelian97** [comment]
I typically enable TRACEM so that the mailbox also receives the non-error traces, is that what you mean? (that one only gets the errors by default)

**Comment by lgirdwood** [comment]
I mean here if TRACE_M is disabled, i.e. you need to retain errors and last trace message.

**Comment by paulstelian97** [comment]
I see, so a form of limited TRACE_M even when TRACE_M itself is disabled.

**Comment by lgirdwood** [comment]
yeah, ideally to fast track CI reports and any user bug reports.

**Comment by lgirdwood** [comment]
@slawblauciak @ktrzcinx @bkokoszx any update here, I do remeber merging a similar feature ??? or shall we move to v1.7 ?

**Comment by slawblauciak** [comment]
Not familiar with this feature I'm afraid.

**Comment by ktrzcinx** [comment]
I don't remember any PR related to this feature.

**Comment by lgirdwood** [comment]
ok, will move - I think we do see panic() in the error log now so maybe that's what I'm seeing.

**Comment by lgirdwood** [comment]
@akloniex @ktrzcinx I think this can be closed now ?

**Comment by ktrzcinx** [comment]
@lgirdwood I don't think so, without CONFIG_TRACEM, traces other than critical are stored only in dma buffer.

**Comment by kv2019i** [comment]
Closing now, with Zephyr mtrace, the trace messages are stored in SRAM window that can (and is) queried.
