### ISSUE TITLE
Volume issue when recording via dirana.

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/sof#247]
Summary: 
I captured several .wav files using arecord -c 2 via dirana, I spoke at a similar volume everytime, but sometimes the recorded sound's volume can be too low to hear clearly. 
Here are the .wav files:
[test.wav.zip](https://github.com/thesofproject/sof/files/2309904/test.wav.zip)

Reproduce step:
1.arecord -D hw:0,1 -c 2 -r 48000 -f s32_le test.wav -vv -i
2.repeat step 1 for several times

Environment:
sof : alpha release branch
kernel : Keyon 4.14 LTS
soft : 53e8c47591c44dd8bfb075f9d8ba5d43142f797d
tplg file : sof-apl-tdf8532.tplg (tplg is modified to 2ch on ssp2)

Log:
[dmesg.log](https://github.com/thesofproject/sof/files/2309915/dmesg.log)
[rmbox-t.log](https://github.com/thesofproject/sof/files/2309919/rmbox-t.log)

**Comment by mengdonglin** [comment]
Close this issue since this platform is no longer support. We'll use other platform to cover capture.
