### ISSUE TITLE
[BUG] cml-010-drop-stable patches missing from master.

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#2485]
The following patches are missing from master and need to be merged.
```git log --pretty=format:"%h%x09%an%x09%s"  origin/master..origin/cml-010-drop-stable``` 

- [x] 5e5f69eb        Janusz Jankowski        interrupt: dynamic clock change for waiti
- [x] cc4c356d        Slawomir Blauciak       workaround: disable hifi3 pcm conversion

**Comment by slawblauciak** [comment]
I don't think we want HIFI3 PCM conversion disabled by default on master.
@jajanusz I don't suppose the dynamic clock change is required either?

**Comment by paulstelian97** [comment]
HIFI3 conversion may no longer need to be disabled as PR#2499 is now merged.

**Comment by lgirdwood** [comment]
Updated, just the clock change now.

**Comment by jajanusz** [comment]
5e5f69e Janusz Jankowski interrupt: dynamic clock change for waiti ->https://github.com/thesofproject/sof/pull/2326
