### ISSUE TITLE
[BUG] Component programming guide is not up to date with code.

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#2489]
**Describe the bug**
https://thesofproject.github.io/latest/developer_guides/firmware/components/index.html appears to be out of data with recent updates to the component programming flows.

**Impact**
Difficult for 3rd parties to integrate components.

**Fix**
The API documentation and diagrams should come more from the doxygen generated pages. i..e the static pages should link/insert doxygen generated data.

**Comment by mmaka1** [comment]
Fixed by https://github.com/thesofproject/sof-docs/pull/194, https://github.com/thesofproject/sof-docs/pull/200, and https://github.com/thesofproject/sof-docs/pull/216.
