### ISSUE TITLE
[FEATURE] Improve topology macro argument validation

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#2515]
**Is your feature request related to a problem? Please describe.**
The topology pre-processor (i.e. M4) has no way to validate input data on macro arguments. This can successfully compile, but fail at runtime.

**Describe the solution you'd like**
Create a "make validate" rule as part of M4 pre-processing. This will invoke M4 using a different include $PATH whereby it's macro definitions do not create ALSA tplg output but validate each argument of a macro i.e. 
1) validates each argument has correct type (string, int, var array, etc)
2) validates argument strings to known enum values and/or lengths with allowed chars.
3) validates argument int values are all within allowed range or enum values.
4) creates a dot graph of topology.

The string/int value validation allowed values can come from the platform header. i.e. valid SSP ports (on BYT it's port 2 etc), max core count. Validation data can also come from hardcoded data like max rates, channels, scheduling periods etc.

**Comment by kv2019i** [comment]
We can close this one, implemented with tplg2 now? @lgirdwood ?
