### ISSUE TITLE
[BUG][APL][WHL] SOF_IPC_PANIC_ASSERT in KD with SSP

### ISSUE THREAD

**Issue by jdrzaszcz** [thesofproject/sof#2546]
**Describe the bug**
Running keyword detection feature with full topology,  using SSP loopback to get injection signal.
When reloading the topology without reloading FW in 17 Iterations is an exception Timeout error in the playback stream and than Panic.

**Topology**
```
                pipe_plb
               +------------------+
        +----+ | +---+  +-------+ |
        |Host|-->|Buf|->|SSP Dai|----------------------------------+
        +----+ | +---+  +-------+ |                                |
               +----------------- +                                |
                                                                   |
                   +-------------------------+                     |
        +--------+ | +---+   +-----+   +---+ |                     |
        |KD Dummy|<->|Buf|<->|ChSel|<->|Buf|<->+                   |
        +--------+ | +---+   +-----+   +---+ | |  pipe_cap         |
                   +-------------------------+ |                   |
                                               |                   |
                             +-----------------+                   |
        +--------------------|-----------------------------------+ |
        |+----+  +------+  +---+  +---+  +---+  +---+  +-------+ | |
        ||Host|<-|Buffer|<-|Kpb|<-|Buf|<-|Vol|<-|Buf|<-|SSP Dai|---+
        |+----+  +------+  +---+  +---+  +---+  +---+  +-------+ |
        +--------------------------------------------------------+
```
**To Reproduce**
Slim Driver python test:
test_02_kd_with_ssp.py 
with --topology_iterations=100
Repo:
https://gitlab.devtools.intel.com/cavs_scripts-py/cavs_scripts-py

**Reproduction Rate**
100 %

**Expected behavior**
Run all topology iterations without timeout and panic.

**Environment**
SOF master 15736c57667e541e619ec82618c322b7977f5fbd

**Logs**
[2020_03_13_09_54_43.zip](https://github.com/thesofproject/sof/files/4328965/2020_03_13_09_54_43.zip)
[2020_02_28_10_11_17.zip](https://github.com/thesofproject/sof/files/4328966/2020_02_28_10_11_17.zip)
[2020_03_13_10_35_59.zip](https://github.com/thesofproject/sof/files/4328967/2020_03_13_10_35_59.zip)

**Comment by tlauda** [comment]
@jdrzaszcz #2557 should fix the issue. Another problem is the fact, that test framework increases pipeline id every topology iteration. Probably the same one should be reused.

**Comment by jdrzaszcz** [comment]
@tlauda yes pr 2557 fix this issue. Btw, thanks for the hint.
