### ISSUE TITLE
[BUG] Wiskey Lake i7-8665U Processor - which DTOOLCHAIN

### ISSUE THREAD

**Issue by buscon** [thesofproject/sof#2571]
I have a Wiskey Lake i7-8665U Processor, can I build sof for such processor? if yes, which toolchain should I set in DTOOLCHAIN ?

thanks

**Comment by lgirdwood** [comment]
@buscon you will need the CNL GCC compiler, we are working on making the Cadence XCC compiler a free download too.
https://thesofproject.github.io/latest/platforms/index.html

However, most laptops and PCs are using FW code signing meaning Intel or the OEM can only sign the code for those devices. If you want to run your own code on Whiskeylake then you will need a Whiskeylake Chromebook or the UP Extreme board.

**Comment by buscon** [comment]
thank you!
