### ISSUE TITLE
[BUG] Segmentation Fault when running testbench for processing components

### ISSUE THREAD

**Issue by sebcarlucci** [thesofproject/sof#2643]
**Describe the bug**
Running the testbench causes a seg fault. I was able to isolate the issue at 
_src/include/sof/audio/pipeline.h_ in the function pipeline_posn_offset_get().

I tried removing commits e34a64d16a582d7399f630a0e7110755a39fca4f and b20191b362a6d14a44eead247ae677edd90ff6dd and this issue was resolved.

**To Reproduce**
Run the testbench

**Reproduction Rate**
100%

**Environment**
sof master branch (e73344a73658cb0b16f5381954c4f41f5ff42ca6)

**Comment by sebcarlucci** [comment]
fyi @singalsu @tlauda

**Comment by singalsu** [comment]
Please try this PR #2630

**Comment by sebcarlucci** [comment]
issue fixed by PR #2630

**Comment by singalsu** [comment]
It's not yet merged. Let's reopen this.

**Comment by paulstelian97** [comment]
@singalsu It is now.

**Comment by singalsu** [comment]
Yep it is. I'll close this!

There's another issue in testbench build it seems that is related to gcc version 9.2.1. I can create a PR for it.
