### ISSUE TITLE
[BUG][DSM] Channel 3,4 are empty when testing with S16_LE format

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#2679]
**Describe the bug**
Tested the DSM on TGL, S24_4LE and S32_LE are working well. but when testing with S16_LE format, channel 3 and 4 are empty in the recorded wav. From waveform, it looks like the data of channel 3 and 4 are mixed in channel 1 and 2. 

![DSM](https://user-images.githubusercontent.com/22468760/78111848-e0ade880-742f-11ea-83fd-3163ddf32fdf.PNG)

**To Reproduce**
aplay -Dhw:0,0 -f S16_LE -r 48000 -c2 sine_s16_le_48k.wav --dump-hw-params & arecord -Dhw:0,0 -f S16_LE -r 48000 -c 4 -d 10 DSM.wav -vv

**Reproduction Rate**
5/5

**Expected behavior**
channel 3,4 should also have data

**Impact**
no data in Channel 3 and 4, and channel 1 and 2 data are also wrong. 

**Environment**
1) Kernel: thesofproject/linux topic/smart-amp
2) Sof: thesofproject/sof tgl-004-drop-stabe 
3) Tplg: sof-tgl-smart-amplifier.m4 (rename it to sof-tgl-nocodec.tplg
4) Platform:TGL

[trace-dsm.txt](https://github.com/thesofproject/sof/files/4413109/trace-dsm.txt)
[dmesg-dsm.txt](https://github.com/thesofproject/sof/files/4413110/dmesg-dsm.txt)

**Comment by slawblauciak** [comment]
Low priority for now, this format is not supported currently.

**Comment by paulstelian97** [comment]
Probably the DMA engine is still configured for 4 bytes per elementary transfer instead of 2? Who's the owner of the DMA engine on this platform?

**Comment by lgirdwood** [comment]
Isn't demux/mux used here ? see #2687

**Comment by emilchudzik** [comment]
Issue fixed on:
Sof: bkokoszx/topic/smart-amp-revert-mux (859110d79)
Tplg: sof-tgl-smart-amplifier.m4 (rename it to sof-tgl-nocodec.tplg)

Checked on:
Kernel: thesofproject/linux topic/smart-amp topic/smart-amp (10b767431cbb) 
Platform:TGL

**Comment by keqiaozhang** [comment]
This issue is fixed in tgl-005-drop-stable branch. We tested it on Volteer-I2S and this issue is not reproducible.
Test recipe:
Driver: fce7f934f + https://github.com/thesofproject/linux/pull/1971 + https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?h=for-next&id=914f674bec6efe42f9d6b036850a618fd1698290
Firmware:
SOF branch:  tgl-005-drop-stable Commit: 277a9717
TPLG: sof-tgl-max98373-rt5682.tplg
