### ISSUE TITLE
[BUG] mux/demux should not do channel mixing

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#2687]
**Describe the bug**
Demux and mux should do demux and mux only. No mixing. Mixing is done by the mixer. Mux/demux currently is over complex and heavy at 70MCPS

**Expected behavior**
No mixing.
Mux N:1 stream only.
Demux 1:N streams only.

**Impact**
It's almost unusable today by most sof-developers due to configuration complexity and doing too much. Lets simplify to reduce complexity and MCPS. There are no uses that need the mixing.

**Comment by slawblauciak** [comment]
Change introduced in https://github.com/thesofproject/sof/pull/3000
Merged to master, closing.
