### ISSUE TITLE
[RFC] enhance topology validation

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof#2689]
**Describe the bug**
Lately I have worked on topology clean up and enhancements. Before every push I need to make sure no side effect nor unwanted changes are accidentally introduced. Simple changes also required careful check. Sometime quotation or extra `,` create different results. hard to find.

Current sof-ci supports checkpatch and build. Defintely we need more.

1. M4 macro validation. I found a feature request, https://github.com/thesofproject/sof/issues/2515. I'm looking at how this might be implemented and integrated.
2. Graph comparison, this is low hanging fruit. We have a tool to generate dot and png. I can compare dot text files and throw an error if diff is found. At least we can keep same graph by this.
3. Ultimately we need diff *.conf files. I did manually every time and go through line by line. Every change will make some difference in conf file. Some are desired, some are not. **I need some input/comment/suggestion for this task**.

This is one example from I fixed(https://github.com/thesofproject/sof/pull/2677) with sof-apl-dmic-a4ch-b2ch.conf comparison.
![ImagePic_0401_001](https://user-images.githubusercontent.com/45636982/78171725-c234f680-7409-11ea-9c48-cfa7b853efd3.png)

DMIC is accidentally put(or not removed). Hard to catch this error without comparing conf. May be `1. m4 macro validation task` above might help here if we can validate type of parameter.
```
PIPELINE_PCM_ADD(sof/pipe-volume-capture.m4,
        6, 6, 4, s16le,
        1000, 0, 0, DMIC,
        48000, 48000, 48000)
```

**Comment by lgirdwood** [comment]
@fredoh9 some of these need to go into the ALSA compiler, i..e validation of type

**Comment by fredoh9** [comment]
There is no immediate and EASY automated solution.
Close for now.
