### ISSUE TITLE
DMA flow unification

### ISSUE THREAD

**Issue by Jocelyn-Li** [thesofproject/sof#27]
The main goal of the unified flow is to make sure that SW/FW/HW sequences are correct, especially in case of DMA stop where sporadic DMA hangs are possible otherwise. It is also a direct preparation for hda-dai implementation that needs to cooperate with the hda-dma.

**Comment by tlauda** [comment]
@lgirdwood @mmaka1 Can we close this as basic unification was done?

**Comment by lgirdwood** [comment]
@mmaka1 fine by me, Ok with you ?
