### ISSUE TITLE
[BUG][TGL][DSM] Unexpected samples at the end of rec file.

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/sof#2701]
**Describe the bug**
There is unexpected samples at the end of recorded file, when used DSM feature on TGL platform with nocodec mode.

Begining is OK:
![begining](https://user-images.githubusercontent.com/41113230/78346041-c8101080-759e-11ea-9e05-8abac43dd29f.PNG)

Ending is not OK:
![end](https://user-images.githubusercontent.com/41113230/78346048-c9d9d400-759e-11ea-81ab-dd3837f8a724.PNG)

**To Reproduce**
terminal1: aplay -fS32_LE -r48000 -c2 -vv -i sine_48_2_32.wav
terminal2: arecord -fS32_LE -r48000 -c4 -vv rec.wav

**Reproduction Rate**
100%

**Expected behavior**
End of the recorded file shouldn't have such additional samples.

**Environment**
Kernel: thesofproject/linux topic/smart-amp (10b767431cbb)
Kconfig: kconfig-sof-nocodec.sh
FW: tgl-004-drop-stable (859110d79)
Tplg: sof-tgl-smart-amplifier.m4 (rename it to sof-tgl-nocodec.tplg)
Platform:TGL

**Logs**
[dsm-dmesg.txt](https://github.com/thesofproject/sof/files/4426302/dsm-dmesg.txt)
[dsm-logger.txt](https://github.com/thesofproject/sof/files/4426303/dsm-logger.txt)

**Comment by bkokoszx** [comment]
Duplicated with #2880. Closed
