### ISSUE TITLE
Commit: e4d567c6: topology: buffer: Add flags field to struct sof_ipc_buffer.

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2714]
This is automatically generated issue to track if changes from commit e4d567c6 found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-004-drop-stable are upstreamed.

**Comment by akloniex** [comment]
https://github.com/thesofproject/sof/pull/2580 which consisted of that exact commit was merged 4 days ago.
@lbetlej Please verify that your inssue generator is properly tuned. Maybe it gave a false-positive, for commit which was on mater and not on tgl branch?
