### ISSUE TITLE
Commit: eb0b270c: topology: fix ID typo in kfbm pipeline

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2715]
This is automatically generated issue to track if changes from commit eb0b270c found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-004-drop-stable are upstreamed.

**Comment by xiulipan** [comment]
@lbetlej  what is AR for these sets of issues?

**Comment by xiulipan** [comment]
close via https://github.com/thesofproject/sof/pull/2405
