### ISSUE TITLE
Commit: 838c99ee: topology: add demux capture pipeline

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2724]
This is automatically generated issue to track if changes from commit 838c99ee found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-004-drop-stable are upstreamed.

**Comment by keyonjie** [comment]
the PR https://github.com/thesofproject/sof/pull/2759 is to address this.

**Comment by keyonjie** [comment]
the PR #2759 is merged, so closing this.
