### ISSUE TITLE
Commit: 84d558a0: [Hack]topology: dsm_demux_coef: hack for nocodec LBM data check

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2726]
This is automatically generated issue to track if changes from commit 84d558a0 found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-004-drop-stable are upstreamed.

**Comment by keyonjie** [comment]
the PR https://github.com/thesofproject/sof/pull/2759 is to address this.

**Comment by keyonjie** [comment]
the PR #2759 is merged, so closing this.
