### ISSUE TITLE
ipc time out after system S3 on UP^2 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#277]
Audio failed to recovery form system S3, it will cause ipc time our error on UP^2 with pcm512 codec tplg.
How to reproduce:
1. aplay -D hw:0,0 -f dat -c 2 audio.wav & sleep 5; echo mem > /sys/power/state
2.  press any keys to wake up 
3. audio stopped after S3 and ipc time out error in dmesg

Test config: sof-dev + sof-master + soft-master
sof-dev: bafb590
sof-master: 9944905
soft-master: 41861aa
Tplg: sof-apl-pcm512x.tplg

[dmesg.log](https://github.com/thesofproject/sof/files/2335022/dmesg.log)
[rmbox-t.log](https://github.com/thesofproject/sof/files/2335023/rmbox-t.log)

**Comment by mengdonglin** [comment]
Remove branch label br-glk because all generic fixes on glk-003 branch have been merged by master.  So testing with master branch will be okay for mature platforms. glk release branch does not focus on compatibility across platforms.

**Comment by ZhendanYang** [comment]
Verified. This issue is gone on APL with both stable-1.2 and master branch.
