### ISSUE TITLE
Firmware oops when pulseaudio is enabled

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#278]
Pulseaudio will cause firmware oops on CNL and BYT
[dmesg.log](https://github.com/thesofproject/sof/files/2335366/dmesg.log)
[rmbox-t.log](https://github.com/thesofproject/sof/files/2335368/rmbox-t.log)

How to reproduce:
1.  make sure pulseaduio is enable(ls /usr/bin/pulseaudio)
2. check the dmesg after system is booted.

**Comment by lgirdwood** [comment]
duplicate of #210

**Comment by ZhendanYang** [comment]
duplicate of #274 .

**Comment by ZhendanYang** [comment]
Test with latest code base, this issue can't reproduce
Test env:
sof master: 299ccbc
sof tool: 60c3937
kernel: sof-dev 51ebd5d
