### ISSUE TITLE
Commit: e9a0359b: trace: add mn class

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2790]
This is automatically generated issue to track if changes from commit e9a0359b44d37afaf78d94c3a7dc86305dbb075f found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-003-drop-stable are upstreamed.

**Comment by jajanusz** [comment]
It's in this PR: https://github.com/thesofproject/sof/pull/2276/commits
