### ISSUE TITLE
Commit: 4d58cf62: drivers: intel: ssp: move M/N to separate driver

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2791]
This is automatically generated issue to track if changes from commit 4d58cf625e462a4d85a09f1d2fd2a84412c00c00 found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-003-drop-stable are upstreamed.

**Comment by jajanusz** [comment]
It's in this PR: https://github.com/thesofproject/sof/pull/2276/commits
