### ISSUE TITLE
Commit: 7a59d686: drivers: intel: mn: spinlock for registers access

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2792]
This is automatically generated issue to track if changes from commit 7a59d6868c120c03ca0bea57f4dcf432748ccfb5 found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-003-drop-stable are upstreamed.

**Comment by jajanusz** [comment]
It's in this PR: https://github.com/thesofproject/sof/pull/2276/commits
