### ISSUE TITLE
Commit: aceeb393: drivers: intel: mn: bclk sources

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2793]
This is automatically generated issue to track if changes from commit aceeb3939083b18c80535b488c74276c5e54e380 found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-003-drop-stable are upstreamed.

**Comment by jajanusz** [comment]
It's in this PR: https://github.com/thesofproject/sof/pull/2276/commits
