### ISSUE TITLE
Commit: fb14aac9: platform: intel: dai: add MCLKs count

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2794]
This is automatically generated issue to track if changes from commit fb14aac95f82bf84ef4d880ee23c1177fe94a46d found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-003-drop-stable are upstreamed.

**Comment by jajanusz** [comment]
It's in this PR: https://github.com/thesofproject/sof/pull/2276/commits
