### ISSUE TITLE
Commit: 34a1df56: drivers: intel: mn: mclk sources

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2795]
This is automatically generated issue to track if changes from commit 34a1df5629e1b78dee37f0a56a0db74766d137c5 found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-003-drop-stable are upstreamed.

**Comment by jajanusz** [comment]
It's in this PR: https://github.com/thesofproject/sof/pull/2276/commits
