### ISSUE TITLE
Commit: 1bb517ab: drivers: intel: mn: refactor mn_set_mclk

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2796]
This is automatically generated issue to track if changes from commit 1bb517ab9f643eda61b0bb4f075812f47b483f71 found as a result of comparison https://github.com/thesofproject/sof/compare/master...tgl-003-drop-stable are upstreamed.

**Comment by jajanusz** [comment]
Squashed into commit https://github.com/thesofproject/sof/pull/2276/commits/c0495a9086b225e78f0ff9c40d05bba467439c0f from this PR: https://github.com/thesofproject/sof/pull/2276/commits
