### ISSUE TITLE
Commit: b93dda55: [HACK]: topology: demux_coef_default: modify pipeline id

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2799]
This is automatically generated issue to track if changes from commit b93dda55ddb6d71dc67fea48e78607724060aabd found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-011-drop-stable are upstreamed.

**Comment by bardliao** [comment]
@lbetlej https://github.com/thesofproject/sof/commit/b93dda55ddb6d71dc67fea48e78607724060aabd is not required for master. It was replaced by https://github.com/thesofproject/sof/pull/2666 and https://github.com/thesofproject/sof/pull/2675
