### ISSUE TITLE
Commit: 5e5f69eb: interrupt: dynamic clock change for waiti

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2815]
This is automatically generated issue to track if changes from commit 5e5f69eb5ad14322a5f4599860a40f8009393d89 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-010-hot-fix2 are upstreamed.

**Comment by jajanusz** [comment]
It's just quick-fix version of proper fix that was applied on master in https://github.com/thesofproject/sof/pull/2326
