### ISSUE TITLE
Commit: b393c4d1: Volume: Always launch ramp in beginning of copy() operations

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2820]
This is automatically generated issue to track if changes from commit b393c4d10585a7a29cf00e8408b64cf59c7c7fbb found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-010-hot-fix2 are upstreamed.

**Comment by singalsu** [comment]
@lbetlej The description is very brief, I don't understand. Is there something for me to do for this and similar other automatic issues?

**Comment by lbetlej** [comment]
@singalsu Correct, you are expected to check if changes from commit b393c4d are upstreamed and close the issue after verification. If they are not upstreamed then the issue remains open to indicate  that there is work left to do.Check #2682 for background on the process.

**Comment by singalsu** [comment]
@lbetlej Thanks for explanation! This was also mentioned today in our team meet with @mengdonglin so we all now now what these are about.

**Comment by singalsu** [comment]
This patch is in master.
