### ISSUE TITLE
Commit: 9ddcb008: dai: ALH set burst_elems

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2823]
This is automatically generated issue to track if changes from commit 9ddcb008ec3ee3dc6a4436ba8dfb721684bc1c9b found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-010-hot-fix2 are upstreamed.

**Comment by RanderWang** [comment]
https://github.com/thesofproject/sof/commit/9ddcb008ec3ee3dc6a4436ba8dfb721684bc1c9b is included in master branch
