### ISSUE TITLE
Commit: 43512458: platform: define and use CONFIG_SYSTICK_PERIOD

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2847]
This is automatically generated issue to track if changes from commit 435124580a6fd49477cf2f1676b74f614000e322 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by tlauda** [comment]
Merged on master as 56ebbad4754011935e461a1cf562afc591fa1e9d#diff-42919f6fbfbb4d0860a530af0fbd9941.
