### ISSUE TITLE
Commit: 9932c338: platform: remove PLATFORM_LL_DEFAULT_TIMEOUT definition

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2848]
This is automatically generated issue to track if changes from commit 9932c3388d8c6e2fed1a2e46266aeda9c34524ba found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by tlauda** [comment]
Merged as 4cd4fd8f12878e3e0c0e09f0affd7b762c04851b.
