### ISSUE TITLE
Commit: 9e14ac1c: agent: add error tracing macro

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2849]
This is automatically generated issue to track if changes from commit 9e14ac1cb3cf6c9893f7b1026ea3b4677eb4fe8e found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by tlauda** [comment]
Merged as aef7bd0ba654cd909b578f275399913e1c3b.
