### ISSUE TITLE
Commit: 28c453cc: agent: refactor agent to be more useful

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2850]
This is automatically generated issue to track if changes from commit 28c453ccf0453348b390d819867225711cb7aa16 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by tlauda** [comment]
Merged as 9e0d994e8d3ab0316e1fdd59fdf98d603e769cb4.
