### ISSUE TITLE
Commit: 123ba8f5: agent: remove disable and enable functions

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2851]
This is automatically generated issue to track if changes from commit 123ba8f5152bb9db11324574d46c1b38cb5aa608 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by tlauda** [comment]
Merged as 0d0ee34a311b879365c5e49eb0aceaa04c4eab3f.
