### ISSUE TITLE
Commit: baf2b2db: platform: remove PLATFORM_IDLE_TIME definition

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2852]
This is automatically generated issue to track if changes from commit baf2b2db4d5f136003783df3d0ab6476ebea8efa found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by tlauda** [comment]
Merged as c07e43fad53afeed4872085a8b8c0056c917adcc.
