### ISSUE TITLE
Commit: 6d543cee: edf_schedule: do not pass sof structure anymore

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2853]
This is automatically generated issue to track if changes from commit 6d543cee74eda17a7d125c639ea4ab7c94437e52 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by tlauda** [comment]
Merged as f724ef10581a93e9524038e218cfd012b56794ba.
