### ISSUE TITLE
Commit: f3ba9394: pm-runtime: cavs: add power gating control for dsp cores

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2854]
This is automatically generated issue to track if changes from commit f3ba93943a54045fdd6d7f193d1c150678732d18 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/commit/14dcd128bda4080f795846ed6aa04503d05c68fd
