### ISSUE TITLE
Commit: 6d4000f9: platform: cavs: use pm-runtime api to power gate dsp cores

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2855]
This is automatically generated issue to track if changes from commit 6d4000f9e519f35020fb2ef85e752ab541cf1a0a found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/commit/b5c8f83c48e2abe79d6cc85b1e48efb42b61dbda
