### ISSUE TITLE
Commit: a928c8fa: pm: cavs: add lps flow

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2856]
This is automatically generated issue to track if changes from commit a928c8fa0d7f6759793ef581056cfc39d831561e found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/commit/de22810b0f60c36e8ed6ac022caa487a898923f1
