### ISSUE TITLE
Commit: 5d3f4a35: ipc: add pm power gating message

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2857]
This is automatically generated issue to track if changes from commit 5d3f4a35e65f14164c98f84e4f04d90d1614c86f found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/commit/bc0cbe2a2746cbe6d40fcd697c6db243cb92a4f6
