### ISSUE TITLE
Commit: b4f0b839: ipc: cavs: read set d0ix request directly from ipc registers

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2858]
This is automatically generated issue to track if changes from commit b4f0b8395748c5b60ebbbe38bd1507328cf11b80 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/commit/5e6ceb0829c19f936f9a7116c75020b0864b6ede
