### ISSUE TITLE
Commit: 55fdc5b4: ipc: pm: handle prevent-power-gating flag in pm-runtime

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2859]
This is automatically generated issue to track if changes from commit 55fdc5b4db8d84a85b9efc246f792fc335350589 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/commit/622472dce0bcc04892ac282ffa8cbcc542a4c2a0
