### ISSUE TITLE
Commit: 4852ae6d: kpb: disable pm-runtime of DSP#0 for data draining

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2860]
This is automatically generated issue to track if changes from commit 4852ae6da8f616ddbabe54ff9b7655f126838f1c found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/commit/53eaa8c8845b67c10d6813042078371875665416
