### ISSUE TITLE
Commit: 88048f48: dma-trace: fix race condition during initialization

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2861]
This is automatically generated issue to track if changes from commit 88048f489a748bf29be4be1eca8b8eb94a66baea found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/commit/78b022bfd312f8a9927ab280a8f5b5f7d858b6ea
