### ISSUE TITLE
Commit: e52bee05: cnl: shim: fix typo in CLKCTL bits definition

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2862]
This is automatically generated issue to track if changes from commit e52bee0570e4fd988d334f8d0e0b8a9ebb76c3c7 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/commit/40f7629f0b06a48da1973f7d30cf4140d3b347a5
