### ISSUE TITLE
Commit: 10b12bb5: cnl: clk: change default clock to 120MHz low power osc

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2863]
This is automatically generated issue to track if changes from commit 10b12bb5a03377bf7509872685afe9ea9edf380f found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged as https://github.com/thesofproject/sof/pull/2064/commits/9adc0bc899959587135d3167bfcfa4892864e638
