### ISSUE TITLE
Commit: 69c9c63e: lib: Make sure shifted quantity is treated as 64bit type

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2870]
This is automatically generated issue to track if changes from commit 69c9c63ee7bab136fba8f6a9614e3fab49197e5a found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by lbetlej** [comment]
Positive verification on 33a0990cc476862e47a5289ba1cc146eed0e

**Comment by dbaluta** [comment]
@lbetlej what's with 33a0990 ?
