### ISSUE TITLE
Commit: 00feda4f: topology: pcm: add helper for creating low power Capture PCM.

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2873]
This is automatically generated issue to track if changes from commit 00feda4f97b3c2c9c76d635ed70897d8f962cf5e found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by keyonjie** [comment]
This is already in master so closing it.
