### ISSUE TITLE
Commit: b3929c67: topology: pipe-kfbm-capture: create low power PCM for KWD PCM

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2874]
This is automatically generated issue to track if changes from commit b3929c67707de2fc3b9c9e770bd50e631eb34c92 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by keyonjie** [comment]
This is already in master so closing it.
