### ISSUE TITLE
Commit: df781a14: trace: complete trace on/off api including dma trace state

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2875]
This is automatically generated issue to track if changes from commit df781a14b3c468c9d83e71493d7a1c3ef6353f9f found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Merged ashttps://github.com/thesofproject/sof/commit/b37efd554f39ae00af1e24350101360604d08164
