### ISSUE TITLE
Commit: 755933e7: ipc: add commands to turn tracing on/off

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2876]
This is automatically generated issue to track if changes from commit 755933e797852ab489ccf6b877487166784d4bf9 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by mmaka1** [comment]
Implemented on master in a different way, by adding a flag to pm_gate IPC command.
