### ISSUE TITLE
Commit: f7dfd05b: add NO_TRACE flag to SETD0IX IPC

### ISSUE THREAD

**Issue by lbetlej** [thesofproject/sof#2877]
This is automatically generated issue to track if changes from commit f7dfd05b9fa4f92264905a47c0d9b155a9ce6602 found as a result of comparison https://github.com/thesofproject/sof/compare/master...cml-008-drop-stable are upstreamed.

**Comment by keyonjie** [comment]
This is already in master so closing it.
