### ISSUE TITLE
[BUG] Glitches on asrc capture stress test.

### ISSUE THREAD

**Issue by rentalagent666** [thesofproject/sof#2980]
**Describe the bug**
When running simultaneous capture and playback on external loopback (same SSP) with ASRC component on capture pipeline, with playback iteration >= 75, there are small gliches on capturead wave. Therefore, the THD value in the wave verification is worse than expected.

**Example captered stream**

Spectogram:
![image](https://user-images.githubusercontent.com/60582003/82986269-d9512880-9ff5-11ea-8f21-b72932b13455.png)

Wave:
![image](https://user-images.githubusercontent.com/60582003/82986407-0dc4e480-9ff6-11ea-9ec5-2ee5fade8be1.png)

**Topology**
```
                +------------------+
    +------+    | +---+  +-------+ |
    | Host |----->|Buf|->|SSP Dai|------------------+
    +------+    | +---+  +-------+ |                |
                +------------------+                |
                                                    |
                +---------------------------------+ |
    +------+    | +---+  +----+  +---+  +-------+ | |
    | Host |<-----|Buf|<-|Asrc|<-|Buf|<-|SSP Dai|<--+
    +------+    | +---+  +----+  +---+  +-------+ |
                +---------------------------------+
```

**To Reproduce**
Ru slim driver python tests from file:
test_01_asrc_simple_capture.py
e.g. 
TestAsrcCapture16000Hz16b16b2ch
TestAsrcCapture48000Hz32b32b2ch
TestAsrcCapture48000Hz16b16b2ch

**Reproduction Rate**
30 %

**Expected behavior**
Captured wave shouldn't have glitches.

**Environment**
I check it on: WHL RVP and TGL RVP,
but as I know from CI tests, it also happens on APL and ICL

Commit: 90ddae9ebe6abbb331a1833a9eacb2d0505865f8 on SOF master branch

**Comment by jdrzaszcz** [comment]
Duplicated
