### ISSUE TITLE
[BUG] Microphone not working Arch Linux kernel 5.7

### ISSUE THREAD

**Issue by Thiago4532** [thesofproject/sof#3052]
Microphone still detected but stopped working since I upgraded to linux kernel 5.7.

Linux Kernel: 5.7.2
sof-firmware: 1.5.1-1
OS: Arch Linux x86_64

**Comment by paulstelian97** [comment]
I assume the reason for closing was that it fixed by itself or you omitted some configuration that was necessary. Care to mention?
