### ISSUE TITLE
[BUG] JSL: S0ix failure while WOV pipeline is running with DSP in D0IX 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#3061]
**Describe the bug**
S0ix suspend failed while WoV is running. 

**To Reproduce**
1. Flash s0ix enabled coreboot and EC on the JSL board with default DB (DA7219+Max98360a).
2. Boot the device.
3. Flash the latest Google kernel with TGL S0IX enable kernel patch.
4. Make sure WOV KWD is working during S0 with the below command
arecord -Dhw:0,6 -M -N -c 2 -f S16_LE -r 16000 --buffer-size=68000 tmp.wav -d 10 -vvv &
5. Make sure S0IX is working on your system without running WOV using suspend_stress_test -c 1
6. Now run the command in step#4 and keep the system to suspend using powerd_dbus_suspend.

**Reproduction Rate**
10/10

**Expected behavior**
System should enter into S0IX with WOV running and should wake up upon detecting the keyword.

**Impact**
With WOV running, system failed to suspend to S0IX and waking up by itself upon issuing the suspend command.

**Environment**
1. Coreboot: Google_Waddledoo.13252.0.2020_05_28_0636 
2. Kernel:  commit id on master branch (117cc1f9fa7e81170064450a096df16fee63f800) + forklift branch (git remote add kernel-be https://chromeos.intel.com:443/internal/kernel-bleeding-edge, git fetch kernel-be, git checkout kernel-be/topics/tgl/i915 -b i915-forklifted-kernel)
3. platform: JSL chromebook
4. sof firmware and tplg: need chrome team to provide the detailed info.

[dmesg.jsl.txt](https://github.com/thesofproject/sof/files/4790672/dmesg.jsl.txt)

**Comment by ClarexZhou** [comment]
Close for verified by chrome team on JSL chromebook, error not seen.
