### ISSUE TITLE
ipc error for GLB_STREAM_MSG: PCM_PARAMS when playback on BYT

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/sof#307]
Summary:
Playback can't work and ipc error is found in dmesg.

[   70.544029] sof-audio sof-audio: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   70.544377] sof-audio sof-audio: error: ipc error for 0x60010000 size 0x14
[   70.544394] sof-audio sof-audio: ASoC: sof-audio hw params failed: -22
[   70.544401] sof-audio sof-audio: pcm: free stream 0 dir 0

0x0 [62.187105]	delta [62.187105]	host eSz
0x10 [62.187108]	delta [0.000002]	value 0x0000000000000300
0x20 [62.187110]	delta [0.000002]	pipe eOp
0x30 [62.187112]	delta [0.000002]	ipc pp0
0x40 [62.187115]	delta [0.000002]	value 0x0000000000000000
0x50 [62.187117]	delta [0.000003]	ipc eAa

Reproduce step:
aplay -D hw:0,0 -c 2 -r 48000 -f s16_le music.wav --period-size=192 --buffer-size=384 -vv -i

Environment:
sof-stable 1.2 : 90b455e07468e4b6ce929852bad0cdedc749587e
kernel : 7889a7ade4e20a81e297e3f5a5aea3b5d7fa55ef
sof tool: d2721194f7a36a4586b670e259c9f696cf4688be
tplg : test-ssp2-mclk-0-I2S-volume-s16le-s16le-48k-19200k-codec.tplg

Log:
[dmesg-ipcerror.log](https://github.com/thesofproject/sof/files/2351585/dmesg-ipcerror.log)
[rmbox-ipcerror.log](https://github.com/thesofproject/sof/files/2351586/rmbox-ipcerror.log)
[rmbox-t-ipcerror.log](https://github.com/thesofproject/sof/files/2351587/rmbox-t-ipcerror.log)

**Comment by xiulipan** [comment]
@ZhendanYang 
Retest please, should be fixed.

**Comment by ZhendanYang** [comment]
Verified. Can't reproduce on latest code base.
Test env:
sof stable-1.2: 7dd4b1d
kernel sof-dev: bc51a6f
soft master: d77beaf

**Comment by ZhendanYang** [comment]
Verified. Can't reproduce on latest code base.
Test env:
sof stable-1.2: 7dd4b1d
kernel sof-dev: bc51a6f
soft master: d77beaf
