### ISSUE TITLE
[FEATURE] Add multi sink support to testbench

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof#3095]
**Is your feature request related to a problem? Please describe.**
Currently testbench only supports single output from process component, this makes it hard to test components that split streams like crossover

**Describe the solution you'd like**
Add multiple sink support to testbench

**Describe alternatives you've considered**
N/A all other solutions require hacking the code block under test

**Additional context**
@singalsu CC for input

**Comment by lgirdwood** [comment]
@ranj063 @singalsu any pointers ?

**Comment by singalsu** [comment]
@cujomalainey Superb, thanks! This has been in my wish list of things to do! I think this should be fairly straightforward to do. Maybe add support for multiple sources too when convenient. Also feel free to clean up command line interface if needed. There's not much dependencies to fix them into scripts.

**Comment by cujomalainey** [comment]
Excellent, that is good to hear, this will allow us to better test the crossover while the UUID stuff works its way through the PR process.

**Comment by cujomalainey** [comment]
@johnylin76 this is done right?
