### ISSUE TITLE
[BUG][TGL][HDA] Need to add PGA volume control on HDA kwd tplg

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/sof#3105]
**Describe the bug**
Need to add PGA volume control on HDA kwd tplg

**To Reproduce**
1."sudo reboot" to reboot system
2.alsamixer
3.Tab

**Reproduction Rate**
10/10

**Expected behavior**
There is PGA volume control on HDA kwd tplg

**Impact**
There is no PGA volume control on HDA kwd tplg
<img width="501" alt="Capture" src="https://user-images.githubusercontent.com/56707932/85976821-ea82c000-ba0d-11ea-8fe7-e97421401d12.PNG">

**Environment**
Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).

Kernel: {sof-dev(f6eb2d31)}
SOF: {Master(b49080c)}
Name of the topology file
Topology: rename sof-hda-generic-4ch-kwd.tplg to sof-hda-generic-4ch.tplg
Name of the platform(s) on which the bug is observed.
Platform: TGL-U RVP with onboard codec ALC711 in HDA mode

[dmesg0629.log](https://github.com/thesofproject/sof/files/4843966/dmesg0629.log)
[sof-logger0629.log](https://github.com/thesofproject/sof/files/4843967/sof-logger0629.log)

**Comment by lgirdwood** [comment]
@mrajwa @keyonjie any comments here ?

**Comment by mrajwa** [comment]
@lgirdwood, it is enough to set it in the topology -> `# define(KFBM_TYPE, `vol-kfbm') `

**Comment by keyonjie** [comment]
yes, I can submit a quick fix for this.

**Comment by keyonjie** [comment]
@Liviali155 https://github.com/thesofproject/sof/pull/3109 is to fix this.

**Comment by Liviali155** [comment]
> @Liviali155 #3109 is to fix this.

Tried with #3109,error not seen
<img width="522" alt="Capture" src="https://user-images.githubusercontent.com/56707932/86076075-08a6f980-babc-11ea-8baa-94831e131511.PNG">

**Comment by ClarexZhou** [comment]
Close for PR merged
