### ISSUE TITLE
[BUG] SOF_VOLUME_LINEAR_ZC initial ramp is not as expected.

### ISSUE THREAD

**Issue by jdrzaszcz** [thesofproject/sof#3180]
**Describe the bug**
When running simultaneous capture and playback on external loopback (same SSP) with Volume component on playback pipeline, inital ramp length is not equal to given initial ramp parameter.
It happens with SofVolumeRamp = SOF_VOLUME_LINEAR_ZC in about 50 % test cases.
It occurs after commit 3dc0ae97ac837bc2d6d41361180d24072ae9a37e.

Example:
INITIAL_RAMP = 400
Format 48kHz 24b/32/ 1ch:

![image](https://user-images.githubusercontent.com/46779093/87425489-083f5000-c5de-11ea-9481-075fc5a5cdc9.png)

Expected 19152.0 samples in initial ramp, but got: 18718
Ramp time 0.38995833333333335 is not equal expected ramp time = 0.399 on channel 1

**Topology**
```
+------------------------------------------------------+
| +------+   +-----+   +-- --+   +-----+   +---------+ |
| | Host |-->| Buf |-->| Vol |-->| Buf |-->| SSP Dai |---+
| +------+   +-----+   +-----+   +-----+   +---------+ | |
+------------------------------------------------------+ |
                                                         |
+-----------------------------------+                    |
| +------+   +-----+   +---------+  |                    |
| | Host |<--| Buf |<--| SSP Dai |<----------------------+
| +------+   +-----+   +---------+  |
+-----------------------------------+
```
**To Reproduce**
Run one of fails slim driver python tests:
![image](https://user-images.githubusercontent.com/46779093/87424964-31abac00-c5dd-11ea-9e25-0c92a7cf09d8.png)
![image](https://user-images.githubusercontent.com/46779093/87425025-46883f80-c5dd-11ea-8a1e-732cf4200655.png)

**Reproduction Rate**
100 %

**Expected behavior**
Ramp length should be equal to given initial_ramp parameter

**Environment**
I checked it with WHL RVP platform.
On CI it occurs on also on APL_RVP and ICL_RVP. 

Commit: 318dc9f7e12ca48458ae3186d9a178c335e3b60a SOF master branch

**Example logs**
[dma_trace_1.log](https://github.com/thesofproject/sof/files/4918907/dma_trace_1.log)
[03_05_TestVolumeInitialRampSimple16000Hz32b32b2ch.zip](https://github.com/thesofproject/sof/files/4918908/03_05_TestVolumeInitialRampSimple16000Hz32b32b2ch.zip)

**Comment by lgirdwood** [comment]
@jdrzaszcz Fwiw, Ramp lengths are not always guaranteed to be equal with ZC enabled, it tries to pick the best zero crossing point per channel up to a certain limit. This can be +/- a certain tolerance.

**Comment by jdrzaszcz** [comment]
@lgirdwood The tolerance in our test is set to +/- 2 %, if it too strict, what value do you propose?

**Comment by lgirdwood** [comment]
@singalsu what do you recommend ?

**Comment by singalsu** [comment]
I tried to avoid 64 bit arithmetic in ramp calculations for speed. Also I recall I kept possibility for pretty slow ramps, maybe near 5s, I don't remember but can check. By going to 64 bit or decreasing max ramp length it could be made more accurate. Halving max. time would 1/2 the length difference.

Though I'm not aware of use case that requires specific ramp length. Are there? Would +/- 10% be reasonable?

**Comment by jdrzaszcz** [comment]
I'm sure what the actual use cases look like (in some topology with src I saw 20 ms for type 2), in our tests the ramp length is between 100 and 1000 ms. I'll change tolerance to +/- 10 % and see how it works.

**Comment by slawblauciak** [comment]
@jdrzaszcz any updates?

**Comment by jdrzaszcz** [comment]
@slawblauciak I check it with 10 % tolerance and its ok.
