### ISSUE TITLE
[BUG] CI regression with APL DMIC 16kHz

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#3258]
The test reports for https://github.com/thesofproject/sof/pull/3245 show a single unexplained issue with APL DMIC16kHz https://sof-ci.01.org/sof-pr-viewer/#/build/PR3245/build5301944

Filing a bug to keep track of the issue in the absence of feedback.

**Comment by slawblauciak** [comment]
@zrombel please clarify.

**Comment by zrombel** [comment]
This test fail was a network issue that caused logs absence on 01.org build report. Previous and next PR tests execution shows no failed tests on mentioned PR. For similar issues validation rerun will be performed. Closing issue.
