### ISSUE TITLE
[BUG] Platform & CPU timer should be distinct

### ISSUE THREAD

**Issue by jajanusz** [thesofproject/sof#3274]
**Describe the bug**
`cpu_timer_get` and `timer_get` that get timers from `struct sof` should return distinct physical or virtual timers, so user can register handler in one of them with not overriding another one.

**To Reproduce**
(On Baytrail) Try to set handler for one timer and then to another, previous one will be removed.
Example in: https://github.com/thesofproject/sof/pull/3268

**Reproduction Rate**
100%

**Expected behavior**
I should get distinct timers or at least should be able to use them like they would be distinct.

**Impact**
Needed for implementation of budgeting in scheduler.

**Environment**
IMX and pre-CAVS platforms (it works as expected only on CAVS platforms).

**Side note**
Probably doxygen should be more verbose and specify that these timers should be distinct.

**Comment by jajanusz** [comment]
@mengdonglin please assign some1 who supports baytrail, thanks

**Comment by lgirdwood** [comment]
@jajanusz ack - but the new API must map easily onto Zephyr clock APIs i..e naming and calling convention @finikorg has Zephyr clock support for all IP on his TODO list IIRC.

**Comment by paulstelian97** [comment]
On the i.MX one, I think we only have one, so we should be able to somehow reuse part of the infrastructure for cascaded IRQs (the part that allows multiple handlers per same interrupt) within the firmware itself.
