### ISSUE TITLE
[FEATURE]Add an error trace message for functionality check 

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof#3281]
**Is your feature request related to a problem? Please describe.**
Add a message like **Hello SOF** into error trace to show error trace works

**Describe the solution you'd like**
- create new component to show this messge
- Add this into one existing component 

**Additional context**
Discussion moved from https://github.com/thesofproject/sof/issues/3265

**Comment by xiulipan** [comment]
@plbossart @lgirdwood @lyakh @paulstelian97 @marc-hb moved the discussion in #3265 here.
 We have 2 proposal:
- create new component to show this message (need to send the message after trace init)
- Add this into one existing component (eg. Add this message in IPC comp, but may show multiple time)

Please have some comments. Then we can refine out logger check test case to track error trace status.

**Comment by paulstelian97** [comment]
I think the message could be shown in either the generic SOF init code or in the platform init code. I suggested IPC only because messages have to be tied to some component.

Or perhaps trace init itself could show a message (configurable, of course) or just dump the message into the mailbox as some sort of initialization.

**Comment by xiulipan** [comment]
@paulstelian97 I tried to add this kind for message into trace init. It used to be very easy in past if we just send trace message into mailbox. But now the trace in mailbox is actually some address and date, then we need a ldc file to parse it out.

I will have try and RFC PRs

**Comment by paulstelian97** [comment]
We don't need ldc file to verify that there is some message, only to actually decode it. You can put in some fixed parameters in the message and the parameters don't need the LDC file to check, if you know how many there should be beforehand.

**Comment by lyakh** [comment]
> @plbossart @lgirdwood @lyakh @paulstelian97 @marc-hb moved the discussion in #3265 here.
> We have 2 proposal:
> 
>     * create new component to show this message (need to send the message after trace init)
> 
>     * Add this into one existing component (eg. Add this message in IPC comp, but may show multiple time)
> 
> 
> Please have some comments. Then we can refine out logger check test case to track error trace status.

Use `&sa_tr` from agent.c?

**Comment by lgirdwood** [comment]
@xiulipan keep it simple. Just emit trace error level in platform_boot() for each platform.

**Comment by marc-hb** [comment]
Was this fixed by commit 67a0a6937 / PR #3319?

**Comment by marc-hb** [comment]
Assuming fixed and closing, re-open if needed.
