### ISSUE TITLE
[BUG] Unable to build topology

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/sof#3336]
**Describe the bug**
Unable to build topology using script build-tools.sh. There is many errors from alsa lib.

**To Reproduce**
cd sof repo
./scripts/build-tool.sh

**Reproduction Rate**
100%

**Environment**
Branch: master
Commit: 2e07bb9d

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/41113230/91023792-4aa17700-e5f7-11ea-84e5-06379439af3e.png)

**Comment by lgirdwood** [comment]
oh, I think we need a check for alsa-lib version inthe tobology cmake. IIUC it needs a recent commit in alsa-lib that is upstream but not part of the last release. @keyonjie fyi - we need a cmake check for this commit or later version of alsa-lib

**Comment by emilchudzik** [comment]
with new alsa-lib, topology building is ok:
```
cd alsa-lib
git pull
./gitcompile
sudo make install
```

**Comment by slawblauciak** [comment]
@emilchudzik good to close?

**Comment by emilchudzik** [comment]
@slawblauciak yes, it can be close
