### ISSUE TITLE
[BUG] Formalize definition of reset callback

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof#3419]
**Describe the bug**
Reset callback definition is not clear on the depth of a reset

```
/**                                                                                                                                                                                
 * Resets component.                                                                                                                                                               
 * @param dev Component device.                                                                                                                                                    
 */   
```

I have noticed many components treat this callback very differently

For example:
 * DCB does nothing (maintains filter state)
 * IIR removes everything including filter config
 * volume does nothing (maintains config)

**Comment by cujomalainey** [comment]
@johnylin76 @singalsu FYI

**Comment by lgirdwood** [comment]
@singalsu can you take a look at this after v1.6.

**Comment by bkokoszx** [comment]
Hi @singalsu I'm just checking SOF 1.7 status. Were you able to take a look at this bug?

@lgirdwood Do we need it in 1.7?
