### ISSUE TITLE
Some trace messages are missing..

### ISSUE THREAD

**Issue by ravulapati** [thesofproject/sof#3442]
We have enabled trace.By following sof documentation we tried to run sof-logger.
We see that some trace messages were not being observed.

What could be the problem.

**Comment by dbaluta** [comment]
Can you add more details? What is the SOF firmware version, what is the log observed and what are the logs you think are missing? Also, what is the command used to retrieve the logs?

**Comment by marc-hb** [comment]
No answer, closing
