### ISSUE TITLE
[GLK][br-glk] playback silence issue after arecord on GLK

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#346]
Test with headset: use arecord to capture audio, then use aplay to check the recorded data or play audio file, there's nothing can be heard. But after hot-plug the headset,  you can hear the sound. repetition rate is 100%.  I also tried to play with speaker after arecord, no such issue.
How to reproduce:
1. arecord -D hw:0,1 -f s32_le -c 2 -r 48000 test.wav
2. aplay -D hw:0,1 test.wav (you can hear nothing at all)
3. do headset hot-plug during the playback, then you can hear the sound.

Test env:
kernel-cros-sof-v4.14-rebase: e4bc814c982d5
sof-glk-003-drop-stable: f245831
soft-master:d77beaf8b

[dmesg.log](https://github.com/thesofproject/sof/files/2369880/dmesg.log)
[rmbox.log](https://github.com/thesofproject/sof/files/2369882/rmbox.log)
[rmbox-t.log](https://github.com/thesofproject/sof/files/2369883/rmbox-t.log)

**Comment by mengdonglin** [comment]
This seems not a firmware bug but more likely to be a codec driver issue.

**Comment by mengdonglin** [comment]
Close this issue since it's not firmware issue, tracking it by kernel issue: https://github.com/thesofproject/linux/issues/154
