### ISSUE TITLE
[FEATURE] Document how to build SOF with Zephyr

### ISSUE THREAD

**Issue by yongzhi1** [thesofproject/sof#3498]
Since SOF Zephyr upstream is close to complete, the time is ready to publish the build instructions so that people can build SOF FW based on stable_v1.6 branch with Zephyr RTOS on master branch.

cc @lrgirdwo

**Comment by lgirdwood** [comment]
@lyakh fyi

**Comment by lyakh** [comment]
> @lyakh fyi

@lgirdwood do I understand it correctly that we first need Zephyr upstream to add SOF as a module, which would make it possible to build firmware and, respectively, to document the process?

**Comment by lgirdwood** [comment]
@lyakh we should state that in the intro and that's planned for Zephyr 2.5. The intro should state that these instructions are temporary and will change as the upstreaming completes. These instruction should show how to build it **today**
We can always update to module when @andyross and @nashif have everything ready on the Zephyr side.

**Comment by lyakh** [comment]
> @lyakh we should state that in the intro and that's planned for Zephyr 2.5. The intro should state that these instructions are temporary and will change as the upstreaming completes. These instruction should show how to build it **today**
> We can always update to module when @andyross and @nashif have everything ready on the Zephyr side.

@lgirdwood today we can build Zephyr with SOF in one of (at least) 3 ways: using as a basis SOF's clone, or the clone by @andyross or mine. The first option has the advantage of being at least a project repository, not a private one, but it's outdated. The latter two options should produce the same result (once @andyross merges my patches) but they use private trees. We could maybe update SOF's zephyr clone?

**Comment by lgirdwood** [comment]
Yes, please update SOF Zephyr clone to match @andyross branch with your fixes too.

**Comment by lgirdwood** [comment]
> Yes, please update SOF Zephyr clone to match @andyross branch with your fixes too.

and use this for the build instructions as it's probably closest to what will merge in Zephyr master.

**Comment by marc-hb** [comment]
> the time is ready to publish the build instructions

Where?

How about https://github.com/thesofproject/sof/wiki ?

> The intro should state that these instructions are temporary and will change as the upstreaming completes

**Comment by lgirdwood** [comment]
> > the time is ready to publish the build instructions
> 
> Where?
> 
> How about https://github.com/thesofproject/sof/wiki ?

Please add to sof-docs

**Comment by marc-hb** [comment]
sof-docs is good for slow-changing documentation (and even for this it tends to be out of date)

**Comment by lgirdwood** [comment]
sof-docs is for all docs today as it's checked by technical writers. If any parts are out of date then they can be updated or marked as bug and assigned for update.

**Comment by yongzhi1** [comment]
Close for lowered priority.

**Comment by lgirdwood** [comment]
@lyakh @yongzhi1 reopen as we need to add more context to existing instructions.

**Comment by iuliana-prodan** [comment]
@lgirdwood @lyakh @yongzhi1 where/what are the existing instructions?

I want to build SOF with Zephyr and I saw this README: https://github.com/thesofproject/sof/blob/master/zephyr/README
Are the repos and branches mentioned there still the ones to use?
Otherwise, which are the latest repos/branches for SOF and Zephyr?

Thanks!

**Comment by lgirdwood** [comment]
> @lgirdwood @lyakh @yongzhi1 where/what are the existing instructions?
> 
> I want to build SOF with Zephyr and I saw this README: https://github.com/thesofproject/sof/blob/master/zephyr/README
> Are the repos and branches mentioned there still the ones to use?
> Otherwise, which are the latest repos/branches for SOF and Zephyr?
> 

Latest PR for sof docs is here 

https://github.com/thesofproject/sof-docs/pull/330#pullrequestreview-586525659

This has not been tested for i.MX yet, so you will need help for iMX SOC support from Zephyr team. @dbaluta is in the loop.

> Thanks!

**Comment by aiChaoSONG** [comment]
@lgirdwood I think we have nice document here: https://thesofproject.github.io/latest/getting_started/build-guide/build-with-zephyr.html, can we close?

**Comment by marc-hb** [comment]
https://thesofproject.github.io/latest/getting_started/build-guide/build-with-zephyr.html has been available for a long time and was just updated again. File more specific issues if/when needed, closing this super generic ask which was done a long time ago. Thanks @aiChaoSONG for the scrubbing help.
