### ISSUE TITLE
[APL][br-glk] DSP panic after booting up on APL with glk-003 branch

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/sof#351]
Summary:
DSP panic after booting on APL with GLK-003 branch firmware.

[    6.901681] sof-audio sof-audio: error : DSP panic!
[    6.901692] sof-audio sof-audio: panic: dsp_oops_offset 788480 offset 788480
[    6.901696] sof-audio sof-audio: status: fw entered - code 00000005
[    6.901716] sof-audio sof-audio: error: can't enter idle
[    6.901718] sof-audio sof-audio: error: trace point 00004000
[    6.901721] sof-audio sof-audio: error: DSP Firmware Oops
[    6.901723] sof-audio sof-audio: error: Exception Cause: IllegalInstructionCause, Illegal instruction
[    6.901726] sof-audio sof-audio: EXCCAUSE 0x00000000 EXCVADDR 0x00000000 PS       0x00060725 SAR     0x00000010
[    6.901729] sof-audio sof-audio: EPC1     0xbe0258dd EPC2     0xbe0160da EPC3     0x00000000 EPC4    0x00000000
[    6.901732] sof-audio sof-audio: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[    6.901734] sof-audio sof-audio: EPS2     0x00060120 EPS3     0x00000000 EPS4     0x00000000 EPS5    0x00000000
[    6.901737] sof-audio sof-audio: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00010198 INTERRU 0x00000222

This issue might caused by PR #343 , I did some changes to the code and this issue disappeared.
yangzhendan@zdyang:~/workspace/reef/sof$ git diff
diff --git a/src/platform/apollolake/include/platform/memory.h b/src/platform/apollolake/include/platform/memory.h
index c911d10..7656c6e 100644
--- a/src/platform/apollolake/include/platform/memory.h
+++ b/src/platform/apollolake/include/platform/memory.h
@@ -135,8 +135,7 @@
 #define HEAP_RT_COUNT64                        256
 #define HEAP_RT_COUNT128               32
 #define HEAP_RT_COUNT256               128
-#define HEAP_RT_COUNT512               8
-#define HEAP_RT_COUNT1024              4
+#define HEAP_RT_COUNT512               32
 
 #define L2_VECTOR_SIZE                 0x1000

Environment:
sof: glk-003-drop-stable f245831ea3282fc52c59791df2a8fac0533ec467
soft: master d77beaf
kernel: sof-dev 64cf3e3

log:
[dmesg-glk.log](https://github.com/thesofproject/sof/files/2370031/dmesg-glk.log)
[rmbox-glk.log](https://github.com/thesofproject/sof/files/2370032/rmbox-glk.log)
[rmbox-t-glk.log](https://github.com/thesofproject/sof/files/2370033/rmbox-t-glk.log)

**Comment by mengdonglin** [comment]
Close this issue because all generic fixes on glk-003 branch have been merged by master. And we should use master branch to test non-GLK platforms to assure compatibility. glk release branch does not focus on compatibility across platforms.
