### ISSUE TITLE
[APL/CNL][br-master]ipc error after boot on APL and CNL.

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/sof#352]
Summary:
There are ipc errors after boot on APL and CNL when pulseaudio is enabled. 
But playback and capture still work.

[    9.330713] sof-audio sof-audio: error: ipc error for 0x60010000 size 0x14
[    9.330723] sof-audio sof-audio: ASoC: sof-audio hw params failed: -22
[    9.330727] sof-audio sof-audio: pcm: free stream 0 dir 1
[    9.330735] sof-audio sof-audio: ipc tx: 0x60030000
[    9.330804] sof-audio sof-audio: ipc tx succeeded: 0x60030000
[    9.330810]  Port0: ASoC: hw_params FE failed -22

Environment:
sof: sof-master 051f827dbbc8b0e11aed524d5d8b763b94f293dd
soft: master d77beaf
kernel: sof-dev 64cf3e3

Log:
[dmesg-ipcerror.log](https://github.com/thesofproject/sof/files/2370105/dmesg-ipcerror.log)
[rmbox-t-ipcerror.log](https://github.com/thesofproject/sof/files/2370106/rmbox-t-ipcerror.log)

**Comment by lgirdwood** [comment]
@ZhendanYang This is normal and expect for pulseaudio and other audio servers at startup time. PA is checking the sound device to see which sample rates and formats it's supports. It only know about supported capabilities by FW returning an error resuylt when an unsupported format is requested.

All sound server init errors should only be logged as a bug if playback/capture does not work.
