### ISSUE TITLE
[BYT][br-1.2] Stress test: keep pause/resume or XRUN injection when playback or capture can cause ipc error

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/sof#353]
Summary:
keep pause/resume or XRUN injection when playback or capture can cause ipc error
[   99.937334] sof-audio sof-audio: error: ipc error for 0x60070000 size 0xc
[   99.937372]  Passthrough: ASoC: trigger FE failed -16
[   99.937395] sof-audio sof-audio: pcm: trigger stream 0 dir 0 cmd 3
[   99.937427] sof-audio sof-audio: ipc tx: 0x60060000
[   99.937933] sof-audio sof-audio: ipc tx succeeded: 0x60060000
[   99.938070] sof-audio sof-audio: pcm: trigger stream 0 dir 0 cmd 4
[   99.938113] sof-audio sof-audio: ipc tx: 0x60070000
[   99.938584] sof-audio sof-audio: error: ipc error for 0x60070000 size 0xc
[   99.938620]  Passthrough: ASoC: trigger FE failed -16

Reproduce step:
1. aplay -D hw:0,0 -c 2 -r 48000 -f s16_le music.wav -vv -i
2. pause/resume or XRUN injection

Environment:
sof: stable1.2 834d3cba0f5f7d2f0184ecf57f0391da08408676
soft: master d77beaf
kernel: sof-dev 64cf3e31

Log:
[dmesg.log](https://github.com/thesofproject/sof/files/2370583/dmesg.log)
[rmbox.log](https://github.com/thesofproject/sof/files/2370584/rmbox.log)
[rmbox-t.log](https://github.com/thesofproject/sof/files/2370585/rmbox-t.log)

**Comment by ZhendanYang** [comment]
Only playback(no pause/resume, no XRUN) can also cause ipc error.
[   56.651142] sof-audio sof-audio: ipc tx: 0x50020000
[   56.651371] sof-audio sof-audio: ipc tx succeeded: 0x50020000
[   56.862720] sof-audio sof-audio: pcm: trigger stream 0 dir 0 cmd 1
[   56.862746] sof-audio sof-audio: ipc tx: 0x60040000
[   56.863033] sof-audio sof-audio: error: ipc error for 0x60040000 size 0xc
[   56.863061]  Passthrough: ASoC: trigger FE failed -16
[dmesg-play.log](https://github.com/thesofproject/sof/files/2387626/dmesg-play.log)
[rmbox-play.log](https://github.com/thesofproject/sof/files/2387627/rmbox-play.log)
[rmbox-t-play.log](https://github.com/thesofproject/sof/files/2387628/rmbox-t-play.log)

**Comment by xiulipan** [comment]
@ZhendanYang 
Retest thanks.

**Comment by ZhendanYang** [comment]
Verified. Can't reproduce on latest code base.
Test env:
sof stable-1.2: 7dd4b1da6ea40bf8c5c404c0e606e48cd3d33e62
kernel sof-dev: bc51a6f
soft master: d77beaf
