### ISSUE TITLE
[FEATURE] Upgrade topologies to work with alsa-lib upstream

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof#3639]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Modify the topologies to use the inclusive language suggested in recent alsa-lib updates

**Comment by plbossart** [comment]
@ranj063 the SOF topologies should build with alsa-lib upstream, you will get a lot of messages telling that the topology needs to change but backwards compatibility is preserved. if that's not the case it's a bug. Can you clarify

I was counting on @libinyang to provide us with alsa-lib upstream packages *before* we can do the change.

Also we may want to be patient and make sure alsa-lib updates are actually propagated in most distros used for SOF development before changing topologies.

**Comment by ranj063** [comment]
@plbossart sorry I had a problem with compilation because of my own changes to alsa-lib master. The SOF topologies compile just fine with a lot of messages about deprecates.

**Comment by lgirdwood** [comment]
@ranj063 good now ? Can we close ?

**Comment by ranj063** [comment]
@lgirdwood yeah. I think we can close this. We still use deprecates but maybe its not super important
