### ISSUE TITLE
[CML][Chromebook][coreboot] I2S square wave frequency is not 400Hz

### ISSUE THREAD

**Issue by lancedkhou** [thesofproject/sof#3916]
There is a chromebook device without smart AMP design using DSP to generate I2S square wave for chromebook developer mode boot beep.

What's the issue we met:
    The I2S square wave frequency generated by DSP was not 400 as requested. It's 800Hz.

What' the expectation:
    400Hz I2S square wave.

Reference codes:

1. chromebook coreboot request 400: https://chromium.googlesource.com/chromiumos/platform/vboot_reference/+/refs/heads/factory-puff-13329.B/firmware/2lib/2ui.c#333
2. Generate I2S square wave with 400:
https://chromium.googlesource.com/chromiumos/platform/depthcharge/+/refs/heads/factory-puff-13329.B/src/drivers/sound/i2s.c#69
3. Send out the I2S data:
https://chromium.googlesource.com/chromiumos/platform/depthcharge/+/refs/heads/factory-puff-13329.B/src/drivers/sound/i2s.c#85
4. The I2S square wave was measure by logic analyzer: 800Hz which is not acceptable with RT1015.

*There is no audio playback issue in Chromebook OS. The issue is specific to Chromebook coreboot(developer mode) UI.

Please help change the I2S square wave to common 400Hz.
Thanks for helping!

Lance

**Comment by lgirdwood** [comment]
@cujomalainey is this using DSP mode or legacy HDA/SSP mode ?

**Comment by cujomalainey** [comment]
@lgirdwood i think it just bit bangs the values out. Wasn't till TGL that we started using SSP. Looking to find our firmware contacts for this. 

Also FYI it is not 400Hz, it is [400kHz](https://chromium.googlesource.com/chromiumos/platform/depthcharge/+/refs/heads/main/src/board/puff/board.c#54)

@lancedkhou I don't think this is an SOF issue, please file a issue on the partner issue tracker and assign quasisec@ or amcrea@ and cc myself (cujomalainey@) and benzh@
