### ISSUE TITLE
Discussion: How to keep track of total bytes transferred to DSP

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/sof#4064]
Compress API needs to keep track of total `consumed` bytes by the Host component (think compress playback). 

On the kernel side, each period time SOF firmware Host component sends us a notification:

```
src/audio/host.c: 130

static void host_update_position(struct comp_dev *dev, uint32_t bytes)                                                                                                                                     
/* ... snip ... */
 if (hd->report_pos >= hd->host_period_bytes) {
                   /* send timestamped position to host
                   * (updates position first, by calling ops.position())
                  */
                 pipeline_get_timestamp(dev->pipeline, dev, &hd->posn);
                 mailbox_stream_write(dev->pipeline->posn_offset, &hd->posn, sizeof(hd->posn))
                 ipc_msg_send(hd->msg, &hd->posn, false);
}
```

On the kernel side, we retrieve the position via:

```
sound/soc/sof/ipc.c: 440

void ipc_period_elapsed() 
   dev_info(sdev->dev, "posn : host 0x%llx dai 0x%llx wall 0x%llx\n", posn.host_posn, posn.dai_posn, posn.wallclock);
```

So, basically Firmware reports to the kernel each period `posn.host_posn` bytes. 

Here comes to confusion. I don't think I understand what exactly is `posn.host_posn` and how to figure out the total_copied bytes from this information.

`posn.host_posn` is updated in Host like this:

`
static int host_position(struct comp_dev *dev, struct sof_ipc_stream_posn *posn)                                                                                                                                                 
{
       struct host_data *hd = comp_get_drvdata(dev);

        /* TODO: improve accuracy by adding current DMA position */
        posn->host_posn = hd->local_pos;
        posn->dai_posn = dev->position;

        return 0;
}

A better solution would be to report the global position (total number of copied bytes). Like this

```
diff --git a/src/audio/host.c b/src/audio/host.c
index 0c456a99f..4be8ba722 100644
--- a/src/audio/host.c
+++ b/src/audio/host.c

      /* TODO: improve accuracy by adding current DMA position */
-       posn->host_posn = hd->local_pos;
+       posn->host_posn = dev->position;

```

**Comment by lgirdwood** [comment]
Does this need to align with ALSA position (or can there be a small difference to cater for the DMA copy) ?
Host position for playback is bytes copied to FW at pipeline entry, DAI position is the presentation position (which will have a small latency between host position). 
CC @plbossart as author of ALSA compressed
