### ISSUE TITLE
[BUG]/scripts/build-tools.sh -T doesn't build development topologies

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/sof#4141]
**Describe the bug**

Running `/scripts/build-tools.sh -T` doesn't build tplg files in `tools/topology/development`

Is this expected behavior? How one would build topologies in `tools/topology/development` using `build-tools.sh` script

**Comment by lgirdwood** [comment]
@singalsu fyi - I assume this is a regression ? @marc-hb fyi.

**Comment by marc-hb** [comment]
They're built only when building everything. Demo:

```
rm tools/topology/development/sof-apl-dmic-asymmetric.m4 
./scripts/build-tools -T # does not care about /development/
./scripts/build-tools    # tries to build /development.
```


This single line is enough to change that:
```diff
--- a/tools/topology/development/CMakeLists.txt
+++ b/tools/topology/development/CMakeLists.txt
@@ -34,6 +34,7 @@ set(TPLGS_UP
 )
 
 add_custom_target(dev_topologies ALL)
+add_dependencies(topologies dev_topologies)
 
 foreach(tplg ${TPLGS})
 	list(GET tplg 0 input)
```

However I have no idea whether that's desirable or not. I think @plbossart, @ranj063  have some informed opinions on what topologies should be built and when? A new `tools/topology/README.md` would not hurt.

>  I assume this is a regression

No idea but there hasn't been any recent change AFAICT

**Comment by fredoh9** [comment]
From SOF-CI, we use "scripts/build-tools.sh" without any option. We should build all.
But I checked on the storage server, I couldn't find development tplg files. Maybe we have some bugs when copying output.

**Comment by fredoh9** [comment]
Sorry for a bit off the topic. This issue started with -T option...

For the storage server, there was my misunderstanding. There is no development directory, but all files are under `tplg` directories. I don't think we have any platform to use development's topology, I think, we are keeping flat directory structure for sake of simplifying deploy script. We have more option to do so also. I created an internal issue to discuss that.

**Comment by dbaluta** [comment]
@fredoh9 thanks for your explanations.
To sum up:
- `./scripts/build-tools.sh  -T` only builds topologies in the main directory
- if one wants to build topologies in `development` directory there is the option to run `./scripts/build-tools.sh` with no params.

**Comment by marc-hb** [comment]
I got tired of this confusion too and I submitted #4210

**Comment by marc-hb** [comment]
> if one wants to build topologies in development directory there is the option to run ./scripts/build-tools.sh with no params.

Except for this "install" race condition I just discovered: #5067
