### ISSUE TITLE
[BUG] dai_config IPC timeout on TGLU_RVP_NOCODEC when arecord

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/sof#4164]
**Describe the bug**
When running check-capture on TGLU_RVP_NOCODEC ,fread  failed in logger_read when arecording

**To Reproduce**
TPLG=sof-tgl-nocodec-ci.tplg ~/sof-test/test-case/check-capture.sh -d 1 -l 1 -r 50

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: aae5bcfa
SOF Branch: main
SOF Commit: ea5d9be6a0c3
TPLG=sof-tgl-nocodec-ci.tplg
Device:TGLU_RVP_NOCODEC [jf-tglu-rvp-nocodec-1]

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/79959904/117754144-564bd100-b24c-11eb-8c39-777a95405add.png)

**dmesg log**
![image](https://user-images.githubusercontent.com/79959904/117754174-6a8fce00-b24c-11eb-84c5-1c4c8b1d22d8.png)

For more detailed log, please refer to http://sof-ci.sh.intel.com/#/result/planresultdetail/3874?model=TGLU_RVP_NOCODEC&testcase=check-capture-50rounds

**Comment by slawblauciak** [comment]
Can you please check if https://github.com/thesofproject/sof/pull/4089 is effective against this issue? Thanks

**Comment by keyonjie** [comment]
looks this is a driver regression, it pass on May 9th daily but failed on May 10th.

**Comment by keyonjie** [comment]
> This issue happens on ADLP_RVP_NOCODEC in May10's daily,plz refer to
> http://sof-ci.sh.intel.com/#/result/planresultdetail/3868?model=ADLP_RVP_NOCODEC&testcase=check-capture-3rounds
> will check whether #4089 works ASAP

it happens on ADLP_RVP_NOCODEC also, not multi-core related? @plbossart FYI.

**Comment by XiaoyunWu6666** [comment]
#4089 is effective against this issue so far

**Comment by lgirdwood** [comment]
> looks this is a driver regression, it pass on May 9th daily but failed on May 10th.

IPC timeouts are FW crashes.

**Comment by XiaoyunWu6666** [comment]
appear on **ADLP_RVP_NOCODEC** too
http://sof-ci.sh.intel.com/#/result/planresultdetail/3910?model=ADLP_RVP_NOCODEC&testcase=multiple-pipeline-capture

**Comment by XiaoyunWu6666** [comment]
appear on **TGLH_0A5E_SDW** too
http://sof-ci.sh.intel.com/#/result/planresultdetail/3910?model=TGLH_0A5E_SDW&testcase=multiple-pipeline-capture-50

**Comment by keyonjie** [comment]
> > looks this is a driver regression, it pass on May 9th daily but failed on May 10th.
> 
> IPC timeouts are FW crashes.

Yes, maybe FW change on 10th lead to this?
Anyway, the PR #4089 will fix it.

**Comment by lgirdwood** [comment]
@XiaoyunWu6666 is this now fixed with recent kernel updates and on stable-v1.8 branch ?

**Comment by XiaoyunWu6666** [comment]
> @XiaoyunWu6666 is this now fixed with recent kernel updates and on stable-v1.8 branch ?

Yes , it is
