### ISSUE TITLE
[BUG]Tplg load failed on ADL-P Chrome RVP (ADLP_RVP_SDW) as coreboot doesn't enable all 4 HDMI pipelines

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/sof#4185]
**Describe the bug**
TPLG load failed on Chrome ADLP_RVP_SDW ,there a mismatch between chrome hardware and TPLG file for ADLP_RVP_SDW [sof-adl-rt711.tplg]

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: 93d91f00
SOF Branch: main
SOF Commit: d337c0a9bab0
TPLG= sof-adl-rt711.tplg
Device:ADLP_RVP_SDW

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/79959904/118094393-41646e80-b401-11eb-8016-1faf7bfc521e.png)

**Comment by XiaoyunWu6666** [comment]
This is a known blocker 
#4041 is the related pr

**Comment by libinyang** [comment]
This is a known issue. We have discussion in https://github.com/thesofproject/sof/pull/4041#discussion_r621949355
We can wait for coreboot to fix it.

**Comment by lgirdwood** [comment]
@libinyang @XiaoyunWu6666 if this is duplicate then please mark as duplicate

**Comment by libinyang** [comment]
> @libinyang @XiaoyunWu6666 if this is duplicate then please mark as duplicate

@lgirdwood This is not a duplicated issue, but a known issue.

**Comment by kv2019i** [comment]
Thanks @libinyang ... I also didn't notice this in the tplg review. This is a bit unfortunate -- if we have some coreboot versions that enable it and some that do not (without passing the info in any runtime discoverable interface), that's going to be a mess. So let's try to get the coreboot changed asap.

**Comment by kv2019i** [comment]
And another PR to address the incorrect DMI info on some of the CI machines: https://github.com/thesofproject/linux/pull/2935

**Comment by XiaoyunWu6666** [comment]
hi @libinyang @kv2019i  should this issue be closed?

**Comment by kv2019i** [comment]
Ack @XiaoyunWu6666 , let's close this.
