### ISSUE TITLE
[FEATURE] Expand selector capabilites

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof#4242]
**Is your feature request related to a problem? Please describe.**
Selector is limited to selecting single channels from 2 or 4 channels, lets make this more generic.

**Describe the solution you'd like**
 CRAS has a useful format for passing channel mappings where, in a byte array, the index is the output channel and and value is the input channel. So when channel 2 and 3 are active (due to PDM1 being wired up, instead of PDM0)  we can pass `2 3 -1 -1` on a 4 channel stream which becomes 2 channel stream.

**Describe alternatives you've considered**
We just need something better

**Additional context**
#4228 this bug is just for external tracking purposes.

**Comment by juimonen** [comment]
demux component? should be able to pick channel combinations...

**Comment by cujomalainey** [comment]
@juimonen interesting, looks like mux or demux should solve the channel mapping problem, thanks for pointing this out, then we can use selector to reduce from 4 to 2 channels @bzhg FYI

**Comment by sathya-nujella** [comment]
Adding @yongzhi1

**Comment by keyonjie** [comment]
Usually we use demux for 1 input source (M channels) to 2 output sinks (N1, N2 channels, N1, N2 <= M) and mux for 2 input sources to 1 output sink. @lgirdwood please help to comment on this.

And for the channel selector (Authored by @lbetlej), it is used for 1 input source to 1 output sink, to expand the feature described here by @cujomalainey , we can add an channel map array as below, and implement the corresponding channel picking function in the selector_copy() function.
```c
struct sof_sel_config {
	/* selector supports 1 input and 1 output */
	uint32_t in_channels_count;	/**< accepted values 0, 2 or 4 */
	uint32_t out_channels_count;	/**< accepted values 0, 1, 2 or 4 */
	/* note: 0 for in_channels_count or out_channels_count means that
	 * these are variable values and will be fetched from pcm params;
	 * if 2 or 4 output channels selected the component works in
	 * a passthrough mode
	 */
	uint32_t sel_channel;	/**< 0..3 */
+       uint32_t out_src_map[MAX_CHAN]; /* index is the output channel index, value is the input channel index (-1 means no output for the channel) */
};
```

**Comment by cujomalainey** [comment]
@keyonjie yes, the channel remapping seems a bit weird to me to be in mux and not selector, but i might be missing a use case.

**Comment by juimonen** [comment]
Originally the mux/demux was a very general "routing matrix", so it can do 1:N and N:1 input/output stream mappings. It was actually also able to mix the channels but that feature was removed as taking too much cpu (again not my choice, I personally would have just kept it as general as possible, but that's another story).

As I understand you should be able to use the mux/demux with 1:1 input/output mapping, only thing it can't do is mix.

But yeah should be tested, I can help to configure the beast if needed. Currently the matrix should be "visible" in m4 so no need for binary blob generation with some external tool. Also mux/demux should complain if you try to mix (i.e. miss-configure the matrix).

https://thesofproject.github.io/latest/algos/demux/demux.html

**Comment by cujomalainey** [comment]
@juimonen thanks for the heads up, we will likely do blob generation anyways since we need to use the same topology across multiple boards which may be using any number of configurations with regards to PDM wiring

**Comment by cujomalainey** [comment]
@sathya-nujella @yongzhi1 Do we have any updates on the test with the Mux?

**Comment by cujomalainey** [comment]
+More Google folk, if you guys have time, it would be great to follow up on this and revert our hack in the topology section and use a mux instead

**Comment by juimonen** [comment]
@cujomalainey ack, let me check with @keyonjie what we can do...

**Comment by lgirdwood** [comment]
Ping @afq984 @bzhg @poloo5582 ?
Will push to v2.1

**Comment by cujomalainey** [comment]
I think this is defunct, it seems that MUX/DEMUX can handle channel reduction/copying/dropping, so I don't think we even really need the selector anymore

**Comment by lgirdwood** [comment]
ok, lets close - we can always reopen if needed. Thanks.
