### ISSUE TITLE
DSP panic after booted when using xcc-built firmware

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/sof#427]
Summary:
When I use xcc to build firmware(sof-apl.ri), DSP panic will occur after booted. But gcc has no such problem.

[    5.773771] sof-audio sof-audio: error : DSP panic!
[    5.773779] sof-audio sof-audio: panic: dsp_oops_offset 788480 offset 788480
[    5.773783] sof-audio sof-audio: status: fw entered - code 00000005
[    5.773803] sof-audio sof-audio: error: runtime exception
[    5.773806] sof-audio sof-audio: error: trace point 00004000
[    5.773808] sof-audio sof-audio: error: DSP Firmware Oops
[    5.773811] sof-audio sof-audio: error: Exception Cause: AllocaCause, MOVSP instruction, if caller’s registers are not in the register file
[    5.773814] sof-audio sof-audio: EXCCAUSE 0x00000005 EXCVADDR 0x00000000 PS       0x00060025 SAR     0x0000001d
[    5.773817] sof-audio sof-audio: EPC1     0xbe01311e EPC2     0xbe02570c EPC3     0xbe0139a8 EPC4    0x00000000
[    5.773820] sof-audio sof-audio: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[    5.773822] sof-audio sof-audio: EPS2     0x00060720 EPS3     0x00060722 EPS4     0x00000000 EPS5    0x00000000
[    5.773825] sof-audio sof-audio: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x000101d0 INTERRU 0x00000222

Test env:
sof master: debe638c97b462fc45ff2a93cd6efcc00145f746
sof tool: 60c3937
kernel: sof-dev 51ebd5d

Log:
[dmesg-xcc.log](https://github.com/thesofproject/sof/files/2422326/dmesg-xcc.log)
rmbox is empty and rmbox -t is full of garbage.

**Comment by ZhendanYang** [comment]
This issue only happen on nocodec up2, but up2+hifiberry has no such issue.

**Comment by mengdonglin** [comment]
@ZhendanYang Could you provide logger info?

**Comment by ZhendanYang** [comment]
This issue can't reproduce with latest code base.
Test env:
sof master: a97cd4f0832c5faf39737c2544a5539c77c250a4
sof tool: 918e401
kernel sof-dev: 32f5efe
