### ISSUE TITLE
[BUG][TGL-13] Expression check failed, TestPtpSimpleStreamOperations

### ISSUE THREAD

**Issue by wszypelt** [thesofproject/sof#4314]
**Describe the bug**

Wave file without glitch

Bug was found in:
02_12_TestPtpSimpleStreamOperations8000Hz16b16b1ch
02_12_TestPtpSimpleStreamOperations8000Hz24b32b4ch
02_12_TestPtpSimpleStreamOperations8000Hz32b32b8ch
02_12_TestPtpSimpleStreamOperations16000Hz16b16b1ch
02_12_TestPtpSimpleStreamOperations16000Hz32b32b4ch
02_12_TestPtpSimpleStreamOperations24000Hz16b16b1ch
02_12_TestPtpSimpleStreamOperations24000Hz24b32b4ch
02_12_TestPtpSimpleStreamOperations24000Hz32b32b8ch
02_12_TestPtpSimpleStreamOperations48000Hz16b16b8ch
02_12_TestPtpSimpleStreamOperations48000Hz24b32b4ch
02_12_TestPtpSimpleStreamOperations48000Hz32b32b2ch

the content of the error:
Expression check failed Expected: 1.01 Got: 3.01 & 5.03 & 7.03

**Topology**
```
                pipe_plb
                +--------------------+
+----------+    | +------+   +-----+ |   +----+
| Host plb |----->|Buffer|-->| Dai |---->|SSPx|
+----------+    | +------+   +-----+ |   +----+
                +--------------------+    |  |
                pipe_cap                  |  |
                +--------------------+    |  |
+----------+    | +------+   +-----+ |   +----+
| Host cap |<-----|Buffer|<--| Dai |---->|SSPx|
+----------+    | +------+   +-----+ |   +----+
                +--------------------+

```
Description:
Simultaneous playback and capture on external loopback (same SSP).
While pipelines are working pause and resume operation are done on playback stream.

**To Reproduce**
Run test with diagnostic driver 02_12_TestPtpSimpleStreamOperations8000Hz16b16b1ch and other

**Reproduction Rate**
~90%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF BRANCH: main HASH: 9a35f65111b9f6603d8ed26a6178511e6cebaa75
2) Name of the platform(s) on which the bug is observed.
    * Platform: TGL RVP - [TGL-13]
3) Test environment:
BRANCH: master HASH: a71a6d87b75a0f64e2924fae30a31ed8a0208014

**Screenshots or console output**

![image](https://user-images.githubusercontent.com/82375849/121190721-9d3cde80-c86b-11eb-8c87-4ede4227c3ee.png)

![image](https://user-images.githubusercontent.com/82375849/121190043-f35d5200-c86a-11eb-9573-7a1315f2a319.png)

![image](https://user-images.githubusercontent.com/82375849/121190097-ffe1aa80-c86a-11eb-9964-44efa776997d.png)

**Logs**
[2021_06_02_15_53_33.zip](https://github.com/thesofproject/sof/files/6616715/2021_06_02_15_53_33.zip)

**Comment by lgirdwood** [comment]
@slawblauciak @wszypelt this looks like a slim driver or CI script issue if no glitches are observed ?

**Comment by antonirx** [comment]
Reproduced on TGL-SSP
5594ad3512830feaa478677718036ffabf51a454

**Comment by antonirx** [comment]
Reproduced on TGL:
c807d6844b535ff4ad90ac6429a2fef46f398cb4

**Comment by wszypelt** [comment]
Test issue
