### ISSUE TITLE
[BUG][TGL] glitch in test 22_00_TestDsmSsp48000Hz32b32b2ch

### ISSUE THREAD

**Issue by wszypelt** [thesofproject/sof#4319]
**Describe the bug**
New glitch was found in test 22_00_TestDsmSsp48000Hz32b32b2ch At the beginning wave file

**Topology**
```
    +----------------------------------------------+
    | +------+   +---+   +- -+   +---+   +-------+ |
    | | Host |-->|Buf|-->|Dsm|-->|Buf|-->|SSP Dai|-------+
    | +------+   +---+   +---+   +---+   +-------+ |     |
    +------------------+   ^   +-------------------+     |
                       |   |   |                         |
                       | +---+ |                         |
                       | |Buf| |                         |
                       | +---+ |                         |
                       +---^---+                         |
    +----------------------|------------------------+    |
    | +------+   +---+   +-|--+   +---+   +-------+ |    |
    | | Host |<--|Buf|<--|Dmux|<--|Buf|<--|SSP Dai|<-----+
    | +------+   +---+   +----+   +---+   +-------+ |
    +-----------------------------------------------+
```
Description:
Simultaneous playback and capture on external loopback (same SSP) with signal verification.
Playback pipeline contains Dynamic Speaker Management (DSM) component.

**To Reproduce**
Run test with Diagnostic driver 22_00_TestDsmSsp48000Hz32b32b2ch
With options --playback-iterations=75

**Reproduction Rate**
Sporadic 1/75

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF BRANCH: main HASH: d6e29ced243079e69beb055730a33ad103b377d7
2) Name of the platform(s) on which the bug is observed.
    * Platform: TGL RVP
3) Test environment:
BRANCH: master HASH: a71a6d87b75a0f64e2924fae30a31ed8a0208014

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/82375849/121327062-66ba9e80-c913-11eb-8f55-6d39a32fdb21.png)

**Logs**

[2021_06_08_23_25_52.zip](https://github.com/thesofproject/sof/files/6622581/2021_06_08_23_25_52.zip)

**Comment by antonirx** [comment]
on TGL issue does not occur
Tested FW hash: 4943aaa
