### ISSUE TITLE
[BUG]sof-logger doesn't work on APL_UP2_NOCODEC_ZEPHYR

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/sof#4413]
**Describe the bug**
sof-logger doesn't work on APL_UP2_NOCODEC_ZEPHYR , showing 'error: Error while reading /etc/sof/sof-apl.ldc'

**To Reproduce**
 sudo sof-logger -l /etc/sof/sof-apl.ldc

**Comment by marc-hb** [comment]
Close this once https://github.com/thesofproject/sof-test/pull/724 is merged and the test is SKIPped

For the longer term and the test to PASS there is issue is #4420

**Comment by marc-hb** [comment]
Test is skipped now
