### ISSUE TITLE
[BUG] glitch in 17_00_TestMultiCoreSameKernelSsp16000Hz32b32b4ch test

### ISSUE THREAD

**Issue by wszypelt** [thesofproject/sof#4429]
**Describe the bug**
In test  17_00_TestMultiCoreSameKernelSsp16000Hz32b32b4ch glitch was found.

**Topology**
```
Topology:
                    pipe_plb core 1
                    +--------------------+
    +----------+    | +------+   +-----+ |   +----+
    | Host plb |----->|Buffer|-->| Dai |---->|SSP0|
    +----------+    | +------+   +-----+ |   +----+
                    +--------------------+    |  |
                                              |  |
                    pipe_cap core 1           |  |
                    +--------------------+    |  |
    +----------+    | +------+   +-----+ |   +----+
    | Host cap |<-----|Buffer|<--| Dai |---->|SSP0|
    +----------+    | +------+   +-----+ |   +----+
                    +--------------------+

```
playback and capture pipelines both on same core (different than default 0) 

**To Reproduce**
Run test with Diagnostic driver 17_00_TestMultiCoreSameKernelSsp16000Hz32b32b4ch
With options --playback-iterations=75

**Reproduction Rate**
Sporadic. 1/75

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF: BRANCH: main HASH: bccecb1a8eed84a0737fdf2878204adfb6cf845d

2) Name of the platform(s) on which the bug is observed.
    * Platform: ICL RVP
3) Test environment:
BRANCH: master HASH: e8fa676f694a584ea7c0cce74e6ed24a7801d749

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/82375849/123796511-7c552f80-d8e5-11eb-9894-449e83e2f02b.png)

[2021_06_29_01_38_22.zip](https://github.com/thesofproject/sof/files/6733358/2021_06_29_01_38_22.zip)

**Comment by antonirx** [comment]
unsupported platform
on TGL issue does not occur
Tested FW hash: 4943aaa
