### ISSUE TITLE
[BUG] Glitches on ASRC component

### ISSUE THREAD

**Issue by kkarask** [thesofproject/sof#4437]
**Describe the bug**
Glitches was found in test 19_00_TestAsrcPlayback8000Hz32b32b2ch
Playback pipeline contains ASRC. 

**Topology**
```
  +---------------------------------+
    +------+    | +---+  +----+  +---+  +-------+ |
    | Host |----->|Buf|->|Asrc|->|Buf|->|SSP Dai|---+
    +------+    | +---+  +----+  +---+  +-------+ | |
                +---------------------------------+ |
                                                    |
                +------------------+                |
    +------+    | +---+  +-------+ |                |
    | Host |<-----|Buf|<-|SSP Dai|<-----------------+
    +------+    | +---+  +-------+ |
                +------------------+
```

**To Reproduce**
Run test 19_00_TestAsrcPlayback8000Hz32b32b2ch with Diagnostic driver

**Reproduction Rate**
Sporadic.

**Environment**
1) Firmware branch name and commit
    * SOF: Branch: main, Hash: eb7add5135fda83c779b936b76e57f54fd293a8d

2) Name of the platform(s) on which the bug is observed.
    * Platform: TGL

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/82518823/123922719-9a27a080-d988-11eb-9825-4bb5c9e1c31d.png)

![image](https://user-images.githubusercontent.com/82518823/123922848-bb888c80-d988-11eb-8b67-1efd02ec6812.png)

[TGL_19_00_TestAsrcPlayback8000Hz32b32b2ch.zip](https://github.com/thesofproject/sof/files/6740425/TGL_19_00_TestAsrcPlayback8000Hz32b32b2ch.zip)

**Comment by kkarask** [comment]
Glitch was found in test 19_00_TestAsrcPlayback8000Hz32b32b2ch on ICL RVP platform too.
Hash:  1165dae2b586bfac8ba2140f52a4e46fa32201a9

![image](https://user-images.githubusercontent.com/82518823/150327876-b9679b0e-f7dc-4276-974b-c64ef383be60.png)

Logs:
[ICL_19_00_TestAsrcPlayback8000Hz32b32b2ch.zip](https://github.com/thesofproject/sof/files/7904601/ICL_19_00_TestAsrcPlayback8000Hz32b32b2ch.zip)

**Comment by lgirdwood** [comment]
@singalsu any comments ? Any idea if we have enough MCPS for each config ?

**Comment by antonirx** [comment]
unsupported platform
on TGL issue does not occur
Tested FW hash: 4943aaa
