### ISSUE TITLE
[BUG] Reset Handler Cleanup

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof#4488]
Follow up from [here](https://github.com/thesofproject/sof/pull/3789/files#diff-c3b15aa3cf6ee70bf6aab304248b7e223c4876a91b558b9ad8cde290a6604c52R326)

Now that we have well defined behaviour for the reset handler we need to followup on cleaning up state in reset. Initial scan shows some components still in violation

- [ ] Codec adapter has number of variables set in prepare and params step that are not zeroed out @ranj063 
- [x] Crossover doesn't reset stream data or processing function pointer - @afq984 
- [x] Dcblock similar to above for crossover  - @afq984 
- [x] DRC `cd->source_format` is not cleaned up - @johnylin76 
- [x] EQ FIR `source_format` isn't cleaned up but doesn't appear to be used? - @singalsu 
- [x]  EQ IIR same var again, could be a local var? Sink format as well - @singalsu 
- [x] IGO fails to clean up all `cd` data stored in `params` step - @fuyuntsuo 
- [x]  Multiband DRC same as DRC  - @johnylin76 
- [x] Mux processing funcs not cleared - @akloniex 
- [x] Selector no state cleaned up - @eddy1021 
- [x] Smart Amp no state cleaned up - @ryans-lee 
- [x] SRC same as EQ IIR - @singalsu 
- [x] TDFB in/out buffer clear only appears to happen when new config appears on prepare, not on pipeline reset? - @singalsu 
- [x] Volume does not clear out old state set in prepare for processing - @singalsu 
- [x]  Host appears to store a number of state variables in hd->config that are never cleared and many not used - @jsarha  
- [x] KPB number of variables set on prepare that are not cleared in reset  - @andrula-song  
- [x] mixer fails to clear mixer function state also has a magic number to stop pipeline walk? - @kv2019i  

Sorry for the large blast radius for messages  just hoping to get some coherency for all components so we can stop propagating errors to new members joining the project through copy paste issues :)

**Comment by singalsu** [comment]
Thanks @cujomalainey for nice summary! I'm targeting make a fix PR before my vacation next week for components assigned to me.

**Comment by lgirdwood** [comment]
@cujomalainey @singalsu I've added check boxes to allow us to follow whats done. @singalsu please update.

**Comment by johnylin76** [comment]
Updated check boxes for drc and multiband_drc since #4546 is merged.

**Comment by cujomalainey** [comment]
Need to check RTNR to see if it needs fixing

**Comment by lgirdwood** [comment]
@kv2019i some mixer, @andrula-song some processing components here.

**Comment by cujomalainey** [comment]
Also AEC needs this

**Comment by lgirdwood** [comment]
@eddy1021 @ranj063 @singalsu fyi - updates on the list.

**Comment by lgirdwood** [comment]
@jsarha fyi - one for you too.

**Comment by jsarha** [comment]
> @jsarha fyi - one for you too.

Gathering context ATM, to get on track what is needed and where...

**Comment by cujomalainey** [comment]
@eddy1021 leave the codec / module adapter to @ranj063 as she is doing a lot of work there right now.

**Comment by jsarha** [comment]
> Host appears to store a number of state variables in hd->config that are never cleared and many not used - @jsarha 

Looks to me that somebody beat me to it:
https://github.com/thesofproject/sof/commit/1c136b1d2f6a7f55bd69c6580ffc979a9880f447

@lgirdwood was there something more to this, or should I just tap my ✅ ?

**Comment by eddy1021** [comment]
Mark `dcblock`, `selector`, `smart amp`, and `kpb` as done.
`crossover` is blocked by pulls #5729

**Comment by lgirdwood** [comment]
> Mark `dcblock`, `selector`, `smart amp`, and `kpb` as done. `crossover` is blocked by pulls #5729

#5729 merged.
@ranj063 any comment on the codec adapter part (in the BUG description) ?
