### ISSUE TITLE
[BUG] Dell XPS 17 9710 No Audio

### ISSUE THREAD

**Issue by joeracer321** [thesofproject/sof#4535]
Several users, myself included do not have functioning audio in Ubuntu.  This bug was originally reported to the Ubuntu board, but after their review, they suggested reporting the bug here.  This issue appears to be common to several distributions and versions.  The original thread can be found here: <<https://bugs.launchpad.net/ubuntu/+source/alsa-driver/+bug/1935850>>. I've attached the text from thread, though I am not the originator of this data.  I am posting on their behalf as it appears the author may not have seen the recommendation to report the bug elsewhere once it had been accepted.

quote: 
_Tried versions 1.6, 1.7 and 1.8. Results from dmesg for each are below.

1.6
-------------------------------------------------------------------------
[ 2.813265] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[ 2.814293] snd_hda_intel 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[ 3.043586] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
[ 3.043747] snd_hda_intel 0000:01:00.1: Disabling MSI
[ 3.043758] snd_hda_intel 0000:01:00.1: Handle vga_switcheroo audio client
[ 3.085850] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[ 3.086244] sof-audio-pci 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[ 3.086263] sof-audio-pci 0000:00:1f.3: enabling device (0000 -> 0002)
[ 3.086518] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[ 4.419572] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[ 4.506416] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[ 4.526665] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 4
[ 4.623692] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:6:1-53680
[ 4.623701] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:17:0 Kernel ABI 3:18:0
[ 4.635902] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:17:0 Kernel ABI 3:18:0
[ 4.655486] sof-audio-pci 0000:00:1f.3: ASoC: physical link SDW3-Capture (id 4) not exist
[ 4.655496] sof-audio-pci 0000:00:1f.3: ASoC: topology: could not load header: -22
[ 4.655760] sof-audio-pci 0000:00:1f.3: error: tplg component load failed -22
[ 4.655767] sof-audio-pci 0000:00:1f.3: error: failed to load DSP topology -22
[ 4.655770] sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[ 4.655773] sof-audio-pci 0000:00:1f.3: ASoC: failed to probe component -22
[ 4.655815] sof_sdw sof_sdw: ASoC: failed to instantiate card -22
[ 8.695612] sof_sdw sof_sdw: snd_soc_register_card failed -22
[ 8.695632] sof_sdw: probe of sof_sdw failed with error -22

1.7
-------------------------------------------------------------------------
[ 3.062326] sof-audio-pci 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[ 3.062905] sof-audio-pci 0000:00:1f.3: enabling device (0000 -> 0002)
[ 3.064154] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[ 4.236932] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[ 4.460375] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[ 4.486526] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 4
[ 4.487058] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:7:0-47d07
[ 4.487062] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
[ 4.487065] sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
[ 4.487070] sof-audio-pci 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[ 4.595907] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:7:0-47d07
[ 4.595914] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
[ 4.595918] sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
[ 4.610245] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:17:0 Kernel ABI 3:18:0
[ 4.629440] sof-audio-pci 0000:00:1f.3: ASoC: physical link SDW3-Capture (id 4) not exist
[ 4.629448] sof-audio-pci 0000:00:1f.3: ASoC: topology: could not load header: -22
[ 4.629706] sof-audio-pci 0000:00:1f.3: error: tplg component load failed -22
[ 4.629712] sof-audio-pci 0000:00:1f.3: error: failed to load DSP topology -22
[ 4.629713] sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[ 4.629715] sof-audio-pci 0000:00:1f.3: ASoC: failed to probe component -22
[ 4.629745] sof_sdw sof_sdw: ASoC: failed to instantiate card -22
[ 4.634785] sof_sdw sof_sdw: snd_soc_register_card failed -2

1.8
-------------------------------------------------------------------------
[ 2.791146] snd_hda_intel 0000:01:00.1: enabling device (0000 -> 0002)
[ 2.792978] snd_hda_intel 0000:01:00.1: Disabling MSI
[ 2.792997] snd_hda_intel 0000:01:00.1: Handle vga_switcheroo audio client
[ 3.039625] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[ 3.040157] sof-audio-pci 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[ 3.040172] sof-audio-pci 0000:00:1f.3: enabling device (0000 -> 0002)
[ 3.040381] sof-audio-pci 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[ 4.130786] sof-audio-pci 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[ 4.390775] sof-audio-pci 0000:00:1f.3: use msi interrupt mode
[ 4.432864] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 4
[ 4.433568] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:8:0-9e7a8
[ 4.433573] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
[ 4.433576] sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
[ 4.433582] sof-audio-pci 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[ 4.530828] sof-audio-pci 0000:00:1f.3: Firmware info: version 1:8:0-9e7a8
[ 4.530835] sof-audio-pci 0000:00:1f.3: Firmware: ABI 3:18:1 Kernel ABI 3:18:0
[ 4.530838] sof-audio-pci 0000:00:1f.3: warn: FW ABI is more recent than kernel
[ 4.553491] sof-audio-pci 0000:00:1f.3: Topology: ABI 3:17:0 Kernel ABI 3:18:0
[ 4.572123] sof-audio-pci 0000:00:1f.3: ASoC: physical link SDW3-Capture (id 4) not exist
[ 4.572132] sof-audio-pci 0000:00:1f.3: ASoC: topology: could not load header: -22
[ 4.573751] sof-audio-pci 0000:00:1f.3: error: tplg component load failed -22
[ 4.573765] sof-audio-pci 0000:00:1f.3: error: failed to load DSP topology -22
[ 4.573767] sof-audio-pci 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[ 4.573771] sof-audio-pci 0000:00:1f.3: ASoC: failed to probe component -22
[ 4.573810] sof_sdw sof_sdw: ASoC: failed to instantiate card -22
[ 4.575005] sof_sdw sof_sdw: snd_soc_register_card failed -22
[ 4.575018] sof_sdw: probe of sof_sdw failed with error -22_

**Comment by plbossart** [comment]
Duplicate of https://github.com/thesofproject/linux/issues/3057
