### ISSUE TITLE
[BUG] Glitch in test 20_01_TestEqIirSimple48000Hz32b32b4ch

### ISSUE THREAD

**Issue by wszypelt** [thesofproject/sof#4565]
**Describe the bug**
Test 20_01_TestEqIirSimple48000Hz32b32b4ch
Glitch in the whole wav file

**Topology**
```
Topology:
+---------------------------------------------------+
| +------+   +-----+   +------+   +-----+   +-----+ |   +----+
| | Host |-->| Buf |-->|IIR EQ|-->| Buf |-->| Dai |---->|SSPx|
| +------+   +-----+   +------+   +-----+   +-----+ |   +----+
+---------------------------------------------------+    |  |
                                                         |  |
                                                         |  |
+-------------------------------+                        |  |
| +------+   +-----+    +-----+ |                       +----+
| | Host |<--| Buf |<---| Dai |<------------------------|SSPx|
| +------+   +-----+    +-----+ |                       +----+
+-------------------------------+

```
Test is performing simultaneous playback and capture on external SSP interface with recorded signal quality verification.
Playback pipeline contains IIR EQ component with basic configuration.

**To Reproduce**
Run test with Diagnostic driver 20_01_TestEqIirSimple48000Hz32b32b4ch
With options --playback-iterations=75

**Reproduction Rate**
Sporadic. 1/75

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF: BRANCH: main HASH: 9648fb65a5b8b86707e0a160efa992f3f3c97f59

2) Name of the platform(s) on which the bug is observed.
    * Platform: ICL RVP
    
3) Test environment:
BRANCH: master HASH: 52309bc5c72c600bf7cfd86e75ab45ecbf075feb

**Screenshots or console output**
![Capture](https://user-images.githubusercontent.com/82375849/127305613-32899892-15be-49cd-a0a8-754fc492e0bb.PNG)

**Logs**
[2021_07_27_05_35_52.zip](https://github.com/thesofproject/sof/files/6892186/2021_07_27_05_35_52.zip)

**Comment by antonirx** [comment]
unsupported platform
on TGL issue does not occur
Tested FW hash: 4943aaa
