### ISSUE TITLE
[BUG] FW boot failure with SOF main when trace mailbox CONFIG_TRACEM is enabled

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof#4699]
**Describe the bug**
FW fails to boot when built with trace mailbox enabled.

What have you tried to diagnose or workaround this issue?
Bisection points to https://github.com/thesofproject/sof/commit/7df367451d0fa638b530c1c92f02d645845dbe53
Reverting the commit fixes the problem.

**To Reproduce**
Build FW with Trace->Trace Mailbox enabled in config

**Reproduction Rate**
100%

**Expected behavior**
No issues during FW boot.

**Impact**
show-stopper

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: https://github.com/thesofproject/linux/commit/a2f06997cc7fdb02665f7d0b9bd6221849911437
    * SOF: https://github.com/thesofproject/sof/commit/6b650bd95fe003cc8f13715aa53feb293e629b70

    
Error log:
[    8.414944] sof-audio-pci-intel-tgl 0000:00:1f.3: error: firmware boot failure
[    8.414988] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[    8.415028] sof-audio-pci-intel-tgl 0000:00:1f.3: status: fw entered - code 00000005
[    8.415098] sof-audio-pci-intel-tgl 0000:00:1f.3: error: extended rom status:  0x5 0x0 0x4000 0x0 0x0 0x0 0x256051f 0x0
[    8.415138] sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
[    8.415169] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to boot DSP firmware -5

**Comment by ranj063** [comment]
@keyonjie FYI

**Comment by keyonjie** [comment]
Thanks for reporting @ranj063 

After debugging, just root caused this to be deadlock in the trace->lock, will submit a fix for it soon.

Good finding here, maybe we should add Not-default kconfig validation coverage to our CI also. @marc-hb @keqiaozhang

**Comment by keyonjie** [comment]
@ranj063 the PR here: https://github.com/thesofproject/sof/pull/4700

**Comment by marc-hb** [comment]
> Good finding here, maybe we should add Not-default kconfig validation coverage to our CI also. @marc-hb @keqiaozhang

CONFIG_TRACEM is likely to have a severe performance impact.

**Comment by marc-hb** [comment]
BTW I rely on CONFIG_TRACEM for my transition to Zephyr "strategy", see (now reverted) commit 0def9056300a
