### ISSUE TITLE
[FEATURE] Reject PCM_PARAMS IPC when in ACTIVE or PAUSED state

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof#4796]
**Is your feature request related to a problem? Please describe.**
Certain CI tests erroneously submit PCM_PARAMS IPC when the pipeline is in ACTIVE or PAUSED state, the firmware accepts and tries to process it.

**Describe the solution you'd like**
Such IPCs should return an error to the host.

**Comment by plbossart** [comment]
isn't it a bug rather?

**Comment by lyakh** [comment]
> isn't it a bug rather?

@plbossart I have been creating too many bugs recently, so I decided to make this a feature :-) It doesn't seem to create any problems at the moment.

**Comment by plbossart** [comment]
Man, I found so many bugs lately, if I started called them features there would be several pages of enhancements!

**Comment by lgirdwood** [comment]
@lyakh thinking the easiest approach here is to ignore the request for compatibility with Windows. i.e. just return success and report this as a warning in the logs.

**Comment by lyakh** [comment]
fixed by #4869
