### ISSUE TITLE
[BUG] Noise before a valid signal in 07_04_TestKdDmic16000Hz16b16b2ch

### ISSUE THREAD

**Issue by wszypelt** [thesofproject/sof#4807]
**Describe the bug**
In test  07_04_TestKdDmic16000Hz16b16b2ch noise before a valid signal was found.

**Topology**
```
        +----------+   +------------------+
        |    OS    |-->|   AUDIO DEVICE   |-----------------------+
        +----------+   +------------------+                       |
                                                                  |
                   +-------------------------+                    |
        +--------+ | +---+   +-----+   +---+ |                    |
        |KD Dummy|<->|Buf|<->|ChSel|<->|Buf|<->+                  |
        +--------+ | +---+   +-----+   +---+ | |  pipe_cap        |
                   +-------------------------+ |                  |
                                               |                  |
                             +-----------------+                  |
        +--------------------|----------------------------------+ |
        |+----+  +------+  +---+  +---+  +---+  +---+  +------+ | |
        ||Host|<-|Buffer|<-|Kpb|<-|Buf|<-|Vol|<-|Buf|<-| DMIC |---+
        |+----+  +------+  +---+  +---+  +---+  +---+  +------+ |
        +-------------------------------------------------------+
```
Description:
Test keyword detection feature with full topology, using to DMIC injector to get signal.

**To Reproduce**
Run test with Diagnostic driver 07_04_TestKdDmic16000Hz16b16b2ch.

**Reproduction Rate**
Sporadic. 1/150

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF: BRANCH: main HASH: 509eef9c96b81006291721a59733e61e96d4ff58

2) Name of the platform(s) on which the bug is observed.
    * Platform: WHL RVP
3) Test environment:
BRANCH: master HASH: 509eef9c96b81006291721a59733e61e96d4ff58

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/82375849/134869153-12a5b18b-b8c7-4619-b347-00baaa980b09.png)

**Logs**
[07_04_TestKdDmic16000Hz16b16b2ch.zip](https://github.com/thesofproject/sof/files/7234503/07_04_TestKdDmic16000Hz16b16b2ch.zip)

**Comment by singalsu** [comment]
There's some Windows UI sound (melody with bells) in the beginning. Assign back to you, it's a lab setup issue.
