### ISSUE TITLE
[FEATURE] Integrate LPS secondary core fixes on main

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#4834]
**Is your feature request related to a problem? Please describe.**
Integrate the LPS secondary core fixes on main. This is just to track.

https://github.com/bkokoszx/sof/commits/tgl-013-drop-stable-secondary_core_restore

**Comment by lgirdwood** [comment]
@andyross fyi - need to make sure Zephyr kernel has a similar flow onn secondary core power done and power up wrt to cache and kernel objects.

**Comment by bkokoszx** [comment]
I've just created a PR #4839

**Comment by kv2019i** [comment]
Given #4839 is merged, this can be closed @bkokoszx  ?

**Comment by bkokoszx** [comment]
@kv2019i 
Yes, I think we can close it.
