### ISSUE TITLE
[BUG] Whole capture with glitch where depth conversion is done on DAI component

### ISSUE THREAD

**Issue by kkarask** [thesofproject/sof#4863]
**Describe the bug**
The whole file with glitch was found in tests where playback pipeline is setup that bit depth conversion is done on DAI component.  Simultaneous playback and capture on external loopback (same SSP) with signal verification.

**To Reproduce**
Run tests with Diagnostic driver:
02_13_TestPtpPlaybackBitDepthConversion16000Hz24b32b1ch
02_13_TestPtpPlaybackBitDepthConversion24000Hz24b32b8ch
02_13_TestPtpPlaybackBitDepthConversion48000Hz32b32b4ch

**Topology**
```
pipe_plb
+-------------------------------+
| +------+   +------+   +-----+ |  +-----+
| | Host |-->|Buffer|-->| Dai |--->| SSP |
| +------+   +------+   +-----+ |  +-----+
+-------------------------------+    | |
                                     | |
pipe_cap                             | |
+-------------------------------+    | |
| +------+   +------+   +-----+ |  +-----+
| | Host |<--|Buffer|<--| Dai |<---| SSP |
| +------+   +------+   +-----+ |  +-----+
+-------------------------------+
```

**Reproduction Rate**
100%

**Environment**
1) Firmware branch name and commit
    * SOF: Branch: main, Hash: b039018d0adcfe347119094ac29f0fc12b671187
2) Name of the platform(s) on which the bug is observed.
    * Platform: ICL RVP, WHL RVP

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/82518823/136791837-a4c77ecc-6d59-4754-a5ad-a684ff705d3d.png)

[WHL_02_13_TestPtpPlaybackBitDepthConversion48000Hz32b32b4ch.zip](https://github.com/thesofproject/sof/files/7322426/WHL_02_13_TestPtpPlaybackBitDepthConversion48000Hz32b32b4ch.zip)

**Comment by wszypelt** [comment]
Test script issue
