### ISSUE TITLE
[BUG]No sound with RT5640 Baytrail sound card (bytcr-rt5640).

### ISSUE THREAD

**Issue by Tuxman2** [thesofproject/sof#4870]
**Describe the bug**
RT5640 Baytrail sound card is not recognized (bytcr-rt5640) and I've got no sound.

**Reproduction Rate**
all the time

**Expected behavior**
Have sound.

**Impact**
Can't use the sound card of my hardware (laptop hybrid PC).

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.14.10
    * SOF: 1.8-1
3) Name of the platform(s) on which the bug is observed.
    * Platform: Baytrail

**Screenshots or console output**
dmesg output:

[   10.448873] sof-audio-acpi-intel-byt 80860F28:00: Detected Baytrail-CR platform
[   10.464987] sof-audio-acpi-intel-byt 80860F28:00: Direct firmware load for intel/sof/sof-byt.ri failed with error -2
[   10.465010] sof-audio-acpi-intel-byt 80860F28:00: error: request firmware intel/sof/sof-byt.ri failed err: -2
[   10.465016] sof-audio-acpi-intel-byt 80860F28:00: you may need to download the firmware from https://github.com/thesofproject/sof-bin/
[   10.465020] sof-audio-acpi-intel-byt 80860F28:00: error: failed to load DSP firmware -2
[   10.465090] sof-audio-acpi-intel-byt 80860F28:00: error: sof_probe_work failed err: -2

Thanks.

Note: Tested on Manjaro 21.1.5.

**Comment by plbossart** [comment]
no we didn't root-cause baytrail issues. lack of time/priorities unfortunately.

**Comment by Tuxman2** [comment]
So, if I use your workaround, could I have sound with my rt5640 Baytrail hardware ?

**Comment by Tuxman2** [comment]
Well, I defined in the /etc/modprobe.d/alsa-base.conf file, the following options: 

> options snd_sof sof_debug = 1
> options snd-intel-dspcfg dsp_driver=2

Always no sound but here is the result of dmesg command:

> [   30.180252]  Baytrail Audio Port: ASoC: no backend DAIs enabled for Baytrail Audio Port
> [   30.180265]  Baytrail Audio Port: ASoC: dpcm_fe_dai_prepare() failed (-22)
> [   30.180911]  Baytrail Audio Port: ASoC: no backend DAIs enabled for Baytrail 

If I define the dsp_driver=3, I've got the same messages as in the first post with dmesg command.
The dsp_driver=1 doesn't work.

Thanks if you know how to solve this issue.

**Comment by Tuxman2** [comment]
Thanks for your help.

Ok, I found the problem. I modified the recent ucm files with old ucm files Ihad. So, I restored the recent ucm files and I added alsa-base.conf file in /etc/modprobe.d/ with 'options snd-intel-dspcfg dsp_driver=2' in it. Now, my hardware is recognized and I have sound. ;-)

I close this topic.
