### ISSUE TITLE
[BUG] Tools fail to build on i686 and musl systems

### ISSUE THREAD

**Issue by cinerea0** [thesofproject/sof#4902]
**Describe the bug**
The tools found in the "tools" directory in this repository cannot be built on i686 or x86_64-musl systems. On i686 systems the tools fail to build because of type mismatch (My knowledge of C is minimal, but it seems like "ld" should be "zd" in convert.c.). On x86_64-musl systems the tools fail to build because a topology file can't be parsed. The full error logs for these can be found here: https://github.com/void-linux/void-packages/pull/33318.

**To Reproduce**
Attempt to build the tools on the platforms listed above.

**Reproduction Rate**
This happens every build attempt.

**Expected behavior**
I expect the tools to build correctly.

**Impact**
This prevents Void Linux from distributing the tools since they currently cannot be built from source on all of the expected architectures. Additionally, due to the way the tools used to be distributed, Void cannot provide an update to v1.9 of sof-firmware.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: N/A
    * SOF: fa8575d29cc30bf0a949f61bc84c9223e6ad4ad1
2) Name of the topology file
    * Topology: sof-cml-nocodec.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: i686 and x86_64-musl

**Screenshots or console output**
<details>
<summary>i686 error</summary>

```
[54/388] Building C object logger/CMakeFiles/sof-logger.dir/convert.c.o
FAILED: logger/CMakeFiles/sof-logger.dir/convert.c.o 
/usr/bin/cc  -I/builddir/sof-1.9/tools/../src/include -I/builddir/sof-1.9/tools/../rimage/src/include -I/builddir/sof-1.9/tools/.. -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=i686 -O2 -Wall -Werror -MD -MT logger/CMakeFiles/sof-logger.dir/convert.c.o -MF logger/CMakeFiles/sof-logger.dir/convert.c.o.d -o logger/CMakeFiles/sof-logger.dir/convert.c.o -c /builddir/sof-1.9/tools/logger/convert.c
/builddir/sof-1.9/tools/logger/convert.c: In function 'fetch_entry':
/builddir/sof-1.9/tools/logger/convert.c:746:44: error: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
  746 |     log_err("Partial read of %u bytes of %lu, reading more\n",
      |                                          ~~^
      |                                            |
      |                                            long unsigned int
      |                                          %u
  747 |      ret, size);
      |           ~~~~                              
      |           |
      |           size_t {aka unsigned int}
/builddir/sof-1.9/tools/logger/convert.c: In function 'logger_read':
/builddir/sof-1.9/tools/logger/convert.c:877:63: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'unsigned int' [-Werror=format=]
  877 |      log_err("file '%s' is unaligned with trace entry size (%ld)\n",
      |                                                             ~~^
      |                                                               |
      |                                                               long int
      |                                                             %d
  878 |       global_config->in_file, sizeof(dma_log));
      |                               ~~~~~~~~~~~~~~~                  
      |                               |
      |                               unsigned int
/builddir/sof-1.9/tools/logger/convert.c: In function 'dump_ldc_info':
/builddir/sof-1.9/tools/logger/convert.c:997:55: error: format '%ld' expects argument of type 'long int', but argument 3 has type 'ssize_t' {aka 'int'} [-Werror=format=]
  997 |  fprintf(out_fd, "Components uuid dictionary size:\t%ld bytes\n",
      |                                                     ~~^
      |                                                       |
      |                                                       long int
      |                                                     %d
  998 |   remaining);
      |   ~~~~~~~~~                                            
      |   |
      |   ssize_t {aka int}
/builddir/sof-1.9/tools/logger/convert.c:1010:26: error: format '%lX' expects argument of type 'long unsigned int', but argument 3 has type 'uintptr_t' {aka 'unsigned int'} [-Werror=format=]
 1010 |   fprintf(out_fd, "\t0x%lX  %s\n", uid_addr, name);
      |                        ~~^         ~~~~~~~~
      |                          |         |
      |                          |         uintptr_t {aka unsigned int}
      |                          long unsigned int
      |                        %X
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

</details>

<details>
<summary>x86_64-musl error</summary>

```
[5/388] Generating sof-cml-nocodec.tplg
ALSA lib parser.c:213:(tplg_load_config) failed to parse topology
Unable to load configuration: Invalid argument
FAILED: topology/topology1/sof-cml-nocodec.tplg /builddir/sof-1.9/tools/build/topology/topology1/sof-cml-nocodec.tplg 
cd /builddir/sof-1.9/tools/build/topology/topology1 && alsatplg ${VERBOSE:+-v 1} -c /builddir/sof-1.9/tools/build/topology/topology1/sof-cml-nocodec.conf -o sof-cml-nocodec.tplg
[7/388] Building C object probes/CMakeFiles/sof-probes.dir/probes_main.c.o
ninja: build stopped: subcommand failed.
```

</details>

**Comment by Johnnynator** [comment]
Openend https://github.com/alsa-project/alsa-lib/issues/187 for part of the musl issue.

>  Are you able to give this a try and submit a fix ?

Done

Regarding `{v}asprintf`, what would be considered a acceptable rename?
Sof already uses quite a few nonstandard functions, so forcing musl into a standard compliant mode will break other parts.

**Comment by lgirdwood** [comment]
> Regarding `{v}asprintf`, what would be considered a acceptable rename?
> Sof already uses quite a few nonstandard functions, so forcing musl into a standard compliant mode will break other parts.

Can you point to the places where we break musl ?

**Comment by Johnnynator** [comment]
> > Regarding `{v}asprintf`, what would be considered a acceptable rename?
> > Sof already uses quite a few nonstandard functions, so forcing musl into a standard compliant mode will break other parts.
> 
> Can you point to the places where we break musl ?

You reimplement `asprintf` and `vsprintf` here:

https://github.com/thesofproject/sof/blob/158089ceb69d8c685992c52d54e07483cec32b05/tools/logger/misc.c#L15-L42

The api differs from what is usually expected on most Unix systems, so the compiler will refuse it on musl, you just got lucky not hitting the problem also on glibc.

**Comment by lgirdwood** [comment]
I wonder why we do this, it could be to support Windows?  
@Johnnynator You are right, we should not be defining if already available. 
@juimonen is this something you can fix. Thanks !

**Comment by lgirdwood** [comment]
@juimonen any update, I did see some related fixes ?

**Comment by juimonen** [comment]
@lgirdwood @Johnnynator https://github.com/thesofproject/sof/pull/5045, just trivial rename to avoid clash. I think this was originally done this way because of windows... would this fix your issue?

**Comment by Johnnynator** [comment]
Yeah, this fixes this specific issue.

The only remaining part is the parsing of topology files. For which there is a different tracking issue: https://github.com/thesofproject/sof/issues/5039

So I suppose this one can be closed for now.
