### ISSUE TITLE
[BUG] cavs-nocodec tplg puts too much content on one DSP core

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#4911]
**Describe the bug**
Using all pipes the nocodec topology exposes leads to DSP overload.

**To Reproduce**
Tested on TGL-H system:

sof-test:
./multiple-pipeline.sh -f p -c 20

**Reproduction Rate**
How often does the issue happen ? i.e. 1/10 (once in ten attempts), 1/1000 or all the time.
Does the reproduction rate vary with any other configuration or user action, if so please describe and show the new reproduction rate.

**Expected behavior**
The topologies should leave some safety marging for DSP utilization so that even if all expose pipes are run, DSP is not above 90+% utilization. With current nocodec topology, this is happening.  Sof-logger should not have large number of "ll drift detected" warnings during a normal successful run.

**Impact**
Audio overrun/underruns can be seen when all audio pipes are used. Especially the dmic pipes are not designed to be used simultaneously, but there are not hard blocks to prevent this from happening.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.15.0-rc4-daily-nocodec-20211022
    * SOF: b82e0efc7557e1bcaaed21ab76e36155404848b3 (origin/main) pipeline: always check pipeline_for_each_comp() return value
2) Name of the topology file
    * Topology: sof-cavs-nocodec.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: TGL-H cavs2.5

**Screenshots or console output**
```
$ sof-logger |grep drift
[    10594771.506085] (          87.343750) c0 sa                          src/lib/agent.c:79   WARN validate(), ll drift detected, delta = 45015
[    10596930.516416] (          95.781250) c0 sa                          src/lib/agent.c:79   WARN validate(), ll drift detected, delta = 41394
[    10599032.807999] (        2102.291504) c0 sa                          src/lib/agent.c:79   WARN validate(), ll drift detected, delta = 40391

$ sof-logger |grep drift |wc -l
4247
```

**Comment by marc-hb** [comment]
ll_schedule: add a DSP load tracker to ll_tasks_execute #4943
