### ISSUE TITLE
[FEATURE] Support build fw with assigned Zephyr commit

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/sof#4917]
**Problem Description**
There are scenarios that need supports on building fw with assigned Zephyr commit.

In CI routine daily test or PR test, we need stable Zephyr for testing, rather than using the newest zephyr every time. This can eliminate the potential negative impacts brought by the newest Zephyr commits so that we can be braver to include zephyr platforms in our PR test.

**Describe the solution you'd like**
xtensa-build-zephyr.sh script needs to be modified to support cloning the newest zephyr repo or from a specific git commit id.

Found zephyr_fetch_and_switch function in this script, maybe we can utilize it and make some refinement.

**Comment by lgirdwood** [comment]
@marc-hb can we close ?

**Comment by marc-hb** [comment]
@keqiaozhang has the new `-c` feature been tested by Jenkins much yet? More in internal issue 69

**Comment by keqiaozhang** [comment]
> has this new `-z` feature been tested by Jenkins much yet?

Yes, Jenkins has been testing this `-z`  feature for 2 weeks.
