### ISSUE TITLE
[FEATURE] Support for ES8336 on Huawei Matebook D14-15-16 with i5-10210u

### ISSUE THREAD

**Issue by playXE** [thesofproject/sof#4939]
**Is your feature request related to a problem? Please describe.**
Huawei laptops ship with an Everest ES8336 sound card that is not supported by sofproject. 
**Describe the solution you'd like**
Adding support for it would be really awesome
**Describe alternatives you've considered**
I already tried this repo which seems to contain a kernel built with support for it but the audio clearly does not work: https://github.com/himozzza/essx8336
**Additional context**
Booting Linux and trying lsmod or dmsg shows only one valid HDMI sound output on the laptop and nothing more. Here's what I get from Device Manager on Windows: 
```
ACPI\VEN_ESSX&DEV_8336&SUBSYS_152D1262
ACPI\ESSX8336
*ESSX8336

```

**Comment by plbossart** [comment]
> Hi, have you found a solution for this?

This is tracked at https://github.com/thesofproject/linux/issues/3248 and the latest code is at https://github.com/thesofproject/linux/pull/3107
