### ISSUE TITLE
set stream tag for host dma and link dma individually

### ISSUE THREAD

**Issue by RanderWang** [thesofproject/sof#497]
Now host dma and link dma share the same stream tag. It is not fit for some cases that the stream tags
of host dma are different with link dma. So we need to set them individually

**Comment by lgirdwood** [comment]
@RanderWang can you confirm who allocates both tags, my understanding is that your change means host tag is allocated by driver and link tag by the FW.

**Comment by mmaka1** [comment]
@lgirdwood Both are done by the driver, so we'd need two separate tags coming down to the FW.

**Comment by keyonjie** [comment]
@lgirdwood yes, currently we are using the same tag for both host dma and link dma, this introducing limitation and issues for hda/hdmi capture where we need the exact correct tag(to align with HDA SDI pin).

**Comment by RanderWang** [comment]
fixed
