### ISSUE TITLE
What does "Initial infrastructure support for MS Windows" mean to release features in v1.9?

### ISSUE THREAD

**Issue by hongshui3000** [thesofproject/sof#4995]
Can you build code on windows? Or can Windows be used as a host to communicate with dsp like linux?
![1637062561(1)](https://user-images.githubusercontent.com/25566498/141978451-db0a8641-eda3-4eb8-bc28-f3c94bb1e203.jpg)

**Comment by dbaluta** [comment]
@hongshui3000 i suppose it is the IPC4 commands protocol used by windows to communicate with the SOF firmware. @lgirdwood could tell you more about this.

**Comment by lgirdwood** [comment]
It is indeed the IPC4 and Extended manifest support being added that is used by the Intel Windows audio DSP driver. This will also extend to support the Microsoft APO APIs (for audio processing too) and many other features used by Windows.

**Comment by hongshui3000** [comment]
good news.

**Comment by lgirdwood** [comment]
> good news.Hope there are some examples of windows and sof communication

There is, please enable the IPC4 MAJOR ABI in the Kconfig to build the Windows based IPC used by the Intel Windows driver. Please note this cannot be tested outside Intel atm as it require access Windows driver code.

**Comment by marc-hb** [comment]
> good news.

Closing.
