### ISSUE TITLE
Playback and capture's volume kctls are mixed in one page 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#50]
There're different views of kctl in amixer setting, but we found that all kctls of playback and capture are mixed together. For example, in playback view page, we also can found the kctl of capture and vice versa. This is a common issue on each platform.
![kctl](https://user-images.githubusercontent.com/22468760/42281603-a0c612fa-7fd6-11e8-95ba-f50aff89f531.PNG)

**Comment by lgirdwood** [comment]
This is an ALSA specific issue that relies on naming strings to help userspace to determine whether a kcontrols playback or capture.
I think here ALSA uses the second string to determine direction, can you try and change the topology to use "PGA4.0 Capture Master Volume" instead ?

**Comment by xiulipan** [comment]
@keqiaozhang 
You can take a reference here about the control name
https://www.alsa-project.org/~tiwai/writing-an-alsa-driver/ch06s03.html

**Comment by lgirdwood** [comment]
“SOURCE DIRECTION FUNCTION”.  Ok, so we need to change topology. e.g. "PGA4.0 Master Capture Volume" should become "Master Capture Volume PGA4.0". Can you update topology kcontrol builder macro to fix this.

**Comment by keqiaozhang** [comment]
@lgirdwood 
Only adjust the string order in topology doesn't help. The root cause may related to the first string. A control is usually defined from the three parts as “SOURCE DIRECTION FUNCTION”.   Source is a string such as “Master”, “PCM”, “CD” and “Line”, so the first string should not be PGA*. Xiuli will help to check how the control name is parsed in kerenl side.

**Comment by tlauda** [comment]
Shouldn't this issue be under linux repo instead of sof?

**Comment by lgirdwood** [comment]
Closed as should be kernel issue.

**Comment by Jocelyn-Li** [comment]
moved https://github.com/thesofproject/linux/issues/43
