### ISSUE TITLE
[FEATURE] SoundWire topologies need to use 3 pipelines for speaker path

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#5043]
As pointed out by @lyakh, the SoundWire topologies use 2 pipelines for the aggregated amplifier/speaker path.

![143814999-15f6cfc8-d70e-422c-9510-f051dade8668](https://user-images.githubusercontent.com/1149035/144104658-2da3ac86-5eda-48c5-ba20-74f9424f2e35.png)

The branch with "BUF3.2" should really be a different pipeline.

The rule is that each input and output to a mixer/mux/demux shall be handled by a different pipeline.

**Comment by juimonen** [comment]
@plbossart isn't this also a driver feature? not sure can asoc handle the 3 pipelines type connection you describe above...
I'm referring to this "virtual dai" thing we have in some topologies to terminate the pipe, would be nice to get rid of that at the same time.

**Comment by plbossart** [comment]
No I don't think it's a driver feature. We've already moved the nocodec and some HDaudio topologies to use the split pipelines with a mixer in the middle. Works fine.

The demux with the virtual dai is a different issue IMHO, it's the coupling between playback and capture that's not well handled.

**Comment by mengdonglin** [comment]
@plbossart @lyakh Can you please share more info why "The rule is that each input and output to a mixer/mux/demux shall be handled by a different pipeline"?

**Comment by plbossart** [comment]
@mengdonglin this is required to allow multiple streams to be handled by the same capture or playback endpoint.

We've started with the 'single pipeline' approach and it's just awful to maintain with a mixer in the middle of a pipeline. It's way simpler to use a 3 pipeline topology as we've done for cavs-nocodec, and are currently extending to HDaudio/SoundWire.

**Comment by lyakh** [comment]
The sof-tgl-sdw-max98373-rt5682.m4 topology has a similar and related issue, arguably even more severe: one capture and one playback PCMs are connected there via a demux and a smart amp. If I count correctly such a topology should be using 5 pipelines, currently that part of the topology is using 2 pipelines. That is also currently causing intermittent multiple-pause-resume failures in daily tests, e.g. in test 8806 from Dec 09-10. It seems like we need a demux-DAI pipeline similar to the pipe-mixer-dai-playback.m4

**Comment by plbossart** [comment]
@lyakh the demux should be at the end of a host pipeline, not the start of a new dai pipeline one as done for the mixer.

**Comment by plbossart** [comment]
> @lyakh the demux should be at the end of a host pipeline, not the start of a new dai pipeline one as done for the mixer.

actually it depends. My comment applies for the case where we use the demux to split the playback stream to go to multiple amps. The case of sof-tgl-sdw-max98373-rt5682.m4 is different, IIRC the demux is on a capture path, isn't it?

**Comment by lyakh** [comment]
> > @lyakh the demux should be at the end of a host pipeline, not the start of a new dai pipeline one as done for the mixer.
> 
> actually it depends. My comment applies for the case where we use the demux to split the playback stream to go to multiple amps. The case of sof-tgl-sdw-max98373-rt5682.m4 is different, IIRC the demux is on a capture path, isn't it?

It is in capture. yes

**Comment by plbossart** [comment]
closing, legacy change that we're not going to improve
