### ISSUE TITLE
How to get dsp log from host?

### ISSUE THREAD

**Issue by lenghonglin** [thesofproject/sof#5077]
Hi Guys, i bought IMX8MP to study SOF.
And i follow this [article](https://thesofproject.github.io/latest/getting_started/nxp/sof_imx_user_guide.html) to build firmware. I get `sof-imx8m.ldc` and `sof-imx8m.ri`. 

 Finally, Then copy to `/lib/firmware/imx/sof/`. But when i reboot the system, don't find `/sys/kernel/debug/sof/` this directory.

And I wonder know how to get dsp log and how to verify sof firmware is be loaded?

**Comment by lgirdwood** [comment]
@lenghonglin Have you enabled debugFS in your kernel. @dbaluta may have a specific kernel Kconfig for the IMX8MP platform. Also please check https://thesofproject.github.io/latest/index.html for details. If they are missing we can add.

**Comment by dbaluta** [comment]
@lenghonglin what kernel are you using? For the SOF debugfs to appear you need:

```
CONFIG_EXPERT=y
CONFIG_SND_SOC_SOF_DEVELOPER_SUPPORT=y
CONFIG_SND_SOC_SOF_DEBUG=y
CONFIG_SND_SOC_SOF_DEBUG_ENABLE_FIRMWARE_TRACE=y
CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE=y

```

**Comment by lenghonglin** [comment]
![image](https://user-images.githubusercontent.com/4686802/145821828-4a50a745-b35a-4f6d-b85e-1279563c050b.png)
I don't see `sof`.

![image](https://user-images.githubusercontent.com/4686802/145822002-fe89f3df-c747-42a3-91ea-2dc1bc56e2be.png)

![image](https://user-images.githubusercontent.com/4686802/145822022-aed9d2e1-767a-4c04-a96e-6f2ced2d7614.png)

But there are  sof files. So i doubt sof is not be loaded.

And this is my device tree, there is no `sof`， whether sof dts is not loaded?

![image](https://user-images.githubusercontent.com/4686802/145822673-c329ac36-0980-4dd2-a83b-f8f1f344155b.png)

**Comment by dbaluta** [comment]
First 5.4 is ancient. 

You could use https://source.codeaurora.org/external/imx/linux-imx?h=lf-5.10.y

We are working on having 5.15 by th end of the year.

Make sure you boot your board with imx8mp-mek-sof-wm9860.dtb otherwise SOF will not be enabled.

**Comment by lenghonglin** [comment]
> First 5.4 is ancient.
> 
> You could use https://source.codeaurora.org/external/imx/linux-imx?h=lf-5.10.y
> 
> We are working on having 5.15 by th end of the year.
> 
> Make sure you boot your board with imx8mp-mek-sof-wm9860.dtb otherwise SOF will not be enabled.

OK, i will try to build 5.15

**Comment by dbaluta** [comment]
@lenghonglin where did you buy i.MX8MP and how much did it cost?

@ranj063 maybe we can figure out a way to send you an i.mx8mp for codec_adapter patches.

An alternate way, would be to enable compress patches for Intel (I can point you to NXP internal tree, current kernel is 5.15). The only way we need to figure out after that is to create a topology for one of your intel boards.

**Comment by ranj063** [comment]
> @lenghonglin where did you buy i.MX8MP and how much did it cost?
> 
> @ranj063 maybe we can figure out a way to send you an i.mx8mp for codec_adapter patches.
> 
> An alternate way, would be to enable compress patches for Intel (I can point you to NXP internal tree, current kernel is 5.15). The only way we need to figure out after that is to create a topology for one of your intel boards.

I like the alternate suggestion @dbaluta

**Comment by dbaluta** [comment]
@ranj063 I think you can try to cherry-pick this patch https://github.com/thesofproject/linux/pull/3222/commits

into your tree and then adapt this topology https://github.com/thesofproject/sof/blob/main/tools/topology/topology1/development/sof-imx8-compr-mp3-wm8960.m4

for intel DAI and codec.

With this kernel is ready! Then on the firmware side you need to set this config options:

CONFIG_COMP_CODEC_ADAPTER
CONFIG_CADENCE_CODEC
CONFIG_CADENCE_CODEC_MP3_DEC_LIB

Lets have a meeting tomorrow to see how it goes. I will be available in your morning time.

**Comment by lenghonglin** [comment]
> First 5.4 is ancient.
> 
> You could use https://source.codeaurora.org/external/imx/linux-imx?h=lf-5.10.y
> 
> We are working on having 5.15 by th end of the year.
> 
> Make sure you boot your board with imx8mp-mek-sof-wm9860.dtb otherwise SOF will not be enabled.

Sorry for an awkward question that How to include imx8mp-mek-sof-wm9860.dtb?

**Comment by dbaluta** [comment]
@lenghonglin lets chat on. https://gitter.im/thesofproject/community

**Comment by marc-hb** [comment]
Is this still an issue?

**Comment by lgirdwood** [comment]
Can reopen if still an issue.
