### ISSUE TITLE
[BUG] [v2.0] FW replied with error. Error code: -22 in test 12_01_TestMixerCapture24000Hz24b32b4ch

### ISSUE THREAD

**Issue by kkarask** [thesofproject/sof#5079]
**Describe the bug**
Error occurs in test 12_01_TestMixerCapture24000Hz24b32b4ch
FW replied with error. Error code: -22 0x00000005 0x00000000 0x00004000

**Topology**
```
+-------------------------+
| +----+   +----+   +---+ |              +----+
| |Host|-->|Buff|-->|Dai| +------------->|SSPx|-----------------+
| +----+   +----+   +---+ |              +----+                 |
+-------------------------+                                     |
                                                                |
+-------------------------+                                     |
| +----+   +----+   +---+ |              +------+               |
| |Host|-->|Buff|-->|Dai| +------------->|SSPx+1|------------+  |
| +----+   +----+   +---+ |              +------+            |  |
+-------------------------+                                  |  |
                                                             |  |
+-------------------------+                                  |  |
| +----+   +----+   +---+ |              +------+            |  |
| |Host|-->|Buff|-->|Dai| +------------->|SSPx+2|---------+  |  |
| +----+   +----+   +---+ |              +------+         |  |  |
+-------------------------+                               |  |  |
                                                          |  |  |
                                                          |  |  |
                                                          |  |  |
                                                          |  |  |
                                    +----------------+    |  |  |
                                    | +----+   +---+ |    |  |  |
                        +-----------+ |Buff|<--|Dai| <----+  |  |
                        |           | +----+   +---+ |       |  |
                        |           +----------------+       |  |
                        |                                    |  |
                        |           +----------------+       |  |
                        |           | +----+   +---+ |       |  |
                        | +---------+ |Buff|<--|Dai| <-------+  |
                        | |         | +----+   +---+ |          |
                        | |         +----------------+          |
                        | |                                     |
+-----------------------v-v-----------------------+             |
| +----+    +----+    +-----+    +----+   +-----+ |             |
| |Host|<---|Buff|<---|Mixer|<---|Buff|<--| Dai |<--------------+
| +----+    +----+    +-----+    +-- -+   +-----+ |
+-------------------------------------------------+
```

**To Reproduce**
Run test 12_01_TestMixerCapture24000Hz24b32b4ch

**Reproduction Rate**
100%

**Environment**
1) Firmware branch name and commit
Git branch: v2.0, Hash: b678a4dcaa1e7ad0c6a056e17dd38bfe095a4464

3) Name of the platform(s) on which the bug is observed.
    * Platform: ICL RVP, APL RVP, WHL RVP

Logs:
[ICL_TestMixerCapture24000Hz24b32b4ch.zip](https://github.com/thesofproject/sof/files/7704077/ICL_TestMixerCapture24000Hz24b32b4ch.zip)

**Comment by bkokoszx** [comment]
@kkarask Do we have a reproduction also on main branch?

**Comment by lgirdwood** [comment]
@kkarask this looks a good test, is there anyway we can get this test topology in topology format for developer debug ? Fyi @lyakh will be looking at connected pipeline issues and logic in the next few weeks so this topology would be needed for the debug.

**Comment by bkokoszx** [comment]
@lgirdwood maybe we are missing some patch from main branch on stable-v2.0?

**Comment by lgirdwood** [comment]
> @lgirdwood maybe we are missing some patch from main branch on stable-v2.0?

@kkarask can you confirm this works on main branch but not on v2.0 ?
I think we have all the fixes, but if we can confirm then I can check for missing patches.

**Comment by kkarask** [comment]
@lgirdwood This bug could be related with #4961. I have checked one more time and this issue occurs only if playback iterations is greater than 1 then the Error code: -22 shows up. 
Sum up this issue doesn't work on main branch either. Sorry for misleading you.

**Comment by wszypelt** [comment]
TGL issue does not occur
Tested FW hash: [4943aaa](https://github.com/thesofproject/sof/commit/4943aaa8907149cf6c02e9046e2ef5d40ba72d74)
