### ISSUE TITLE
[FEATURE][Zephyr] Implement arch_cpu_disable_core and cpu_power_down_core in wrapper.c

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#5094]
**Is your feature request related to a problem? Please describe.**
Currently secondary cores are only powered down when DSP is put to suspend, or via out-of-band means (on Intel cAVS1.5, host controls power directly for the DSP cores).

Zephyr now implements interface to start/stop xtensa cores, so this should be used in wrapper.c.

**Comment by lgirdwood** [comment]
We need to start using native Zephyr APIs and wrap the xtos version of these functions.

**Comment by bkokoszx** [comment]
@mwasko fyi

**Comment by kv2019i** [comment]
Implemented with https://github.com/thesofproject/sof/pull/5298 .

The native interface will be a Zephyr replacement of SOF runtime PM for DSP cores.

**Comment by lgirdwood** [comment]
@kv2019i can we close now ?

**Comment by kv2019i** [comment]
Yes, closing.

**Comment by kv2019i** [comment]
Unfortunately have to reopen this immediately back :( -> https://github.com/thesofproject/sof/pull/5303

**Comment by kv2019i** [comment]
With @juimonen 's PR https://github.com/thesofproject/sof/pull/7183 merged, we can close this.
