### ISSUE TITLE
Topology file missing for Latitude 7320 Detachable

### ISSUE THREAD

**Issue by prof-dr-pepper** [thesofproject/sof#5111]
The topology file "sof-tgl-rt711-l0-rt1316-l1-mono-rt714-l3.tplg" that is required for https://github.com/thesofproject/linux/issues/3161 to work is still missing in sof-bin.

Regards,
Marcus

**Comment by marc-hb** [comment]
It has not been backported to 1.9.x (feel free to cherry-pick 425743e7723422 and submit) but it is in 2.0 which is being released: https://github.com/thesofproject/sof-bin/blob/main/v2.0.x/sof-tplg-v2.0/sof-tgl-rt711-l0-rt1316-l1-mono-rt714-l3.tplg
