### ISSUE TITLE
[BUG] [Topology1] Macro "PIPELINE_FORMAT" and "PCM_ID" not expanded

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof#5193]
**Describe the bug**
The macro `PIPELINE_FORMAT` is not replaced with its value, for example, s32le, in the generated conf by m4.

**To Reproduce**
Run script to build topology: `./script/build-tools.sh -T`
Search the keyword `PIPELINE_FORMAT` from sof/tools/build-tools/topology/\*.conf

Issue introduced by c687815185948d49350e4b58d59e786ac16339e1, confirmed.

PCM_ID is not expanded, `PIPELINE_FORMAT` and `PCM_ID` are the only two macro that not expanded after c68781518

**Comment by aiChaoSONG** [comment]
@lkoenig FYI

**Comment by lgirdwood** [comment]
That's good to know PIPELINE_FORMAT is being set by accident. @lkoenig are you able to fix and set to s32le ?

**Comment by lkoenig** [comment]
@lgirdwood I took the option to define it as the DAI_FORMAT. Should I instead define it as s32le ?

**Comment by lgirdwood** [comment]
> @lgirdwood I took the option to define it as the DAI_FORMAT. Should I instead define it as s32le ?

No, I think the fix is fine. Lets wait for @aiChaoSONG to validate and close.

**Comment by lkoenig** [comment]
PCM_ID is also reported to not be defined.
The issue  PCM_ID is caused by detect pipeline being created with PIPELINE_ADD instead of PIPELINE_PCM_ADD.
detect pipeline expect to be attached to a PCM.
I wonder if the correct fix would be to use PIPELINE_PCM_ADD in those case  ? @lgirdwood what do you think ?

**Comment by lkoenig** [comment]
PR #5194 contains CL to address issues shown in that bug report.
The .conf files after those change differs from the ones prior c687815 
A quick fix could be also to revert  c687815

**Comment by lkoenig** [comment]
@mwasko just wanted to make sure you saw the comment I made [above](https://github.com/thesofproject/sof/issues/5193#issuecomment-1014274876)
