### ISSUE TITLE
[BUG] Remove HiFi code duplication in HiFi buffer management

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof#5273]
Tracking bug for https://github.com/thesofproject/sof/pull/5169#discussion_r790016690

**Comment by cujomalainey** [comment]
Turns out github links don't point to resolved comments properly. This bug is track the deduplication of *_setup_circular(source) functions in HiFi sections.

**Comment by lgirdwood** [comment]
@cujomalainey fyi @singalsu is creating a spreadsheet for all the SIMD optimizations/cleanups. Will be able to share it soon.

**Comment by singalsu** [comment]
I've noticed that audio_stream_bytes_without_wrap() performs better in many cases than using same circular start-end registers for several circular buffers in the hot loop.  I will test the most important components with such change and change code if my test devices show processing time improvement.

**Comment by lgirdwood** [comment]
50% complete, should be fully complete for v2.2

**Comment by kv2019i** [comment]
@singalsu @andrula-song Can you update on status? I put milestone tentatively to v2.6, but we can pull in to v2.5 if we are ready.

**Comment by cujomalainey** [comment]
@singalsu any chance you can share that doc?

**Comment by andrula-song** [comment]
I checked our code, there are still two components to can remove the duplication of the circular buffer setting, one is eq_fir and another is tdfb.

**Comment by singalsu** [comment]
@kv2019i @cujomalainey Please keep 2.6 as target even if this would be a small change. We have other bugs fixing going on, better to not risk those for 2.5.

**Comment by andrula-song** [comment]
PR https://github.com/thesofproject/sof/pull/7499 is under review.

**Comment by alex-cri** [comment]
@andrula-song, @singalsu, with PR #7499  merged can we close this?

**Comment by andrula-song** [comment]
I have test several method to remove that duplication in TDFB HiFi part, but unfortunately, I found there is only about 0.2MCPS improvement but it needs about 19+ MCPS, So I did not create a PR for TDFB since such improvement seems meaningless. So I think we can close this issue now.

**Comment by cujomalainey** [comment]
Can you share the data in a draft PR for us to see the diff, MCPS isn't the only metric of importance here

**Comment by andrula-song** [comment]
here is the draft https://github.com/thesofproject/sof/pull/7700

**Comment by alex-cri** [comment]
@cujomalainey, is there further feedback that you feel is relevant for this issue?
