### ISSUE TITLE
clk: Null dereference reported by Coverity

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#531]
Coverity reports an Explicit null dereference in clock_set_freq()

path:
const struct freq_table *freq_table = NULL;
switch (clock) {
default: break;
}
idx = clock_get_freq(freq_table, freq_table_size, hz);

The default case should be an error?

**Comment by tlauda** [comment]
@plbossart Can you rerun Coverity to confirm it's fixed with #598?

**Comment by michalgrodzicki** [comment]
@plbossart please verify and/or close it.

**Comment by plbossart** [comment]
On 1/28/19 2:32 AM, michalgrodzicki wrote:
>
> @plbossart <https://github.com/plbossart> please verify and/or close it.
>
Sorry, I've asked CI to support Coverity for a while now, and I am not 
going to keep doing this verification if it can be automated.

**Comment by michalgrodzicki** [comment]
@plbossart - who promissed you add Coverity to the CI?
I'm askingbecause this person should be owner of the issue

**Comment by michalgrodzicki** [comment]
Hi @xiulipan, did you have a chance to check issue by the Coverity scan?

**Comment by tlauda** [comment]
@xiulipan Any updates?

**Comment by tlauda** [comment]
@xiulipan Fixed with #598.
