### ISSUE TITLE
eq_iir: Array compared against 0 (Coverity)

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#532]
/* Copy new config, find size from header */
   	
CID 324982 (#1 of 1): Array compared against 0 (NO_EFFECT)
array_null: Comparing an array to null is not useful: (*cdata).data->data, since the test will always evaluate as true.
   	Was (*cdata).data->data formerly declared as a pointer?
530                if (!cdata->data->data) {
531                        trace_eq_error("edn");
532                        return -EINVAL;
533                }

**Comment by singalsu** [comment]
This issues was fixed by PR #582.

**Comment by zeroDivider** [comment]
Solved by deleting :'D perfect
