### ISSUE TITLE
[BUG] [Zephyr] Wrong rimage signing schema used when building for IPC4

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#5335]
**Describe the bug**
When SOF is built for IPC4, a different signing schema (e.g. "tgl-cavs") must be used. 

When building for Zephyr, signing schema is not change and resulting image is not correct. 

Zephyr signing tool (west zephyr/scripts/west_commands/sign.py) takes the target from RIMAGE_TARGET.

SOF scripts to build with IPC4 should specify an alternative target RIMAGE_TARGET when building for Zephyr&IPC4.

In XTOS build, matching logic is in src/arch/xtensa/CMakeLists.txt and set via config override:
sof/src/arch/xtensa/configs/override/tigerlake_ipc4.config (from #5227)

Original report from @XiaoyunWu6666 and @aiChaoSONG 

- https://github.com/thesofproject/sof/issues/5335
- https://github.com/thesofproject/sof/issues/5357
- https://github.com/zephyrproject-rtos/zephyr/pull/42724
- https://github.com/zephyrproject-rtos/zephyr/pull/42949
- https://github.com/zephyrproject-rtos/zephyr/pull/42993

**Comment by lgirdwood** [comment]
@marc-hb IIUC, you have a few WIP PRs to support Zephyr. Do any cover this ?

**Comment by aiChaoSONG** [comment]
I filed a patch on zephyr side to add sign schema overriding support https://github.com/zephyrproject-rtos/zephyr/pull/42724. @lgirdwood @kv2019i @lyakh not sure they will accept it.

**Comment by lgirdwood** [comment]
Moving to v2.2 since this is related to IPC4

**Comment by marc-hb** [comment]
> @marc-hb IIUC, you have a few WIP PRs to support Zephyr. Do any cover this ?

Not sure what you're referring to sorry. In any case I don't have any WIP related to this.

**Comment by marc-hb** [comment]
> In any case I don't have any WIP related to this.

Well now I have. A bit:
- https://github.com/zephyrproject-rtos/zephyr/pull/42993

**Comment by aiChaoSONG** [comment]
Correct rimage sign schema on sof side: https://github.com/thesofproject/sof/pull/5412
