### ISSUE TITLE
eq_fir: Array compared against 0 (Coverity)

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#535]
/* Copy new config, find size from header */
   	
CID 324977 (#1 of 1): Array compared against 0 (NO_EFFECT)
array_null: Comparing an array to null is not useful: (*cdata).data->data, since the test will always evaluate as true.
   	Was (*cdata).data->data formerly declared as a pointer?
563                if (!cdata->data->data) {
564                        trace_eq_error("edn");
565                        return -EINVAL;
566                }

**Comment by plbossart** [comment]
@singalsu not the PR doesn't make the warning go away. I don't quite get why we use these variable length array, what's wrong with old-fashioned pointers?

**Comment by singalsu** [comment]
This issue was fixed by PR #582.
