### ISSUE TITLE
Array bounds need to be validated

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#537]
Some client code that use arrays for representing resources (like DMA drivers to represent channels) do not validate incoming array indexes against array bounds. All array indexes must be validated when indexes are passed in from non local code.

**Comment by jajanusz** [comment]
@mmaka1 Is it done/WIP?

**Comment by lgirdwood** [comment]
@jajanusz I think this is mostly done now, it was especially needed on the DMA drivers as channels were using arrays.
