### ISSUE TITLE
[BUG]dcache_invalidate_region causes ram data to be modified

### ISSUE THREAD

**Issue by lenghonglin** [thesofproject/sof#5414]
**Describe the bug**

with capture pipeline , during `dummy_dma_copy_crt_elem()`,  call `dcache_invalidate_region` cause ram data to be modified.

![image](https://user-images.githubusercontent.com/4686802/155485141-2f6ed130-cf77-4a17-8f2e-b91511486279.png)

![image](https://user-images.githubusercontent.com/4686802/155484754-ade16508-4ec0-47b6-955f-33a711cd9ce3.png)

as 1st picture, we can see `rptr` and `wptr`  is same with `dcache_invalidate_region`.  i think ram data is the same as cache data.

and see next picture:

![image](https://user-images.githubusercontent.com/4686802/155485166-e14db3ca-77cb-4a7e-9731-5a237979a707.png)

![image](https://user-images.githubusercontent.com/4686802/155482764-3dec70ba-d418-461a-98e8-077ea65b48f5.png)

![image](https://user-images.githubusercontent.com/4686802/155483065-58e4a2ad-1778-4a20-90f2-f82db05ca622.png)

but after `dcache_invalidate_region`, the ram data is be modify to `0x60709800`, it shoud be `0x60709c00`. copy_size is 1024.

as we know, `dcache_invalidate_region` is just invalidate cache data, and let cpu read ram data directly, not modify ram data.

the other thing is `rptr 0x605087f0` is not 32 byte alignment. 

How to ensure that cache operation addresses are 32 byte aligned

**Reproduction Rate**

almost 100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: Zephyr 2.7.0
    * SOF: 1.5.0

**Comment by fuyuntsuo** [comment]
Are these screen captures part of Xtensa Xplorer? Can we run SOF fw on that?

**Comment by lenghonglin** [comment]
> Can we run SOF fw on that?

Xtensa Xplorer,  we can run SOF fw

**Comment by dbaluta** [comment]
I honestly do not understand the problem, but let me give you some pointers. At a first glance, after you invalidate the cache you re-read the data from RAM (but data from RAM could have been updated by the DMA, so you get different values from what was in the cache).

Next part: data alignment comes from your DMA driver.

You can have a look at `src/audio/host.c`:

host_params:
-> dma_get_attribute(hd->dma, DMA_ATTR_BUFFER_ADDRESS_ALIGNMENT, &addr_align);

Also, how are you able to see the address contens in real time using Xtensa Explorer? Are you using a debugger?

**Comment by lenghonglin** [comment]
> I honestly do not understand the problem, but let me give you some pointers. At a first glance, after you invalidate the cache you re-read the data from RAM (but data from RAM could have been updated by the DMA, so you get different values from what was in the cache).
> 
> Next part: data alignment comes from your DMA driver.
> 
> You can have a look at `src/audio/host.c`:
> 
> host_params: -> dma_get_attribute(hd->dma, DMA_ATTR_BUFFER_ADDRESS_ALIGNMENT, &addr_align);
> 
> Also, how are you able to see the address contens in real time using Xtensa Explorer? Are you using a debugger?
> 
> Cc: @paulstelian97

Thanks , i use dummy-dma in host

Yes , i use jlink to debug hifi4.

**Comment by paulstelian97** [comment]
This looks like something unrelated is interacting with the sg elem (did some interrupt happen in the meantime?). Indeed this doesn't look like normal behaviour.

However do note that after copying a segment the driver is supposed to update and change to a different sg elem. Remember that elems is a full blown array, not just a simple pointer (you're only showing elems[0] in that debug screen). Also, while in the middle of the copy an elem isn't supposed to change once the copy is done it typically does change.

This does need further analysis.

**Comment by lgirdwood** [comment]
Sorry, not following this. @lenghonglin  are you saying that the data pointed to by rptr is being modified or that rptr is being modified ?

I would expect the rptr->data to be modified after invalidate if your local cache copy is not coherent with the data in RAM (e.g. host or DMA has copied data to rptr->data).

**Comment by fuyuntsuo** [comment]
Hi @lenghonglin sorry to interrupt. Just wondering how to run SOF fw on Xtensa Xplorer?

Is it a pure emulation? Or kind of debug board overlooking a real system?

**Comment by lenghonglin** [comment]
> 

We reserved the JTAG debugging interface of DSP

**Comment by lenghonglin** [comment]
> 

We reserved the JTAG debugging interface of DSP

**Comment by lenghonglin** [comment]
> Hi @lenghonglin sorry to interrupt. Just wondering how to run SOF fw on Xtensa Xplorer?
> 
> Is it a pure emulation? Or kind of debug board overlooking a real system?

We reserved the JTAG debugging interface of DSP
