### ISSUE TITLE
[FEATURE] Variable buffer sizes in pipeline

### ISSUE THREAD

**Issue by sanzazacuro** [thesofproject/sof#5422]
**Is your feature request related to a problem? Please describe.**
Is it possible to have different buffer sizes for a pipeline? For instance, a component in a pipeline can have 48 samples input and 500 samples output sent to host?

I tried creating variable widget buffer configs for a pipeline, but the actual frame size in component did not change:
```
pseudo:
NUM_SAMPLES = 500
W_BUFFER(2, NUM_SAMPLES ,PLATFORM_HOST_MEM_CAP)
```
![pipe1](https://user-images.githubusercontent.com/25507763/155523957-a78bf288-8748-4423-ba9b-e0b33248fee3.png)

**Comment by sanzazacuro** [comment]
How would ALSA (arecord) react to this?

**Comment by dbaluta** [comment]
What worked for me with codec_adapter component (like your custom component is to have some internal deep buffers and thus mitigate having some fixed input / output buffers.

But your question is valid. I think you can setup the buffers sizes from topology files.

**Comment by lgirdwood** [comment]
Ack, it is possible to set any sizes for each stage in the pipeline topology. The main thing is to keep the buffer small for latency and large enough for headroom.
