### ISSUE TITLE
[BUG] [ADL][ZEPHYR] boot fail to error: can't set params for DMA for trace -110

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#5456]
**Describe the bug**
https://sof-ci.01.org/sofpr/PR5443/build12190/devicetest/?model=TGLU_UP_HDA_ZEPHYR&testcase=verify-kernel-boot-log

This is a regression caused by merging of:
https://github.com/zephyrproject-rtos/zephyr/pull/41828

**Comment by keqiaozhang** [comment]
This issue has been solved and does not appear in the daily testing of all ADL / TGL zephyr platforms. Test ID:10681.
