### ISSUE TITLE
[FEATURE] Provide average cycle count info for performance counter

### ISSUE THREAD

**Issue by johnylin76** [thesofproject/sof#5522]
**Is your feature request related to a problem? Please describe.**
Most SOF developers rely on performance counter to get MCPS for a running component. Currently performance counter only report the peak value which can be a lot larger than average due to the characteristics of LL scheduler. An example is if a component has the processing period larger than the pipeline period.

**Describe the solution you'd like**
The average cycle count could be provided by the average calculation per chunk, which should not spend too much cost. 

**Describe alternatives you've considered**
DSP load tracker has provided the average value but it counts the overall cycle spent for tasks per schedule period. It is not suitable for MCPS measurement of one component.

**Additional context**
#5425 is for the resolution of the similar problem. However I wonder that for some audio processing, the required computation cycle may be varied by the content in the sample chunk in addition to the sample count, e.g. DRC deals with the sample chunk which has the constant signal intensity vs. the drastic ramping signal intensity.

**Comment by kv2019i** [comment]
When this is implemented, feature needs to be documented to https://thesofproject.github.io/latest/developer_guides/debugability/perf-counters/index.html?highlight=performance
