### ISSUE TITLE
debugability: macros breaking multicore builds (sof section .text not fitting in region sof_text)

### ISSUE THREAD

**Issue by mwierzbix** [thesofproject/sof#553]
Building multicore (for instance with `--with-arch=xtensa-smp `), we get following error mesasge
`sof section `.text' will not fit in region `sof_text'`

**Comment by mwierzbix** [comment]
It would maybe be good if Travis had both single- and mult- core builds?

**Comment by lgirdwood** [comment]
@mwierzbix already given this task to @xiulipan , but this makes it official.

**Comment by mwierzbix** [comment]
I was just about to PR a workaround, and with both @mmaka1 and @akloniex to investigate.

**Comment by lgirdwood** [comment]
I guess you will be able to fix first since it's evening time now for @xiulipan

**Comment by mwierzbix** [comment]
Temporary fix would be to add `0x800` to `SOF_TEST_SIZE` to allow other developers to work while we work this issue out.

And if we don't manage, then maybe @xiulipan will :)

**Comment by lgirdwood** [comment]
Sorry, I was meaning have @xiulipan fix Travis CI for SMP builds, not for memory sizes

**Comment by mwierzbix** [comment]
Oh, well then he would discover that they fail because of this :P

**Comment by mwierzbix** [comment]
Status update: workaround is already merged to master, @akloniex has a fix PRed.
