### ISSUE TITLE
[BUG] glitches in the whole file during stress test with Dmic on JSL 

### ISSUE THREAD

**Issue by kkarask** [thesofproject/sof#5595]
**Describe the bug**
The whole file with glitches was found in test 05_03_TestDmicFifoBSimpleCapture48000hz32b32b4ch

Capture on DMIC interface FIFO B with signal verification.

**Topology**
```
  +----------+      +------------------+
    |    OS    |----->|   AUDIO DEVICE   |-----------------+
    +----------+      +------------------+                 |
                                                           |
                  +---------------------------+            |
    +----------+  | +------+   +------------+ |  +------+  |
    | Host cap |<---|Buffer|<--| Dai Fifo_B |<---| DMIC |<-+
    +----------+  | +------+   +------------+ |  +------+
                  +---------------------------+
```

**To Reproduce**
Run test 05_03_TestDmicFifoBSimpleCapture48000hz32b32b4ch with Diagnostic driver

**Reproduction Rate**
1/75

**Environment**
1) Firmware branch name and commit
    * SOF: Branch: v2.1-rc1, Hash: d93efb7a68676e23306e1468ff345318b0eade06

2) Name of the platform(s) on which the bug is observed.
    * Platform: JSL

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/82518823/159902692-85fc3b84-bf37-479d-ba55-a4a5e8ff6695.png)
[JSL_05_03.zip](https://github.com/thesofproject/sof/files/8340900/JSL_05_03.zip)

**Comment by singalsu** [comment]
Thanks, can you please also upload the wav file?

**Comment by kkarask** [comment]
Wav file:
[TestDmicFifoBSimpleCapture48000hz32b32b4ch.test_2022_03_24_02_58_52_fifo_b_tplg0_iter18.wav.zip](https://github.com/thesofproject/sof/files/8389393/TestDmicFifoBSimpleCapture48000hz32b32b4ch.test_2022_03_24_02_58_52_fifo_b_tplg0_iter18.wav.zip)

**Comment by wszypelt** [comment]
unsupported platform
on TGL issue does not occur
Tested FW hash: https://github.com/thesofproject/sof/commit/4943aaa8907149cf6c02e9046e2ef5d40ba72d74
