### ISSUE TITLE
[FEATURE] Hide idc_send_msg() from SOF application code

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#5679]
**Is your feature request related to a problem? Please describe.**
All SOF drivers currently expose idc_send_msg() as an interface for core-to-core communication (src/include/sof/drivers/idc.h). This is used both by low-level operating system code (e.g. arch/xtensa/lib/cpu.c) as well as application code (e.g. src/ipc/ipc-common.c).

In high level application code, to perform actions like "run this function on core X", SOF application code should be changed to use more generic OS interfaces. Under the hood, IDC messages will be used to wake up another core, but this should be an implementation detail not directly visible in audio application code.

**Describe the solution you'd like**
Zephyr k_p4wq_submit() is one candidate. Or alternatively, defining a new SOF specific interface build on top of that that is used by all sof/src/audio and sof/src/ipc/ to queue work to other cores).

**Comment by lyakh** [comment]
@kv2019i @aborisovich how about `ipc_process_on_core()` for one of the most common IDC uses - for IPC and a similar API for other uses? `k_p4wq_submit()` seems too implementation-specific to me too.

**Comment by lgirdwood** [comment]
@nashif @andyross which Zephyr API should be used here to abstract inter processor communication e.g. to make IDC API generic.

**Comment by aborisovich** [comment]
> 

Yes I agree, function should be named something like `ipc_process_on_core()` or maybe `ipc_process_core_local()` ? (a discreet reference to standard C "thread local" but no threads here obviously). It should probably call `k_p4wq_submit()` inside its body as implementation detail but the k_p4wq_submit name does not seem like a intuitively named function for this purpose in higher level API.

**Comment by lgirdwood** [comment]
> > 
> 
> Yes I agree, function should be named something like `ipc_process_on_core()` or maybe `ipc_process_core_local()` ? (a discreet reference to standard C "thread local" but no threads here obviously). It should probably call `k_p4wq_submit()` inside its body as implementation detail but the k_p4wq_submit name does not seem like a intuitively named function for this purpose in higher level API.

@aborisovich @kv2019i @nashif @andyross API naming proposed sounds good to me, but this is one for the Zephyr folks to align.

**Comment by kv2019i** [comment]
There's one additional set of users found in src/include/sof/audio/component_ext.h:
 - IDC_MSG_TRIGGER, IDC_MSG_PREPARE

It seems these are not used anywhere, but we need to address this one way or another.
