### ISSUE TITLE
[FEATURE] CMake can pass FW micro version to rimage

### ISSUE THREAD

**Issue by mengdonglin** [thesofproject/sof#5693]
**Purpose**
Lower the risk of releasing FW binaries which are built and signed before SOF release tag is applied.
CMake can pass FW micro version to rimage as well so that rimage can store major.minor.micro version in ADSP manifest. Today it only pass major and minor version to rimage.

This feature can help us check FW version of a FW binary *.ri using https://github.com/thesofproject/sof/blob/main/tools/sof_ri_info/sof_ri_info.py
Thus we needn't check FW macro, minor and micro version of each *.ri by testing in Linux and checking version in dmesg of FW ready IPC on each supported platform.

**Describe the solution you'd like**
 https://github.com/thesofproject/sof/blob/main/src/arch/xtensa/CMakeLists.txt also need pass SOF_MAJOR, SOF_MINOR and SOF_MICRO in '-f x.y.z' to rimage

https://github.com/thesofproject/sof/blob/main/src/arch/xtensa/CMakeLists.txt#L460
https://github.com/thesofproject/sof/blob/main/src/arch/xtensa/CMakeLists.txt#L501

COMMAND ${PROJECT_BINARY_DIR}/rimage_ep/build/rimage
			-o sof-${fw_name}.ri
			-c "${PROJECT_SOURCE_DIR}/rimage/config/${fw_name}.toml"
			-k ${RIMAGE_PRIVATE_KEY}
			-i ${RIMAGE_IMR_TYPE}
			-f ${SOF_MAJOR}.${SOF_MINOR}.${SOF_MICRO}

**Additional Context**
Please find additional context in in https://github.com/thesofproject/rimage/issues/90

**Comment by lgirdwood** [comment]
@marc-hb any comments ?

**Comment by mengdonglin** [comment]
@aiChaoSONG Thanks, you will find my PR is almost same as your comments :)
