### ISSUE TITLE
[BUG] ASSERTION FAIL with arch_is_in_isr() when triger start

### ISSUE THREAD

**Issue by lenghonglin** [thesofproject/sof#5751]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4686802/165875057-af4ae336-9198-48ee-9b63-40212f08b1f6.png)

when enable `CONFIG_ASSERT` . It show `ASSERTION FAIL` .

![image](https://user-images.githubusercontent.com/4686802/165878580-81625161-4d72-4e3e-8248-fe72cd12f533.png)

It seem `k_sem_take` execute in isr.

**To Reproduce**
when triger start, maybe it will cause this assert.

**Reproduction Rate**
maybe 1/10

**Impact**
It will cause zephyr fatal

**Environment**
    * Zephyr: v2.7.0-rc2-335-g817dbe8afbb4
    * SOF: v1.8-rc1-592-ga7cbfc324cc8-dirty
    * Platform: CSK6001

**Comment by plbossart** [comment]
asserts are evil. I don't know how many times I'll have to ask that they be removed with proper error handling used instead. @lgirdwood FYI

**Comment by kv2019i** [comment]
@lenghonglin Can you retest with newer SOF and Zephyr? You are using very old versions of both (SOF1.8 versus latest SOF2.1 and Zephyr2.7 versus Zephyr3.0 released).

I don't see how this can happen with current code. The domain thread is specifically run in a Zephyr thread, not ISR:
```
       thread = k_thread_create(&dt->ll_thread,
»       »       »       »        ll_sched_stack[core],
»       »       »       »        ZEPHYR_LL_STACK_SIZE,
»       »       »       »        zephyr_domain_thread_fn, zephyr_domain, NULL, NULL,
```

**Comment by lenghonglin** [comment]
> @lenghonglin Can you retest with newer SOF and Zephyr? You are using very old versions of both (SOF1.8 versus latest SOF2.1 and Zephyr2.7 versus Zephyr3.0 released).
> 
> I don't see how this can happen with current code. The domain thread is specifically run in a Zephyr thread, not ISR:
> 
> ```
>        thread = k_thread_create(&dt->ll_thread,
> »       »       »       »        ll_sched_stack[core],
> »       »       »       »        ZEPHYR_LL_STACK_SIZE,
> »       »       »       »        zephyr_domain_thread_fn, zephyr_domain, NULL, NULL,
> ```

https://github.com/zephyrproject-rtos/zephyr/pull/42806  this pr slove my problem

**Comment by kv2019i** [comment]
Solved in latest release, so closing the issue.
