### ISSUE TITLE
[BUG] Scheduling/frame size for dmic pipeline seems capped at low rate

### ISSUE THREAD

**Issue by sanzazacuro** [thesofproject/sof#5763]
**Describe the bug**
I want to increase the frame size/scheduling of a dmic pipeline from the default 1000us/48 frames to 10 000us/480 frames. However, the pipeline seems capped at 128 frames when I try to adjust it higher. Im guessing this is due to some hardware outside the DSP. So my question is, how can I up this rate to around 480 frames? Is there any other place than the `PIPELINE_PCM_ADD` or `DMIC_CONFIG/DAI_CONFIG` this can be set? Thanks.

**To Reproduce**
Use intel dmic pipeline, set frames argument in PIPELINE_PCM_ADD to 10 000.

**Reproduction Rate**
100%

**Expected behavior**
Modules in the dmic pipeline should have 480 frames, not 128 frames.

**Impact**
Showstopper

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: 5.15
    * SOF: 5ef33e6310b7921cb2fdae4bf2ae798d26cb5438
2) Name of the topology file
    * Topology: sof-tgl-max98357a-rt5682.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: Tigerlake, HP Chromebook x360

**Comment by lgirdwood** [comment]
@singalsu I assume the DMIC can handle larger period sizes like 10ms ?
@sanzazacuro what error do you see when you try a 10ms period with DMIC ?

**Comment by singalsu** [comment]
@sanzazacuro It should not be DMIC IP related, the FIFO is not even 1 ms deep so default 1 ms schedule consists of several DMA bursts.  Did you change the period also for DAI_ADD?

**Comment by singalsu** [comment]
I got 48 kHz DMIC pipeline running with 10 ms scheduling but not 16 kHz. The error I get into FW trace with a modified sof-hda-generic-2ch.tplg is this. The topology macro intel-generic-dmic.m4 seems to calculate buffers sizes for the pipeline wrong when I tried to change macro values from 1000 to 10000.

```
[       16068.228528] (       16068.228516) c0 dma-trace          ../audio/volume/volume.c:1255 ERROR volume_prepare(): sink buffer size 16 is insufficient < 640
[       16093.436861] (          25.208332) c0 dma-trace          ....../pipeline-params.c:347  ERROR pipeline_prepare(): ret = -12, dev->comp.id = 58
[       16115.780610] (          22.343750) c0 dma-trace            src/ipc/ipc3/handler.c:313  ERROR ipc: pipe 11 comp 58 prepare failed -12
```
@sanzazacuro Are you able to check if you get the same error? With my device I view the error trace with command:

`sudo /usr/local/bin/sof-logger -l /lib/firmware/intel/sof/sof-tgl-h.ldc`

**Comment by singalsu** [comment]
@sanzazacuro If you have similar error, please check if PR #5795 helps.

**Comment by lgirdwood** [comment]
@sanzazacuro did the update fix your issue ? if so we can close.

**Comment by sanzazacuro** [comment]
Yes, thanks, COMP_PERIOD_FRAMES fixed the issue.
