### ISSUE TITLE
Metallic noise occurs after suspend/resume

### ISSUE THREAD

**Issue by markyang** [thesofproject/sof#577]
**Summary:**
  This issue cannot be reproduced on UP2 now(slept 50 times), but metallic noise was found.
  sof-logger is empty. sof-logger -t log is attached below.

**dmesg:**
```
[ 1725.525343] PM: suspend entry (deep)
[ 1725.525346] PM: Syncing filesystems ... done.
[ 1725.526265] Freezing user space processes ... (elapsed 0.002 seconds) done.
[ 1725.529255] OOM killer disabled.
[ 1725.529257] Freezing remaining freezable tasks ... (elapsed 0.002 seconds) done.
[ 1725.531416] Suspending console(s) (use no_console_suspend to debug)
[ 1725.640177] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[ 1725.782240] sof-audio sof-audio: tag 1 not opened!
[ 1725.782259] sof-audio sof-audio: pcm: trigger stream 0 dir 0 cmd 5
[ 1725.782295] sof-audio sof-audio: ipc tx: 0x60000000: GLB_STREAM_MSG: unknown type
[ 1725.782567] sof-audio sof-audio: error: ipc error for 0x60000000 size 0xc
[ 1725.782584]  Port5: ASoC: trigger FE failed -22
[ 1725.782613] sof-audio sof-audio: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 1725.782802] sof-audio sof-audio: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 1725.809053] sof-audio sof-audio: DSP core(s) enabled? 0 : core_mask 3
[ 1725.809087] sof-audio sof-audio: Debug PCIR: 00000000 at  00000044
[ 1725.809095] sof-audio sof-audio: Debug PCIW: 00000010 at  00000044
[ 1725.869295] ACPI: Preparing to enter system sleep state S3
[ 1725.869887] PM: Saving platform NVS memory
[ 1725.869894] Disabling non-boot CPUs ...
[ 1725.886709] smpboot: CPU 1 is now offline
```

**Test steps:**
1. aplay -Dhw:0,0 -r 48000 -c 2 -f s16_le -i -vv ~/Music/18_WAV_48000Hz_stereo_16bit.wav
2. run the following scripts:
i=0
while [ $i -lt 50 ]
do
        rtcwake -m mem -s 3
        sleep 3
        let i++
done

**Test env:**
sof master: 40c054ab
sof tool: 937032f
kernel sof-dev: af44aa9b
tplg: sof-apl-pcm512x.tplg-937032f

**Log:**
[dmesg-apl.log](https://github.com/thesofproject/sof/files/2556338/dmesg-apl.log)
[logger-t.txt](https://github.com/thesofproject/sof/files/2556340/logger-t.txt)

_Originally posted by @markyang in https://github.com/thesofproject/sof/issues/522#issuecomment-436526382_

**Comment by ranj063** [comment]
@markyang if you cannot reproduce on up2, which platform did you see it on? The test environment seems to suggest it was the up2.

**Comment by markyang** [comment]
**Summary:**
  This metallic noise issue also cannot be reproduced on UP2 using the latest image.

**Test env:**
sof master: 43120c92
sof tool: 5894ed4c
kernel sof-dev: 21947cd7
tplg: sof-apl-pcm512x.tplg-5894ed4c

**Comment by markyang** [comment]
**Summary:**
  This metallic noise issue also cannot be reproduced on UP2 using the latest image.
**Test env:**
sof master: 43120c92
sof tool: 5894ed4c
kernel sof-dev: 21947cd7
tplg: sof-apl-pcm512x.tplg-5894ed4c
