### ISSUE TITLE
APL gcc toolchain cannot build xtensa-smp

### ISSUE THREAD

**Issue by jajanusz** [thesofproject/sof#581]
Our toolchain for apl is bugged, it should have threadptr support, but it does not.
What results in errors like:
`Error: unknown opcode or format name 'rur.threadptr'` when trying to compile apl for smp

Sorry for posting it here but https://github.com/thesofproject/crosstool-ng has disabled issues

**Comment by lgirdwood** [comment]
@jajanusz which GCC version do you have ? iirc, I added threadptr a while ago

**Comment by jajanusz** [comment]
@lgirdwood gcc 8.1 from today from https://github.com/thesofproject/crosstool-ng
Travis had the same problem: https://travis-ci.org/thesofproject/sof/jobs/454734132#L1663

**Comment by lgirdwood** [comment]
@xiulipan is the travis CI container using latest overlay HEAD (which has THREADPTR register support)

**Comment by lgirdwood** [comment]
@jajanusz doubled checked and some overlays were missing. now pushed.  @xiulipan CI container will need updated.

**Comment by xiulipan** [comment]
@lgirdwood 
I will update the docker image ASAP.

**Comment by xiulipan** [comment]
@lgirdwood @jajanusz 
docker image update done. Please have a push to have a test with #570

**Comment by jajanusz** [comment]
@xiulipan @lgirdwood 
Thanks for updates, now it works
