### ISSUE TITLE
Compile the sof topology2 file on windows

### ISSUE THREAD

**Issue by hongshui3000** [thesofproject/sof#5835]
sof is already able to support windows, is there any plan for alsatplg to support being able to run on windows. In this way topology compilation can also be done on windows.

**Comment by plbossart** [comment]
alsatplg is part of the alsa-utils package, which is not maintained by this SOF team - though we did make contributions.

Even in Windows, you can use WSL to open a Linux terminal and compile topologies. Not sure what the ask is here really.

**Comment by hongshui3000** [comment]
> 

I learned from the sof doc that this alsatplg is needed to compile the topology. But the documentation doesn't mention how to install the alsatplg . I am not clear how to install it in WLS or linux

**Comment by lgirdwood** [comment]
@aborisovich is the expert on getting stuff to build on Windows. @hongshui3000 can you look at the python build script and see how this build topology1 on Windows, we may be able to modify for topology2 ?

**Comment by lgirdwood** [comment]
> > @aborisovich is the expert on getting stuff to build on Windows. @hongshui3000 can you look at the python build script and see how this build topology1 on Windows, we may be able to modify for topology2 ?
> 
> I looked at the script and I didn't find a way to build topology1 on Windows. What did I miss?

Sorry, your right - this file is just building the FW and not the topology on Windows.

Can you try https://thesofproject.github.io/latest/developer_guides/tech/compile_wsl.html and adapt WSL to install alsa-utils and follow these instructions ?

https://thesofproject.github.io/latest/developer_guides/topology2/topology2.html#building-2-0-configuration-files

It seems we need to be able to build alsa-lib and alsa-utils from git on WSL ?

**Comment by hongshui3000** [comment]
building the topology on wsl is a usable alternative. At least for windows users they don't need to start a linux host, just to build a topology.

**Comment by lgirdwood** [comment]
> building the topology on wsl is a usable alternative. At least for windows users they don't need to start a linux host, just to build a topology.
> 
> Although alsa-utils can be installed on wsl, the version is not the latest. I see alsa-utils (1.1.3-1ubuntu1) installed on my system. I think maybe it can't keep up with the requirements of sof

Yeah, we do work on alsa-lib and alsa-utils packages as part of SOF so we do need a good method to make sure we can support git version of these packages on WSL. 

Were you able to build alsa-lib or alsa-utils from git on WSL ? If so it's probably worth a PR updating sof docs to help others on WSL.

**Comment by hongshui3000** [comment]
> > building the topology on wsl is a usable alternative. At least for windows users they don't need to start a linux host, just to build a topology.
> > Although alsa-utils can be installed on wsl, the version is not the latest. I see alsa-utils (1.1.3-1ubuntu1) installed on my system. I think maybe it can't keep up with the requirements of sof
> 
> Yeah, we do work on alsa-lib and alsa-utils packages as part of SOF so we do need a good method to make sure we can support git version of these packages on WSL.
> 
> Were you able to build alsa-lib or alsa-utils from git on WSL ? If so it's probably worth a PR updating sof docs to help others on WSL.

Some dependent packages are missing, and some cannot be downloaded from the default address. I am currently unable to compile them on wsl

**Comment by lgirdwood** [comment]
> Some dependent packages are missing, and some cannot be downloaded from the default address. I am currently unable to compile them on wsl

Which deps ? My understanding is that alsa-lib and alsa-utils can be stripped down to the bare minimum by using ```./configure --disable-this --disable-that``` and so on.

**Comment by hongshui3000** [comment]
alsa-lib
![image](https://user-images.githubusercontent.com/25566498/170512811-0e4a4963-9b8a-4566-9834-f23f0a5af485.png)
![image](https://user-images.githubusercontent.com/25566498/170513057-745a0d8e-f6da-43fc-ac78-1733a2ddf40c.png)
alsa-utils
![image](https://user-images.githubusercontent.com/25566498/170513370-b62eccaf-daf1-42e9-9cb9-fc738bd36d89.png)

**Comment by hongshui3000** [comment]
![image](https://user-images.githubusercontent.com/25566498/170605454-3f0a6ee6-b3ab-4577-a7da-edc4dc3dbcc8.png)
autoconf can be installed, but still shows that libtool is missing

**Comment by hongshui3000** [comment]
autoconf can be installed, but still shows that libtool is missing
![image](https://user-images.githubusercontent.com/25566498/170605665-d80a6345-c1ea-414e-8fb0-c95d27388476.png)

**Comment by lgirdwood** [comment]
@hongshui3000 apologies, I thought libtooli would be pulled in as a dependency of auto tools. pls try
```sudo apt-get install libtool```

**Comment by lgirdwood** [comment]
If you hit another tool not found can you google form "ubuntu install <toolname>". This should give you the apt-get package name etc

**Comment by hongshui3000** [comment]
After installing the tool, it can be compiled, but the compilation of alsa-lib can be successful, but the compilation of alsa-utils fails and the log is as follows. Do you have any suggestions?
```
~/alsa-utils$ ./gitcompile
configure.ac:10: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:11: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
./gitcompile: line 10: gettextize: command not found
configure.ac:10: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:11: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
configure.ac:15: installing './compile'
configure.ac:21: installing './config.guess'
configure.ac:21: installing './config.sub'
configure.ac:6: installing './missing'
alsactl/Makefile.am: installing './depcomp'
axfer/test/Makefile.am:9: warning: source file '../container.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
axfer/test/Makefile.am:9: warning: source file '../container-riff-wave.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:9: warning: source file '../container-au.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:9: warning: source file '../container-voc.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:9: warning: source file '../container-raw.c' is in a subdirectory,
axfer/test/Makefile.am:9: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container-riff-wave.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container-au.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container-voc.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../container-raw.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../mapper.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../mapper-single.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
axfer/test/Makefile.am:20: warning: source file '../mapper-multiple.c' is in a subdirectory,
axfer/test/Makefile.am:20: but option 'subdir-objects' is disabled
topology/nhlt/Makefile.am:8: warning: source file 'intel/intel-nhlt.c' is in a subdirectory,
topology/nhlt/Makefile.am:8: but option 'subdir-objects' is disabled
topology/nhlt/Makefile.am:8: warning: source file 'intel/dmic-nhlt.c' is in a subdirectory,
topology/nhlt/Makefile.am:8: but option 'subdir-objects' is disabled
topology/nhlt/Makefile.am:8: warning: source file 'intel/dmic/dmic-debug.c' is in a subdirectory,
topology/nhlt/Makefile.am:8: but option 'subdir-objects' is disabled
topology/nhlt/Makefile.am:8: warning: source file 'intel/dmic/dmic-process.c' is in a subdirectory,
topology/nhlt/Makefile.am:8: but option 'subdir-objects' is disabled
topology/nhlt/Makefile.am:8: warning: source file 'intel/ssp-nhlt.c' is in a subdirectory,
topology/nhlt/Makefile.am:8: but option 'subdir-objects' is disabled
topology/nhlt/Makefile.am:8: warning: source file 'intel/ssp/ssp-debug.c' is in a subdirectory,
topology/nhlt/Makefile.am:8: but option 'subdir-objects' is disabled
topology/nhlt/Makefile.am:8: warning: source file 'intel/ssp/ssp-process.c' is in a subdirectory,
topology/nhlt/Makefile.am:8: but option 'subdir-objects' is disabled
configure.ac:10: error: possibly undefined macro: AM_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:11: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:45: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:193: error: possibly undefined macro: AC_CHECK_PROG
CFLAGS=-O2 -Wall -pipe -g
./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
./configure: line 2973: syntax error near unexpected token `external'
./configure: line 2973: `AM_GNU_GETTEXT(external)'
```

**Comment by lgirdwood** [comment]
> After installing the tool, it can be compiled, but the compilation of alsa-lib can be successful, but the compilation of alsa-utils fails and the log is as follows. Do you have any suggestions?@lgirdwood

Does installing gettext help ?

```sudo apt-get install gettext```

Also you will need to run ```./configure --disable-all-stuff-you-dont-need```

**Comment by hongshui3000** [comment]
The program installation can be completed, but it cannot run normally. The following libraries exist, but the display still cannot be found. Is the version of the library wrong?
```
$ alsatplg
alsatplg: /usr/lib/x86_64-linux-gnu/libasound.so.2: version `ALSA_1.2.6' not found (required by /usr/lib/libatopology.so.2)


:/usr/lib/x86_64-linux-gnu$ find libasound.so.2
libasound.so.2
```

**Comment by lgirdwood** [comment]
The runtime linker does not know where to find your new ALSA library (it may be installed in a different place for WSL). I would search your WSL filesystem for all copies of libasound.so and make sure your new version is getting copied to the correct place.

**Comment by hongshui3000** [comment]
yes it can work now. Thanks
