### ISSUE TITLE
[BUG] THD value is larger than acceptable in TestEqFirSimple

### ISSUE THREAD

**Issue by dkrzysiak** [thesofproject/sof#5841]
**Describe the bug**
THD value is larger than acceptable in TestEqFirSimple
Issue found in:
[ICL]
20_00_TestEqFirSimple8000Hz32b32b4ch

**Topology**
Description:
Test is performing simultaneous playback and capture on external SSP interface with recorded signal quality verification.
Playback pipeline contains FIR EQ component with basic configuration.
```

Topology:
+---------------------------------------------------+
| +------+   +-----+   +------+   +-----+   +-----+ |   +----+
| | Host |-->| Buf |-->|FIR EQ|-->| Buf |-->| Dai |---->|SSPx|
| +------+   +-----+   +------+   +-----+   +-----+ |   +----+
+---------------------------------------------------+    |  |
                                                         |  |
                                                         |  |
+-------------------------------+                        |  |
| +------+   +-----+    +-----+ |                       +----+
| | Host |<--| Buf |<---| Dai |<------------------------|SSPx|
| +------+   +-----+    +-----+ |                       +----+
+-------------------------------+

```

**To Reproduce**
Run tests with Diagnostic driver:
20_00_TestEqFirSimple8000Hz32b32b4ch Repro: 1/75
With options --playback-iterations=75

**Reproduction Rate**
1/75

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF BRANCH: main HASH: https://github.com/thesofproject/sof/commit/6c4f3ea42f0d04e9a421dd8325cdbc9be31056bf
2) Name of the platform(s) on which the bug is observed.
    * Platform: ICL RVP
3) Test environment:
   BRANCH: master HASH: 4c2b56f9d4e4519a5fe456ea2ef33f166ea6a45d

**Screenshots or console output**
01:54:18.354     => Topology Iteration 0, Playback Iteration 0
01:54:18.434       audio_verification.py:74, in log_result()
                    THD value is larger than acceptable value (-80.00) on channel 0: -9.16

01:54:18.434       audio_verification.py:74, in log_result()
                    THD value is larger than acceptable value (-80.00) on channel 1: -11.47

01:54:18.434       audio_verification.py:74, in log_result()
                    THD value is larger than acceptable value (-80.00) on channel 2: -10.85

01:54:18.439       audio_verification.py:74, in log_result()
                    THD value is larger than acceptable value (-80.00) on channel 3: -10.84

<img width="708" alt="audio_02" src="https://user-images.githubusercontent.com/105642643/169523704-ca6f1b5a-5ea2-413e-936d-4dbdc66963a2.PNG">
<img width="577" alt="audio_01" src="https://user-images.githubusercontent.com/105642643/169523716-b237c175-d51b-441f-804c-c4171be4e3b8.PNG">

[12_00_EqFir.zip](https://github.com/thesofproject/sof/files/8739923/12_00_EqFir.zip)

**Comment by lgirdwood** [comment]
@dkrzysiak do we know if these are pipeline glitches or processing quality issues ?

**Comment by dkrzysiak** [comment]
@lgirdwood I would bet on pipeline, repro was performed locally on pre-checked ICL. To my mind, machine error was excluded.

**Comment by antonirx** [comment]
unsupported platform
on TGL issue does not occur
Tested FW hash: 4943aaa
