### ISSUE TITLE
[BUG] SNR value is smaller than acceptable value in TestPtpPlaybackBitDepthConversion

### ISSUE THREAD

**Issue by dkrzysiak** [thesofproject/sof#5878]
**Describe the bug**
SNR value is smaller than acceptable value in TestPtpPlaybackBitDepthConversion
Issue found in:
[ICL]
02_13_TestPtpPlaybackBitDepthConversion8000Hz16b16b2ch

**Topology**
Description:
Simultaneous playback and capture on external loopback (same SSP) with signal verification.
Playback pipeline is setup that bit depth conversion is done on DAI component
(e.g.: if host component is set for bit depth 16/16b, DAI is converting to 24/32b on first topology iteration, and to 32/32b on second).

```
Topology:
pipe_plb
+-------------------------------+
| +------+   +------+   +-----+ |  +-----+
| | Host |-->|Buffer|-->| Dai |--->| SSP |
| +------+   +------+   +-----+ |  +-----+
+-------------------------------+    | |
                                     | |
pipe_cap                             | |
+-------------------------------+    | |
| +------+   +------+   +-----+ |  +-----+
| | Host |<--|Buffer|<--| Dai |<---| SSP |
| +------+   +------+   +-----+ |  +-----+
+-------------------------------+
```

**To Reproduce**
Run tests with Diagnostic driver:
02_13_TestPtpPlaybackBitDepthConversion8000Hz16b16b2ch 1/75
With options --playback-iterations=75

**Reproduction Rate**
1/75

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF BRANCH: main HASH: https://github.com/thesofproject/sof/commit/6c4f3ea42f0d04e9a421dd8325cdbc9be31056bf
2) Name of the platform(s) on which the bug is observed.
    * Platform: ICL
3) Test environment:
   BRANCH: master HASH: a145313efc604a967d057843d7c27c1aee7add7f

**Screenshots or console output**
<img width="727" alt="bug_1PNG" src="https://user-images.githubusercontent.com/105642643/171372676-0ababe5f-0395-48c9-b2c7-4d5f2637145c.PNG">

<img width="595" alt="bug_2" src="https://user-images.githubusercontent.com/105642643/171372687-b16a1304-23fe-4970-8879-7ea594b888d6.PNG">

[logs.zip](https://github.com/thesofproject/sof/files/8812872/logs.zip)

**Comment by wszypelt** [comment]
unsupported platform
on TGL issue does not occur
Tested FW hash: https://github.com/thesofproject/sof/commit/4943aaa8907149cf6c02e9046e2ef5d40ba72d74
