### ISSUE TITLE
[BUG] Playback file not found in captured file in TestMixerPlayback

### ISSUE THREAD

**Issue by dkrzysiak** [thesofproject/sof#5879]
**Describe the bug**
Playback file not found in captured file in TestMixerPlayback
Issue found in:
[ICL]
12_00_TestMixerPlayback16000Hz16b16b8ch

**Topology**
Description:
Mix 3 playback pipelines into one using Mixer component, loopback signal on external SSP connection, record signal on record pipeline with audio verification.

```
Topology:
+--------------------------------------------------+
| +------+   +-----+   +-----+   +-----+   +-----+ |   +----+
| | Host |-->| Buf |-->| Mix |-->| Buf |-->| Dai |---->|SSPx|
| +------+   +-----+   +-----+   +-----+   +-----+ |   +----+
+-------------------------^------------------------+    |  |
           ...            |                             |  |
           ...            |                             |  |
+--------------------+    |                             |  |
| +------+   +-----+ |    |                             |  |
| | Host |-->| Buf |------+                             |  |
| +------+   +-----+ |                                  |  |
+--------------------+                                  |  |
                                                        |  |
+----------------------------------------+              |  |
| +------+   +-----+             +-----+ |             +----+
| | Host |<--| Buf |<------------| Dai |<--------------|SSPx|
| +------+   +-----+             +-----+ |             +----+
+----------------------------------------+
```

**To Reproduce**
Run tests with Diagnostic driver:
12_00_TestMixerPlayback16000Hz16b16b8ch 1/75
With options --playback-iterations=75

**Reproduction Rate**
1/75

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF BRANCH: main HASH: https://github.com/thesofproject/sof/commit/6c4f3ea42f0d04e9a421dd8325cdbc9be31056bf
2) Name of the platform(s) on which the bug is observed.
    * Platform: ICL
3) Test environment:
   BRANCH: master HASH: a145313efc604a967d057843d7c27c1aee7add7f

**Screenshots or console output**

<img width="732" alt="bug_12_00" src="https://user-images.githubusercontent.com/105642643/171429198-418da8f3-db56-4aa6-af34-4a7f28e29592.PNG">

[logs.zip](https://github.com/thesofproject/sof/files/8815093/logs.zip)

**Comment by antonirx** [comment]
unsupported platform
on TGL issue does not occur
Tested FW hash: 4943aaa
