### ISSUE TITLE
[BUG] SNR value is smaller than acceptable value in TestPtpVolumeLoopback

### ISSUE THREAD

**Issue by dkrzysiak** [thesofproject/sof#5922]
**Describe the bug**
SNR value is smaller than acceptable value in TestPtpVolumeLoopback
Issue found in:
[WHL]
02_03_TestPtpVolumeLoopback48000Hz24b32b8ch

**Topology**
Description:
Simultaneous playback and capture on external loopback (same SSP) with signal verification.
Playback pipeline contains volume component.

```
Topology:
           +--------------------------------+
    +----+ | +---+  +---+  +---+  +-------+ |
    |Host|-->|Buf|->|Vol|->|Buf|->|SSP Dai|---+
    +----+ | +---+  +---+  +---+  +-------+ | |
           +--------------------------------+ |
                                              |
           +------------------+               |
    +----+ | +---+  +-------+ |               |
    |Host|<--|Buf|<-|SSP Dai|<----------------+
    +----+ | +---+  +-------+ |
           +------------------+

```

**To Reproduce**
02_03_TestPtpVolumeLoopback48000Hz24b32b8ch 1/50

**Reproduction Rate**
1/50

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * SOF BRANCH: main HASH: https://github.com/thesofproject/sof/commit/6c4f3ea42f0d04e9a421dd8325cdbc9be31056bf
2) Name of the platform(s) on which the bug is observed.
    * Platform: WHL
3) Test environment:
   BRANCH: master HASH: b4886bebbe49454850d59f1a49a0460e590db71c

**Screenshots or console output**
<img width="732" alt="Przechwytywanie" src="https://user-images.githubusercontent.com/105642643/173785436-ae566c66-6793-4d42-b83d-194ced4fc249.PNG">

[logs.zip](https://github.com/thesofproject/sof/files/8907576/logs.zip)

**Comment by lgirdwood** [comment]
@singalsu looks at first glance like the gain sign could be flipping ? but I dont see how this could be per sample, possibly DMA/SSP ?

**Comment by singalsu** [comment]
@dkrzysiak Is there by chance a similar test without volume. Does it pass always?

**Comment by lgirdwood** [comment]
@dkrzysiak btw, is this with Zephyr or xtos ?

**Comment by dkrzysiak** [comment]
@singalsu there isn't. Volume has a specific topology, where SSP Dai is part of pipe_plb. 
@lgirdwood xtos

**Comment by wszypelt** [comment]
unsupported platform
on TGL issue does not occur
Tested FW hash: 4943aaa8907149cf6c02e9046e2ef5d40ba72d74
