### ISSUE TITLE
[BUG][Zephyr] performance lower with PCM0/mixer pipe of sof-cavs-nocodec

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#5930]
**Describe the bug**
Performance between Zephyr and XTOS builds is on par with PCM2 pipeline with sof-cavs-nocodec, but with the same FW versions (SOF/Zephyr), on same hardware, the PCM0/PCM3 pipelines that include a mixer, show significantly slower pipeline execution.

Issue can be seen with SOF2.0 and SOF2.1 releases, so this is not a recent regression.

**To Reproduce**
aplay -vv -i -Dplughw:0,2 -fcd -traw /dev/zero

**Reproduction Rate**
100%

**Expected behavior**
Performance in Zephyr build is on par with XTOS build.

**Impact**
Increased power consumption, limitation of how many algorithms can fit.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: f7d6f01d0d16e84e
    * SOF: 1083bc2a39fbfcf4056ece5983ff00532e370179
    * Zephyr: 416dd6cd369786dad096522715d16eb8712b2f68
2) Name of the topology file
    * Topology: sof-tgl-nocodec.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: TGL/cAVS2.5

**Screenshots or console output**

XTOS build
```
[     9363124.401042] (      149026.609375) c2 ll-schedule        ./schedule/ll_schedule.c:186  INFO task 0xbe1e0400 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3> avg 1067, max 1090
[     9363189.973958] (          65.572914) c2 ll-schedule        ./schedule/ll_schedule.c:186  INFO task 0xbe1e0480 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3> avg 2082, max 2122
[    10387124.401042] (      149026.515625) c2 ll-schedule        ./schedule/ll_schedule.c:186  INFO task 0xbe1e0400 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3> avg 1071, max 1096
[    10387190.182292] (          65.781250) c2 ll-schedule        ./schedule/ll_schedule.c:186  INFO task 0xbe1e0480 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3> avg 2080, max 2127
```

Zephyr build
```
[    14849690.104167] (      345592.250000) c2 zll-schedule       src/schedule/zephyr_ll.c:144  INFO ll task 0xbe087b00 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3> avg 1700, max 2928
[    14849790.416667] (         100.312500) c2 zll-schedule       src/schedule/zephyr_ll.c:144  INFO ll task 0xbe087c80 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3> avg 3309, max 4639
[    15886629.296875] (      345430.468750) c2 zll-schedule       src/schedule/zephyr_ll.c:144  INFO ll task 0xbe087b00 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3> avg 1694, max 2456
[    15886729.921875] (         100.625000) c2 zll-schedule       src/schedule/zephyr_ll.c:144  INFO ll task 0xbe087c80 pipe-task <f11818eb-e92e-4082-82a3-dc54c604ebb3> avg 3326, max 4609
```

**Comment by kv2019i** [comment]
V2.5 branching this week and nobody assigned, so moving to v2.6.

**Comment by lgirdwood** [comment]
@andrula-song @singalsu @kv2019i @btian1 still seeing this performance as above ? if not can we close ?

**Comment by kv2019i** [comment]
We no longer have XTOS support in SOF main for Intel targets, so this issue is now invalid. We need to track performance via other means. Closing this one.
