### ISSUE TITLE
[FEATURE] Update branch protection rules for `mt8195/*`

### ISSUE THREAD

**Issue by afq984** [thesofproject/sof#5945]
Please help with updating the branch protection rules for `mt8195/*`:

1. Change the pattern from `mt8195/*` to one of:
    1.  `mt????/v0.*`
    1.  `mt[0-9][0-9][0-9][0-9]/v0.*`
1. Owners: Change to @thesofproject/google + @thesofproject/mediatek

**Comment by lgirdwood** [comment]
@afq984 sorry for the delay, COVID finally caught me last week. I've used option i. Please try.

**Comment by afq984** [comment]
Thanks, it works:
`mt8186/v0.1` is now protected, can `push`, and can't `push --force`
