### ISSUE TITLE
[BUG] [XTOS/Zephyr] IPC4: any pipeline with GAIN module is broken

### ISSUE THREAD

**Issue by ujfalusi** [thesofproject/sof#5986]
**Describe the bug**
Any IPC4 pipeline involving a GAIN (or Volume) module does not work, as of now causing a firmware crash with NULL pointer dereference

**To Reproduce**
Use IPC4 SOF firmware (XTOS or Zephyr) with a topology containing GAIN module, like cavs-mixin-mixout-hda.tplg (TGLU_UP_HDA)
`aplay -Dplughw:0,0 <wav file> -v`

**Reproduction Rate**
10/10

**Expected behavior**
Firmware does not crash, audio works as with pipelines w/o GAIN module

**Impact**
GAIN/Volume is not usable at all.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: HEAD
    * SOF: HEAD
2) Name of the topology file
    * Topology: cavs-mixin-mixout-hda.tplg (copied as sof-hda-generic.tplg)
3) Name of the platform(s) on which the bug is observed.
    * Platform: TGL (upx-i11)

**Screenshots or console output**
1. NULL point dereference:
https://github.com/thesofproject/sof/blob/4b4b752a149bd7b25c846d4117f58e5ce64bc275/src/audio/module_adapter/module/volume/volume.c#L571
vol is referenced at
https://github.com/thesofproject/sof/blob/4b4b752a149bd7b25c846d4117f58e5ce64bc275/src/audio/module_adapter/module/volume/volume.c#L541
and `cfg->data` is _never_ allocated in case of IPC4.

2. obs of gain module is not initialized, causing allocation error due to bogus size when trying to connect components:
```
[12206.957286] snd_sof:sof_ipc4_route_setup: sof-audio-pci-intel-tgl 0000:00:1f.3: bind gain.1.1 -> mixin.1.1
[12206.957302] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx      : 0x45000006|0x2: MOD_BIND
[12206.957453] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: 0x65000003|0x2: MOD_BIND
[12206.957457] sof-audio-pci-intel-tgl 0000:00:1f.3: FW reported error: 3 - Not enough space in the IPC reply buffer to complete the request
[12206.957848] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc error for msg 0x45000006|0x2
[12206.957853] sof-audio-pci-intel-tgl 0000:00:1f.3: sof_ipc4_route_setup: failed to bind modules gain.1.1 -> mixin.1.1
```
and
```
[00:00:01.679,000] <err> ipc: ipc_comp_connect() connecting src 60000, or dst 20000
[00:00:01.679,000] <err> ipc: ipc4_create_buffer() buf_size 2081245312
[00:00:01.679,000] <inf> ipc: buffer new size 0x7c0d4880 id 1.0 flags 0x0
[00:00:01.679,000] <err> buffer: buffer_alloc(): could not alloc size = 2081245312 bytes of type = 0
[00:00:01.679,000] <err> ipc: failed to allocate buffer to bind 393216 to 131072
[00:00:01.679,000] <err> ipc: ipc4: 1 failed err 3
```
Even working around these, the pipeline will fail to start with another firmware crash.

**Comment by ujfalusi** [comment]
fwiw, the `0x7c0d4880` is a curious number for a buffer size on a gain module...

**Comment by aiChaoSONG** [comment]
@ranj063 FYI

**Comment by ujfalusi** [comment]
fyi, @lgirdwood, @plbossart

**Comment by ranj063** [comment]
@ujfalusi I think this is expected. The gain module conversion to use module API with IPC4 was likely not tested.

**Comment by ujfalusi** [comment]
@ranj063, if it is expected then the GAIN should not be part of any (IPC4) topology as it is not working?

**Comment by RanderWang** [comment]
I may get some hint. We should copy spec to module->private_data but now we copy spec data to dst->data which is at some offset of module->private_data since adapter is built for processing. https://github.com/thesofproject/sof/blob/main/src/audio/module_adapter/module/generic.c#L56

**Comment by ranj063** [comment]
@RanderWang @ujfalusi I figured out why you're seeing the failure with the gaim module with the module interface. It is because of this line while creating buffers during module binding:
https://github.com/thesofproject/sof/blob/4b4b752a149bd7b25c846d4117f58e5ce64bc275/src/ipc/ipc4/helper.c#L243

Fundamentally, this is wrong. We should never access the individual component's private data outside of the module itself. You are accessing the OBS from the module's drv data in the IPC helper code. This needs to be fixed

**Comment by ranj063** [comment]
@ujfalusi please check if https://github.com/thesofproject/sof/pull/5994 fixes the issue for you

**Comment by RanderWang** [comment]
> 

As you know all the modules inherites from base_module_config in C++, so we can use the first base module cfg

**Comment by ujfalusi** [comment]
> > @RanderWang, fyi: #5987 will fix the NULL pointer dereference, but still the GAIN will break any pipeline later on.
> 
> [0001-module_adapter-Add-support-for-IPC4-in-module_adapte.txt](https://github.com/thesofproject/sof/files/9057833/0001-module_adapter-Add-support-for-IPC4-in-module_adapte.txt) @RanderWang @ujfalusi could you please try if this patch helps?

The firmware crash is fixed by this patch.

**Comment by ujfalusi** [comment]
This is now fixed, closing.
