### ISSUE TITLE
[BUG] ipc tx error for 0x60010000 when testing playback on APL_UP2_PCM512X

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#6003]
**Describe the bug**
Playback failed on PCM 0,0  with  ipc tx error for 0x60010000.
This is a sof regression with 100% reproduction rate. So far we only observe this issue on APL_UP2_PCM512X only.
The bisect shows that this issue is caused by:
https://github.com/thesofproject/sof/commit/95f6f88be705858a61915e07e22cedb7d739018e

**To Reproduce**
aplay   -Dhw:0,0 -r 48000 -c 2 -f S16_LE -d 3 /dev/zero -v -q

**Reproduction Rate**
100%

![image](https://user-images.githubusercontent.com/22468760/178626954-1a13dee9-8360-45f6-afba-4f1a6155dbb8.png)

**Environment**
Kernel Commit: 
[fd7e21ca645a](https://github.com/thesofproject/linux/commit/fd7e21ca645a)
SOF Commit: 
[4be016befc75](https://github.com/thesofproject/sof/commit/4be016befc75)

**Screenshots or console output**
```
aplay   -Dhw:0,0 -r 48000 -c 2 -f S16_LE -d 3 /dev/zero -v -q
aplay: set_params:1432: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 48000
PERIOD_TIME: (85333 85334)
PERIOD_SIZE: 4096
PERIOD_BYTES: 16384
PERIODS: 4
BUFFER_TIME: (341333 341334)
BUFFER_SIZE: 16384
BUFFER_BYTES: 65536
TICK_TIME: 0
```

**dmesg**
```
[  200.693865] kernel: snd_sof_intel_hda_common:hda_dsp_stream_hw_params: sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x160]=0x40000 successful
[  200.693881] kernel: snd_sof_intel_hda_common:hda_dsp_stream_hw_params: sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x160]=0x40000 successful
[  200.693886] kernel: snd_sof_intel_hda_common:hda_dsp_stream_setup_bdl: sof-audio-pci-intel-apl 0000:00:0e.0: period_bytes:0x4000
[  200.693888] kernel: snd_sof_intel_hda_common:hda_dsp_stream_setup_bdl: sof-audio-pci-intel-apl 0000:00:0e.0: periods:4
[  200.693926] kernel: snd_sof:sof_ipc3_pcm_hw_params: sof-audio-pci-intel-apl 0000:00:0e.0: stream_tag 1
[  200.693933] kernel: snd_sof:ipc3_log_header: sof-audio-pci-intel-apl 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  200.693997] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: ipc tx error for 0x60010000 (msg/reply size: 108/20): -22
[  200.694001] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: HW params ipc failed for stream 1
[  200.694004] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: ASoC: error at snd_soc_pcm_component_hw_params on 0000:00:0e.0: -22
[  200.694010] kernel:  Port5: ASoC: __soc_pcm_hw_params() failed (-22)
[  200.695132] kernel: snd_sof:ipc3_log_header: sof-audio-pci-intel-apl 0000:00:0e.0: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  200.695711] kernel:  Port5: ASoC: dpcm_fe_dai_hw_params failed (-22)
[  200.695732] kernel: snd_sof:sof_pcm_hw_free: sof-audio-pci-intel-apl 0000:00:0e.0: pcm: free stream 0 dir 0
[  200.698144] kernel: snd_sof:sof_pcm_close: sof-audio-pci-intel-apl 0000:00:0e.0: pcm: close stream 0 dir 0
```

[dmesg.txt](https://github.com/thesofproject/sof/files/9098013/dmesg.txt)
[logger.txt](https://github.com/thesofproject/sof/files/9098014/logger.txt)

**Comment by softwarecki** [comment]
@keqiaozhang Please check this patch https://github.com/softwarecki/sof/commit/c204bfd7ce02d14ad17b18b8175ee085e7f4e21e

**Comment by marc-hb** [comment]
@softwarecki how about submitting your tentative fix as a draft PR? It looks like a fix, not like a debug patch... 

I don't think PR testing includes the configuration that was regressed (otherwise it would have been caught in the first place...) but testing on other hardware configurations never hurts.

**Comment by keqiaozhang** [comment]
> @keqiaozhang Please check this patch [softwarecki@c204bfd](https://github.com/softwarecki/sof/commit/c204bfd7ce02d14ad17b18b8175ee085e7f4e21e)

Confirmed that the patch can fix the issue.
