### ISSUE TITLE
Append toolchain version next to SOF version in dmesg

### ISSUE THREAD

**Issue by dbaluta** [thesofproject/sof#6017]
**Is your feature request related to a problem? Please describe.**
Users need a way to find out which toolchain was used to compile the firmware. For the moment there is no way (as i know) to dynamically determine this at runtime.

**Describe the solution you'd like**

We need to find a way to append toolchain version, to be displayed in this message:

[   13.923997] sof-audio-of-imx8m 3b6e8000.dsp: Firmware info: version 2:1:0-7ca3a

**Comment by lgirdwood** [comment]
@dbaluta I think we have this already, but it may be behind a Kconfig for reproducible builds. Can you check ?

**Comment by dbaluta** [comment]
@lgirdwood indeed we have this in /work/repos/sof/CMakeLists.txt:77

```
# get compiler name and version
execute_process(
»       COMMAND ${CMAKE_C_COMPILER} --version
»       OUTPUT_VARIABLE cc_version_output
»       OUTPUT_STRIP_TRAILING_WHITESPACE
»       ERROR_QUIET
)
```

I need to find a way to enable it on Zephyr. It works without zephyr for now.
