### ISSUE TITLE
[BUG] alsatplg: Support SSP direction for each DAI

### ISSUE THREAD

**Issue by yongzhi1** [thesofproject/sof#6087]
**Describe the bug**
SSP DAI direction based on individual dai_index is not supported:
https://github.com/alsa-project/alsa-utils/blob/master/topology/nhlt/intel/ssp/ssp-process.c#L531

**To Reproduce**
Sample changes https://github.com/yongzhi1/sof/tree/test-ssp1-playback.

Build above topology and check loopback capture on SSP0.

**Reproduction Rate** 100%

**Expected behavior**
We should be able to config SSP direction for each DAI.

**Comment by juimonen** [comment]
@yongzhi1 could you try out:
https://github.com/juimonen/alsa-utils/tree/dai_index_fix

thanks!

**Comment by yongzhi1** [comment]
Hi, thank you @juimonen for the quick fix, it works as expected now!!

**Comment by yongzhi1** [comment]
Hi, @juimonen can you push https://github.com/juimonen/alsa-utils/tree/dai_index_fix for merging? thanks!!

**Comment by juimonen** [comment]
@yongzhi1  https://github.com/alsa-project/alsa-utils/pull/164, has been there for a while...
