### ISSUE TITLE
[BUG] microphone not detected and not working on 2022 Razer Blade 14

### ISSUE THREAD

**Issue by turowicz** [thesofproject/sof#6116]
**Describe the bug**
I've installed Ubuntu 22.04 on a 2022 Razer Blade 14. Audio playback appears to be working, but the built in microphone, is not being detected, doesn't seem to be recording any sound. I am also not able to detect a connected BT speaker with a mic (Jabra).

![image](https://user-images.githubusercontent.com/1055391/183909163-62c805c7-4d36-4bdd-ac19-f6f0845cd85a.png)

**To Reproduce**
Clean install of Ubuntu 22.04. I have updated the kernel to 5.19.0 and applied ath11k patches to get wifi support.

**Reproduction Rate**
100%

**Expected behavior**
I expect the microphone to be detected and to record when enabled.

**Impact**
I can't use the built in microphone for video conferencing. I have tried bluetooth microphones with no luck.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: `5.19.0-051900-generic`
    * SOF: `firmware-sof-signed/jammy-updates,jammy-updates,now 2.0-1ubuntu3 all [installed,automatic]`
2) Name of the topology file
    * Topology: I'm not sure how to determine this.
3) Name of the platform(s) on which the bug is observed.
    * Platform: x86_64

**Screenshots or console output**
dmesg: [dmesg.zip](https://github.com/thesofproject/sof/files/9300310/dmesg.zip)

**Comment by plbossart** [comment]
@turowicz an you please attach the result of 'alsa-info', it's not clear that you are even using the SOF driver?

**Comment by turowicz** [comment]
http://alsa-project.org/db/?f=c857e693b115cecaa37910551102054d8c9e1c8c

**Comment by plbossart** [comment]
That's an AMD device, that will be for the AMD folks to comment on. I have no idea if this platform is supposed to be handled by SOF.

**Comment by turowicz** [comment]
I came here from there: https://github.com/thesofproject/sof/issues/5989

**Comment by lgirdwood** [comment]
@thesofproject/amd fyi.

**Comment by flyingfalling** [comment]
I have an identical issue (identical laptop). I don't see SOF stuff being loaded at all (which may be the issue?), but the similar laptop (razer blade 15 2022) problem was solved by a change in topology file, and so we were hoping such a simple fix was available for the 14-inch version as well. I was directed here by: https://www.linuxquestions.org/questions/linux-hardware-18/audio-issues-with-razer-blade-15-2022-a-4175708817/page2.html which referenced the solution of SOF project members for the 15-inch model in https://github.com/thesofproject/sof/issues/5989

The difference is of course that the 14-inch uses that AMD ryzen 6000 processor, whereas the 15-inch uses the 12-gen intel one.

I am attaching alsa info (although it is largely identical to the poster above):
http://alsa-project.org/db/?f=896e5ae8fbb2855d67023d2beb9469da52d782bc

You mentioned that the part is AMD card...but your referenced AMD team here @thesofproject/amd does not seem to exist?

**Comment by lgirdwood** [comment]
> You mentioned that the part is AMD card...but your referenced AMD team here @thesofproject/amd does not seem to exist?

@balakishorepati fyi

**Comment by pramodhrachuri** [comment]
any update on this?

**Comment by turowicz** [comment]
I just installed kernel 6.2 and problem disappeared
