### ISSUE TITLE
[BUG][IPC4] ipc timed out for 0x13020004|0x0 GLB_SET_PIPELINE_STATE on TGLU_UP_HDA_IPC4ZPH

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#6118]
**Describe the bug**
This issue happens when testing playback on TGLU_UP_HDA with IPC4 SOF Zephyr configuration. 
The IPC error is:
```
[  133.679307] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc timed out for 0x46010006|0x10004
[  133.679309] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: failed to unbind modules gain.3.1 -> copier.host.3.1
[  133.679312] kernel: snd_sof:sof_widget_free: sof-audio-pci-intel-tgl 0000:00:1f.3: widget gain.3.1 freed
[  133.679316] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx      : 0x12030000|0x0: GLB_DELETE_PIPELINE
[  134.183367] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc timed out for 0x12030000|0x0
[  134.183372] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: failed to free pipeline widget pipeline.3
[  134.183378] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Failed to free connected widgets
[  134.183388] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_hw_free on 0000:00:1f.3: -110
```
It seem that this issue only happens with HDA mode. we didn't observer this issue with SDW or I2S mode.

**To Reproduce**
TPLG=/lib/firmware/intel/avs-tplg/cavs-mixin-mixout-hda.tplg MODEL=TGLU_UP_HDA_IPC4ZPH ~/sof-test/test-case/check-playback.sh -d 10 -l 1 -r 1

**Reproduction Rate**
100%

** TPLG **
![image](https://user-images.githubusercontent.com/22468760/183919410-f7022f32-4c75-4b55-bbfa-d2d8578bb649.png)

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: sof-dev/[67fc9186384f](https://github.com/thesofproject/linux/commit/67fc9186384f)
    * SOF: main/[a10e118a4d25](https://github.com/thesofproject/sof/commit/a10e118a4d25)
    * Zephyr:[8e55e59c5917](https://github.com/zephyrproject-rtos/zephyr/commit/zephyr-v3.1.0-3042-g8e55e59c5917)
2) Name of the topology file
    * Topology:cavs-mixin-mixout-hda.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: TGLU_UP_HDA_IPC4ZPH

[dmesg.txt](https://github.com/thesofproject/sof/files/9300633/dmesg.txt)

**Comment by keqiaozhang** [comment]
This issue is still reproducible on TGLU_UP_HDA_IPC4ZPH.
Please refer to inner test: http://sof-ci.sh.intel.com/#/result/planresultdetail/14754?model=TGLU_UP_HDA_IPC4ZPH&testcase=check-capture-all-formats

**Comment by lyakh** [comment]
> This issue is still reproducible on TGLU_UP_HDA_IPC4ZPH. Please refer to inner test: http://sof-ci.sh.intel.com/#/result/planresultdetail/14754?model=TGLU_UP_HDA_IPC4ZPH&testcase=check-capture-all-formats

@keqiaozhang correct me if I'm wrong, but the original bug description was for playback, whereas this bug, that you linked here, seems to be for capture? It *can* well be the same kind prob

**Comment by keqiaozhang** [comment]
I have filed a new one to track the capture issue:https://github.com/thesofproject/sof/issues/6203

**Comment by keqiaozhang** [comment]
> but the original bug description was for playback, whereas this bug, that you linked here, seems to be for capture?

I have filed a new one to track the capture issue:https://github.com/thesofproject/sof/issues/6203
