### ISSUE TITLE
[BUG] script xtensa-build-zephyr.py fails on Windows

### ISSUE THREAD

**Issue by aborisovich** [thesofproject/sof#6122]
Script xtensa-build-zephyr.py fails its execution on Windows system.
It looks like west_root_dir variable value returned by west tool has postfix of "/r" (carriage return) character (where on linux os it is a "\n" (newline character).
![image](https://user-images.githubusercontent.com/12482515/184036982-c39fbd55-2802-47bd-9a2f-89bd9266472a.png)

**To Reproduce**
Execute command `./sof/scripts/xtensa-build-zephyr.py tgl`

**Reproduction Rate**
100%

**Expected behavior**
Script `./scripts/xtensa-build-zephyr.py` works on Windows OS without errors.

**Impact**
Annoyance - we still can build using west tool directly according to [Build with Zephyr](https://thesofproject.github.io/latest/getting_started/build-guide/build-with-zephyr.html) guide.

**Environment**
1) Branch name and commit hash:
    * SOF: main
2) Operating system:
    * Windows
3) Name of the platform(s) on which the bug is observed.
    * Platform: all

Bug introduced by commit 608833cf27afd0c327e97929f8c0222064c4ee71 .

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/12482515/184035074-0201b335-0058-4b0a-b53a-7ff1374a42ef.png)

**Comment by lgirdwood** [comment]
> It looks like west_root_dir variable value returned by west tool has postfix of "/r" (carriage return) character (where on linux os it is a "\n" (newline character). ![image](https://user-images.githubusercontent.com/12482515/184036982-c39fbd55-2802-47bd-9a2f-89bd9266472a.png)

@aborisovich do we need an ```if (WIN32)``` here in the script do use ```\r```?

**Comment by aborisovich** [comment]
Well yeah but in bug resolution I just stripped down all trailing whitespaces.
Basically on linux OS west command `west topdir` returns eg.:
_/home/root/projects/sof_workspace/sof\n_
And on Windows OS west topdir returns eg.:
_C:\workspace\sof_workspace\sof/r_
(note trailing visible whitespaces).
So I just removed them all.
