### ISSUE TITLE
[BUG][TPLG] IPC4 topology2 fails to build

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#6321]
**Describe the bug**
This issue is caused by the change in `tools/topology/topology2/CMakeLists.txt`. 
- https://github.com/thesofproject/sof/pull/6284#issuecomment-1254527710

Commit ID: https://github.com/thesofproject/sof/commit/784bce763c0e2951746b62ade1e521c1f1ebd3ed.
![image](https://user-images.githubusercontent.com/22468760/191642326-3c1e1cdc-cee0-4c75-bfe9-bdf7580a9910.png)

It seems that `CONFIG_CAVS` and `CONFIG_ACE` flags are not set, then cavs/ace subdirectories can not be created.

**To Reproduce**
`./scripts/build-tools.sh -T`

**Comment by mengdonglin** [comment]
@softwarecki @mwasko Can you help on this issue?

@plbossart @ranj063 FYI. Topology binaries for ACE and cAVS platforms are going to be splitted.

**Comment by marc-hb** [comment]
Fix: `git show 784bce763c0e -- tools/ | git apply -R`

**Comment by ujfalusi** [comment]
Submitted a fix: https://github.com/thesofproject/sof/pull/6325

**Comment by ujfalusi** [comment]
> @softwarecki @mwasko Can you help on this issue?
> 
> @plbossart @ranj063 FYI. Topology binaries for ACE and cAVS platforms are going to be splitted.

It does not mean that the splitting _must_ break existing builds.
Looks to me that 784bce763c0e2951746b62ade1e521c1f1ebd3ed has not even compile tested (for topologies at least) and I do wonder why CI let that patch slip through. I know that we only test IPC3/topology1 in CI, but the build system should have complained at least to block it.

It is one thing to have separate topology2 files for CAVS/ACE, but I don't really see the reason why they have to be exclusive.

**Comment by keqiaozhang** [comment]
Fixed by [PR#6325](https://github.com/thesofproject/sof/pull/6325)
