### ISSUE TITLE
[BUG][CHROME] DSP Panic in MultiCore group tests

### ISSUE THREAD

**Issue by antonirx** [thesofproject/sof#6372]
**Describe the bug**
Tests affected:
17_01_TestMultiCoreMultiKernelSsp24000Hz24b32b8ch
17_06_TestMultiCoreCompSrcPlb48000Hz32b32b8ch
17_08_TestMulticoreKdCore1PlaybackD0ix16000Hz16b16b
17_09_TestMulticoreKdWithResetCore0PlaybackD0ixCoreSwitch16000Hz24b32b
**Topology**
```                   pipe_plb core 0
                    +--------------------+
    +----------+    | +------+   +-----+ |   +----+
    | Host plb |----->|Buffer|-->| Dai |---->|SSP0|
    +----------+    | +------+   +-----+ |   +----+
                    +--------------------+    |  |
                                              |  |
                    pipe_cap core 1           |  |
                    +--------------------+    |  |
    +----------+    | +------+   +-----+ |   +----+
    | Host cap |<-----|Buffer|<--| Dai |---->|SSP0|
    +----------+    | +------+   +-----+ |   +----+
                    +--------------------+
```
**To Reproduce**
Run test with Diagnostic driver:
17_06_TestMultiCoreCompSrcPlb48000Hz32b32b8ch

**Reproduction Rate**
100%

**Environment**
    SOF: BRANCH: main
    PLATFORM: TGL
    BUILD: CHROME 5694cfa01234dee8f9e8f311f27cf7a6bf2f9454

**Screenshots or console output**
![image](https://user-images.githubusercontent.com/100357478/194006390-9e9cb696-3a73-44c5-b160-d03546ef4e18.png)
![image](https://user-images.githubusercontent.com/100357478/194006444-565fa039-4353-405c-ab40-b6ccfefd6c89.png)

**Logs**
[17_9_DSP_PANIC_TESTS.zip](https://github.com/thesofproject/sof/files/9713849/17_9_DSP_PANIC_TESTS.zip)

**Comment by lgirdwood** [comment]
@antonirx can this be duplicated with IPC4 pipeline and Zephyr RTOS ?

**Comment by antonirx** [comment]
At the moment we have no scenarios for multicore and I2S, we can create them if needed for this bug.

**Comment by antonirx** [comment]
Reproduced on TGL:
c807d6844b535ff4ad90ac6429a2fef46f398cb4
new failures:
17_00_TestMultiCoreSameKernelSsp16000Hz32b32b4ch
17_05_TestMultiCoreCompVolCap8000Hz16b16b1ch
17_05_TestMultiCoreCompVolCap48000Hz32b32b8ch
17_07_TestMultiCoreSrcCap8000Hz16b16b1ch
17_07_TestMultiCoreSrcCap16000Hz24b32b1ch
22_05_TestDsmMulticoreSsp48000Hz24b32b2ch

**Comment by lgirdwood** [comment]
> At the moment we have no scenarios for multicore and I2S, we can create them if needed for this bug.

Yes please, we need to create these for IPC4/Zephyr config. @mwasko fyi.

**Comment by antonirx** [comment]
Not reproduced on TGL: 8bfcf59980b7302bc3621dc3b889ac279ad81ae4
