### ISSUE TITLE
cherry trail/ bay trail beeps when playing video for a while.

### ISSUE THREAD

**Issue by MRazor12** [thesofproject/sof#6384]
**Describe the bug**
When i play audio, it beeps for a short while or nonstop.

**To Reproduce**
Replay a video for a few minutes and the beeping will start again.

**Reproduction Rate**
5/5 times it happens again

**Expected behavior**
I expected it to play the video without any beeping.

**Impact**
The video that i want to watch stops playing when beeping

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {SHA}
    * SOF: {SHA}
2) Name of the topology file
    * Topology: {FILE}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {Linux kernel 6.0.0-1 openSUSE Tumbleweed}

**Comment by plbossart** [comment]
Known issue that will not be fixed. Work-around described in https://github.com/thesofproject/sof/issues/4662

sudo gedit /etc/modprobe.d/sof.conf

add options snd_sof sof_debug=1 to first line

close and reboot.
