### ISSUE TITLE
[BUG] Do not call get_llp_reg_info() at each dai_dma_position_update()

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#6424]
**Describe the bug**
See https://github.com/thesofproject/sof/pull/6421 and comment https://github.com/thesofproject/sof/pull/6421#issuecomment-1278770839

**Comment by lgirdwood** [comment]
@kv2019i can we close, looks like the PRs are merged.

**Comment by kv2019i** [comment]
Let's close when #6441 is merged.
