### ISSUE TITLE
[BUG] "No source info" in check-signal-stop-start-playback-50

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#6431]
**Describe the bug**
This is one specific issue we have been tracking as part of https://github.com/thesofproject/sof/issues/6220

Issues has been rootcaused to incorrect clearing of mixer module state in reset and identified by following log in FW log:

[    2.019000] <err> mixer: No source info
[    2.019000] <err> pipe: pipeline_copy(): ret = -22, start->comp.id = 262145, dir = 1
[    2.019000] <err> pipe: pipeline_task(): xrun recovery failed! pipeline is stopped.

**Reproduction Rate**
100%

**Expected behavior**
No error from firmware.

**Impact**
Showstopper

**Environment**
SOF main as tested in 17th Oct daily tests.

**Comment by kv2019i** [comment]
FYI @serhiy-katsyuba-intel

**Comment by serhiy-katsyuba-intel** [comment]
The PR has been submitted: https://github.com/thesofproject/sof/pull/6433

**Comment by lgirdwood** [comment]
@kv2019i can we close as PR merged ?

**Comment by kv2019i** [comment]
Yes, let's close.
