### ISSUE TITLE
[BUG][IPC4] FW reported error: 104 when testing simultaneous-playback-capture or multiple-pipeline on TGLU_RVP_SDW and TGLU_RVP_HDA 

### ISSUE THREAD

**Issue by miRoox** [thesofproject/sof#6460]
**Describe the bug**
CI (ID: 16575) observed the IPC error with "FW reported error: 104 - Other failure of module instance initialization request" when testing simultaneous-playback-capture or multiple-pipeline on TGLU_RVP_SDW and TGLU_RVP_HDA.

**To Reproduce**
```
TPLG=/lib/firmware/intel/avs-tplg/cavs-mixin-mixout-hda.tplg MODEL=TGLU_UP_HDA_IPC4ZPH ~/sof-test/test-case/simultaneous-playback-capture.sh -l 25
```
or
```
TPLG=/lib/firmware/intel/avs-tplg/cavs-sdw.tplg MODEL=TGLU_RVP_SDW_IPC4ZPH ~/sof-test/test-case/multiple-pipeline.sh -f c -l 50
```

**Reproduction Rate**
Nearly 100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: https://github.com/thesofproject/linux/commit/20a4b0774e58
    * SOF: https://github.com/thesofproject/sof/commit/73a413a38fc2
2) Name of the topology file
    * Topology: cavs-sdw.tplg (for SDW) or cavs-mixin-mixout-hda.tplg (for HDA)
3) Name of the platform(s) on which the bug is observed.
    * Platform: TGLU_RVP_SDW_IPC4ZPH, TGLU_UP_HDA_IPC4ZPH

**Screenshots or console output**

**dmesg**
```
[ 2349.605106] kernel: snd_sof:sof_ipc4_widget_setup: sof-audio-pci-intel-tgl 0000:00:1f.3: Create widget copier.host.3.1 instance 3 - pipe 3 - core 0
[ 2349.605108] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx      : 0x40030004|0x30015: MOD_INIT_INSTANCE [data size: 84]
[ 2349.605476] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: 0x60000068|0x30015: MOD_INIT_INSTANCE
[ 2349.605479] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW reported error: 104 - Other failure of module instance initialization request
[ 2349.605617] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc error for msg 0x40030004|0x30015
[ 2349.605621] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: failed to create module copier.host.3.1
[ 2349.605628] kernel: snd_sof:sof_widget_free: sof-audio-pci-intel-tgl 0000:00:1f.3: widget gain.3.1 freed
```

[full_dmesg-simultaneous-playback-capture.txt](https://github.com/thesofproject/sof/files/9835353/full_dmesg-simultaneous-playback-capture.txt)
[mtrace-simultaneous-playback-capture.txt](https://github.com/thesofproject/sof/files/9835354/mtrace-simultaneous-playback-capture.txt)

**Comment by keqiaozhang** [comment]
Closing this bug as it have been fixed.
