### ISSUE TITLE
[BUG] ipc timed out for 0x13000004|0x1 when playback on MTL platforms

### ISSUE THREAD

**Issue by miRoox** [thesofproject/sof#6516]
**Describe the bug**
playback at first time fails with ipc timed out for 0x13000004|0x1.

NOTE: On the main branch, the runtime power management is not ready, so we disabled runtime PM on our MTL DUTs with the kernel option `options snd-sof-pci sof_pci_debug=0x01`.

**To Reproduce**
```
aplay   -Dhw:0,0 -r 48000 -c 2 -f S16_LE -d 10 /dev/zero -v -q
```

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: topic/sof-dev | https://github.com/thesofproject/linux/commit/69c5960521f2
    * SOF: main | https://github.com/thesofproject/sof/commit/ef62a508930c
2) Name of the topology file
    * Topology: cavs-mtl-sdw-dmic.tplg, sof-mtl-nocodec.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: MTLP_RVP_SDW, MTLP_RVP_NOCODEC

**Screenshots or console output**

**dmesg**
```
[  228.323809] kernel: snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x13000004|0x1: GLB_SET_PIPELINE_STATE [data size: 12]
[  228.825380] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc timed out for 0x13000004|0x1
[  228.825480] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: preventing DSP entering D3 state to preserve context
[  228.825484] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump start ]------------
[  228.825515] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: Host IPC initiator: 0x93000004|0x1|0x0, target: 0x1b060000|0x0|0x0, ctl: 0x3
[  228.825541] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump end ]------------
[  228.825559] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump start ]------------
[  228.825584] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: IPC timeout
[  228.825597] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (6)
[  228.825621] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM status: 0x5, ROM error: 0x0
[  228.825638] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM debug status: 0x50000005, ROM debug error: 0x0
[  228.825660] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ROM feature bit enabled
[  228.825675] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump end ]------------
[  228.825694] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: failed to set final state 4 for all pipelines
[  228.825715] kernel: sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -110
[  228.825739] kernel:  Jack out: ASoC: trigger FE cmd: 1 failed: -110
```
[mtrace.txt](https://github.com/thesofproject/sof/files/9947773/mtrace.txt)

**Comment by keqiaozhang** [comment]
This issue disappeared after the Zephyr update. But let's keep it open for one more day, I will close it if it doesn't happen tomorrow.

**Comment by keqiaozhang** [comment]
This issue is not reproducible in CI, closing it.
