### ISSUE TITLE
Modify version tagging to make reproducible release builds

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof#653]
Ideally it would be nice if release builds were reproducible by local builders. Currently with the way version.sh is setup that is not possible because it includes a build number and timestamp in the header which cannot be reproduced by local builders. For dev builds this is fine but for a release builds it would be ideal to disable this or set it to fixed values so one could run a sha checksum comparison and get the same output.

**Comment by xiulipan** [comment]
@cujomalainey 
I think @ranj063 adn @lgirdwood had some patch to remove the timestamp and build number for the release build from https://github.com/thesofproject/sof/pull/524 and https://github.com/thesofproject/sof/pull/529
The default build now is release version that only contains the git commit hash.

Please check if it meet you requirement.

**Comment by cujomalainey** [comment]
@xiulipan thanks for the headsup, we should add that to the docs so everyone is aware of that when building releases

**Comment by xiulipan** [comment]
@cujomalainey 
I will close this issue and track with a sof-doc issue.
