### ISSUE TITLE
logger complains about abi mismatch

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof#662]
While trying to run the logger with the latest SOF master, I see the error: 
Error: abi version in sof-apl.ldc file does not coincide with abi version used by logger

**Comment by ranj063** [comment]
kernel branch: cros-sof-v4.14-rebase
topology: SOF master (sof-glk-da7219.m4)

**Comment by ranj063** [comment]
@lgirdwood yes I used SOF master for logger, topology and firmware. I will send the PR

**Comment by lgirdwood** [comment]
Thanks, btw ABI going through some changes to make all this go away with future ABI updates, hence the failures atm. Some more ABI PRs pending shortly.

**Comment by mengdonglin** [comment]
Need to monitor 
https://github.com/thesofproject/sof/pull/663
https://github.com/thesofproject/sof/pull/664
and further kernel update to fix this issue.

**Comment by stevyan** [comment]
**Summary:** 
Issue isn't seen both on the APL (pcm512x ) & BYT (rt5651):

**Test Env:**
sof master: b3692cd7
sof tool: b3692cd7
kernel sof-dev: d72b338b 
tplg: sof-apl-pcm512x.tplg-b3692cd7, sof-byt-rt5651-b3692cd7.tplg

**Comment by xiulipan** [comment]
@stevyan 
Are you sure about the test case?
I used the latest logger and still see the error. But some older logger have no such issues

```
sudo ./sof-logger -l sof-apl.ldc
Error: abi version in sof-apl.ldc file does not coincide with abi version used by logger.
```

**Comment by xiulipan** [comment]
@ranj063 
From you log, it seems we got some wrong ldc abi version.
`33554432 `is `0x2000000`, thus the SOF_ABI_VERSION_MAJOR is 2.

**Comment by xiulipan** [comment]
@stevyan @bkokoszx @akloniex 
Retest with build server binary, no error.
Confused about why the original bug happen.

**Comment by bkokoszx** [comment]
@ranj063 
Could you try to rebuild rimage, then SOF and afterwards try to reproduce issue?

**Comment by ranj063** [comment]
@bkokoszx yes this problem does go away after building rimage.
I just realized that BUILD_RIMAGE is set to 0 in the xtensa_build_all script. 
I thought we always build rimage before building the FW.

@xiulipan do you know why we changed this?

**Comment by xiulipan** [comment]
@ranj063 
That maybe some old code remaining. I was intend to have some args to set rimage build to speed up CI build and local build. That change is gone somehow, but the flag used for it is still in the scripts.
Let me have some fix for that.

**Comment by mengdonglin** [comment]
@xiulipan will rimage building be optional or based on the change of its dependencies?

**Comment by lgirdwood** [comment]
@ranj063 I hit this, but it's because the top level Makefile does not recurse into the tools directory to re-make the tools. You need to do this manually.

**Comment by ranj063** [comment]
@mengdonglin closing this as the issue is fixed by building rimage
