### ISSUE TITLE
"make dist" to release sof tarball

### ISSUE THREAD

**Issue by zhuyingjiang** [thesofproject/sof#670]
Make tarball release of SOF, using the version number getting from git tag. automatically  generate sof-x.y.tar.gz.

**Comment by jajanusz** [comment]
I can add tar packaing that follows kernel convention, so it will be something like `make tar-src-pkg`.
Only issue that it has comparing to autotools' `make dist` is that it has to be done in git repository (I guess it's nonissue at all). Other than that it's easier to develop, cos it's based on git-archive feature and easier to maintain, cos developers don't have to add anything to makefiles so `make dist` could track what to include in tar

**Comment by zhuyingjiang** [comment]
@jajanusz Good to know, let's follow kernel convention. And there is a problem with previous "make dist" is that it can't compile using the same compile steps in git after untar the tarball. Please note me when your solution is ready, I will double check and make it work with this.

**Comment by zhuyingjiang** [comment]
Close, this is move to #954, and solved in #951
