### ISSUE TITLE
[BUG][mtl-002] noise/playback drag issue observed with mtl-002-drop stable release

### ISSUE THREAD

**Issue by RDharageswari** [thesofproject/sof#6727]
mtl-002-drop stable release results in playback drag issue.

topology and firmware used from mtl-002-drop stable branch

**Comment by RDharageswari** [comment]
[topologyandloopbackfile.zip](https://github.com/thesofproject/sof/files/10163454/topologyandloopbackfile.zip)
This issue is observed with the nocodec topology as well. Please find attached the no_codec topology and the captured loopback file with noise

**Comment by jairaj-arava** [comment]
@sathya-nujella @yongzhi1 @udaymb

**Comment by lgirdwood** [comment]
@mwasko @marcinszkudlinski  fyi

**Comment by aborisovich** [comment]
Is it I2S or HDA configuration?
What tolopogy configuration is there?

**Comment by juimonen** [comment]
@aborisovich in the topology zip file there is nocodec tplg -> so I would assume I2S/SSP.

**Comment by RDharageswari** [comment]
driver, firmware logs and the captured loopback file
[fw_driver_logs_loopbackdatacaptured_issue.zip](https://github.com/thesofproject/sof/files/10198540/fw_driver_logs_loopbackdatacaptured_issue.zip)
[working_logs.zip](https://github.com/thesofproject/sof/files/10198541/working_logs.zip)

**Comment by mwasko** [comment]
> driver, firmware logs and the captured loopback file [fw_driver_logs_loopbackdatacaptured_issue.zip](https://github.com/thesofproject/sof/files/10198540/fw_driver_logs_loopbackdatacaptured_issue.zip) [working_logs.zip](https://github.com/thesofproject/sof/files/10198541/working_logs.zip)

@RDharageswari we are still missing  logs from the SW that include IPC payloads. This information is critical to reproduce the problem with a FW tests. @juimonen, @lgirdwood can someone from SW team can help here?

**Comment by lgirdwood** [comment]
@ranj063 @ujfalusi can someone provide the kernel option to dump all the IPC logs into dmesg. Thanks !

**Comment by ujfalusi** [comment]
`options snd_sof sof_debug=0x341` should print all dumps and log all messages (even DMA position updates - for dtrace BIT(8)) and their completion.
Or do we want to dump the messages itself? They will flood the kernel log pretty fast...

**Comment by ujfalusi** [comment]
Actually, if the kernel is configured with `DEBUG_VERBOSE` then the kernel sent message payload is printed out (normal and large messages as well).

**Comment by abonislawski** [comment]
This can be fixed with i2s master link clock selection. Confirmed today with Dhara.
For mtl-002 we can do quick fix with manual selection but for main branch a proper mechanism should be developed using driver config.

**Comment by mengdonglin** [comment]
Closing as being fixed.
