### ISSUE TITLE
[BUG][MTL]: Headset capture resuls in I/O error with mtl-002 firmware

### ISSUE THREAD

**Issue by RDharageswari** [thesofproject/sof#6818]
Headset capture results in I/O error.
Please find attached the driver and firmware logs.
This issue is with the https://github.com/thesofproject/sof/tree/mtl-002-drop-stable firmware
[boot_rc15.txt](https://github.com/thesofproject/sof/files/10242723/boot_rc15.txt)
[fw_error_rc15.txt](https://github.com/thesofproject/sof/files/10242724/fw_error_rc15.txt)
[kernellog_rc15.txt](https://github.com/thesofproject/sof/files/10242725/kernellog_rc15.txt)

localhost ~ # arecord -Dhw:0,0 hp_cap.wav -c2 -r48000 -fs24_le -d15 -vv
Recording WAVE 'hp_cap.wav' : Signed 24 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-rt5682' device 0 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S24_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 32
  buffer_size  : 8192
  period_size  : 2048
  period_time  : 42666
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 2048
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 8192
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904
  appl_ptr     : 0
  hw_ptr       : 0
#+                                                 | 00%arecord: pcm_read:2161:                                                                              read error: Input/output error

**Comment by RDharageswari** [comment]
@abonislawski @mengdonglin @sathya-nujella @udaymb @yongzhi1

**Comment by mengdonglin** [comment]
@RDharageswari Can this issue with RT5682 headset capture be reproduced with previous mtl-002 release (SOF: mtl-002-drop-stable | https://github.com/thesofproject/sof/commit/fd0824097a3e)?

**Comment by RDharageswari** [comment]
Able to repro this issue with the no-codec topology also

**Comment by yongzhi1** [comment]
The xun in [fw_error_rc15.txt](https://github.com/thesofproject/sof/files/10242724/fw_error_rc15.txt) looks similar to https://github.com/thesofproject/sof/issues/6724 and was observed for capture only as commented by https://github.com/thesofproject/sof/issues/6724#issuecomment-1344029264

**Comment by RDharageswari** [comment]
Last fix shared by @abonislawski is working well without any errors.

**Comment by keqiaozhang** [comment]
@RDharageswari can we close this issue?

**Comment by udaymb** [comment]
> @RDharageswari can we close this issue?

@keqiaozhang - Is the fix part of the mtl-002 branch?

**Comment by keqiaozhang** [comment]
> > @RDharageswari can we close this issue?
> 
> @keqiaozhang - Is the fix part of the mtl-002 branch?

As Dhara confirmed that the fix share by @abonislawski can fix the issue, so I wonder if the fix has landed on mtl-002 and we can close this bug.

**Comment by udaymb** [comment]
@abonislawski shared this FW [sof-mtl-8cd208873234e9ed02d4caaea7ae224b.ri.txt](https://github.com/thesofproject/sof/files/10267536/sof-mtl-8cd208873234e9ed02d4caaea7ae224b.ri.txt)

topology on max98357a and rt5682 codec - [sof-mtl-max98357a-rt5682-9c077c288605e8c581c6d25ef131a8dc.tplg.txt](https://github.com/thesofproject/sof/files/10267546/sof-mtl-max98357a-rt5682-9c077c288605e8c581c6d25ef131a8dc.tplg.txt)

Below option is set
options snd_sof sof_debug=128

With this the speaker playback, headset playback and capture, dmic capture works fine

**Comment by udaymb** [comment]
@abonislawski - There are 2 additional commits in branch https://github.com/thesofproject/sof/tree/mtl-002-drop-stable

Please confirm, other than this there are no other changes, and would there be a release based on these changes?

**Comment by mszleszy** [comment]
@RDharageswari I've check logs attached, we have IPC request& extension part but the payload part is missing, and this part is crucial for repro attempt.

![image](https://user-images.githubusercontent.com/87766157/210356383-28b409a2-817a-4814-997b-af21ea0822e0.png)

Is there any chance for ipc messages with their payloads included?

**Comment by abonislawski** [comment]
> @abonislawski - There are 2 additional commits in branch https://github.com/thesofproject/sof/tree/mtl-002-drop-stable
> 
> Please confirm, other than this there are no other changes, and would there be a release based on these changes?

mtl-002 is ready to use, no more changes

**Comment by RDharageswari** [comment]
with the mtl-002 firmware.
capture is still noisy with the below format S24_LE, same is clear with s32_le
localhost ~ # arecord -Dhw:0,0 hp_cap.wav -c2 -r48000 -fs24_le -d15 -vv.

**Comment by RDharageswari** [comment]
tried the same with mtl-003 firmware. Still the noise issue is observed.
localhost ~ # arecord -Dhw:0,0 hp_cap.wav -c2 -r48000 -fs24_le -d15 -vv
Recording WAVE 'hp_cap.wav' : Signed 24 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-rt5682' device 0 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S24_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 32
  buffer_size  : 8192
  period_size  : 2048
  period_time  : 42666
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 2048
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 8192
  silence_threshold: 0
  silence_size : 0
  boundary     : 4611686018427387904
  appl_ptr     : 0
  hw_ptr       : 0
[logs.zip](https://github.com/thesofproject/sof/files/10386852/logs.zip)
please find the kernel, firmware trace logs and the captured file in the attachment.
Please let me know if you need more info

**Comment by kfrydryx** [comment]
@RDharageswari Is this issue still relevant?

**Comment by RDharageswari** [comment]
we see the I/O error with mtl-003 release as well. I can raise a separate bug to track that.
