### ISSUE TITLE
[BUG] various IPC ERROR/TIMEOUTs when testing multiple playback on IPC3 Zephyr platforms

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#6820]
**Describe the bug**
We observed this issue on all IPC3 Zephyr platforms when testing multiple playback. This is a firmware regression and caused by:
https://github.com/thesofproject/sof/commit/41a16145fc2d436812d893bed320dc008017b056

The IPC ID is different on different platforms:
```
ADLP_RVP_NOCODEC_ZEPHYR: ipc tx error for 0x60010000 |  GLB_STREAM_MSG: PCM_PARAMS
ADLP_RVP_SDW_ZEPHYR: ipc tx timed out for 0x60010000 | GLB_STREAM_MSG: PCM_PARAMS
TGLH_SKU0A5E_SDW_ZEPHYR: ipc tx timed out for 0x60050000 | GLB_STREAM_MSG: TRIG_STOP
TGLH_SKU0A70_HDA_ZEPHYR: ipc tx error for 0x60010000 | GLB_STREAM_MSG: PCM_PARAMS
TGLU_UP_HDA_ZEPHYR: ipc tx error for 0x60040000 | GLB_STREAM_MSG: TRIG_START
ADLP_SKU0B00_SDCA_ZEPHYR: ipc tx timed out for 0x60050000 GLB_STREAM_MSG: TRIG_STOP
.....
```
For details, please refer to inner test ID:19040

**To Reproduce**
~/sof-test/test-case/multiple-pipeline.sh -f p -l 50

**Reproduction Rate**
100%

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: 
[d6e19d271118](https://github.com/thesofproject/linux/commit/d6e19d271118)

SOF Branch: main
SOF Commit: 
[41a16145fc2d](https://github.com/thesofproject/sof/commit/41a16145fc2d)

Zephyr Commit: 
[zephyr-v3.2.0-2606-gc5b270e7b003](https://github.com/zephyrproject-rtos/zephyr/commit/zephyr-v3.2.0-2606-gc5b270e7b003)

**Comment by mengdonglin** [comment]
Won't fix IPC3 issue on SOF main branch.
