### ISSUE TITLE
How to build the sof firmware for Alder Lake target

### ISSUE THREAD

**Issue by waterphotography** [thesofproject/sof#6895]
Hi,

I'm currently working on a Chromebook target with Alder Lake platform. But it looks adl is not in the list of supported platforms in the sof firmware build script. I tried to rename and use the tdl firmware, but it didn't work. Could anyone help point out how to build the sof firmware for adl platform? Thank you very much!

**Comment by aiChaoSONG** [comment]
For platforms use community key (chromebook should be one of such), adl and tgl share the same build target, which is tgl. as you can see here, the adl firmware is symbol link to tgl firmware: https://github.com/thesofproject/sof-bin/tree/main/v2.3.x/sof-v2.3/community

So theoretically, it should work to build the tgl target, and rename it. could you please provide more information? what is the build command you run? what is the error in dmesg?

**Comment by plbossart** [comment]
also there are two variants for TGL and TGL-H, you need to make sure you use the right version for your device.

**Comment by waterphotography** [comment]
@aiChaoSONG @plbossart it works on my side. Thanks for your kind help!
