### ISSUE TITLE
2 samples of SSP port are silent 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#69]
There are 2 samples(49,50) of SSP port are silent (0).  This issue is happened on APL with passthrough and volume topologies. Please see below:
![sampling_issue](https://user-images.githubusercontent.com/22468760/42426380-21c10f46-835a-11e8-8dab-d125cf50561a.jpg)

**Comment by zhigang-wu** [comment]
this is periodically or only one time in the whole playing process?

**Comment by tlauda** [comment]
Is it playback or capture issue?

**Comment by lgirdwood** [comment]
Period size is 48 samples. @keqiaozhang can you also confirm if HW DMA linked list mode is used or not here ?

**Comment by tlauda** [comment]
@keqiaozhang Issue should be fixed with #84. Please reconfirm, that both passthrough and volume pipelines don't have this problem anymore.

**Comment by keqiaozhang** [comment]
This issue is fixed in latest code base.
sof-master:6b94226b81efc8a71cc01d962f460fa5a7fa850d

**Comment by keqiaozhang** [comment]
This issue is fixed by PR#84.
