### ISSUE TITLE
Remove Xrun recovery inside FW.

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/sof#710]
SOF FW will need to remove recovery trying code, e.g. pipeline_prepare(), trigger start, and schedule copy.

Just keep sending Xrun IPC to host driver side, host framework(e.g. ALSA) will help to handle this recovery if possible, e.g. trigger stop and start.

**Comment by lgirdwood** [comment]
ok, no objections from me but we need to make sure drivers *does* do the recovery.

**Comment by keyonjie** [comment]
@lgirdwood sure, @bardliao is working on that.

**Comment by bardliao** [comment]
@keyonjie @lgirdwood My plan is to return SNDRV_PCM_POS_XRUN in sof_pcm_pointer when kernel receive the XRUN message from FW.

**Comment by slawblauciak** [comment]
FW xrun recovery will be disabled once driver fully handles the situation
https://github.com/thesofproject/linux/issues/660

**Comment by jajanusz** [comment]
WIP #1439

**Comment by tlauda** [comment]
It's disabled in FW.
