### ISSUE TITLE
[BUG] SOF build fails to dw_wdt_isr error with Zephyr mainline

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#7126]
**Describe the bug**
Build failure with latest Zephyr main line

https://github.com/thesofproject/sof/actions/runs/4222153768/jobs/7330313865

** logs **
```
/zep_workspace/zephyr/drivers/watchdog/wdt_dw.c:181:13: error: 'dw_wdt_isr' defined but not used [-Werror=unused-function]
  181 | static void dw_wdt_isr(const struct device *dev)
      |             ^~~~~~~~~~
```
**Impact**
Showstopper, prevents Zephyr baseline updates to SOF main

**Comment by kv2019i** [comment]
Seems to relate to "drivers: watchdog: Add a new driver for Synopsys DesignWare watchdog" that was merged today. Assigning to @softwarecki

**Comment by kv2019i** [comment]
FYI @juimonen

**Comment by softwarecki** [comment]
Fixed in https://github.com/zephyrproject-rtos/zephyr/pull/54993

**Comment by kv2019i** [comment]
Thanks @softwarecki !  @juimonen @abonislawski This means we can't handle the dai_config change or update to SSP-blob until 54993 is merged and we update directly to that (the intermediate versions won't work). And when we do that update, then we need Jaska's dai_config SOF PR to go in at the same time.

**Comment by lgirdwood** [comment]
@kv2019i https://github.com/zephyrproject-rtos/zephyr/pull/54993 now merged.
