### ISSUE TITLE
Speakers not working on Jasperlake chromebook with rt1015 amp.

### ISSUE THREAD

**Issue by WeirdTreeThing** [thesofproject/sof#7162]
On the MAGPIE chromebook and many other jsl boards with rt1015, speakers will not work in linux. Tested on fedora on kernel version `6.2.0-0.0.next.20230217.259.vanilla.fc37.x86_64` from [this copr](https://copr.fedorainfracloud.org/coprs/g/kernel-vanilla/next/). Headphones work just fine though.

The expected `aplay -l` output on ChromeOS is:
```
List of PLAYBACK Hardware Devices 
card 0: sofrt5682 [sof-rt5682], device 0: Speakers () []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 1: Headset () []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 2: HDMI1 () []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 3: HDMI2 () []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 4: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
While on linux it is:
```
List of PLAYBACK Hardware Devices
card 0: sofrt5682 [sof-rt5682], device 0: Headphones (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 1: Headset (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 2: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 3: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofrt5682 [sof-rt5682], device 4: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
On linux, playback from the "Headset" PCM works just fine and output comes from wired headphones. Playing audio through the "Headphones" PCM gives no output. Other Jasperlake chromebooks with different speaker amps like max98360 work fine.

**Comment by cujomalainey** [comment]
Thanks, reassigning this issue to follow up on the topology bug

**Comment by WeirdTreeThing** [comment]
I'll try modifying the UCM to get pipewire to work without any workarounds.

**Comment by WeirdTreeThing** [comment]
I was able to fix the UCM issues.

**Comment by lgirdwood** [comment]
@WeirdTreeThing can we close ?

**Comment by WeirdTreeThing** [comment]
Using the ChromeOS topology as a workaround works for now but the upstream topology is still broken.

**Comment by cujomalainey** [comment]
I have an email chat with @stolx going, will make sure that is fixed

**Comment by stolx** [comment]
jsl topologies are not in main branch anymore.
Please suggest which branch still needs to be fixed if any.

**Comment by WeirdTreeThing** [comment]
I see that jsl was removed in b637889efb5e99e9f87f0ed1b081826f6ff992f0, can I ask why it was removed?

**Comment by cujomalainey** [comment]
@lgirdwood @mwasko can answer why it was removed

It needs to be fixed in stable-v2.2

**Comment by lgirdwood** [comment]
> @lgirdwood @mwasko can answer why it was removed
> 
> It needs to be fixed in stable-v2.2

Ack - stable v2.2 - 
@WeirdTreeThing The Intel team removed the older Intel platforms due to the effort involved in bringing all platforms onto Zephyr and IPC4. It is better to focus effort on the more recent and newer Intel platforms (with more capabilities) to maximize the audio features we could bring on the newer platforms.

**Comment by WeirdTreeThing** [comment]
Well if jsl support was dropped there is nothing to fix so the issue can be closed.

**Comment by cujomalainey** [comment]
@WeirdTreeThing the devices are getting long term support on the stable v2.2 branch till the device EOLs

**Comment by WeirdTreeThing** [comment]
Oh sorry, I didn't realize that.

**Comment by stolx** [comment]
@WeirdTreeThing @cujomalainey, got the fix here #7266 
unfortunately, I have no device to try it on.
but .conf files generated out of .m4 files look correct now.

**Comment by cujomalainey** [comment]
if "Speaker" is showing up in .conf then that is good enough for me

**Comment by WeirdTreeThing** [comment]
I tested on the jsl device and it works perfectly.

**Comment by stolx** [comment]
thank you @WeirdTreeThing , @cujomalainey
