### ISSUE TITLE
[ADL/TGL/MTL NOCODEC] Frequency response is different between left and right channel

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof#7184]
Found alsabat failure with ADLP_RVP_NOCODEC_IPC4ZPH.
https://sof-ci.01.org/linuxpr/PR4212/build3371/devicetest/index.html?model=ADLP_RVP_NOCODEC_IPC4ZPH&testcase=check-alsabat-headset-playback

- Kernel PR: 4212
- SOF Branch: main
- SOF Commit: a74ad932700c
-  Zephyr Commit: zephyr-v3.3.0-200-g9af2789cad17
- tplg: sof-adl-nocodec.tplg

![sof-adl-nocodec](https://user-images.githubusercontent.com/45636982/221083553-bfabff52-f449-4f88-8975-1805df63882f.png)

alsabat test only complains about right channel.

```
BAT analysis: signal has 65536 frames at 48000 Hz, 2 channels, 2 bytes per sample.

Channel 1 - Checking for target frequency 821.00 Hz
Amplitude: 31128.9; Percentage: [95]
Detected peak at 821.04 Hz of 41.56 dB
 Total 42.4 dB from 818.85 to 823.24 Hz
 PASS: Peak detected at target frequency
Detected at least 1 signal(s) in total

Channel 2 - Checking for target frequency 821.00 Hz
Amplitude: 30990.5; Percentage: [94]
Detected peak at 815.92 Hz of 20.72 dB
 Total 20.7 dB from 815.92 to 815.92 Hz
Detected peak at 821.04 Hz of 38.11 dB
 Total 39.5 dB from 817.38 to 822.51 Hz
 PASS: Peak detected at target frequency
Detected peak at 823.97 Hz of 20.52 dB
 Total 39.5 dB from 823.97 to 823.97 Hz
 PASS: Peak detected at target frequency
Detected at least 3 signal(s) in total

Return value is -1003
```

Attached: [ADLP_RVP_NOCODEC_alsabat_wav_captured.zip](https://github.com/thesofproject/linux/files/10820349/ADLP_RVP_NOCODEC_alsabat_wav_captured.zip)

- bat.wav.9LAB5b ; alsabat test output
- left.wav ; only left channel
- right.wav ; only right channel- 

Left and Right channels are separated. Did frequency analysis.
![left_fa_20230223_190923](https://user-images.githubusercontent.com/45636982/221087037-11c7ae08-c1dd-4454-98ef-5ec9dc3ddaf0.png)
![right_fa_20230223_190930](https://user-images.githubusercontent.com/45636982/221087039-e42b45d1-8c6f-4858-97f0-5599f0ff3557.png)

One caveat is I couldn't reproduce this manually with same device.

**Comment by juimonen** [comment]
tried to reproduce with tgl, but just could not....

**Comment by singalsu** [comment]
There's a glitch in the second channel at about 0.466s time:

![Screenshot from 2023-02-28 11-25-10](https://user-images.githubusercontent.com/28754793/221810088-627fc9a2-bb3d-449e-9584-57f9aa634cba.png)

**Comment by singalsu** [comment]
One sample is from 1ms ago:

![Screenshot from 2023-02-28 11-28-23](https://user-images.githubusercontent.com/28754793/221810674-a0fb51cc-d51a-4b2b-95f2-6ae17cd59a32.png)

![Screenshot from 2023-02-28 11-27-36](https://user-images.githubusercontent.com/28754793/221810736-1606d007-b42e-4c7a-8011-3229adf1e186.png)

**Comment by juimonen** [comment]
yeah, so there is the phase difference from smart amp between channels, but also some "gaps/peaks" in the channels. I think I actually also spotted them also in the left channel, but much more rarely than right channel. So I suspect something is fishy with buffer copy, somewhere.

**Comment by ranj063** [comment]
@aiChaoSONG can you please look into this?

**Comment by lgirdwood** [comment]
Unlikely DMA as glitch would happen on both channels at the same time. Is SSP loopback mode used here ? SSP reads one word in FIFO at a time.

**Comment by juimonen** [comment]
I tried with mtl device and ssp1 and ssp2 are clean with the alsabat test. This has to be something to do with the complex pipeline with smart amp feedback.
