### ISSUE TITLE
[BUG]: IPC timeout observed for topology with mux components

### ISSUE THREAD

**Issue by maruthi-machani** [thesofproject/sof#7185]
with PR: https://github.com/thesofproject/sof/pull/7099 observing IPC timeout with TDM mode (Mux component) on AMD platforms.
Attaching the error snippet.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/101189005/221838171-9739826f-123a-4995-90fd-5b8d0564882a.png)

**Comment by maruthi-machani** [comment]
![image](https://user-images.githubusercontent.com/101189005/222333616-2b794a40-27fe-45a4-834a-98890e1e45d2.png)

**Comment by lgirdwood** [comment]
@ujfalusi @lyakh any inputs here ?
@maruthi-machani do you have FW logs prior to timeout ? i.e. any logs from shared memory on your platform.

**Comment by ujfalusi** [comment]
@maruthi-machani, a description on how this failure can be triggered would help

**Comment by maruthi-machani** [comment]
Issue observed during initial topology loading. by reverting the changes in ipc-common.c, the topology load is successful.

**Comment by lgirdwood** [comment]
@maruthi-machani not seeing this on Intel HW atm, are able to add some debug, it looks like an exception (I'm not sure why the kernel would say the otherwise). I can only think we are trying to deref a mux buffer that does not or no longer exists ?

**Comment by kv2019i** [comment]
@maruthi-machani Do you have time to debug this for v2.5? We can't really see this on any Intel platform, so we'd need help on the debug. We are targetting for a v2.5-rc1 end of this week.

**Comment by maruthi-machani** [comment]
@kv2019i we need sometime to debug this. seems this is specific to AMD platform.

**Comment by maruthi-machani** [comment]
@kv2019i we are observing for pipeline_29 buffer_get_comp() is waiting to acquire the buffer (buffer_acquire()).
Is this happen due to improper termination of pipeline_29 (ACPHS_VIRTUAL Dai). Can you suggest any reference topology for proper termination of mux component having two PCM playbacks.

**Comment by maruthi-machani** [comment]
@kv2019i with the echo-ref dai topology, the issue of waiting to acquire the buffer got resolved. Also IPC timeout not observed.

**Comment by maruthi-machani** [comment]
with AMD topology specific changes the issue is resolved, no blocker.

**Comment by lgirdwood** [comment]
> with AMD topology specific changes the issue is resolved, no blocker.

@maruthi-machani Have these updates been merged, can we close ?

**Comment by maruthi-machani** [comment]
updates merged https://github.com/thesofproject/sof/pull/7313, please close the issue.

**Comment by maruthi-machani** [comment]
updates merged https://github.com/thesofproject/sof/pull/7313,  closing the issue.
