### ISSUE TITLE
not an error in this PR, but please make *an additional* commit to fix this - let's not abuse the API by dropping the `const` qualifier. `sys_mm_drv_query_memory_regions()` returns type `const struct sys_mm_drv_region *` so it's only for users who only need read-only access. Presumably, users, needing read-write access should use the `virtual_memory_regions` array directly (otherwise why would they make it global, right?). Strangely though that array isn't declared in any header (sparse probably complains about it), so we need a patch for Zephyr too.

### ISSUE THREAD

**Issue by dabekjakub** [thesofproject/sof#7329]
not an error in this PR, but please make *an additional* commit to fix this - let's not abuse the API by dropping the `const` qualifier. `sys_mm_drv_query_memory_regions()` returns type `const struct sys_mm_drv_region *` so it's only for users who only need read-only access. Presumably, users, needing read-write access should use the `virtual_memory_regions` array directly (otherwise why would they make it global, right?). Strangely though that array isn't declared in any header (sparse probably complains about it), so we need a patch for Zephyr too.
**Alternatively** you can make this variable and `.virtual_region` in `struct virtual_memory_heap` `const` and then keep using this function

_Originally posted by @lyakh in https://github.com/thesofproject/sof/pull/7276#discussion_r1145851847_

**Comment by lgirdwood** [comment]
@dabekjakub looks like the context is in the subject. Do we also need to track a Zephyr PR here too ?
