### ISSUE TITLE
11 samples of SSP waveform point are error on APL with nocodec tplg

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/sof#74]
environment:
sof-dev:   bbe7c7a835b66dfe34eee7feeea78893cbb71a01
sof:      fa48c42abf83155d1bd42fafd4993d9b421ab5e0
soft:     ff8eb10b1877bb0fac8adf0124c36762a5f912fd 

Reproduce Steps:
using test-ssp5-mclk-0-I2S-volume-s16le-s16le-48k-24576k-nocodec.tplg as sof-apl-nocodec.tplg
run : alsabat -Dhw:0,0 -f dat -c2 -r 48000 -F 997 
audacity open /tmp/bat.wav.*
![image](https://user-images.githubusercontent.com/29194447/42450223-09ccf790-83b6-11e8-977e-19af061f2a3d.png)

**Comment by zhuqingliang** [comment]
[dmesg.log](https://github.com/thesofproject/sof/files/2176120/dmesg.log)
[rmbox.log](https://github.com/thesofproject/sof/files/2176121/rmbox.log)

**Comment by lgirdwood** [comment]
How can you capture analog data if this is nocodec mode ? It seems like this should be using a topology for a codec.

**Comment by tlauda** [comment]
What does alsabat exactly do in terms of FW pipelines?
Does it create both render and capture pipelines and somehow loopbacks it back from SSP?
I'm trying to understand if this is for sure render problem or maybe a capture problem.

**Comment by keqiaozhang** [comment]
alsabat will create playback and capture pipeline, then play a specific sine wav and capture it through the loopback. 
Today I used logic pro to capture the data from SDO port, look like the data is normal, so it's most like a capture issue.
![screenshot from 2018-07-10 16-02-00](https://user-images.githubusercontent.com/22468760/42497192-183d5f72-845b-11e8-83e8-ef2d057990d5.png)

**Comment by lgirdwood** [comment]
@keqiaozhang SSP capture FIFO  is probably full of stale data. It could be cleared during trigger by reading the SSP FIFO directly using DSP reads.

**Comment by Jocelyn-Li** [comment]
Keqiao, please make sure it is FW issue or driver issue.

**Comment by tlauda** [comment]
@zhuqingliang You have used command run : alsabat -Dhw:0,0 -f dat -c2 -r 48000 -F 997, but screen from Audacity says it's 44.1 kHz. Which one is wrong?

**Comment by lgirdwood** [comment]
@keqiaozhang, @tlauda   ok, since this is first time only then we should read the SSP FIFO as part of the SSP driver init to clear out any stale samples. Should be a easy fix to try.

**Comment by tlauda** [comment]
Please verify on current top of master. I cannot reproduce this problem anymore.

**Comment by zhuqingliang** [comment]
We perform test with  e69ebddb4f61a0e7047efb728f7d7525171b6690 . There are a long period of blank bit at the head of bat.wav* .  The reproduce percentage is about 20% to 30%.
reproduce steps ：
1.using test/test-ssp5-mclk-1-I2S-volume-s32le-s32le-48k-24576k-nocodec.tplg
2.reboot 
3. run ` alsabat -Dhw:0,0 -f s32_le -r 48000 -c2 -F300`  once boot up
4. audacity open /tmp/bat.wav.*
![image](https://user-images.githubusercontent.com/29194447/42857465-8fbb34c6-8a7c-11e8-8e86-8239584f4230.png)

**Comment by lgirdwood** [comment]
@zhuqingliang have you verified this delay/race is not coming from alsabat/Linux userspace ?

**Comment by tlauda** [comment]
@zhuqingliang Can you provide dmesg log? I'm using the same topology and the same alsabat command, but I cannot reproduce this issue. Tried to reboot and run alsabat ~20 times.

**Comment by zhuqingliang** [comment]
If run alsabat several times , the issues will not happen again .

**Comment by keqiaozhang** [comment]
This issue is fixed  by PR#111.
