### ISSUE TITLE
[BUG] Audio playback gets heavily distorted after rapid pause/release on HDA analog output 

### ISSUE THREAD

**Issue by ujfalusi** [thesofproject/sof#7478]
**Describe the bug**
While testing audio playback on hw:0,0 on UPX-i11 board I have checked pause/resume with aplay -i (holding <SPACE> key to rapid pause/resume) and after  few seconds the audio playback got corrupted.
The playback continued normally, firmware reported no issues, but the audio is completely distorted, high pitched and garbled.

**To Reproduce**

aplay -iv -Dhw:0,0 file.wav (48K 16bit)

Sounds good, no distortion.
Now, press and HOLD the ``<SPACE>`` key to rapid pause/resume aplay.
After few seconds you can hear that the sound starts to be up-shifted pitched, now release <SPACE> and if it is paused, press it again to resume.
Audio is pitched up, distorted, garbled
Not affecting HDMI (ChainDMA).

The same issue present on DeepBuffer PCM (-Dhw:0,31)

**Reproduction Rate**
10/10

**Expected behavior**
audio is not distorted

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: topic/sof-dev or upstream linux-next
    * SOF: ebaa1429f9d40dc17a28438193789a771cbab2cf
2) Name of the topology file
    * Topology: sof-hda-generic.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: TGL (UPX-i11)

**Screenshots or console output**
nothing out of ordinary in logs, all looks error free.

**Comment by plbossart** [comment]
Someone was talking about finding something to keep themselves busy yesterday @ujfalusi.

Humm, wish granted, eh? wow, nice bug, this will be a tough one to crack.

**Comment by ujfalusi** [comment]
Update: it is not the rapid pause/resume, it can be a slow, pasue/resume, small wait, pause/resume.
After the 10th or so iteration the audio starts to be distorted.

**Comment by ujfalusi** [comment]
Update: it is not reproducible with the reference firmware.

**Comment by ujfalusi** [comment]
this is the original tplg path:
![image](https://user-images.githubusercontent.com/12640614/233984194-7df0a93c-9781-4ba5-ab38-2e82bf9a3828.png)


I have tried with these variations:
![image](https://user-images.githubusercontent.com/12640614/233983385-3274a185-c974-4784-a9f4-b86d361cbafe.png) ![image](https://user-images.githubusercontent.com/12640614/233983494-204bbd99-14aa-474a-b4bd-087bde4486e8.png) ![image](https://user-images.githubusercontent.com/12640614/233983589-01edfd86-503f-44dd-895c-629be80e797d.png)

all of them exhibiting the same issue, the last one (without gains) interestingly will reproduce it much faster (4th pause/resume sequence)

**Comment by ujfalusi** [comment]
I'm using GCC to build the firmware, I got an XCC built binary and that works OK, I cannot reproduce the issue
