### ISSUE TITLE
[BUG] multiple-pause-resume failed with input/output error in MTLP NOCODEC

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof#7495]
**Describe the bug**

read error: Input/output error happens with multiple-pause-resume test in MTLP_RVP_NOCODEC. dmesg/mtrace doesn't print any error. It have happened occasionally, come and go. No issue open for this, hoping it might be fixed with other fixes. Apparently it's not. pcm_read error but this is not DMIC specific. Only found with NOCODEC tplg.

Found in latest PR test,
https://sof-ci.01.org/sofpr/PR7474/build6198/devicetest/index.html

```
=== PAUSE ===                                                            
(6/50) pcm'DMIC0 Raw' cmd'arecord' id'5': Wait for 40 ms before pause

(6/50) pcm'DMIC0 Raw' cmd'arecord' id'5': Wait for 23 ms before resume
arecord: pcm_read:2221: read error: Input/output error
```

Last seen in intel internal daily test is on Apr 16th. 
planresultdetail/23643?model=MTLP_RVP_NOCODEC&testcase=multiple-pause-resume-50

```
=== PAUSE ===                                                            
(5/50) pcm'Deepbuffer Port0' cmd'aplay' id'8': Wait for 46 ms before pause

(5/50) pcm'Deepbuffer Port0' cmd'aplay' id'8': Wait for 45 ms before resume
arecord: pcm_read:2221: read error: Input/output error
```

**To Reproduce**
TPLG=/lib/firmware/intel/sof-ace-tplg/sof-mtl-nocodec.tplg MODEL=MTLP_RVP_NOCODEC ~/sof-test/test-case/multiple-pause-resume.sh -r 50

**Reproduction Rate**
Not so high, 2-3 times per week

**Environment**

- Kernel Branch: topic/sof-dev
- Kernel Commit: [57d1c63077e3](https://github.com/thesofproject/linux/commit/57d1c63077e3)
- SOF Branch: main
- SOF Commit: [c7e98ee73188](https://github.com/thesofproject/sof/commit/c7e98ee73188)

**Screenshots or console output**
[mtrace-mtlp-nocodec.txt](https://github.com/thesofproject/sof/files/11297904/mtrace-mtlp-nocodec.txt)
[dmesg-mtlp-nocodec.txt](https://github.com/thesofproject/sof/files/11297905/dmesg-mtlp-nocodec.txt)

**Comment by keqiaozhang** [comment]
This issue no longer exists in CI. closing this bug.
