### ISSUE TITLE
[BUG][IPC4] Failed parsing IPC4 Copier tokens for widget copier.HDA.51.1 for cavs-rt5682

### ISSUE THREAD

**Issue by yongzhi1** [thesofproject/sof#7505]
**Describe the bug**
Seems when SSP and HDMI co-exist, <intel/hw_config_cardinal_clk.conf> is picked to construct HDMI which caused parsing error during tplg load:
```
[    8.700401] sof-audio-pci-intel-mtl 0000:00:1f.3: Failed parsing IPC4 Copier tokens for widget copier.HDA.51.1 err: -22
[    8.712501] sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to add widget id 0 type 27 name : copier.HDA.51.1 stream iDisp1
[    8.725443] sof_rt5682 mtl_mx98360_rt5682: ASoC: failed to load widget copier.HDA.51.1
[    8.734322] sof_rt5682 mtl_mx98360_rt5682: ASoC: topology: could not load header: -22
[    8.743186] sof-audio-pci-intel-mtl 0000:00:1f.3: error: tplg component load failed -22
[    8.752176] sof-audio-pci-intel-mtl 0000:00:1f.3: error: failed to load DSP topology -22
```
**Reproduction Rate**
100%

**Expected behavior**
TPLG should be loaded successfully. 

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/4459333/1
    * SOF: {ca68ba68f22c2bf3c209b62466a2aaac6b09ea2d}
2) Name of the topology file
    * Topology: {sof-ace-tplg/sof-mtl-max98357a-rt5682-ssp2-ssp0.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {MTL}

**Comment by yongzhi1** [comment]
Thanks @ranj063 , with https://github.com/thesofproject/sof/pull/7474 the issue is fixed, I got alarmed because of:

```
	HDA5 {
		id 4
		fsync_freq 48000
		mclk_freq 24576000
		tdm_slots 2
		tx_slots 3
		rx_slots 3
		format I2S
		bclk codec_consumer
		fsync codec_consumer
		mclk codec_mclk_in
		data {
		}
	}
```

**Comment by abonislawski** [comment]
@yongzhi1 can we close if fixed?
