### ISSUE TITLE
IIR EQ should be optimized with HiFi3 intrinsics

### ISSUE THREAD

**Issue by singalsu** [thesofproject/sof#758]
GCC built generic C version is slow though it's fast enough for realtime operation while there is not much other processing in firmware. Compilation with xt-xcc gives better performance but good MCPS performance and low power is achieved only with intrinsics optimized code like volume, FIR, and SRC components.

**Comment by singalsu** [comment]
@jajanusz OK, got it. It's a fairly small task, I'll start doing next week.

**Comment by jajanusz** [comment]
@singalsu It would be great. However it's low priority task, so feel free to do it only if you have nothing better to do.

**Comment by lgirdwood** [comment]
@singalsu lets have this for v1.4 since it's a small task, Btw does FIR require the same ?

**Comment by singalsu** [comment]
@lgirdwood FIR is optimized already since it was hit worst by generic C implementation. Fortunately I did the intrinsics version for year ago OSTS demo.

**Comment by singalsu** [comment]
@lgirdwood I didn't find time for this, new ETA is beginning of July, after my vacation ends plus need some work days.

**Comment by singalsu** [comment]
SOF PR #1624 addresses this requirement.

**Comment by singalsu** [comment]
This can be closed since PR #1624 is merged.
