### ISSUE TITLE
[BUG] topology1: FW pcm_params fail with large period size >44739

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#7652]
**Describe the bug**
Continuation of 
https://github.com/thesofproject/sof/issues/7476

See log in https://github.com/thesofproject/sof/issues/7476#issuecomment-1550896125

**Comment by Vamshigopal** [comment]
@kv2019i  i took the conf file and dmesg at different instances, so im not sure, let me share the logs and conf file with 50ms period size.
i do agree with your assumption, as i see same error for 50ms, 80ms.. i.e SOF_TKN_SCHED_PERIOD > 44739

**Comment by kv2019i** [comment]
@Vamshigopal Bugfix candidate at https://github.com/thesofproject/sof/pull/7655
I didn't realize we had similar signed 32bit arithmetic in FW to calculate the frame size. :( So this obviously fails in the same conditions as the m4 calculations failed.

**Comment by kv2019i** [comment]
Fix merged, closing.
