### ISSUE TITLE
[BUG][IPC4] fix 24bit variant type support

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#7697]
**Describe the bug**
See kernel side bug fro background and description
https://github.com/thesofproject/linux/issues/4383

FW should honor MSB_INTEGER/LSB_INTEGER in IPC4 audio_format definiton. 

IPC3 did not make a distinction between the two variants, so this has been wrong in both kernel and FW, but this needs to be addressed. 

FYI @RanderWang @serhiy-katsyuba-intel @abonislawski @singalsu

**Comment by kv2019i** [comment]
The current SOF mainline ignores the copier config for DAI side and chooses the LSB/MSB variant based on interface type:
https://github.com/thesofproject/sof/pull/7573

.... and sample_type is not considered here at all (in current SOF).

**Comment by mengdonglin** [comment]
https://github.com/thesofproject/sof/pull/7959 submitted for this.
