### ISSUE TITLE
[CLEANUP] Legacy Fuzzer

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/sof#7709]
Decide what to do about the fuzzer on  stable-v2.2 

EDIT: The beginning of the discussion is in
- #7675

**Comment by marc-hb** [comment]
These should probably be updated:

https://thesofproject.github.io/latest/developer_guides/fuzzing/fuzzing_in_docker.html
https://github.com/thesofproject/sof-docs/tree/master/developer_guides/fuzzing

**Comment by marc-hb** [comment]
stable-v2.2 removal submitted in
- #7795

**Comment by lgirdwood** [comment]
@lyakh @juimonen did the legacy fuzzer get fully removed form main ?

**Comment by marc-hb** [comment]
Yes however I'm afraid sof-docs still describes it, see above.

**Comment by lgirdwood** [comment]
> Yes however I'm afraid sof-docs still describes it, see above.

ok, can you send a PR to remove from sof-docs. Thanks. I will close here.
