### ISSUE TITLE
PM D3 entry fixes for CNL, WHL, CML, ICL

### ISSUE THREAD

**Issue by Jocelyn-Li** [thesofproject/sof#773]
Make sure PM entry is completed prior to IPC.  Reference https://github.com/thesofproject/sof/pull/772 for APL fixes

**Comment by RanderWang** [comment]
@Jocelyn-Li  I don't understand the idea of 772. And I discuss with other team member, they also don't understand it. We don't know whether kernel driver needs to be refined

**Comment by lgirdwood** [comment]
@RanderWang this is for FW only. Please have a look at the PM shutdown sequence (PM ops and IPC ops) on APL and see if similar changes have to be made for other platforms.

**Comment by lgirdwood** [comment]
@RanderWang ping, any questions ?

**Comment by RanderWang** [comment]
Hi Liam,  sorry for late. I am busy with other issues.
One Question: I find there is no power_down.s on ICL. AS I know, ICL is almost the same as CNL in FW,
so could I copy from CNL and modify it for ICL? Thanks.

**Comment by lgirdwood** [comment]
@RanderWang I think so, but @lbetlej will be able to confirm for sure.

**Comment by lbetlej** [comment]
@RanderWang @lgirdwood - correct the power_down.s from CNL can be used for ICL . Note that I've just a bit cleaned up the file see PR#894 in case you want to copy it.

**Comment by lbetlej** [comment]
@RanderWang  @lgirdwood - BTW> the driver shall make sure that is not accessing memory window (only IPC registers) during pm_ctx_save handling.

**Comment by lgirdwood** [comment]
@ranj063 fyi, we cannot read mailbox after receiving PD IPC reply
