### ISSUE TITLE
IPC timed out after system is booted 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#79]
This issue is caused by PR#71:trace: fix dma trace with repeated data bug on APL&CNL.
Due to the compilation issue #78 and #75, I only found this issue on APL. Will check on other platforms after the compilation issues are fixed.
[dmesg.log](https://github.com/thesofproject/sof/files/2183091/dmesg.log)
[rmbox.log](https://github.com/thesofproject/sof/files/2183092/rmbox.log)

**Comment by RanderWang** [comment]
I also checked it at commit: fa48c42abf which my patch is based on at the day I made PR, not such issue. I think it is not caused by my patch but I will help to fix it.

**Comment by xiulipan** [comment]
should be fixed by #82 
@keqiaozhang  could you test to confirm

**Comment by keqiaozhang** [comment]
This issue is fixed.

**Comment by keqiaozhang** [comment]
This issue is fixed  by https://github.com/thesofproject/sof/pull/82
