### ISSUE TITLE
[BUG] LunarLake: number of cores must be changed to 5

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#7926]
cloning issue https://github.com/thesofproject/linux/issues/4472

The hardware supports 5 cores but the firmware can only support 4 so far. This is clearly not quite right. Adding as a P1 issue to make sure this is tracked and resolved for both firmware and kernel.

**Comment by lgirdwood** [comment]
@mwasko pls re-assign as needed, we can then validate with kernel when ready. Thanks.

**Comment by abonislawski** [comment]
@jxstelter is this zephyr core count issue still valid?

**Comment by marcinszkudlinski** [comment]
looks like newest SOF (21ed10abf8a2673f13dea3fd39a063c561083054)  has 5 cores enabled
![image](https://github.com/thesofproject/sof/assets/84508161/8c808757-6820-4ec4-868b-a871408a7369)

**Comment by lgirdwood** [comment]
I think we can close now unless we need a kernel PR ? @plbossart .

**Comment by plbossart** [comment]
kernel PR https://github.com/thesofproject/linux/pull/4487 is merged already so we are good to go.
