### ISSUE TITLE
SOF doesnt handle XRUNS correctly

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof#795]
Creating a github issue based on the partner issue created by @cujomalainey 
https://partnerissuetracker.corp.google.com/u/2/issues/121161381

Steps to reproduce: 
Run speaker-test -D hw:0,0 -t sine -c 2
Suspend and resume the task repeatedly (using C-z and fg)
Eventually you will get an iteration where the sine wave it noticeably no longer playing the correct tune and sounds distorted.

**Comment by keqiaozhang** [comment]
@ranj063 
I cannot reproduce this issue on one Bobba.
I tested the speaker-test on speaker, sound is good, no obvious noise, then I tested it on headset and recorded the sound, the waveform looks good also, no distortion.
Screen shot and the wav file are attached, please refer.
![screenshot from 2019-01-08 14-22-41](https://user-images.githubusercontent.com/22468760/50813512-971c3e00-1351-11e9-904b-53e0c6e05079.png)
[record.zip](https://github.com/thesofproject/sof/files/2735421/record.zip)

Test recipe:
ChromeOS: R72-11316.61.0
Kernel: google release branch/release-R72-11316.B-chromeos-4.14 + your fix/6b0e12c(ASoc: SOF: use optimized register polling)

**Comment by ranj063** [comment]
@cujomalainey looks like the issue cannot be reproduced on our boards. Could you please verify with the latest R72 build?

**Comment by ranj063** [comment]
@keqiaozhang Thanks for testing. I'm closing this one as it has been confirmed to be fixed
