### ISSUE TITLE
[BUG][MTL-005.0.3] IPC timed out when doing start/stop speaker/jack pipeline while dmic is running

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof#7980]
**Describe the bug**
An error of ipc timed out is observed when start/stop speaker/jack pipeline while dmic is running.

**To Reproduce**
1. do arecord through **dmic** pipeline:  arecord -Dhw:0,4 -f s32_le -c2 -i -r 48000 -vvv /dev/null
2. do aplay through **speaker** pipeline: aplay -Dhw:0,2 -f dat -c 2 -d5 -i -vvv /dev/zero
3. kill aplay with CTRL+C, and start it again
4. loop step 3.

**Reproduction Rate**
not high, about 5%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {sof-dev 70d2c68e48d0}
    * SOF: {MTL-005.0.3 release} https://github.com/thesofproject/sof/releases/tag/releases%2Fmtl%2Fv5.0.3
2) Name of the topology file
    * Topology: {sof-mtl-rt711-l0-rt1316-l23-rt714-l1.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: MTL RVP with external SoundWire codecs on GEN4 AIOC (RVP name: sh-mtlp-rvp-sdw-09, not in CI farm)
     Headset: ALC711 on link 0, 
     Speaker: ALC1316 x2 on link 2 & 3 
     DMIC: ALC714 on link1.  
     kernel options snd_soc_sof_sdw quirk=2

[dmesg_ipc_timedout.txt](https://github.com/thesofproject/sof/files/12158208/dmesg_ipc_timedout.txt)
[mtrace_ipc_timedout.txt](https://github.com/thesofproject/sof/files/12158256/mtrace_ipc_timedout.txt)

``` dmesg
[  900.674516] snd_sof_intel_hda_common:hda_dsp_stream_trigger: sof-audio-pci-intel-mtl 0000:00:1f.3: FW Poll Status: reg[0x1c0]=0x2014001e successful
[  901.987265] snd_sof:sof_pcm_trigger: sof-audio-pci-intel-mtl 0000:00:1f.3: pcm: trigger stream 2 dir 0 cmd 0
[  901.987282] snd_sof:sof_ipc4_trigger_pipelines: sof-audio-pci-intel-mtl 0000:00:1f.3: trigger cmd: 0 state: 3
[  901.987296] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x13000003|0x1: GLB_SET_PIPELINE_STATE [data size: 12]
[  902.493326] sof-audio-pci-intel-mtl 0000:00:1f.3: ipc timed out for 0x13000003|0x1
[  902.493349] sof-audio-pci-intel-mtl 0000:00:1f.3: Attempting to prevent DSP from entering D3 state to preserve context
[  902.493357] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump start ]------------
[  902.493374] sof-audio-pci-intel-mtl 0000:00:1f.3: Host IPC initiator: 0x93000003|0x1|0x0, target: 0x1b060000|0x0|0x0, ctl: 0x3
[  902.493382] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ IPC dump end ]------------
[  902.493387] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump start ]------------
[  902.493392] sof-audio-pci-intel-mtl 0000:00:1f.3: IPC timeout
[  902.493398] sof-audio-pci-intel-mtl 0000:00:1f.3: fw_state: SOF_FW_BOOT_COMPLETE (7)
[  902.493410] sof-audio-pci-intel-mtl 0000:00:1f.3: ROM status: 0x0, ROM error: 0x0
[  902.493415] sof-audio-pci-intel-mtl 0000:00:1f.3: ROM debug status: 0x50000005, ROM debug error: 0x0
[  902.493422] sof-audio-pci-intel-mtl 0000:00:1f.3: ROM feature bit enabled
[  902.493426] sof-audio-pci-intel-mtl 0000:00:1f.3: ------------[ DSP dump end ]------------
[  902.493448] sof-audio-pci-intel-mtl 0000:00:1f.3: failed to pause all pipelines
[  902.493456] sof-audio-pci-intel-mtl 0000:00:1f.3: ASoC: error at soc_component_trigger on 0000:00:1f.3: -110
[  902.493467]  Speaker: ASoC: trigger FE cmd: 0 failed: -110
```
``` mtrace
[00:00:54.870,363] <inf> ll_schedule: zephyr_ll_task_done: num_tasks 4 total_num_tasks 4
[00:00:54.871,048] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.871,345] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.871,918] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.872,095] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.873,061] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): Copy_bytes 0 + avail bytes 16 < period bytes 384, possible glitch
[00:00:54.873,326] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.873,505] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.874,076] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.874,253] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.874,948] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.875,125] <wrn> dai_comp: comp:3 0x40003 dai_zephyr_copy(): nothing to copy
[00:00:54.886,245] <inf> pipe: remove_pipeline_cps_consumption: Unregistering KCPS consumption: 6388, core: 0
```

xrun first happened, and then set pipeline state ipc to STOP is not replied (IPC timeout at  902.493326),  kernel try to free the pipelines, and failed (free widget ipc timedout also).  After the issue happened, redoing DMIC capture still works. but speaker playback cannot work anymore, because widget   not freed, and restart the pipeline will create the same widget again, thus we got `[  314.168426] sof-audio-pci-intel-mtl 0000:00:1f.3: FW reported error: 104 - Other failure of module instance initialization request`.

**Comment by syedk008** [comment]
I do not observe the issue with the sof-fw commit id:1a96df1e63e68754c58ce777bd8c5a62f6d06f58.

**Comment by mengdonglin** [comment]
We didn't reproduce this issue on SOF main branch commit https://github.com/thesofproject/sof/commit/1a96df1e63e68754c58ce777bd8c5a62f6d06f58 in 0.5 hour *stress* test.

But we cannot check if this issue can be reproduced by the tip of SOF main branch, as another issue https://github.com/thesofproject/sof/issues/7979 was introduced by commit https://github.com/thesofproject/sof/commit/e424b874a477617d080f368ae67b46d19b7e6d4d on top of https://github.com/thesofproject/sof/commit/1a96df1e63e68754c58ce777bd8c5a62f6d06f58. 

![image](https://github.com/thesofproject/sof/assets/8703742/3f60fcf8-4e6e-4b37-af6f-62b8397f9a7b)

**Comment by keqiaozhang** [comment]
This issue cannot be reproduced on mtl-006. No reproductions in CI tests. Closing this bug.
