### ISSUE TITLE
[FEATURE] Implement SOF_IPC4_FW_PARAM_SYSTEM_TIME to sync host and FW timestamps

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#8016]
**Is your feature request related to a problem? Please describe.**
Host is sending SOF_IPC4_FW_PARAM_SYSTEM_TIME to synchronize the host and DSP timestamps so that timestamps in logs can be compared directly. 

**Describe the solution you'd like**
Implement IPC4 handle to set the timestamp epoch and implement a custom timestamp generator and set this using Zephyr log_set_timestamp_func() (in order for logging subsystem to use this timestamp).

**Describe alternatives you've considered**
Setting the Zephyr kernel time is one option, but there is currently no API to do this from applications and this could create many issues (i.e. time going back for kernel code).

**Additional context**

**Comment by kv2019i** [comment]
@btian1 this is one potential, please assign to yourself if you have bandwidth

**Comment by plbossart** [comment]
@ujfalusi and I already discussed this, I can't recall what the outcome was and where this discussion took place.

**Comment by ujfalusi** [comment]
@plbossart , @kv2019i, the kernel is sending the time when the mtrace is enabled.
The message setup starts here:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/sound/soc/sof/ipc4-mtrace.c#n433
and the send is
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/sound/soc/sof/ipc4-mtrace.c#n444

The epoch is adjusted as per specification, but I'm no longer sure if we should do that and just send the time directly.

**Comment by ujfalusi** [comment]
This is the SOF/Zephyr side handling of the message, right?

**Comment by lgirdwood** [comment]
@kv2019i IIUC, driver is sending the message but we need to make sure we get teh message to Zephyr. @abonislawski @mwasko @nashif we will need this for PSS.

**Comment by kv2019i** [comment]
@alex-cri @lgirdwood @mengdonglin proposing to move to v2.8 . work not yet started, so this did not make the v2.7 cut

**Comment by RanderWang** [comment]
> @plbossart , @kv2019i, the kernel is sending the time when the mtrace is enabled. The message setup starts here: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/sound/soc/sof/ipc4-mtrace.c#n433 and the send is https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/sound/soc/sof/ipc4-mtrace.c#n444
> 
> The epoch is adjusted as per specification, but I'm no longer sure if we should do that and just send the time directly.

@ujfalusi we need the kernel and FW work in the same time domain. In kernel log, the time is increased from the OS boot up, but the time sent for fw is  UTC, epoch is 1601-01-01 00:00:00, so the time domain is still different,  can we change the time to kernel log so that easy for us to check the time between kernel log and fw log ?

````
[    6.366234] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx      : MOD_LARGE_CONFIG_SET [data size: 76]
[    6.366559] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: MOD_LARGE_CONFIG_SET
[    6.366593] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx done : MOD_LARGE_CONFIG_SET [data size: 76]
````

**Comment by ujfalusi** [comment]
The IPC4 specification is explicitly tells that the epoch for the set time is 1601-01-01 00:00:00, this is why the kernel driver converts it.

**Comment by lgirdwood** [comment]
We can spell this out with some comments if needed. TBH using an epoch in FW is a waste of cycles, we shoulds use native timer value and do any epoch conversion in host.

**Comment by kv2019i** [comment]
No consensus in the review this week, pushing to v2.9, but let's try to get to main this month in any case.

**Comment by marc-hb** [comment]
All merged, close?
