### ISSUE TITLE
[BUG][sparse] mm_drv_intel_adsp_tlb.c:147:20: warning: incorrect type in initializer (different address spaces)

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#8054]
Seen in CI since this week:
mm_drv_intel_adsp_tlb.c:147:20: warning: incorrect type in initializer (different address spaces)

https://github.com/thesofproject/sof/actions/runs/5878948715/job/15942028924?pr=7986

**Comment by kv2019i** [comment]
@jxstelter @lyakh Not sure yet why this is popping up now, but let's try to fix asap so more sparse issued don't slip through (while CI is red on this).

**Comment by jxstelter** [comment]
> @jxstelter @lyakh Not sure yet why this is popping up now, but let's try to fix asap so more sparse issued don't slip through (while CI is red on this).

The warnings looks strange. Zephyr is set to this commit:
commit 431108d89e1750dbea05dce64dbb7fd329aa610e (HEAD -> Branch_431108d8)

Code lines marked shows even comment space (eg. line 204)

**Comment by lyakh** [comment]
> @jxstelter @lyakh Not sure yet why this is popping up now, but let's try to fix asap so more sparse issued don't slip through (while CI is red on this).

@kv2019i isn't it because we've now enabled the MM remapping on TGL? https://github.com/thesofproject/sof/pull/7986/commits/22f1562050c7d5262b7cfbc8c0ce421308ffa548 @ujfalusi

**Comment by ujfalusi** [comment]
The SOF side fix (seen in MTL/LNL builds): https://github.com/thesofproject/sof/pull/8058

**Comment by ujfalusi** [comment]
The Zephyr side: https://github.com/zephyrproject-rtos/zephyr/pull/61630

**Comment by kv2019i** [comment]
Issue fixed, closing.
