### ISSUE TITLE
Baytrail/Broadwell: enable XCC compiler

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#810]
maybe with New Year's resolution this will get done in 2019?

**Comment by ranj063** [comment]
@plbossart I will look into getting BYT working. But I havent been successful in getting the core config tarball for BDW/HSW. @michalgrodzicki can you please help with that?

**Comment by xiulipan** [comment]
@ranj063 Please CC me once this is all done. And we can update our CI to track BYT/BDW XCC build status.

**Comment by tlauda** [comment]
@ranj063 Is there any progress?

**Comment by plbossart** [comment]
@xiulipan XCC is enabled for BYT, yes? What about BDW?

**Comment by xiulipan** [comment]
@plbossart BDW/CHT/BYT XCC build are enabled, I think we can close this issue now.
