### ISSUE TITLE
[BUG] ramp time extended by 0.03s after capture gain curve_duration change

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#8238]
**Describe the bug**
Observed this issue on all IPC4-nocodec(single core) platforms.  it caused alsabat test failures.
The ramp time extended by 0.03s after capture gain curve_duration change(https://github.com/thesofproject/sof/commit/d0d74a477f64a83654bccb3905175584d05d9257):
![image](https://github.com/thesofproject/sof/assets/22468760/ea78614a-071c-4aaa-b658-def3dabd1d06)

**To Reproduce**
check the alsabat wav file

**Reproduction Rate**
100%

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {[cffcac365eac](https://github.com/thesofproject/linux/commit/cffcac365eac0d60dc38959cadaa5078bc924b8e)}
    * SOF: {[capture gain curve_duration change](https://github.com/thesofproject/sof/commit/d0d74a477f64a83654bccb3905175584d05d9257)}
2) Name of the topology file
    * Topology: {nocodec tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {NOCODEC-IPC4 platforms}

**Comment by marc-hb** [comment]
The commit message says "This change increases the ramp duration from 20 ms to 50 ms"

So it's not a bug, it's a feature? :-)

**Comment by keqiaozhang** [comment]
> So it's not a bug, it's a feature? :-)

Not sure about this, but alsabat cannot survive from such long ramp time.

**Comment by singalsu** [comment]
Ouch, but there's justification for this change. 1) capture artefacts mitigation accidentally dropped from tplg2 vs. tplg1 2) we can avoid a big MCPS peak with this lower rate ramp.

Is there a way to ask alsabat to ignore a bit long audio from beginning?

**Comment by singalsu** [comment]
If not possible to change alsabat we can have a test topology with short ramp?

**Comment by singalsu** [comment]
I could not find from alsabat command line options to ignore audio from very beginning of test. I don't like at all to change something because of limitation in our test procedure but this might help https://github.com/thesofproject/sof/pull/8242 .

**Comment by lgirdwood** [comment]
@singalsu ack, the topology used for the test can have its ramp shortened, providing its not a end user topology. i.e. testing only topology.

**Comment by marc-hb** [comment]
Let's wait for validation in the next daily test run.

Stupid Github auto close anti-feature: https://github.com/orgs/community/discussions/17308

**Comment by keqiaozhang** [comment]
Confirmed that alsabat test passed after applying PRhttps://github.com/thesofproject/sof/pull/8242 on nocodec platforms. Closing this bug.
