### ISSUE TITLE
[BUG] Terrible audio under Linux on Dell XPS 15 laptop, model 9530 (2023)

### ISSUE THREAD

**Issue by berbmit** [thesofproject/sof#8293]
Describe the bugNew XPS 15 laptop, model 9530 (2023) with latest Linux Mint installed.   Installation was straightforward, everything seems to work very nicely after upgrading to a kernel later than 6.2 to get wifi working.  All updates are applied.

Under Linux the sound is pathetic and weak.

The sound works well under Windows (from testing before deleting windows and installing Linux) the sound was full and strong.  Under Linux the sound is pathetic and weak.  

It seems the woofers are not being detected, as other online comments have noted. With only the 2 tweeters firing under linux the sound is unsurprisingly weak.   Have googled extensively, and seems I am not alone in this problem.

Also noted by others is that the problem existed in prior model and a kernel patch fix was possible, but the fix did not work with the 9530 model as it uses different hardware.

I have tried playing with alsamixer, no options exist to make any difference.   
I have tried kernels all the way up to the latest 6.5 with no fix.
I made sure I have the latest firmware from repositories.

This is a huge frustration for music and games and Zoom calls for work.

From (https://nanoreview.net/en/laptop/dell-xps-15-9530-2023) it seems the sound specs are:
Audio chip Realtek ALC3281
Speakers 2.2 (2 tweeters and 2 woofers)
Power 2x2W, 2x3W

**Environment**
Runnigf latest Linux 
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {SHA}
    * SOF: {SHA}
2) Name of the topology file
    * Topology: {FILE}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {PLATFORM}

**Screenshots or console output**
If applicable, add a screenshot (drag-and-drop an image), or console logs
(cut-and-paste text and put a code fence (\`\`\`) before and after, to help
explain the issue.

Please also include the relevant sections from the firmware log and kernel log in the report (and attach the full logs for complete reference). Kernel log is taken from *dmesg* and firmware log from *sof-logger*. See https://thesofproject.github.io/latest/developer_guides/debugability/logger/index.html

**Comment by lgirdwood** [comment]
@berbmit do you have a dmesg you can share ? 
Fwiw, we often find that there are extra HDA control verbs that have to be added to the HDA driver to enable certain output amplifiers. This could be one of these cases.

**Comment by plbossart** [comment]
see the suggestions here @berbmit 
https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html

Note that Windows drivers have platform-specific information that isn't in ACPI, and the firmware also embeds 3rd party processing that is not included in the firmware used for Linux due to redistribution rights, so it's not unexpected unfortunately that the audio loudness and quality trails compared to a Windows laptop.
