### ISSUE TITLE
Add SOF plugin build test in CI 

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof#8545]
**Is your feature request related to a problem? Please describe.**
Make sure the SOF plugin compiles with all new PRs

**Describe the solution you'd like**
Add build test to the CI

Build instructions:

cd sof
mkdir build_plugin
cd build_plugin
cmake ../tools/plugin

**Comment by marc-hb** [comment]
Submitted:
- #8560

**Comment by marc-hb** [comment]
@ranj063 close as done?
