### ISSUE TITLE
[BUG][ARL] Boot from IMR fails after system S3 suspend

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#8715]
**Describe the bug**
DSP boot fails after system resume.

When cold boot is forced (with "sof_debug=0x80"), issue is not seen. 

**To Reproduce**

**Reproduction Rate**
TBD (not seen on all systems)

**Expected behavior**
IMR boot works after system suspend

**Impact**
high

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: sof-dev
    * SOF: 2024-01-08 daily
2) Name of the topology file
    * Topology: hda-genreic
3) Name of the platform(s) on which the bug is observed.
    * Platform: arl

**Screenshots or console output**

**Comment by mengdonglin** [comment]
There is a potential fix https://github.com/thesofproject/linux/pull/4770

**Comment by kv2019i** [comment]
This issue is limited to resume from S3.

**Comment by kv2019i** [comment]
With https://github.com/thesofproject/linux/pull/4775 merged on SOF Linux driver side, we can close this as invalid/wontfix, right?

**Comment by ujfalusi** [comment]
@kv2019i, yes, we are not going to try IMR boot in case when we resume from S3 suspend.
