### ISSUE TITLE
[BUG] CONFIG_ZEPHYR_HAL_NXP_MODULE was set to y during tgl/mtl/lnl build

### ISSUE THREAD

**Issue by btian1** [thesofproject/sof#8782]
**Describe the bug**
please check build log, you will find:
![image](https://github.com/thesofproject/sof/assets/17277136/3483dde9-0abc-4d39-af18-cfe7e4e6520b)
or check .config file with build-mtl/zephyr/.config
CONFIG_ZEPHYR_HAL_NXP_MODULE=y

**To Reproduce**
check above

**Reproduction Rate**
100%.

**Expected behavior**
above definition should not happen in intel platform build.

**Impact**
not well evaluated.

**Comment by lgirdwood** [comment]
adding @dbaluta - worth checking also if Intel Kconfigs are not being set for NXP builds. @btian1 any clue here ?

**Comment by btian1** [comment]
below link generated file Kconfig.modules during pre-build:
https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/modules/zephyr_module.cmake#L60
and in generated file: 
build-mtl/Kconfig/Kconfig.modules

there is definition for:

menu "hal_nxp (/home/btian1/sof_mtl/modules/hal/nxp)"
osource "$(ZEPHYR_HAL_NXP_KCONFIG)"
config ZEPHYR_HAL_NXP_MODULE
        bool
        default y
endmenu

I just don't know how Kconfig.modules was generated with above link, @marc-hb , @kv2019i , could you guide here?

**Comment by kv2019i** [comment]
Aa, I think this comes automatically for all modules we list in sof/west.yml. So we have hal_nxp there, so this config is added automatically in the build
https://docs.zephyrproject.org/latest/develop/modules.html

So I think this is harmless. Nothing gets build due to this module being there, it's jus a kconfig that tells the module is present in the work area. We have these two (and not all are used by all SOF builds):

../build-mtl/zephyr/.config:
....
CONFIG_ZEPHYR_SOF_MODULE=y
CONFIG_ZEPHYR_HAL_NXP_MODULE=y
CONFIG_ZEPHYR_XTENSA_MODULE=y
CONFIG_ZEPHYR_MBEDTLS_MODULE=y
CONFIG_ZEPHYR_MIPI_SYS_T_MODULE=y
CONFIG_ZEPHYR_TINYCRYPT_MODULE=y

**Comment by iuliana-prodan** [comment]
As @kv2019i mentioned above the nxp_hal is imported, by default, for all platforms from SOF's west.yml - https://github.com/thesofproject/sof/blob/main/west.yml#L57

We can change this issue in a feature - import nxp_hal only for NXP platforms. 
But, TBH I didn't find a solution for this (or at least a few months ago when I checked this).

Maybe we can make it optional?
https://github.com/zephyrproject-rtos/zephyr/blob/main/submanifests/optional.yaml#L36
https://docs.zephyrproject.org/latest/contribute/external.html#integration-as-optional-modules
@kv2019i @marc-hb what do you think?
I'll check to see if is possible

**Comment by marc-hb** [comment]
Making west modules optional would complicate CI and other things. I don't think we need to get into SOF package management yet (like https://github.com/zephyrproject-rtos/zephyr/pull/61505 just did), I think we have enough more important problems to solve.

Please just stop dumping gigabyte-big, entire SDKs in that repo :-)
https://github.com/zephyrproject-rtos/hal_nxp/pull/270#issuecomment-1872623423

PS: thank you @btian1 for paying attention to the build logs. Most people seem to miss warnings there :-) However I think this one can be closed.

**Comment by marc-hb** [comment]
> above definition should not happen in intel platform build.

Try  `menuconfig` for an "Intel build" of the Linux kernel and see how many non-Intel things you will find in Kconfig ;-)

**Comment by btian1** [comment]
it is not only have a config during build: CONFIG_ZEPHYR_HAL_NXP_MODULE

it have include path involved, this is also acceptable for tgl/mtl/lnl build? check build.ninja:
I am afraid it will eventually cause conflicts when build:

**ZEPHYR_HAL_NXP_MODULE_DIR=/home/btian1/sof_mtl/modules/hal/nxp ZEPHYR_HAL_NXP_KCONFIG=/home/btian1/sof_mtl/zephyr/modules/hal_nxp/Kconfig_**** 

../build-mtl/build.ninja:241:  COMMAND = cd /home/btian1/sof_mtl/build-mtl/zephyr/kconfig && /usr/bin/cmake -E env ZEPHYR_BASE=/home/btian1/sof_mtl/zephyr PYTHON_EXECUTABLE=/usr/bin/python3.8 srctree=/home/btian1/sof_mtl/zephyr KERNELVERSION=0x3056300 APPVERSION= CONFIG_=CONFIG_ KCONFIG_CONFIG=/home/btian1/sof_mtl/build-mtl/zephyr/.config ARCH=xtensa ARCH_DIR=/home/btian1/sof_mtl/zephyr/arch BOARD_DIR=/home/btian1/sof_mtl/zephyr/boards/xtensa/intel_adsp_ace15_mtpm BOARD_REVISION= KCONFIG_BINARY_DIR=/home/btian1/sof_mtl/build-mtl/Kconfig APPLICATION_SOURCE_DIR=/home/btian1/sof_mtl/sof/app ZEPHYR_TOOLCHAIN_VARIANT=xt-clang TOOLCHAIN_KCONFIG_DIR=/home/btian1/sof_mtl/zephyr/cmake/toolchain/xt-clang TOOLCHAIN_HAS_NEWLIB=n TOOLCHAIN_HAS_PICOLIBC=n EDT_PICKLE=/home/btian1/sof_mtl/build-mtl/zephyr/edt.pickle ZEPHYR_SOF_MODULE_DIR=/home/btian1/sof_mtl/sof **_### **ZEPHYR_HAL_NXP_MODULE_DIR=/home/btian1/sof_mtl/modules/hal/nxp ZEPHYR_HAL_NXP_KCONFIG=/home/btian1/sof_mtl/zephyr/modules/hal_nxp/Kconfig_**** ZEPHYR_XTENSA_MODULE_DIR=/home/btian1/sof_mtl/modules/hal/xtensa ZEPHYR_MBEDTLS_MODULE_DIR=/home/btian1/sof_mtl/modules/crypto/mbedtls ZEPHYR_MBEDTLS_KCONFIG=/home/btian1/sof_mtl/zephyr/modules/mbedtls/Kconfig ZEPHYR_MIPI_SYS_T_MODULE_DIR=/home/btian1/sof_mtl/modules/debug/mipi-sys-t ZEPHYR_TINYCRYPT_MODULE_DIR=/home/btian1/sof_mtl/modules/crypto/tinycrypt SHIELD_AS_LIST= DTS_POST_CPP=/home/btian1/sof_mtl/build-mtl/zephyr/zephyr.dts.pre DTS_ROOT_BINDINGS=/home/btian1/sof_mtl/zephyr/dts/bindings /usr/bin/python3.8 /home/btian1/sof_mtl/zephyr/scripts/kconfig/guiconfig.py /home/btian1/sof_mtl/zephyr/Kconfig

**Comment by marc-hb** [comment]
> it have include path involved

Which include path did you see?

**Comment by btian1** [comment]
ZEPHYR_HAL_NXP_MODULE_DIR=/home/btian1/sof_mtl/modules/hal/nxp ZEPHYR_HAL_NXP_KCONFIG=/home/btian1/sof_mtl/zephyr/modules/hal_nxp/Kconfig_**

**Comment by marc-hb** [comment]
These don't look like include paths.

An "include path" is telling the compiler where to look for .h files.

**Comment by marc-hb** [comment]
Please re-open if you find a real issue (= outside Kconfig)
