### ISSUE TITLE
unit testing: create a test for cross-heap buffer allocation

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof#884]
A new unit test is desired, that would:
1. use rballoc() to allocate buffer memory equal to the size of the first buffer heap minus 1KiB
2. use rballoc() to allocate 2KiB of buffer memory with caps = SOF_MEM_CAPS_RAM

Purpose: test falling back from the first heap to a following one when the former one is exhausted.

**Comment by tlauda** [comment]
Done in #1416.
