### ISSUE TITLE
Huawei matebook d15, no soundcard, No I2S link information provided, using SSP0 [codec es8336]

### ISSUE THREAD

**Issue by Dmitony** [thesofproject/sof#8852]
**Describe the bug**
Sound card is not detected.
`tony@huawei:~$ aplay -l
aplay: device_list:277: no sound card found...`
 A new kernel, version 6.7, was installed; both our own kernel assemblies and those from the repository were used for installation. Currently using the version from the launchpad.
`tony@huawei:~$ uname -r
6.7.0-060700-generic`

**To Reproduce**
Huawei matebook d15, default setup alsa. When you turn on legacy mode
`options snd-intel-dspcfg dsp_driver=1`
the card with the HDA driver is detected, the sound starts working on one speaker out of 2 and the linear output to the microphone works. The built-in micron does not work on the default configuration or on the outdated one

**Expected behavior**
What can you try to do so that the card is detected on the new driver and the built-in microphone and sound work?

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel:6.7.0-060700-generic 
    * SOF: Firmware info: version 2:2:0-57864
2) Name of the topology file
    * Topology: {FILE} alsa-topology-conf                            1.2.5.1-2 
3) Name of the platform(s) on which the bug is observed.
    * Platform: Ubuntu 23.10

**Screenshots or console output**
[alsa-info](https://alsa-project.org/db/?f=acd54f2e32d2f87c3b34e0e380ad99c1699c000a)
dmesg 
`
<pre><font color="#26A269"><b>tony@huawei</b></font>:<font color="#12488B"><b>~</b></font>$ sudo journalctl --boot=0  | egrep -i &apos;sof|sound|audio|8336&apos;
фев 12 14:03:24 huawei kernel: <font color="#C01C28"><b>sof</b></font>tware IO TLB: area num 8.
фев 12 14:03:24 huawei kernel: pps_core: <font color="#C01C28"><b>Sof</b></font>tware ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti &lt;giometti@linux.it&gt;
фев 12 14:03:24 huawei kernel: PCI-DMA: Using <font color="#C01C28"><b>sof</b></font>tware bounce buffering for IO (SWIOTLB)
фев 12 14:03:24 huawei kernel: <font color="#C01C28"><b>sof</b></font>tware IO TLB: mapped [mem 0x0000000063205000-0x0000000067205000] (64MB)
фев 12 14:03:24 huawei kernel: Modules linked in: snd_hda_intel(+) ecdh_generic snd_intel_dspcfg iwlmvm(+) snd_soc_es8316 joydev mc ecc i915(+) snd_intel_sdw_acpi kvm snd_soc_core mac80211 snd_hda_codec snd_compress snd_hda_core ac97_bus snd_pcm_dmaengine snd_hwdep irqbypass libarc4 snd_pcm crct10dif_pclmul polyval_clmulni polyval_generic ghash_clmulni_intel sha512_ssse3 snd_seq_midi sha256_ssse3 sha1_ssse3 drm_buddy snd_seq_midi_event cmdlinepart aesni_intel ttm snd_rawmidi mei_pxp spi_nor processor_thermal_device_pci_legacy crypto_simd iwlwifi mei_hdcp drm_display_helper cryptd mtd processor_thermal_device snd_seq processor_thermal_wt_hint intel_rapl_msr processor_thermal_rfim cec huawei_wmi processor_thermal_rapl snd_seq_device rapl ledtrig_<font color="#C01C28"><b>audio</b></font> rc_core intel_rapl_common spi_intel_pci cfg80211 intel_cstate mei_me snd_timer sparse_keymap wmi_bmof i2c_i801 processor_thermal_wt_req spi_intel processor_thermal_power_floor snd i2c_smbus drm_kms_helper mei processor_thermal_mbox i2c_algo_bit <font color="#C01C28"><b>sound</b></font>core intel_soc_dts_iosf igen6_edac
фев 12 14:03:24 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
фев 12 14:03:24 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: enabling device (0000 -&gt; 0002)
фев 12 14:03:24 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
фев 12 14:03:24 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_<font color="#C01C28"><b>audio</b></font>_component_bind_ops [i915])
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 5
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: unknown <font color="#C01C28"><b>sof</b></font>_ext_man header type 3 size 0x30
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-<font color="#C01C28"><b>audio</b></font>-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font> <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font>: No I2S link information provided, using SSP0. This may need to be modified with the quirk module parameter
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font> <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font>: quirk mask 0x20
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font> <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font>: quirk SSP0
фев 12 14:03:25 huawei kernel: <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font> <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font>: quirk DMIC enabled
фев 12 14:03:25 huawei kernel: audit: type=1400 audit(1707728605.251:4): apparmor=&quot;STATUS&quot; operation=&quot;profile_load&quot; profile=&quot;unconfined&quot; name=&quot;/opt/micro<font color="#C01C28"><b>sof</b></font>t/msedge/msedge&quot; pid=732 comm=&quot;apparmor_parser&quot;
фев 12 14:03:26 huawei rsyslogd[924]: [origin <font color="#C01C28"><b>sof</b></font>tware=&quot;rsyslogd&quot; swVersion=&quot;8.2306.0&quot; x-pid=&quot;924&quot; x-info=&quot;https://www.rsyslog.com&quot;] start
фев 12 14:03:28 huawei systemd[1411]: Listening on pipewire-pulse.socket - PipeWire Pulse<font color="#C01C28"><b>Audio</b></font>.
фев 12 14:03:28 huawei systemd[1411]: Started pipewire-pulse.service - PipeWire Pulse<font color="#C01C28"><b>Audio</b></font>.
фев 12 14:03:29 huawei gnome-shell[1494]: Extension ding@raster<font color="#C01C28"><b>sof</b></font>t.com already installed in /usr/share/gnome-shell/extensions/ding@raster<font color="#C01C28"><b>sof</b></font>t.com. /usr/share/gnome-shell/extensions/ding@raster<font color="#C01C28"><b>sof</b></font>t.com will not be loaded
фев 12 14:03:35 huawei kernel: <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font> <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font>: No I2S link information provided, using SSP0. This may need to be modified with the quirk module parameter
фев 12 14:03:35 huawei kernel: <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font> <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font>: quirk mask 0x20
фев 12 14:03:35 huawei kernel: <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font> <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font>: quirk SSP0
фев 12 14:03:35 huawei kernel: <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font> <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font>: quirk DMIC enabled
фев 12 14:03:35 huawei kernel: platform <font color="#C01C28"><b>sof</b></font>-essx<font color="#C01C28"><b>8336</b></font>: deferred probe pending
фев 12 14:03:36 huawei systemd[2255]: Listening on pipewire-pulse.socket - PipeWire Pulse<font color="#C01C28"><b>Audio</b></font>.
фев 12 14:03:36 huawei systemd[2255]: Started pipewire-pulse.service - PipeWire Pulse<font color="#C01C28"><b>Audio</b></font>.
фев 12 14:03:37 huawei systemd[2255]: Starting org.gnome.SettingsDaemon.<font color="#C01C28"><b>Sound</b></font>.service - GNOME <font color="#C01C28"><b>sound</b></font> sample caching service...
фев 12 14:03:37 huawei systemd[2255]: Started org.gnome.SettingsDaemon.<font color="#C01C28"><b>Sound</b></font>.service - GNOME <font color="#C01C28"><b>sound</b></font> sample caching service.
фев 12 14:03:37 huawei systemd[2255]: Reached target org.gnome.SettingsDaemon.<font color="#C01C28"><b>Sound</b></font>.target - GNOME <font color="#C01C28"><b>sound</b></font> sample caching target.
фев 12 14:03:38 huawei telegram-desktop_telegram-desktop.desktop[2827]: [AL<font color="#C01C28"><b>SOF</b></font>T] (EE) Failed to connect PipeWire event context (errno: 112)
фев 12 14:03:39 huawei snapd-desktop-i[3453]: New theme: gtk=Yaru icon=Yaru cursor=Yaru, <font color="#C01C28"><b>sound</b></font>=Yaru
фев 12 14:03:48 huawei systemd[1411]: Stopping pipewire-pulse.service - PipeWire Pulse<font color="#C01C28"><b>Audio</b></font>...
фев 12 14:03:48 huawei systemd[1411]: Stopped pipewire-pulse.service - PipeWire Pulse<font color="#C01C28"><b>Audio</b></font>.
фев 12 14:03:48 huawei systemd[1411]: Closed pipewire-pulse.socket - PipeWire Pulse<font color="#C01C28"><b>Audio</b></font>.
</pre>

`

**Comment by plbossart** [comment]
kernel issue https://github.com/thesofproject/linux/issues/4814
