### ISSUE TITLE
Enable native build on Windows

### ISSUE THREAD

**Issue by jajanusz** [thesofproject/sof#888]
We have now CMake that can generate native makefiles for NMake/Ninja for Windows.
However there is still 1 thing that prevents us from building everything we need on Windows - Rimage.

Rimage has dependency on elf headers, so we need some kind of system-independent elf header file in rimage sources.

We can achieve it easily by using this:
https://github.com/google/rekall/blob/master/tools/windows/winpmem/executable/elf.h

I think it's good candidate and looks like it already has 2-clause BSD license.

@mmaka1 @lgirdwood 
Do you think it's good idea to add it to our rimage?

**Comment by plbossart** [comment]
On 1/24/19 12:28 PM, Janusz Jankowski wrote:
>
> We have now CMake that can generate native makefiles for NMake/Ninja 
> for Windows.
> However there is still 1 thing that prevents us from building 
> everything we need on Windows - Rimage.
>
> Rimage has dependency on elf headers, so we need some kind of 
> system-independent elf header file in rimage sources.
>
> We can achieve it easily by using this:
> https://github.com/google/rekall/blob/master/tools/windows/winpmem/executable/elf.h
>
> I think it's good candidate and looks like it already has 2-clause BSD 
> license.
>
IANAL, but SOF relies on 3-clause BSD license terms.

Someone would need to check what 2-clause BSD means.

**Comment by jajanusz** [comment]
@plbossart 
Thanks for the info. IANAL too, but ISC is functionally equal to 2-clause BSD and we already have ISC in Kconfig lib.
Anyway, I guess we should leave it to people that actually are lawyers.
Can some maintainer resolve this issue?

**Comment by lgirdwood** [comment]
BSD 2 clause is the same as BSD 3 clause minus the following condition.
```
 Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.
```
From https://en.wikipedia.org/wiki/BSD_licenses
