### ISSUE TITLE
Change pipeline copy policy to handle data not aligned to period size

### ISSUE THREAD

**Issue by tlauda** [thesofproject/sof#889]
In order to fully support timer driven pipeline scheduling, the policy for pipeline data copy has to change. Fixed size of copied data is not flexible enough and requires many workarounds and shortcuts across the code base. Required changes:
1. HD-DMA: calculate transferred data size based on buffer size, read pointer and write pointer.
2. DW-DMA: calculate transferred data size based on linked list size, sar and dar.
3. Refactor components to handle period unaligned data.

**Comment by lgirdwood** [comment]
@tlauda do you need any flags from topology here to define enable this capability in a pipeline ? @mengdonglin fyi.

**Comment by tlauda** [comment]
Done.
