### ISSUE TITLE
[FEATURE] A way to natively install sof into windows 10 for devces that use it

### ISSUE THREAD

**Issue by Dae-Hang-Sook** [thesofproject/sof#8987]
**Is your feature request related to a problem? Please describe.**
The inability to install into windows 10 no matter what is done or tried.

**Describe the solution you'd like**
A way to natively install sof into windows 10 for devces that use it. (glkda7219max in my case)

**Describe alternatives you've considered**
Paying for the ability to do this. (Coolstar)

**Additional context**
I'd like to be able to install sof firmware just as easily in windows as in linux and also for free just like in linux.

**Comment by plbossart** [comment]
This isn't really a firmware feature, rather a problem on the Windows driver side.

**Comment by marc-hb** [comment]
SOF is simply not supported with Windows right now and it will never be with very old products like GLK.

**Comment by Dae-Hang-Sook** [comment]
> This isn't really a firmware feature, rather a problem on the Windows driver side.

Will anything ever be done or just not at all?

**Comment by plbossart** [comment]
It's fair to say that no one has any plans to support this feature on GLK and Windows10. That ship has sailed many moons ago.

**Comment by Dae-Hang-Sook** [comment]
> It's fair to say that no one has any plans to support this feature on GLK and Windows10. That ship has sailed many moons ago.

My bad, I meant just SOF in general this time, not just GLK devices.
