### ISSUE TITLE
firmware panic when running aplay on hw:0,5 but without hdmi displayer connection

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#901]
Without the HDMI connection, run aplay on HDMI will cause firmware panic, but what's interesting is that after this issue happened, both speaker and headset still can work.
How to reproduce:
1. without HDMI/DP displayer connection or set Pin5-Port* Mux to none
2. run aplay on hdmi
aplay -Dhw:0,5 -f dat -c 2 /dev/zero

sof-branch: glk-006-drop-stable
kernel:cros-sof-v4.14-rebase

dmesg:
```
[   38.147420] sof-audio sof-audio: ipc tx: 0x50010000
[   38.147613] sof-audio sof-audio: ipc tx succeeded: 0x50010000
[   38.147645] sof-audio sof-audio: ipc tx: 0x40020000
[   38.147789] sof-audio sof-audio: ipc tx succeeded: 0x40020000
[   38.147952] sof-audio sof-audio: ipc rx: 0x90020000
[   38.147968] sof-audio sof-audio: ipc rx done: 0x90020000
[   38.155441] sof-audio sof-audio: pcm: open stream 5 dir 0
[   38.155480] sof-audio sof-audio: period min 192 max 16384 bytes
[   38.155482] sof-audio sof-audio: period count 2 max 16
[   38.155484] sof-audio sof-audio: buffer max 65536 bytes
[   38.155801] HDMI HDA Codec ehdaudio0D2: ASoC: can't set intel-hdmi-hifi1 hw params: -19
[   38.155808]  iDisp1: ASoC: hw_params BE failed -19
[   38.155811]  HDMI1: ASoC: hw_params BE failed -19
[   38.155815] sof-audio sof-audio: pcm: free stream 5 dir 0
[   38.155854] sof-audio sof-audio: ipc tx: 0x60030000
[   38.155938] sof-audio sof-audio: error : DSP panic!
[   38.155943] sof-audio sof-audio: panic: dsp_oops_offset 788480 offset 788480
[   38.155947] sof-audio sof-audio: status: fw entered - code 00000005
[   38.156097] sof-audio sof-audio: error: runtime exception
[   38.156099] sof-audio sof-audio: error: trace point 00004000
[   38.156102] sof-audio sof-audio: error: panic happen at :0
[   38.156105] sof-audio sof-audio: error: DSP Firmware Oops
[   38.156108] sof-audio sof-audio: error: Exception Cause: LoadStorePIFDataErrorCause, Synchronous PIF data error during LoadStore access
[   38.156111] sof-audio sof-audio: EXCCAUSE 0x0000000d EXCVADDR 0x000027c0 PS       0x00060025 SAR     0x0000001d
[   38.156114] sof-audio sof-audio: EPC1     0xbe01edf9 EPC2     0xbe02aa05 EPC3     0xbe027660 EPC4    0x00000000
[   38.156117] sof-audio sof-audio: EPC5     0x00000000 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[   38.156120] sof-audio sof-audio: EPS2     0x00060720 EPS3     0x00060722 EPS4     0x00000000 EPS5    0x00000000
[   38.156123] sof-audio sof-audio: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x000101d8 INTERRU 0x00000222
[   38.156126] sof-audio sof-audio: stack dump from 0xbe07ed10
[   38.156130] sof-audio sof-audio: 0xbe07ed10: be01edf9 00060535 0000001d 00000064
[   38.156134] sof-audio sof-audio: 0xbe07ed14: be023eaf be07edb0 be04c268 00000064
[   38.156137] sof-audio sof-audio: 0xbe07ed18: 00000000 00000000 00000000 00000000
[   38.156140] sof-audio sof-audio: 0xbe07ed1c: c06dcf1b ffffffff eba77828 ffff99e6
[   38.156143] sof-audio sof-audio: 0xbe07ed20: 000c0800 00000000 0dead000 00000000
[   38.156146] sof-audio sof-audio: 0xbe07ed24: 41a3fea8 ffffba60 9ef18f2c ffffffff
[   38.156150] sof-audio sof-audio: 0xbe07ed28: 00000000 00000000 9ef18f44 ffffffff
[   38.156153] sof-audio sof-audio: 0xbe07ed2c: 41a3ff48 ffffba60 9eee75a0 ffffffff
[   38.156156] sof-audio sof-audio: error: waking up any trace sleepers
[   38.456813] sof-audio sof-audio: error: ipc timed out for 0x60030000 size 0xc
[   38.456843] sof-audio sof-audio: status: fw entered - code 00000005
[   38.457035] sof-audio sof-audio: error: runtime exception
[   38.457038] sof-audio sof-audio: error: trace point 00004000
[   38.457040] sof-audio sof-audio: error: panic happen at :0
[   38.457043] sof-audio sof-audio: error: DSP Firmware Oops
```
[dmesg.log](https://github.com/thesofproject/sof/files/2802125/dmesg.log)
[logger-t.log](https://github.com/thesofproject/sof/files/2802126/logger-t.log)

**Comment by xiulipan** [comment]
@keqiaozhang @plbossart 
This seems to be the same issue I meet when debuging https://github.com/thesofproject/linux/issues/532

**Comment by lgirdwood** [comment]
@dabekjakub  The interesting thing is that this exception location crops up a lot with HDMI related issues (EXCVADDR 0x000027c0 is very near HDA IP addresses). HDA driver has an array that may be incorrectly indexed when this happens ?

**Comment by dabekjakub** [comment]
@lgirdwood 
There is no exception data in fs again so our automated scripts stopped working :D Will have to decipher it.

In my testing i also saw ipc timeout before the panic.

**Comment by dabekjakub** [comment]
You are probably right - this is the place that relates to the exception adress provided , i am looking into it.

```
0xbe01d809 is in hda_dma_stop (/home/admin/SOF/sof/src/include/sof/io.h:61).
56              *((volatile uint32_t*)reg) = val;
57      }
58
59      static inline void io_reg_update_bits(uint32_t reg, uint32_t mask, uint32_t value)
60      {
61              io_reg_write(reg, (io_reg_read(reg) & (~mask)) | (value & mask));
62      }
63
64      static inline uint16_t io_reg_read16(uint32_t reg)
65      {
```

**Comment by mmaka1** [comment]
@lgirdwood, @dabekjakub  
> The interesting thing is that this exception location crops up a lot with HDMI related issues (EXCVADDR 0x000027c0 is very near HDA IP addresses). HDA driver has an array that may be incorrectly indexed when this happens ?

Yes, looks like a gap between the link input and the host output blocks. Could be either wrong index of a link dma or a negative (-2) channel index of the host output because another interesting thing is that channel arg is of 'int' type in a couple of places while tested only against upper bound (channel >= HDA_DMA_MAX_CHANS) in the internal hda dma routines. Could be consistently checked to 'unsigned int' but negative value is used in some places to indicate an error.

**Comment by dabekjakub** [comment]
fixed in prs #903 and #930

**Comment by juimonen** [comment]
@dabekjakub, yeah the confusion was that i didn't know i was partly fixing this issue, I was fixing it along the way when doing some other pr :)

**Comment by juimonen** [comment]
@dabekjakub I think issue https://github.com/thesofproject/sof/issues/747 is also fixed with these same prs. It used to oops with wrong params and invalid dma channel. With these prs it should return proper error from SRC.
