### ISSUE TITLE
[FEATURE] Ability to use Zephyr shell with SOF 

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#9081]
**Is your feature request related to a problem? Please describe.**
Add overlay (or build option) to implement Zephyr shell (https://docs.zephyrproject.org/latest/services/shell/index.html) support to SOF, and a backend that allows to attach to the shell from host CPU (over e.g. a memory window backend). This offers a new debugging and development option for SOF development, opening up possibility to observe system state and execute test sequences on the DSP.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kv2019i** [comment]
Working on this now,

**Comment by lgirdwood** [comment]
@andyross @cujomalainey fyi

**Comment by cujomalainey** [comment]
Interesting, would it just appear as a tty to the kernel?

**Comment by lgirdwood** [comment]
> Interesting, would it just appear as a tty to the kernel?

That's the intention. The kernel tty would just be a passthrough from the DSP. Similar to how GDB would work.

**Comment by andyross** [comment]
Ended up here after commenting on this Zephyr PR: (https://github.com/zephyrproject-rtos/zephyr/pull/72158)

This sounds cool.  Ironically I've never been a shell person on the Zephyr side (almost always if you're chasing a bug it's easier to just rebuild/reflash the whole app rather than trying to "use it interactively").

But one big feature it would add here is the ability to do whitebox testing on live audio firmware, something that the kernel driver normally tries its hardest to prevent.   Having a backchannel from userspace would be really nice, even if you have to use the slightly crufty shell API to do it.

**Comment by lgirdwood** [comment]
> But one big feature it would add here is the ability to do whitebox testing on live audio firmware, something that the kernel driver normally tries its hardest to prevent. Having a backchannel from userspace would be really nice, even if you have to use the slightly crufty shell API to do it.

Ack, we were thinking things like injecting errors in pipelines, dumping state during tuning- really a method to help increase technical velocity in many ways.

**Comment by kv2019i** [comment]
First Zephyr PR submitted for review https://github.com/zephyrproject-rtos/zephyr/pull/72738 . SOF PR to add a config overlay and (possible) Linux SOF client to create the pty, will come later.

**Comment by cujomalainey** [comment]
@johnylin76 with relation to #5521

**Comment by kv2019i** [comment]
Current set of PRs in progress:
- https://github.com/thesofproject/sof/pull/9133
- https://github.com/zephyrproject-rtos/zephyr/pull/72738
- dependency for above: https://github.com/zephyrproject-rtos/zephyr/pull/72799

**Comment by kv2019i** [comment]
Dependencies merged, now waiting for the https://github.com/zephyrproject-rtos/zephyr/pull/72738 to be merged in Zephyr.

Uploaded a sof-docs PR to https://github.com/thesofproject/sof-docs/pull/496 to document shell usage with some examples.

**Comment by kv2019i** [comment]
While waiting for Zephyr side PR to be merged, here's one more draft on SOF side that adds first custom command:

https://github.com/thesofproject/sof/pull/9174

**Comment by kv2019i** [comment]
Shell backend now merged to Zephyr. Next step is to bring in the changes to SOF main via https://github.com/thesofproject/sof/pull/9179

**Comment by kv2019i** [comment]
Main feature completed and merged to v2.10. The SOF side config overlay (convenience to build with shell) and additional SOF custom commands, are still in progress, but these goes go out of the scope for this original feature request.

Follow-up PRs:
- SOF: https://github.com/thesofproject/sof/pull/9133
- SOF: https://github.com/thesofproject/sof/pull/9174
- SOF docs: https://github.com/thesofproject/sof-docs/pull/496
