### ISSUE TITLE
[BUG] IPC3/4 fuzzer build broken with Zephyr PR 71378

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#9101]
**Describe the bug**
As discussed in https://github.com/zephyrproject-rtos/zephyr/pull/71378#pullrequestreview-2011374611 , recent changes in Zephyr mainline break the SOF fuzzer builds and the github CI checks using these builds.

**To Reproduce**
https://github.com/thesofproject/sof/actions/runs/8972185189/job/24639608648?pr=9098

**Reproduction Rate**
100%

**Expected behavior**
Fuzzer build works.

**Impact**
Fuzzer not usable with SOF.

**Environment**
https://sof-ci.01.org/sofpr/PR9098/build4470/build/index.html

```
Parsing /home/runner/work/sof/sof/workspace/zephyr/Kconfig
/home/runner/work/sof/sof/workspace/build-fuzz/zephyr/misc/generated/extra_kconfig_options.conf:2: warning:
      attempt to assign the value '100' to the undefined symbol ARCH_POSIX_FUZZ_TICKS

error: Aborting due to Kconfig warnings

Loaded configuration '/home/runner/work/sof/sof/workspace/zephyr/boards/native/native_posix/native_posix_defconfig'
Merged configuration '/home/runner/work/sof/sof/workspace/sof/app/prj.conf'
Merged configuration '/home/runner/work/sof/sof/workspace/sof/app/stub_build_all_ipc3.conf'
Merged configuration '/home/runner/work/sof/sof/workspace/build-fuzz/zephyr/misc/generated/extra_kconfig_options.conf'
CMake Error at /home/runner/work/sof/sof/workspace/zephyr/cmake/modules/kconfig.cmake:391 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  /home/runner/work/sof/sof/workspace/zephyr/cmake/modules/zephyr_default.cmake:132 (include)
  /home/runner/work/sof/sof/workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:[66](https://github.com/thesofproject/sof/actions/runs/8972185189/job/24639608648?pr=9098#step:7:67) (include)
  /home/runner/work/sof/sof/workspace/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:5 (find_package)
```

**Comment by kv2019i** [comment]
Marking as P1 for now as we have the fuzzer tests in our github PR test flow.

**Comment by andyross** [comment]
Hm.  That PR's original version was breaking, but the refactored one was safe I thought.  Looks like it's just a missing kconfig we can replace upstream, give me a moment to try it out.

**Comment by andyross** [comment]
Confirmed that reverting the PR works to recover a fuzz build: `git revert --no-edit 2bff629d296f...82fa83048e66`

A few things got moved to the sample that were part of the core fuzz rig and I missed them in review.  Trying to decide whether it's best to move those back piecewise upstream, or just add them to SOF as that's the new architecture anyway.  (The end result here is that the "outer loop" in the fuzzer becomes part of the app and not the architecture layer, in preparation for deprecating "native_posix" in favor of the equivalent "native_sim" arch which is based on an out of tree project).

**Comment by andyross** [comment]
First cut at a fix up, @marc-hb I'm not 100% sure how to exercise all the CI cases (though... maybe CI will just run them on the PR, heh) so wouldn't hurt for you to give it a spin.
