### ISSUE TITLE
[BUG] check-kmod-load-unload-after-playback.sh failed on LNL with SoundWire when testing an unrelated PR

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof#9122]
**Describe the bug**
A PR #9115 with no runtime changes failed jenkins testing on LNL: the check-kmod-load-unload-after-playback.sh test failed with a timeout and kernel error messages:
```
[ 2021.409075] kernel: rt711-sdca sdw:0:0:025d:0711:01: rt711_sdca_dev_resume: Initialization not complete, timed out
[ 2021.424492] kernel: soundwire_bus:sdw_show_ping_status: soundwire sdw-master-0-0: PING status: 0x1
[ 2021.424536] kernel: rt711-sdca sdw:0:0:025d:0711:01: intel_resume_child_device: pm_runtime_resume failed: -110
[ 2021.424658] kernel: soundwire sdw-master-0-0: sdw_intel_exit: intel_resume_child_device failed: -110
```

**To Reproduce**
So far only seen once

**Reproduction Rate**
unknown

**Impact**
Breaks CI testing

**Comment by plbossart** [comment]
known issue already tracked here: https://github.com/thesofproject/linux/issues/4943
