### ISSUE TITLE
CML only support 48K: when play 44.1K music, it be converted to 48K

### ISSUE THREAD

**Issue by DarrenxWang** [thesofproject/sof#913]
Summary:
CML only support 48K: when play 44.1K music, it be converted to 48K

Test steps:
Play 44.1k music, eg.
`
whl@whl-dev:~$ aplay -Dhw:0,0 -c2 -r44100 -fs16_le  Music/Titanium_20.wav
Playing WAVE 'Music/Titanium_20.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
Warning: rate is not accurate (requested = 44100Hz, got = 48000Hz)
         please, try the plug plugin
`

Test env:
sof cml-001-drop-stable: 1f5a9657114
kernel topic/cros-sof-v4.19: f69d618
tplg: sof-cnl-rt5682.tplg

**Comment by lgirdwood** [comment]
@DarrenxWang this is expected behavior as there is no SRC in any of the pipelines in this topology. If this is a requirement then a new enhancement should be created.
