### ISSUE TITLE
testbench broken

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof#916]
Commit https://github.com/thesofproject/sof/commit/f15512e920889238d2940f2b3be6b932705bceb2#diff-d52adf685085b31685bcc42be6141593 broke testbench by creating private copies of variables in different C-files, including the common_test.h header and switching over functions in topology.c to using those variables without removing function parameters, that thus have been made redundant.

**Comment by singalsu** [comment]
OK, thanks for reporting this!

**Comment by singalsu** [comment]
I just created PR #1033 to address this.

**Comment by singalsu** [comment]
The PR is merged and this can be closed.
