### ISSUE TITLE
[BUG] SOF build fails with Zephyr main since June 1st

### ISSUE THREAD

**Issue by kv2019i** [thesofproject/sof#9201]
**Describe the bug**
Last working Zephyr mainline: https://github.com/thesofproject/sof/pull/9179
First failing: https://github.com/thesofproject/sof/pull/9189

List of code changes needed to build SOF:
 - https://github.com/thesofproject/sof/pull/9190
 - https://github.com/thesofproject/sof/pull/9199

**Comment by kv2019i** [comment]
Fixed with https://github.com/thesofproject/sof/pull/9199

**Comment by marc-hb** [comment]
Confirmed in https://github.com/thesofproject/sof/actions/workflows/daily-tests.yml !

<img width="429" alt="Screenshot 2024-06-13 at 11 30 38" src="https://github.com/thesofproject/sof/assets/46978960/cf2c9764-0e9b-4a80-8547-a68a6ff232b6">
