### ISSUE TITLE
topology: DAI_CONFIG isn't aligned across BYT/CHT files

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#924]
sof-byt-nocodec.m4: DAI_CONFIG(SSP, 2, 2, NoCodec-2,
sof-byt-rt5645.m4: DAI_CONFIG(SSP, 2, 0, SSP2-Codec,
sof-byt-rt5651.m4: DAI_CONFIG(SSP, 2, 0, SSP2-Codec,
sof-cht-nocodec.m4: DAI_CONFIG(SSP, 2, 0, NoCodec-2,
sof-cht-max98090.m4: DAI_CONFIG(SSP, 2, 0, SSP2-Codec,

This really needs to be revisited, it's obvious some files are not maintained.
@ranj063 can you take a look?

**Comment by lgirdwood** [comment]
@ranj063 can we close ?

**Comment by ranj063** [comment]
@lgirdwood yes. @plbossart can you please confirm?
