### ISSUE TITLE
XCC compile failed on CNL

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/sof#93]
The root cause is that we miss X6H3CNL_2016_4_linux of builds.
[config.log](https://github.com/thesofproject/sof/files/2188869/config.log)

**Comment by keqiaozhang** [comment]
Thanks Tomasz for sharing the build of "X6H3CNL_2016_4_linux", 
After installed it, now I can use xt-xcc to compile firmware on CNL.

**Comment by tlauda** [comment]
@keqiaozhang So issue can be closed?

**Comment by xiulipan** [comment]
@tlauda @keqiaozhang 
Should the config be updated to some place that we can access?

**Comment by keqiaozhang** [comment]
This issue is fixed  by https://github.com/thesofproject/sof/pull/77
