### ISSUE TITLE
[BUG] SoundWire topologies: headset and mic capture are not processed consistently between IPC3 and IPC4 solutions

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof#9307]
**Describe the bug**

in IPC3 products, the headset capture does not have any EQIIR processing, while the mic capture does.

![image](https://github.com/user-attachments/assets/e10ebfa2-ca97-41d7-a70a-4a5460485255)

In IPC4 products, the headset capture does have an EQIIR processing while the mic capture does not.

![image](https://github.com/user-attachments/assets/42fc6a22-76cd-43cf-a729-321534ab3a97)

This is inconsistent and leads to confusion on capabilities, as noted in https://github.com/thesofproject/linux/issues/3766

**To Reproduce**
use existing topologies

**Reproduction Rate**

100%

**Expected behavior**

Consistent behavior for all new IPC4 products. We are not going to fix IPC3 at this point.

**Impact**

user experience, specifically pop-clicks on capture start

@singalsu please chime in with recommendations.

We can 
a) add the EQIIR on mic capture and keep it active
b) remove EQIIR on all paths
c) all the EQIIR on mic capture but have the default as bypassed.

**Comment by singalsu** [comment]
Option a) probably. A low frequency cutoff highpass (e.g. 40 Hz) is a good bet for all acoustical mic applications. Option c) also works, we will be able to use UCM to set up the EQ when need.

Option b) is not feasible. The IIRs have been added after reports about strong DC pulses in capture begin or with headset button presses.

**Comment by plbossart** [comment]
ok for a), makes sense to deal with button-press and other shenanigans, and IPC4 topology will be better than IPC3 ones.

@ranj063 is this something we can do with the pipeline extension stuff or are there still some dependencies to be worked out with the topology compiler?

**Comment by kv2019i** [comment]
@singalsu v2.12 stuff?

**Comment by plbossart** [comment]
I added the EQIIR for all IPC4 capture path in 
https://github.com/thesofproject/sof/pull/9331

So I think this can be closed?
