### ISSUE TITLE
remove conditional compilation from host.c and dai.c

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof#936]
We currently have conditional compilation for DW_DMA and HDA DMA in host.c and dai.c. This should now be removed and new DMA driver ops added to push the DMA driver specific logic back into the DMA drivers (and not higher level users like host and dai).

@michalgrodzicki I've assigned to you so it's on your radar for later on. @mmaka1 fyi.

**Comment by tlauda** [comment]
@lgirdwood dai.c no longer has conditional compilation. host.c conditional compilation removal is already tracked in #1052, so closing this one.
