### ISSUE TITLE
fail to load all codec topologies under topology/test directory  on GP platform

### ISSUE THREAD

**Issue by zhuqingliang** [thesofproject/sof#96]
description:
topoogy/sof-apl-tdf8532.tplg load well , but topology/test/test-ssp4-mclk-0-I2S-volume-s16le-s16le-48k-24576k-codec.tplg load failed.
environment:
sof-dev: a3a39f21218c074c71cd28b0c2c782b1626df3e3
sof: c454399e8890c1d7eb007857f0dbe018d244eeb7
soft: 47339d2302f445c3b35d50f9720ee649dd2f739b
tplg file name :
topology/test/test-ssp4-mclk-0-I2S-volume-s16le-s16le-48k-24576k-codec.tplg
topology/test/test-ssp4-mclk-0-I2S-volume-s24le-s24le-48k-24576k-codec.tplg

reproduce steps:
check dmesg log when boot up

log:
[dmesg3.log](https://github.com/thesofproject/sof/files/2192819/dmesg3.log)
[rmbox3.log](https://github.com/thesofproject/sof/files/2192820/rmbox3.log)

**Comment by tlauda** [comment]
From dmesg3.log:
[    6.514771] sof-audio sof-audio: ASoC: physical link SSP4-Codec (id 0) not exist
[    6.514777] sof-audio sof-audio: error: tplg component load failed -22
[    6.514789] sof-audio sof-audio: error: failed to load DSP topology -22
[    6.514792] sof-audio sof-audio: ASoC: failed to probe component -22

It's drivers issue, not FW. Can you confirm and close?

**Comment by xiulipan** [comment]
@zhuqingliang 
Please move this bug into SOFT repo.
https://github.com/thesofproject/soft/issues

This bug is because GP has multiple DAIs and test topology is all set with dai id to be 0

**Comment by Jocelyn-Li** [comment]
Moved to https://github.com/thesofproject/soft/issues/27
