### ISSUE TITLE
Add parameter checker for tplg macros

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof#960]
m4 doesnt care about the number of parameters passed when calling the macros. It just ignores the ones that havent been passed. 
Add a parameter checker to check if the mandatory parameters have been passed.

**Comment by lbetlej** [comment]
m4 format to be deprecated

**Comment by ranj063** [comment]
@lbetlej whats the replacement plan

**Comment by lgirdwood** [comment]
@lbetlej can you open a new enhancement for topology definition syntax/parsing to replace M4. This needs to be discussed and aligned. Some  requirements would be #define and #include support alongside param checking.

**Comment by ranj063** [comment]
Fixed by https://github.com/thesofproject/sof/pull/1193
