### ISSUE TITLE
Deduplicate contents of platform headers

### ISSUE THREAD

**Issue by jajanusz** [thesofproject/sof#977]
There are a lot of common defines for cavs platforms that are duplicated in apollolake, cannonlake, icelake, suecreek.
I think it's better to move common parts to `cavs/something.h` and in `platform/something.h` just use`#include <cavs/something.h>`.

Or looking at it in different way: we should separate what is platform setting and what is cavs/ip setting, and have just platform setting include cavs settings for cavs version of this platform.

**Comment by jajanusz** [comment]
@mmaka1 @lgirdwood 
Please comment

**Comment by lgirdwood** [comment]
Common files can be de-duplicated, but files with significant differences should remain in platform/ otherwise it get's too messy.

**Comment by lbetlej** [comment]
done
